export type NimiErrorSource = 'realm' | 'runtime' | 'sdk';

export type NimiError = Error & {
  code: string;
  reasonCode: string;
  actionHint: string;
  traceId: string;
  retryable: boolean;
  source: NimiErrorSource;
  details?: Record<string, unknown>;
};

export type ScopeName = string;

export type ScopeCatalogVersion = string;

export type CatalogHash = string;

export type ExternalPrincipalId = string;

export type ScopeDomain = 'realm' | 'runtime' | 'app';

export type ScopeCatalogStatus = 'draft' | 'published' | 'revoked';

export type ScopeManifest = {
  manifestVersion: string;
  scopes: ScopeName[];
};

export type ScopeCatalogEntry = {
  scopeCatalogVersion: ScopeCatalogVersion;
  catalogHash: CatalogHash;
  status: ScopeCatalogStatus;
  scopes: ScopeName[];
};

export type ScopeListCatalogInput = {
  appId: string;
  include?: ScopeDomain[];
};

export type ScopeRegisterAppScopesInput = {
  appId: string;
  manifest: ScopeManifest;
};

export type ScopePublishCatalogInput = {
  appId: string;
};

export type ScopeRevokeAppScopesInput = {
  appId: string;
  scopes: ScopeName[];
};

export type ScopeCatalogDescriptor = {
  appId: string;
  realmScopes: ScopeName[];
  runtimeScopes: ScopeName[];
  appScopes: ScopeName[];
  draft: ScopeCatalogEntry | null;
  published: ScopeCatalogEntry | null;
  revokedScopes: ScopeName[];
};

export type ScopeCatalogPublishResult = ScopeCatalogEntry & {
  publishedAt: string;
};

export type ScopeCatalogRevokeResult = ScopeCatalogEntry & {
  revokedScopes: ScopeName[];
  reauthorizeRequired: boolean;
};

export type AiRoutePolicy = 'local-runtime' | 'token-api';

export type AiFallbackPolicy = 'deny' | 'allow';

export type AiStreamEventType =
  | 'started'
  | 'delta'
  | 'tool_call'
  | 'tool_result'
  | 'usage'
  | 'completed'
  | 'failed';

export type AuthorizationPreset = 'readOnly' | 'full' | 'delegate';

export type AppPolicyMode = 'preset' | 'custom';

export type AppResourceSelectors = Record<string, string[]>;

export type AppConsentEvidence = {
  subjectUserId: string;
  consentId: string;
  consentVersion: string;
  decisionAt: string;
};

export type AppGrantPolicy = {
  policyVersion: string;
  policyMode: AppPolicyMode;
  preset?: AuthorizationPreset;
  scopes: ScopeName[];
  resourceSelectors?: AppResourceSelectors;
  canDelegate: boolean;
  maxDelegationDepth: number;
  ttlSeconds: number;
};

export type AppAccessTokenDescriptor = {
  tokenId: string;
  appId: string;
  subjectUserId: string;
  externalPrincipalId: ExternalPrincipalId;
  effectiveScopes: ScopeName[];
  policyVersion: string;
  issuedScopeCatalogVersion: ScopeCatalogVersion;
  expiresAt?: string;
};

export type DelegatedAccessTokenDescriptor = {
  tokenId: string;
  parentTokenId: string;
  effectiveScopes: ScopeName[];
  expiresAt?: string;
};

export const ReasonCode = {
  ACTION_ACCEPTED: 'ACTION_ACCEPTED',
  ACTION_COMMITTED: 'ACTION_COMMITTED',
  ACTION_CONTEXT_INVALID: 'ACTION_CONTEXT_INVALID',
  ACTION_DRY_RUN_UNSUPPORTED: 'ACTION_DRY_RUN_UNSUPPORTED',
  ACTION_EXECUTED: 'ACTION_EXECUTED',
  ACTION_EXECUTING: 'ACTION_EXECUTING',
  ACTION_EXECUTION_BRIDGE_FAILED: 'ACTION_EXECUTION_BRIDGE_FAILED',
  ACTION_EXECUTION_FAILED: 'ACTION_EXECUTION_FAILED',
  ACTION_IDEMPOTENCY_KEY_CONFLICT: 'ACTION_IDEMPOTENCY_KEY_CONFLICT',
  ACTION_IDEMPOTENCY_KEY_REQUIRED: 'ACTION_IDEMPOTENCY_KEY_REQUIRED',
  ACTION_IDEMPOTENCY_REPLAYED: 'ACTION_IDEMPOTENCY_REPLAYED',
  ACTION_INPUT_INVALID: 'ACTION_INPUT_INVALID',
  ACTION_INPUT_SCHEMA_INVALID: 'ACTION_INPUT_SCHEMA_INVALID',
  ACTION_NOT_FOUND: 'ACTION_NOT_FOUND',
  ACTION_OPAQUE_HIGH_RISK_FORBIDDEN: 'ACTION_OPAQUE_HIGH_RISK_FORBIDDEN',
  ACTION_OUTPUT_SCHEMA_INVALID: 'ACTION_OUTPUT_SCHEMA_INVALID',
  ACTION_PERMISSION_DENIED: 'ACTION_PERMISSION_DENIED',
  ACTION_RUNTIME_STORE_UNAVAILABLE: 'ACTION_RUNTIME_STORE_UNAVAILABLE',
  ACTION_VERIFIED: 'ACTION_VERIFIED',
  ACTION_VERIFY_REQUIRED: 'ACTION_VERIFY_REQUIRED',
  ACTION_VERIFY_TICKET_EXPIRED: 'ACTION_VERIFY_TICKET_EXPIRED',
  ACTION_VERIFY_TICKET_INVALID: 'ACTION_VERIFY_TICKET_INVALID',
  AI_APP_ID_CONFLICT: 'AI_APP_ID_CONFLICT',
  AI_APP_ID_REQUIRED: 'AI_APP_ID_REQUIRED',
  AI_CONNECTOR_CREDENTIAL_MISSING: 'AI_CONNECTOR_CREDENTIAL_MISSING',
  AI_CONNECTOR_DISABLED: 'AI_CONNECTOR_DISABLED',
  AI_CONNECTOR_ID_REQUIRED: 'AI_CONNECTOR_ID_REQUIRED',
  AI_CONNECTOR_IMMUTABLE: 'AI_CONNECTOR_IMMUTABLE',
  AI_CONNECTOR_INVALID: 'AI_CONNECTOR_INVALID',
  AI_CONNECTOR_LIMIT_EXCEEDED: 'AI_CONNECTOR_LIMIT_EXCEEDED',
  AI_CONNECTOR_NOT_FOUND: 'AI_CONNECTOR_NOT_FOUND',
  AI_CONTENT_FILTER_BLOCKED: 'AI_CONTENT_FILTER_BLOCKED',
  AI_FINISH_CONTENT_FILTER: 'AI_FINISH_CONTENT_FILTER',
  AI_FINISH_LENGTH: 'AI_FINISH_LENGTH',
  AI_INPUT_INVALID: 'AI_INPUT_INVALID',
  AI_LOCAL_ENDPOINT_REQUIRED: 'AI_LOCAL_ENDPOINT_REQUIRED',
  AI_LOCAL_MANIFEST_INVALID: 'AI_LOCAL_MANIFEST_INVALID',
  AI_LOCAL_MODEL_ALREADY_INSTALLED: 'AI_LOCAL_MODEL_ALREADY_INSTALLED',
  AI_LOCAL_MODEL_PROFILE_MISSING: 'AI_LOCAL_MODEL_PROFILE_MISSING',
  AI_LOCAL_MODEL_UNAVAILABLE: 'AI_LOCAL_MODEL_UNAVAILABLE',
  AI_MEDIA_IDEMPOTENCY_CONFLICT: 'AI_MEDIA_IDEMPOTENCY_CONFLICT',
  AI_MEDIA_JOB_NOT_CANCELLABLE: 'AI_MEDIA_JOB_NOT_CANCELLABLE',
  AI_MEDIA_JOB_NOT_FOUND: 'AI_MEDIA_JOB_NOT_FOUND',
  AI_MEDIA_OPTION_UNSUPPORTED: 'AI_MEDIA_OPTION_UNSUPPORTED',
  AI_MEDIA_SPEC_INVALID: 'AI_MEDIA_SPEC_INVALID',
  AI_MODALITY_NOT_SUPPORTED: 'AI_MODALITY_NOT_SUPPORTED',
  AI_MODEL_ID_REQUIRED: 'AI_MODEL_ID_REQUIRED',
  AI_MODEL_NOT_FOUND: 'AI_MODEL_NOT_FOUND',
  AI_MODEL_NOT_READY: 'AI_MODEL_NOT_READY',
  AI_MODEL_PROVIDER_MISMATCH: 'AI_MODEL_PROVIDER_MISMATCH',
  AI_MODULE_CONFIG_INVALID: 'AI_MODULE_CONFIG_INVALID',
  AI_OUTPUT_INVALID: 'AI_OUTPUT_INVALID',
  AI_PROVIDER_AUTH_FAILED: 'AI_PROVIDER_AUTH_FAILED',
  AI_PROVIDER_CIRCUIT_OPEN: 'AI_PROVIDER_CIRCUIT_OPEN',
  AI_PROVIDER_ENDPOINT_FORBIDDEN: 'AI_PROVIDER_ENDPOINT_FORBIDDEN',
  AI_PROVIDER_INTERNAL: 'AI_PROVIDER_INTERNAL',
  AI_PROVIDER_RATE_LIMITED: 'AI_PROVIDER_RATE_LIMITED',
  AI_PROVIDER_TIMEOUT: 'AI_PROVIDER_TIMEOUT',
  AI_PROVIDER_UNAVAILABLE: 'AI_PROVIDER_UNAVAILABLE',
  AI_REQUEST_CREDENTIAL_CONFLICT: 'AI_REQUEST_CREDENTIAL_CONFLICT',
  AI_REQUEST_CREDENTIAL_INVALID: 'AI_REQUEST_CREDENTIAL_INVALID',
  AI_REQUEST_CREDENTIAL_MISSING: 'AI_REQUEST_CREDENTIAL_MISSING',
  AI_ROUTE_FALLBACK_DENIED: 'AI_ROUTE_FALLBACK_DENIED',
  AI_ROUTE_UNSUPPORTED: 'AI_ROUTE_UNSUPPORTED',
  AI_STREAM_BROKEN: 'AI_STREAM_BROKEN',
  APP_AUTHORIZATION_DENIED: 'APP_AUTHORIZATION_DENIED',
  APP_CONSENT_INVALID: 'APP_CONSENT_INVALID',
  APP_CONSENT_MISSING: 'APP_CONSENT_MISSING',
  AUTH_CONTEXT_MISSING: 'AUTH_CONTEXT_MISSING',
  APP_DELEGATION_DEPTH_EXCEEDED: 'APP_DELEGATION_DEPTH_EXCEEDED',
  APP_DELEGATION_FORBIDDEN: 'APP_DELEGATION_FORBIDDEN',
  APP_GRANT_INVALID: 'APP_GRANT_INVALID',
  APP_MODE_DOMAIN_FORBIDDEN: 'APP_MODE_DOMAIN_FORBIDDEN',
  APP_MODE_MANIFEST_INVALID: 'APP_MODE_MANIFEST_INVALID',
  APP_MODE_SCOPE_FORBIDDEN: 'APP_MODE_SCOPE_FORBIDDEN',
  APP_MODE_WORLD_RELATION_FORBIDDEN: 'APP_MODE_WORLD_RELATION_FORBIDDEN',
  APP_NOT_REGISTERED: 'APP_NOT_REGISTERED',
  APP_RESOURCE_OUT_OF_SCOPE: 'APP_RESOURCE_OUT_OF_SCOPE',
  APP_RESOURCE_SELECTOR_INVALID: 'APP_RESOURCE_SELECTOR_INVALID',
  APP_SCOPE_CATALOG_UNPUBLISHED: 'APP_SCOPE_CATALOG_UNPUBLISHED',
  APP_SCOPE_CONFLICT: 'APP_SCOPE_CONFLICT',
  APP_SCOPE_FORBIDDEN: 'APP_SCOPE_FORBIDDEN',
  APP_SCOPE_MANIFEST_INVALID: 'APP_SCOPE_MANIFEST_INVALID',
  APP_SCOPE_NAMESPACE_FORBIDDEN: 'APP_SCOPE_NAMESPACE_FORBIDDEN',
  APP_SCOPE_REVOKED: 'APP_SCOPE_REVOKED',
  APP_TOKEN_EXPIRED: 'APP_TOKEN_EXPIRED',
  APP_TOKEN_REVOKED: 'APP_TOKEN_REVOKED',
  BUILD_REGISTRATION_FAILED: 'BUILD_REGISTRATION_FAILED',
  CAPABILITY_CATALOG_MISMATCH: 'CAPABILITY_CATALOG_MISMATCH',
  CODEGEN_BUNDLE_TOO_LARGE: 'CODEGEN_BUNDLE_TOO_LARGE',
  CODEGEN_CAPABILITY_DENIED: 'CODEGEN_CAPABILITY_DENIED',
  CODEGEN_CAPABILITY_UNKNOWN: 'CODEGEN_CAPABILITY_UNKNOWN',
  CODEGEN_MOD_ID_REQUIRED: 'CODEGEN_MOD_ID_REQUIRED',
  CODEGEN_PATTERN_EVAL_FORBIDDEN: 'CODEGEN_PATTERN_EVAL_FORBIDDEN',
  CODEGEN_PATTERN_FETCH_FORBIDDEN: 'CODEGEN_PATTERN_FETCH_FORBIDDEN',
  CODEGEN_PATTERN_HOST_IMPORT_FORBIDDEN: 'CODEGEN_PATTERN_HOST_IMPORT_FORBIDDEN',
  CODEGEN_PATTERN_IMPORTSCRIPTS_FORBIDDEN: 'CODEGEN_PATTERN_IMPORTSCRIPTS_FORBIDDEN',
  CODEGEN_PATTERN_LOCALSTORAGE_FORBIDDEN: 'CODEGEN_PATTERN_LOCALSTORAGE_FORBIDDEN',
  CODEGEN_PATTERN_NEW_FUNCTION_FORBIDDEN: 'CODEGEN_PATTERN_NEW_FUNCTION_FORBIDDEN',
  CODEGEN_PATTERN_PROCESS_ENV_FORBIDDEN: 'CODEGEN_PATTERN_PROCESS_ENV_FORBIDDEN',
  CODEGEN_PATTERN_REQUIRE_FORBIDDEN: 'CODEGEN_PATTERN_REQUIRE_FORBIDDEN',
  CODEGEN_PATTERN_WEBSOCKET_FORBIDDEN: 'CODEGEN_PATTERN_WEBSOCKET_FORBIDDEN',
  CODEGEN_PATTERN_XMLHTTPREQUEST_FORBIDDEN: 'CODEGEN_PATTERN_XMLHTTPREQUEST_FORBIDDEN',
  CODEGEN_T1_CONSENT_REQUIRED: 'CODEGEN_T1_CONSENT_REQUIRED',
  COMPAT_NO_MIN_VERSION: 'COMPAT_NO_MIN_VERSION',
  COMPAT_OK: 'COMPAT_OK',
  CONFIG_APPLIED: 'CONFIG_APPLIED',
  CONFIG_INVALID: 'CONFIG_INVALID',
  CONFIG_RESTART_REQUIRED: 'CONFIG_RESTART_REQUIRED',
  COMPAT_RUNTIME_TOO_NEW: 'COMPAT_RUNTIME_TOO_NEW',
  COMPAT_RUNTIME_TOO_OLD: 'COMPAT_RUNTIME_TOO_OLD',
  DISCOVERY_ALLOWED: 'DISCOVERY_ALLOWED',
  DISCOVERY_MODE_UNKNOWN: 'DISCOVERY_MODE_UNKNOWN',
  DISCOVERY_SOURCE_BLOCKED: 'DISCOVERY_SOURCE_BLOCKED',
  DISCOVERY_SOURCE_UNTRUSTED: 'DISCOVERY_SOURCE_UNTRUSTED',
  ENTRY_NOT_FOUND: 'ENTRY_NOT_FOUND',
  ENTRY_READ_FAILED: 'ENTRY_READ_FAILED',
  EXTERNAL_PRINCIPAL_NOT_REGISTERED: 'EXTERNAL_PRINCIPAL_NOT_REGISTERED',
  EXTERNAL_PRINCIPAL_PROOF_INVALID: 'EXTERNAL_PRINCIPAL_PROOF_INVALID',
  EXTERNAL_PRINCIPAL_PROOF_MISSING: 'EXTERNAL_PRINCIPAL_PROOF_MISSING',
  FACTORY_MISSING: 'FACTORY_MISSING',
  GRANT_TOKEN_CHAIN_ROOT_NOT_FOUND: 'GRANT_TOKEN_CHAIN_ROOT_NOT_FOUND',
  GRANT_TOKEN_CHAIN_ROOT_REQUIRED: 'GRANT_TOKEN_CHAIN_ROOT_REQUIRED',
  KISMET_ROUTE_UNAVAILABLE: 'KISMET_ROUTE_UNAVAILABLE',
  LIFECYCLE_NOT_FOUND: 'LIFECYCLE_NOT_FOUND',
  LOAD_FACTORY_FAILED: 'LOAD_FACTORY_FAILED',
  LOCAL_AI_AUDIT_WRITE_FAILED: 'LOCAL_AI_AUDIT_WRITE_FAILED',
  LOCAL_AI_CAPABILITY_MISSING: 'LOCAL_AI_CAPABILITY_MISSING',
  LOCAL_AI_DEPENDENCIES_DECLARATION_MISSING: 'LOCAL_AI_DEPENDENCIES_DECLARATION_MISSING',
  LOCAL_AI_DEPENDENCY_SNAPSHOT_FAILED: 'LOCAL_AI_DEPENDENCY_SNAPSHOT_FAILED',
  LOCAL_AI_DEPENDENCY_SNAPSHOT_RESOLVER_MISSING: 'LOCAL_AI_DEPENDENCY_SNAPSHOT_RESOLVER_MISSING',
  LOCAL_AI_HF_DOWNLOAD_PAUSED: 'LOCAL_AI_HF_DOWNLOAD_PAUSED',
  LOCAL_AI_MOD_ID_REQUIRED: 'LOCAL_AI_MOD_ID_REQUIRED',
  LOCAL_AI_PROVIDER_TIMEOUT: 'LOCAL_AI_PROVIDER_TIMEOUT',
  LOCAL_CHAT_PROACTIVE_ALLOWED: 'LOCAL_CHAT_PROACTIVE_ALLOWED',
  LOCAL_CHAT_PROACTIVE_POLICY_UNAVAILABLE: 'LOCAL_CHAT_PROACTIVE_POLICY_UNAVAILABLE',
  LOCAL_ONLY_NOT_SYNCED: 'LOCAL_ONLY_NOT_SYNCED',
  LOCAL_RUNTIME_LIFECYCLE_WRITE_DENIED: 'LOCAL_RUNTIME_LIFECYCLE_WRITE_DENIED',
  MOD_STATE_INVALID_KEY: 'MOD_STATE_INVALID_KEY',
  MOD_STATE_INVALID_OP: 'MOD_STATE_INVALID_OP',
  MOD_STATE_STORAGE_ERROR: 'MOD_STATE_STORAGE_ERROR',
  MOD_STATE_UNAVAILABLE: 'MOD_STATE_UNAVAILABLE',
  MOD_STATE_VALUE_TOO_LARGE: 'MOD_STATE_VALUE_TOO_LARGE',
  MOD_NOT_INSTALLED: 'MOD_NOT_INSTALLED',
  PLAY_PROVIDER_UNAVAILABLE: 'PLAY_PROVIDER_UNAVAILABLE',
  OPERATION_ABORTED: 'OPERATION_ABORTED',
  PAGE_TOKEN_INVALID: 'PAGE_TOKEN_INVALID',
  PRINCIPAL_UNAUTHORIZED: 'PRINCIPAL_UNAUTHORIZED',
  PROTOCOL_DOMAIN_FIELD_CONFLICT: 'PROTOCOL_DOMAIN_FIELD_CONFLICT',
  PROTOCOL_ENVELOPE_INVALID: 'PROTOCOL_ENVELOPE_INVALID',
  PROTOCOL_VERSION_MISMATCH: 'PROTOCOL_VERSION_MISMATCH',
  RUNTIME_BRIDGE_DAEMON_UNAVAILABLE: 'RUNTIME_BRIDGE_DAEMON_UNAVAILABLE',
  RUNTIME_CALL_FAILED: 'RUNTIME_CALL_FAILED',
  RUNTIME_EXCEPTION: 'RUNTIME_EXCEPTION',
  RUNTIME_GRPC_CANCELLED: 'RUNTIME_GRPC_CANCELLED',
  RUNTIME_GRPC_PERMISSION_DENIED: 'RUNTIME_GRPC_PERMISSION_DENIED',
  RUNTIME_MOD_REGISTER_FAILED: 'RUNTIME_MOD_REGISTER_FAILED',
  RUNTIME_ROUTE_CAPABILITY_MISSING: 'RUNTIME_ROUTE_CAPABILITY_MISSING',
  RUNTIME_ROUTE_DEGRADED: 'RUNTIME_ROUTE_DEGRADED',
  RUNTIME_ROUTE_HEALTHY: 'RUNTIME_ROUTE_HEALTHY',
  RUNTIME_ROUTE_MODEL_MISSING: 'RUNTIME_ROUTE_MODEL_MISSING',
  RUNTIME_ROUTE_UNAVAILABLE: 'RUNTIME_ROUTE_UNAVAILABLE',
  AUTH_DENIED: 'AUTH_DENIED',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_UNSUPPORTED_PROOF_TYPE: 'AUTH_UNSUPPORTED_PROOF_TYPE',
  REALM_CONFLICT: 'REALM_CONFLICT',
  REALM_NOT_FOUND: 'REALM_NOT_FOUND',
  REALM_RATE_LIMITED: 'REALM_RATE_LIMITED',
  REALM_UNAVAILABLE: 'REALM_UNAVAILABLE',
  RUNTIME_UNAVAILABLE: 'RUNTIME_UNAVAILABLE',
  RUNTIME_UNSPECIFIED_ERROR: 'RUNTIME_UNSPECIFIED_ERROR',
  SANDBOX_CAPABILITY_DENIED: 'SANDBOX_CAPABILITY_DENIED',
  SANDBOX_CAPABILITY_GRANTED: 'SANDBOX_CAPABILITY_GRANTED',
  SANDBOX_CAPABILITY_PATTERN_MATCH: 'SANDBOX_CAPABILITY_PATTERN_MATCH',
  SANDBOX_PROFILE_INACTIVE: 'SANDBOX_PROFILE_INACTIVE',
  SANDBOX_PROFILE_NOT_FOUND: 'SANDBOX_PROFILE_NOT_FOUND',
  SANDBOX_WILDCARD_GRANT: 'SANDBOX_WILDCARD_GRANT',
  SDK_AI_PROVIDER_BASE64_UNAVAILABLE: 'SDK_AI_PROVIDER_BASE64_UNAVAILABLE',
  SDK_AI_PROVIDER_CONFIG_INVALID: 'SDK_AI_PROVIDER_CONFIG_INVALID',
  SDK_AI_PROVIDER_RUNTIME_REQUIRED: 'SDK_AI_PROVIDER_RUNTIME_REQUIRED',
  SDK_AI_PROVIDER_SUBJECT_USER_ID_REQUIRED: 'SDK_AI_PROVIDER_SUBJECT_USER_ID_REQUIRED',
  SDK_APP_ID_REQUIRED: 'SDK_APP_ID_REQUIRED',
  SDK_MOD_HOST_MISSING: 'SDK_MOD_HOST_MISSING',
  SDK_REALM_CONFIG_INVALID: 'SDK_REALM_CONFIG_INVALID',
  SDK_REALM_ENDPOINT_REQUIRED: 'SDK_REALM_ENDPOINT_REQUIRED',
  SDK_REALM_TOKEN_REQUIRED: 'SDK_REALM_TOKEN_REQUIRED',
  SDK_RUNTIME_METHOD_UNAVAILABLE: 'SDK_RUNTIME_METHOD_UNAVAILABLE',
  SDK_RUNTIME_VERSION_INCOMPATIBLE: 'SDK_RUNTIME_VERSION_INCOMPATIBLE',
  SDK_SCOPE_CATALOG_INVALID: 'SDK_SCOPE_CATALOG_INVALID',
  SDK_SCOPE_CATALOG_VERSION_CONFLICT: 'SDK_SCOPE_CATALOG_VERSION_CONFLICT',
  SDK_TRANSPORT_INVALID: 'SDK_TRANSPORT_INVALID',
  SDK_RUNTIME_BASE64_DECODER_UNAVAILABLE: 'SDK_RUNTIME_BASE64_DECODER_UNAVAILABLE',
  SDK_RUNTIME_BASE64_ENCODER_UNAVAILABLE: 'SDK_RUNTIME_BASE64_ENCODER_UNAVAILABLE',
  SDK_RUNTIME_CODEC_MISSING: 'SDK_RUNTIME_CODEC_MISSING',
  SDK_RUNTIME_NODE_GRPC_EMPTY_RESPONSE: 'SDK_RUNTIME_NODE_GRPC_EMPTY_RESPONSE',
  SDK_RUNTIME_NODE_GRPC_ENDPOINT_REQUIRED: 'SDK_RUNTIME_NODE_GRPC_ENDPOINT_REQUIRED',
  SDK_RUNTIME_NODE_GRPC_STREAM_CLOSE_FAILED: 'SDK_RUNTIME_NODE_GRPC_STREAM_CLOSE_FAILED',
  SDK_RUNTIME_NODE_GRPC_STREAM_OPEN_FAILED: 'SDK_RUNTIME_NODE_GRPC_STREAM_OPEN_FAILED',
  SDK_RUNTIME_NODE_GRPC_UNARY_FAILED: 'SDK_RUNTIME_NODE_GRPC_UNARY_FAILED',
  SDK_RUNTIME_REQUEST_BYTES_REQUIRED: 'SDK_RUNTIME_REQUEST_BYTES_REQUIRED',
  SDK_RUNTIME_REQUEST_ENCODE_FAILED: 'SDK_RUNTIME_REQUEST_ENCODE_FAILED',
  SDK_RUNTIME_RESPONSE_DECODE_FAILED: 'SDK_RUNTIME_RESPONSE_DECODE_FAILED',
  SDK_RUNTIME_STREAM_DECODE_FAILED: 'SDK_RUNTIME_STREAM_DECODE_FAILED',
  SDK_RUNTIME_TAURI_INVOKE_MISSING: 'SDK_RUNTIME_TAURI_INVOKE_MISSING',
  SDK_RUNTIME_TAURI_LISTEN_MISSING: 'SDK_RUNTIME_TAURI_LISTEN_MISSING',
  SDK_RUNTIME_TAURI_STREAM_CLOSE_FAILED: 'SDK_RUNTIME_TAURI_STREAM_CLOSE_FAILED',
  SDK_RUNTIME_TAURI_STREAM_FAILED: 'SDK_RUNTIME_TAURI_STREAM_FAILED',
  SDK_RUNTIME_TAURI_STREAM_ID_MISSING: 'SDK_RUNTIME_TAURI_STREAM_ID_MISSING',
  SDK_RUNTIME_TAURI_STREAM_OPEN_FAILED: 'SDK_RUNTIME_TAURI_STREAM_OPEN_FAILED',
  SDK_RUNTIME_TAURI_STREAM_REMOTE_ERROR: 'SDK_RUNTIME_TAURI_STREAM_REMOTE_ERROR',
  SDK_RUNTIME_TAURI_UNARY_BYTES_MISSING: 'SDK_RUNTIME_TAURI_UNARY_BYTES_MISSING',
  SDK_RUNTIME_TAURI_UNARY_FAILED: 'SDK_RUNTIME_TAURI_UNARY_FAILED',
  SDK_TARGET_REQUIRED: 'SDK_TARGET_REQUIRED',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  SOCIAL_PRECONDITION_FAILED: 'SOCIAL_PRECONDITION_FAILED',
  SOURCE_DEFAULTED: 'SOURCE_DEFAULTED',
  STATE_DISABLED: 'STATE_DISABLED',
  STATE_ENABLED: 'STATE_ENABLED',
  STATE_UNINSTALLED: 'STATE_UNINSTALLED',
  SUBJECT_ACCOUNT_MISMATCH: 'SUBJECT_ACCOUNT_MISMATCH',
  TRANSITION_INITIAL: 'TRANSITION_INITIAL',
  TRANSITION_VALID: 'TRANSITION_VALID',
  WF_DAG_INVALID: 'WF_DAG_INVALID',
  WF_NODE_CONFIG_MISMATCH: 'WF_NODE_CONFIG_MISMATCH',
  WF_TASK_NOT_FOUND: 'WF_TASK_NOT_FOUND',
  WF_TIMEOUT: 'WF_TIMEOUT',
  WORLD_STUDIO_CONNECTOR_MISSING: 'WORLD_STUDIO_CONNECTOR_MISSING',
  WORLD_STUDIO_EMBEDDING_BUILDING: 'WORLD_STUDIO_EMBEDDING_BUILDING',
  WORLD_STUDIO_EMBEDDING_BUILD_FAILED: 'WORLD_STUDIO_EMBEDDING_BUILD_FAILED',
  WORLD_STUDIO_EMBEDDING_NOT_BUILT: 'WORLD_STUDIO_EMBEDDING_NOT_BUILT',
  WORLD_STUDIO_EMBEDDING_NOT_REQUIRED: 'WORLD_STUDIO_EMBEDDING_NOT_REQUIRED',
  WORLD_STUDIO_EMBEDDING_READY: 'WORLD_STUDIO_EMBEDDING_READY',
  WORLD_STUDIO_EMBEDDING_ROUTE_UNREADY: 'WORLD_STUDIO_EMBEDDING_ROUTE_UNREADY',
  WORLD_STUDIO_LOCAL_MODEL_MISSING: 'WORLD_STUDIO_LOCAL_MODEL_MISSING',
  WORLD_STUDIO_LOCAL_MODEL_UNAVAILABLE: 'WORLD_STUDIO_LOCAL_MODEL_UNAVAILABLE',
  WORLD_STUDIO_LOCAL_MODEL_UNHEALTHY: 'WORLD_STUDIO_LOCAL_MODEL_UNHEALTHY',
  WORLD_STUDIO_ROUTE_BINDING_MISSING: 'WORLD_STUDIO_ROUTE_BINDING_MISSING',
  WORLD_STUDIO_ROUTE_READY: 'WORLD_STUDIO_ROUTE_READY',
  WORLD_STUDIO_TOKEN_MODEL_UNAVAILABLE: 'WORLD_STUDIO_TOKEN_MODEL_UNAVAILABLE',
  WORLD_STUDIO_TOKEN_ROUTE_INCOMPLETE: 'WORLD_STUDIO_TOKEN_ROUTE_INCOMPLETE',
} as const;

export type NimiErrorCode = keyof typeof ReasonCode;

export type ReasonCodeValue = typeof ReasonCode[keyof typeof ReasonCode];

const RETRYABLE_REASON_CODES: ReadonlySet<string> = new Set([
  ReasonCode.AI_PROVIDER_RATE_LIMITED,
  ReasonCode.AI_PROVIDER_UNAVAILABLE,
  ReasonCode.AI_PROVIDER_TIMEOUT,
  ReasonCode.AI_STREAM_BROKEN,
  ReasonCode.SESSION_EXPIRED,
  ReasonCode.RUNTIME_UNAVAILABLE,
  ReasonCode.RUNTIME_BRIDGE_DAEMON_UNAVAILABLE,
]);

export function isRetryableReasonCode(code: string): boolean {
  return RETRYABLE_REASON_CODES.has(code);
}
