import type { ModelConfigCopy } from './types.js';

export const DEFAULT_MODEL_CONFIG_COPY: Required<ModelConfigCopy> = Object.freeze({
  title: 'AI configuration',
  description: 'Choose capability intent. Runtime validates the selected implementation when execution starts.',
  backLabel: 'Back',
  configuredSummary: 'Capability intents configured',
  emptySummary: 'No capability intent configured',
  routeLabel: 'Execution intent',
  localLabel: 'Local',
  cloudLabel: 'Cloud',
  saveLocalLabel: 'Save Local intent',
  saveCloudLabel: 'Save Cloud intent',
  savingLabel: 'Saving…',
  advancedLabel: 'Advanced',
  advancedHint: 'Required features are contract-local. Portable defaults must not contain Runtime connection or machine binding fields.',
  requiredFeaturesLabel: 'Required features',
  requiredFeaturesPlaceholder: 'Comma-separated capability features',
  defaultsLabel: 'Portable defaults (JSON)',
  defaultsPlaceholder: 'Optional capability defaults',
  localSelectedLabel: 'Machine selection',
  localMissingLabel: 'No Local Capability Configuration is selected for this capability.',
  localBrokenLabel: 'The selected Local Capability Configuration is currently blocked.',
  localUnavailableLabel: 'Machine Local AI Configuration could not be read.',
  localMismatchLabel: (features) => `The selected local configuration does not support: ${features}`,
  openMachineLabel: 'Open Local AI Configurations',
  cloudImplementationLabel: 'Cloud implementation',
  cloudImplementationPlaceholder: 'Choose an implementation',
  cloudTargetLabel: 'Provider-model target',
  cloudTargetPlaceholder: 'Choose a target',
  cloudTargetDialogTitle: 'Choose a Cloud target',
  cloudTargetDialogDescription: 'This choice remains a draft until the AIConfig owner is explicitly saved.',
  cloudTargetConfirmation: 'I confirm this implementation and provider-model target.',
  cloudAuthorizationLabel: 'Account authorization',
  cloudAuthorizationNone: 'No authorization selected',
  cloudAuthorizationNeeded: 'Account authorization is still selection-required. You may save this state and select an account later.',
  cloudAuthorizationRevoked: 'The selected account authorization was revoked.',
  cloudConnectorLabel: 'Create authorization from connector',
  cloudConnectorPlaceholder: 'Choose a connector',
  cloudCreateGrantLabel: 'Create authorization',
  cloudAuthorizationSeparation: 'Authorization identifies the account only; it does not select the implementation or provider-model target.',
  cloudAccountLabel: (account) => `Selected account: ${account}`,
  cloudImpactAppLabel: (account) => `Use ${account}. Provider usage may incur charges, and request data will leave this machine for this App capability.`,
  cloudImpactSharedLabel: (account) => `Use ${account}. Provider usage may incur charges and request data will leave this machine for every LocalAgent, including deferred and proactive work.`,
  cloudLoadFailed: 'Cloud implementation, target, or account choices could not be loaded.',
  retryLabel: 'Retry',
  loadFailed: 'AIConfig could not be loaded.',
  saveFailed: 'AIConfig could not be saved.',
  technicalDetailsLabel: 'Technical details',
  unsupportedCapabilityLabel: 'This capability is not admitted by the canonical Kit catalog.',
  notConfiguredLabel: 'Not configured',
  configuredLabel: 'Configured',
  selectionRequiredLabel: 'Selection required',
  blockedLabel: 'Blocked',
  mismatchLabel: 'Feature mismatch',
  cancelLabel: 'Cancel',
  confirmSelectionLabel: 'Use selection',
  capabilityLabel: (_capability, fallback) => fallback,
  capabilityDescription: (_capability, fallback) => fallback,
});

export function resolveModelConfigCopy(copy: ModelConfigCopy | undefined): Required<ModelConfigCopy> {
  return { ...DEFAULT_MODEL_CONFIG_COPY, ...copy };
}
