import type { ModelConfigCopy } from './types.js';

export const DEFAULT_MODEL_CONFIG_COPY: Required<ModelConfigCopy> = Object.freeze({
  title: 'Models',
  description: 'Choose the model used for each capability.',
  backLabel: 'Back',
  detailTitle: (capabilityLabel) => `${capabilityLabel} settings`,
  activeModelLabel: 'Active Model',
  activeModelHint: 'Choose another model',
  activeModelConfiguredLabel: 'set up',
  activeModelSetupPendingLabel: 'setup needed',
  modelPickerTitle: 'Select Model',
  modelPickerSearchPlaceholder: 'Search models',
  modelPickerLoadingLabel: 'Loading models…',
  modelPickerEmptyLabel: 'No models are available for this capability.',
  configuredSummary: 'Model settings complete',
  emptySummary: 'No model selected',
  routeLabel: 'Run mode',
  localLabel: 'On-device',
  cloudLabel: 'Cloud',
  saveLocalLabel: 'Save settings',
  saveCloudLabel: 'Save settings',
  savingLabel: 'Saving…',
  advancedLabel: 'Advanced',
  advancedHint: 'Required model capabilities and default parameters are saved with these model settings.',
  requiredFeaturesLabel: 'Required model capabilities',
  requiredFeaturesPlaceholder: 'Enter model capabilities, separated by commas',
  defaultsLabel: 'Default parameters',
  defaultsPlaceholder: 'Leave a field empty to keep that parameter unset.',
  defaultsUnsetLabel: 'Not set',
  defaultsTrueLabel: 'True',
  defaultsFalseLabel: 'False',
  defaultsListPlaceholder: 'One value per line',
  defaultsLocalEffectivePlaceholder: (value) => `Not set · Engine default ${value}`,
  defaultsCloudEffectivePlaceholder: 'Not set · Provider decides',
  defaultsRandomValue: 'random',
  localChoiceDescription: 'Use the model selected under On-device models.',
  localSelectedLabel: 'Currently used on this device',
  localMissingLabel: 'No on-device model is selected for this capability.',
  localBrokenLabel: 'The selected on-device model is unavailable.',
  localUnavailableLabel: 'The on-device model selection could not be loaded.',
  localMismatchLabel: (features) => `The selected on-device model does not support: ${features}`,
  openMachineLabel: 'Open on-device models',
  cloudConnectorPickerLabel: 'Cloud Connector',
  cloudConnectorPickerPlaceholder: 'Select a configured Connector',
  cloudConnectorSelectionRequired: 'Select a configured Connector before choosing a model.',
  cloudNoConnectorsLabel: 'No configured Cloud Connector is available.',
  openCloudConnectorsLabel: 'Configure Cloud Connectors',
  cloudImplementationLabel: 'Cloud service',
  cloudImplementationPlaceholder: 'Choose a cloud service',
  cloudTargetLabel: 'Cloud model',
  cloudTargetPlaceholder: 'Choose a cloud model',
  cloudTargetDialogTitle: 'Choose a cloud model',
  cloudTargetDialogDescription: 'Review the provider and model, then confirm your choice.',
  cloudTargetConfirmation: 'I confirm this cloud service and model.',
  cloudAuthorizationLabel: 'Cloud execution route',
  cloudAuthorizationNone: 'Current Nimi account',
  cloudConnectorLabel: 'Create authorization from connector',
  cloudConnectorPlaceholder: 'Choose a connector',
  cloudAuthorizationSeparation: 'Nimi resolves the current account Connector and credential at execution time.',
  cloudAccountLabel: (account) => `Execution owner: ${account}`,
  cloudImpactAppLabel: (account) => `Use ${account}. Requests may leave this device and incur provider charges.`,
  cloudImpactSharedLabel: (account) => `Use ${account} for every local agent, including proactive tasks. Requests may leave this device and incur provider charges.`,
  cloudLoadFailed: 'Cloud service, model, or account choices could not be loaded.',
  retryLabel: 'Retry',
  loadFailed: 'Model settings could not be loaded.',
  saveFailed: 'Model settings could not be saved.',
  technicalDetailsLabel: 'Technical details',
  unsupportedCapabilityLabel: "This capability isn't supported in this version.",
  notConfiguredLabel: 'Not configured',
  configuredLabel: 'Configured',
  selectionRequiredLabel: 'Selection required',
  blockedLabel: 'Blocked',
  mismatchLabel: 'Feature mismatch',
  cancelLabel: 'Cancel',
  confirmSelectionLabel: 'Use selection',
  capabilityLabel: (_capability, fallback) => fallback,
  capabilityDescription: (_capability, fallback) => fallback,
});

export function resolveModelConfigCopy(copy: ModelConfigCopy | undefined): Required<ModelConfigCopy> {
  return { ...DEFAULT_MODEL_CONFIG_COPY, ...copy };
}
