// Code generated by sdks/generators/generate.mjs; DO NOT EDIT.

package coregenerated

import (
	"context"
	"fmt"

	"github.com/nimiplatform/nimi/sdks/go/coreclient"
	sdkstypes "github.com/nimiplatform/nimi/sdks/go/types"
)

type RealmOperationDescriptor struct {
	OperationID string
	Service     string
	Method      string
	Path        string
}

var RealmOperations = []RealmOperationDescriptor{
	{OperationID: "addFriend", Service: "User", Method: "POST", Path: "/api/human/accounts/{id}/friends"},
	{OperationID: "addGroupParticipant", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats/{chatId}/participants"},
	{OperationID: "addGroupSourceParticipant", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats/{chatId}/source-participants"},
	{OperationID: "archiveBundle", Service: "Bundles", Method: "POST", Path: "/api/bundles/{bundleId}/archive"},
	{OperationID: "bindEmail", Service: "Auth", Method: "POST", Path: "/api/auth/me/email"},
	{OperationID: "bindWallet", Service: "Me", Method: "POST", Path: "/api/human/me/wallets"},
	{OperationID: "blockUser", Service: "Me", Method: "POST", Path: "/api/human/me/blocks/{id}"},
	{OperationID: "changeEmail", Service: "Auth", Method: "PATCH", Path: "/api/auth/me/email"},
	{OperationID: "checkEmail", Service: "Auth", Method: "POST", Path: "/api/auth/email/check"},
	{OperationID: "checkHandle", Service: "User", Method: "GET", Path: "/api/human/check-handle"},
	{OperationID: "cloneAsset", Service: "Assets", Method: "POST", Path: "/api/assets/{assetId}/clone"},
	{OperationID: "commitRealmGroupSourceMessageCandidate", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats/{chatId}/source-message-candidate-commits"},
	{OperationID: "createAsset", Service: "Assets", Method: "POST", Path: "/api/assets"},
	{OperationID: "createAudioDirectUpload", Service: "Resources", Method: "POST", Path: "/api/resources/audio/direct-upload"},
	{OperationID: "createBundle", Service: "Bundles", Method: "POST", Path: "/api/bundles"},
	{OperationID: "createGroup", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats"},
	{OperationID: "createImageDirectUpload", Service: "Resources", Method: "POST", Path: "/api/resources/images/direct-upload"},
	{OperationID: "createPost", Service: "Posts", Method: "POST", Path: "/api/world/posts"},
	{OperationID: "createTextResource", Service: "Resources", Method: "POST", Path: "/api/resources/texts"},
	{OperationID: "createVideoDirectUpload", Service: "Resources", Method: "POST", Path: "/api/resources/videos/direct-upload"},
	{OperationID: "deletePost", Service: "Posts", Method: "DELETE", Path: "/api/world/posts/by-id/{id}"},
	{OperationID: "deleteResource", Service: "Resources", Method: "DELETE", Path: "/api/resources/{resourceId}"},
	{OperationID: "denyMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "POST", Path: "/api/human/me/permission-grants/by-id/{grantId}/deny"},
	{OperationID: "disable2Fa", Service: "Me2fa", Method: "POST", Path: "/api/auth/me/2fa/disable"},
	{OperationID: "EconomyController_acceptGift", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/gifts/{id}/accept"},
	{OperationID: "EconomyController_calculateWithdrawal", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/withdrawals/calculate"},
	{OperationID: "EconomyController_cancelSubscription", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/subscription/cancel"},
	{OperationID: "EconomyController_canWithdraw", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/withdrawals/can-withdraw"},
	{OperationID: "EconomyController_createConnectDashboard", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/connect/dashboard"},
	{OperationID: "EconomyController_createConnectOnboarding", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/connect/onboarding"},
	{OperationID: "EconomyController_createPortalSession", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/subscription/portal"},
	{OperationID: "EconomyController_createSparkCheckout", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/spark/checkout"},
	{OperationID: "EconomyController_createSubscriptionCheckout", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/subscription/checkout"},
	{OperationID: "EconomyController_createWithdrawal", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/withdrawals/create"},
	{OperationID: "EconomyController_getBalances", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/balances"},
	{OperationID: "EconomyController_getConnectStatus", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/connect/status"},
	{OperationID: "EconomyController_getGemHistory", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/gem/history"},
	{OperationID: "EconomyController_getGiftCatalog", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/gifts/catalog"},
	{OperationID: "EconomyController_getReceivedGifts", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/gifts/received"},
	{OperationID: "EconomyController_getRevenueShareConfig", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/revenue-share/config"},
	{OperationID: "EconomyController_getSentGifts", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/gifts/sent"},
	{OperationID: "EconomyController_getSourceOrigin", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/revenue-share/source-origin/{sourceRef}"},
	{OperationID: "EconomyController_getSparkHistory", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/spark/history"},
	{OperationID: "EconomyController_getSparkPackages", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/spark/packages"},
	{OperationID: "EconomyController_getSubscription", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/subscription"},
	{OperationID: "EconomyController_getSubscriptionTiers", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/subscription/tiers"},
	{OperationID: "EconomyController_getWithdrawal", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/withdrawals/by-id/{id}"},
	{OperationID: "EconomyController_getWithdrawalConfig", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/withdrawals/config"},
	{OperationID: "EconomyController_getWithdrawalHistory", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/withdrawals/history"},
	{OperationID: "EconomyController_previewRevenueDistribution", Service: "Economy (Currency & Gifts)", Method: "GET", Path: "/api/economy/revenue-share/preview"},
	{OperationID: "EconomyController_rejectGift", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/gifts/{giftId}/reject"},
	{OperationID: "EconomyController_sendGift", Service: "Economy (Currency & Gifts)", Method: "POST", Path: "/api/economy/gifts/send"},
	{OperationID: "editGroupMessage", Service: "Group Chats", Method: "PATCH", Path: "/api/human/group-chats/{chatId}/messages/{messageId}"},
	{OperationID: "editMessage", Service: "Human Chats", Method: "PATCH", Path: "/api/human/chats/{chatId}/messages/{messageId}"},
	{OperationID: "enable2Fa", Service: "Me2fa", Method: "POST", Path: "/api/auth/me/2fa/enable"},
	{OperationID: "expireMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "POST", Path: "/api/human/me/permission-grants/by-id/{grantId}/expire"},
	{OperationID: "ExploreController_checkStatus", Service: "Explore", Method: "GET", Path: "/api/explore/status"},
	{OperationID: "finalizeResource", Service: "Resources", Method: "POST", Path: "/api/resources/{resourceId}/finalize"},
	{OperationID: "getAsset", Service: "Assets", Method: "GET", Path: "/api/assets/{assetId}"},
	{OperationID: "getAuthJwks", Service: "Jwks", Method: "GET", Path: "/api/auth/jwks"},
	{OperationID: "getBundle", Service: "Bundles", Method: "GET", Path: "/api/bundles/{bundleId}"},
	{OperationID: "getChatById", Service: "Human Chats", Method: "GET", Path: "/api/human/chats/{chatId}"},
	{OperationID: "getExploreFeed", Service: "Explore", Method: "GET", Path: "/api/explore"},
	{OperationID: "getGroup", Service: "Group Chats", Method: "GET", Path: "/api/human/group-chats/{chatId}"},
	{OperationID: "getHomeFeed", Service: "Posts", Method: "GET", Path: "/api/world/posts"},
	{OperationID: "getMe", Service: "Me", Method: "GET", Path: "/api/human/me"},
	{OperationID: "getMutualFriends", Service: "User", Method: "GET", Path: "/api/human/accounts/{id}/mutual-friends"},
	{OperationID: "getMutualFriendsCount", Service: "User", Method: "GET", Path: "/api/human/accounts/{id}/mutual-friends/count"},
	{OperationID: "getMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "GET", Path: "/api/human/me/permission-grants/by-id/{grantId}"},
	{OperationID: "getMyAppPermissionGrantStatus", Service: "Me / Permission Grants", Method: "GET", Path: "/api/human/me/permission-grants/status"},
	{OperationID: "getMyAppPermissionGrantView", Service: "Me / Permission Grants", Method: "GET", Path: "/api/human/me/permission-grants/view"},
	{OperationID: "getMyBlockedUsers", Service: "Me", Method: "GET", Path: "/api/human/me/blocks"},
	{OperationID: "getMyCapabilities", Service: "Me", Method: "GET", Path: "/api/human/me/capabilities"},
	{OperationID: "getMyCreatorEligibility", Service: "Me", Method: "GET", Path: "/api/human/me/creator-eligibility"},
	{OperationID: "getMyNotificationSettings", Service: "Me", Method: "GET", Path: "/api/human/me/notification-settings"},
	{OperationID: "getMyPendingFriendRequests", Service: "Me", Method: "GET", Path: "/api/human/me/friends/pending"},
	{OperationID: "getMyPPConfig", Service: "Me", Method: "GET", Path: "/api/human/me/pp-config"},
	{OperationID: "getMySettings", Service: "Me", Method: "GET", Path: "/api/human/me/settings"},
	{OperationID: "getMyTiers", Service: "Me", Method: "GET", Path: "/api/human/me/tiers"},
	{OperationID: "getMyWallets", Service: "Me", Method: "GET", Path: "/api/human/me/wallets"},
	{OperationID: "getPost", Service: "Posts", Method: "GET", Path: "/api/world/posts/by-id/{id}"},
	{OperationID: "getPublicPost", Service: "Posts", Method: "GET", Path: "/api/world/posts/public/{id}"},
	{OperationID: "getResource", Service: "Resources", Method: "GET", Path: "/api/resources/{resourceId}"},
	{OperationID: "getUnreadCount", Service: "Notifications", Method: "GET", Path: "/api/human/notifications/unread-count"},
	{OperationID: "getUser", Service: "User", Method: "GET", Path: "/api/human/accounts/{id}"},
	{OperationID: "getUserByHandle", Service: "User", Method: "GET", Path: "/api/human/handle/{handle}"},
	{OperationID: "getUserFriends", Service: "User", Method: "GET", Path: "/api/human/accounts/{id}/friends"},
	{OperationID: "getWorldPosts", Service: "WorldPost", Method: "GET", Path: "/api/world/by-id/{worldId}/posts"},
	{OperationID: "grantMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "POST", Path: "/api/human/me/permission-grants/by-id/{grantId}/grant"},
	{OperationID: "introspectSession", Service: "Auth", Method: "POST", Path: "/api/auth/sessions/introspect"},
	{OperationID: "InvitationController_generateCode", Service: "Invitations", Method: "POST", Path: "/api/invitations"},
	{OperationID: "InvitationController_listMyCodes", Service: "Invitations", Method: "GET", Path: "/api/invitations"},
	{OperationID: "InvitationController_verifyCode", Service: "Invitations", Method: "POST", Path: "/api/invitations/verify"},
	{OperationID: "issueRuntimeRealmGrant", Service: "Runtime Realm Grants", Method: "POST", Path: "/api/runtime/realm-grants/issue"},
	{OperationID: "likePost", Service: "Posts", Method: "POST", Path: "/api/world/posts/by-id/{postId}/like"},
	{OperationID: "linkOauth", Service: "Auth", Method: "POST", Path: "/api/auth/oauth/link"},
	{OperationID: "listAssets", Service: "Assets", Method: "GET", Path: "/api/assets"},
	{OperationID: "listBundles", Service: "Bundles", Method: "GET", Path: "/api/bundles"},
	{OperationID: "listChats", Service: "Human Chats", Method: "GET", Path: "/api/human/chats"},
	{OperationID: "listGroupMessages", Service: "Group Chats", Method: "GET", Path: "/api/human/group-chats/{chatId}/messages"},
	{OperationID: "listGroups", Service: "Group Chats", Method: "GET", Path: "/api/human/group-chats"},
	{OperationID: "listLikedPosts", Service: "Posts", Method: "GET", Path: "/api/world/posts/liked"},
	{OperationID: "listMessages", Service: "Human Chats", Method: "GET", Path: "/api/human/chats/{chatId}/messages"},
	{OperationID: "listMyAppPermissionGrants", Service: "Me / Permission Grants", Method: "GET", Path: "/api/human/me/permission-grants"},
	{OperationID: "listMyFriendIds", Service: "Me", Method: "GET", Path: "/api/human/me/friends"},
	{OperationID: "listMyFriendsWithDetails", Service: "Me", Method: "GET", Path: "/api/human/me/friends/list"},
	{OperationID: "listNotifications", Service: "Notifications", Method: "GET", Path: "/api/human/notifications"},
	{OperationID: "listOnlineUsers", Service: "User", Method: "GET", Path: "/api/human/online"},
	{OperationID: "listResources", Service: "Resources", Method: "GET", Path: "/api/resources"},
	{OperationID: "logout", Service: "Auth", Method: "POST", Path: "/api/auth/logout"},
	{OperationID: "markChatRead", Service: "Human Chats", Method: "POST", Path: "/api/human/chats/{chatId}/read"},
	{OperationID: "markGroupRead", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats/{chatId}/read"},
	{OperationID: "markNotificationRead", Service: "Notifications", Method: "POST", Path: "/api/human/notifications/{notificationId}/read"},
	{OperationID: "markNotificationsRead", Service: "Notifications", Method: "POST", Path: "/api/human/notifications/read"},
	{OperationID: "oauthAuthorize", Service: "Auth", Method: "GET", Path: "/api/auth/oauth/authorize"},
	{OperationID: "oauthLogin", Service: "Auth", Method: "POST", Path: "/api/auth/oauth/login"},
	{OperationID: "oauthToken", Service: "Auth", Method: "POST", Path: "/api/auth/oauth/token"},
	{OperationID: "passwordLogin", Service: "Auth", Method: "POST", Path: "/api/auth/password/login"},
	{OperationID: "passwordRegister", Service: "Auth", Method: "POST", Path: "/api/auth/password/register"},
	{OperationID: "prepare2Fa", Service: "Me2fa", Method: "POST", Path: "/api/auth/me/2fa/prepare"},
	{OperationID: "prepareBindWallet", Service: "Me", Method: "POST", Path: "/api/human/me/wallets/prepare-bind"},
	{OperationID: "publishBundle", Service: "Bundles", Method: "POST", Path: "/api/bundles/{bundleId}/publish"},
	{OperationID: "recallGroupMessage", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats/{chatId}/messages/{messageId}/recall"},
	{OperationID: "recallMessage", Service: "Human Chats", Method: "POST", Path: "/api/human/chats/{chatId}/messages/{messageId}/recall"},
	{OperationID: "refreshToken", Service: "Auth", Method: "POST", Path: "/api/auth/refresh"},
	{OperationID: "RelationshipController_createRelationship", Service: "Relationships (Meta-Graph)", Method: "POST", Path: "/api/human/relationships"},
	{OperationID: "RelationshipController_deleteRelationship", Service: "Relationships (Meta-Graph)", Method: "DELETE", Path: "/api/human/relationships/{id}"},
	{OperationID: "RelationshipController_getMyRelationships", Service: "Relationships (Meta-Graph)", Method: "GET", Path: "/api/human/relationships/me"},
	{OperationID: "RelationshipController_updateRelationship", Service: "Relationships (Meta-Graph)", Method: "PATCH", Path: "/api/human/relationships/{id}"},
	{OperationID: "removeFriend", Service: "User", Method: "DELETE", Path: "/api/human/accounts/{id}/friends"},
	{OperationID: "removeGroupParticipant", Service: "Group Chats", Method: "DELETE", Path: "/api/human/group-chats/{chatId}/participants/{accountId}"},
	{OperationID: "removeGroupSourceParticipant", Service: "Group Chats", Method: "DELETE", Path: "/api/human/group-chats/{chatId}/source-participants/{runtimeParticipantSlotId}"},
	{OperationID: "ReportController_createReport", Service: "Governance", Method: "POST", Path: "/api/reports"},
	{OperationID: "requestAccountDeletion", Service: "MeAccountData", Method: "POST", Path: "/api/auth/me/account-deletion"},
	{OperationID: "requestDataExport", Service: "MeAccountData", Method: "POST", Path: "/api/auth/me/data-export"},
	{OperationID: "requestEmailOtp", Service: "Auth", Method: "POST", Path: "/api/auth/email/otp/request"},
	{OperationID: "requestMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "POST", Path: "/api/human/me/permission-grants"},
	{OperationID: "ReviewController_createReview", Service: "Reviews (Economy/Trust)", Method: "POST", Path: "/api/economy/reviews"},
	{OperationID: "ReviewController_getReviews", Service: "Reviews (Economy/Trust)", Method: "GET", Path: "/api/economy/reviews"},
	{OperationID: "revokeMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "POST", Path: "/api/human/me/permission-grants/by-id/{grantId}/revoke"},
	{OperationID: "searchHumanUsers", Service: "User", Method: "GET", Path: "/api/human/search"},
	{OperationID: "searchIndexedUsers", Service: "Search", Method: "GET", Path: "/api/search/users"},
	{OperationID: "searchPosts", Service: "Search", Method: "GET", Path: "/api/search/posts"},
	{OperationID: "sendGroupMessage", Service: "Group Chats", Method: "POST", Path: "/api/human/group-chats/{chatId}/messages"},
	{OperationID: "sendMessage", Service: "Human Chats", Method: "POST", Path: "/api/human/chats/{chatId}/messages"},
	{OperationID: "SourceConnectionController_connect", Service: "Source Connections", Method: "POST", Path: "/api/human/source-connections"},
	{OperationID: "SourceConnectionController_connectPublicSource", Service: "Source Connections", Method: "POST", Path: "/api/human/source-connections/public-source"},
	{OperationID: "SourceConnectionController_get", Service: "Source Connections", Method: "GET", Path: "/api/human/source-connections/{id}"},
	{OperationID: "SourceConnectionController_list", Service: "Source Connections", Method: "GET", Path: "/api/human/source-connections"},
	{OperationID: "SourceConnectionController_remove", Service: "Source Connections", Method: "DELETE", Path: "/api/human/source-connections/{id}"},
	{OperationID: "startChat", Service: "Human Chats", Method: "POST", Path: "/api/human/chats"},
	{OperationID: "supersedeMyAppPermissionGrant", Service: "Me / Permission Grants", Method: "POST", Path: "/api/human/me/permission-grants/by-id/{grantId}/supersede"},
	{OperationID: "syncChatEvents", Service: "Human Chats", Method: "GET", Path: "/api/human/chats/{chatId}/sync"},
	{OperationID: "syncGroupEvents", Service: "Group Chats", Method: "GET", Path: "/api/human/group-chats/{chatId}/sync"},
	{OperationID: "TransitController_abandon", Service: "Transits", Method: "POST", Path: "/api/world/transit/{id}/abandon"},
	{OperationID: "TransitController_complete", Service: "Transits", Method: "POST", Path: "/api/world/transit/{id}/complete"},
	{OperationID: "TransitController_createTransit", Service: "Transits", Method: "POST", Path: "/api/world/transit"},
	{OperationID: "TransitController_getActiveTransit", Service: "Transits", Method: "GET", Path: "/api/world/transit/active/{runtimeSourceRef}"},
	{OperationID: "TransitController_getTransit", Service: "Transits", Method: "GET", Path: "/api/world/transit/{id}"},
	{OperationID: "TransitController_listTransits", Service: "Transits", Method: "GET", Path: "/api/world/transit"},
	{OperationID: "translateText", Service: "Translation", Method: "POST", Path: "/api/translation/translate"},
	{OperationID: "unbindWallet", Service: "Me", Method: "DELETE", Path: "/api/human/me/wallets/{walletId}"},
	{OperationID: "unblockUser", Service: "Me", Method: "DELETE", Path: "/api/human/me/blocks/{id}"},
	{OperationID: "unlikePost", Service: "Posts", Method: "DELETE", Path: "/api/world/posts/by-id/{postId}/like"},
	{OperationID: "unlinkOauth", Service: "Auth", Method: "DELETE", Path: "/api/auth/oauth/{provider}"},
	{OperationID: "updateAsset", Service: "Assets", Method: "PATCH", Path: "/api/assets/{assetId}"},
	{OperationID: "updateBundle", Service: "Bundles", Method: "PATCH", Path: "/api/bundles/{bundleId}"},
	{OperationID: "updateGroup", Service: "Group Chats", Method: "PATCH", Path: "/api/human/group-chats/{chatId}"},
	{OperationID: "updateGroupParticipantRole", Service: "Group Chats", Method: "PATCH", Path: "/api/human/group-chats/{chatId}/participants/{accountId}"},
	{OperationID: "updateMe", Service: "Me", Method: "PATCH", Path: "/api/human/me"},
	{OperationID: "updateMyHandle", Service: "Me", Method: "PATCH", Path: "/api/human/me/handle"},
	{OperationID: "updateMyNotificationSettings", Service: "Me", Method: "PATCH", Path: "/api/human/me/notification-settings"},
	{OperationID: "updateMyPPConfig", Service: "Me", Method: "PUT", Path: "/api/human/me/pp-config"},
	{OperationID: "updateMySettings", Service: "Me", Method: "PATCH", Path: "/api/human/me/settings"},
	{OperationID: "updatePassword", Service: "Auth", Method: "PUT", Path: "/api/auth/me/password"},
	{OperationID: "updatePost", Service: "Posts", Method: "PATCH", Path: "/api/world/posts/by-id/{id}"},
	{OperationID: "updateResource", Service: "Resources", Method: "PATCH", Path: "/api/resources/{resourceId}"},
	{OperationID: "verify2Fa", Service: "Auth", Method: "POST", Path: "/api/auth/2fa/verify"},
	{OperationID: "verifyEmailOtp", Service: "Auth", Method: "POST", Path: "/api/auth/email/otp/verify"},
	{OperationID: "walletChallenge", Service: "Auth", Method: "POST", Path: "/api/auth/wallet/challenge"},
	{OperationID: "walletLogin", Service: "Auth", Method: "POST", Path: "/api/auth/wallet/login"},
	{OperationID: "WorldCoreController_bootstrapOasisWorld", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/oasis/bootstrap"},
	{OperationID: "WorldCoreController_createRealmPersona", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/personas"},
	{OperationID: "WorldCoreController_createRuntimeSourceSnapshot", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/runtime-source-snapshots"},
	{OperationID: "WorldCoreController_createWorldCharacter", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/worlds/{worldId}/characters"},
	{OperationID: "WorldCoreController_createWorldCore", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/worlds"},
	{OperationID: "WorldCoreController_createWorldEntity", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/worlds/{worldId}/entities"},
	{OperationID: "WorldCoreController_createWorldRelationship", Service: "Realm Core", Method: "POST", Path: "/api/realm/core/worlds/{worldId}/relationships"},
	{OperationID: "WorldCoreController_getOasisWorld", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/oasis"},
	{OperationID: "WorldCoreController_getRealmPersona", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/personas/{personaId}"},
	{OperationID: "WorldCoreController_getWorldCharacter", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/world-characters/{characterId}"},
	{OperationID: "WorldCoreController_getWorldCore", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/worlds/{worldId}"},
	{OperationID: "WorldCoreController_getWorldEntity", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/world-entities/{entityId}"},
	{OperationID: "WorldCoreController_getWorldRelationship", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/world-relationships/{relationshipId}"},
	{OperationID: "WorldCoreController_listRealmPersonas", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/personas"},
	{OperationID: "WorldCoreController_listWorldCharacters", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/worlds/{worldId}/characters"},
	{OperationID: "WorldCoreController_listWorldCores", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/worlds"},
	{OperationID: "WorldCoreController_listWorldEntities", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/worlds/{worldId}/entities"},
	{OperationID: "WorldCoreController_listWorldRelationships", Service: "Realm Core", Method: "GET", Path: "/api/realm/core/worlds/{worldId}/relationships"},
	{OperationID: "WorldCoreController_replaceRealmPersona", Service: "Realm Core", Method: "PUT", Path: "/api/realm/core/personas/{personaId}"},
	{OperationID: "WorldCoreController_replaceWorldCharacter", Service: "Realm Core", Method: "PUT", Path: "/api/realm/core/world-characters/{characterId}"},
	{OperationID: "WorldCoreController_replaceWorldCore", Service: "Realm Core", Method: "PUT", Path: "/api/realm/core/worlds/{worldId}"},
	{OperationID: "WorldCoreController_replaceWorldEntity", Service: "Realm Core", Method: "PUT", Path: "/api/realm/core/world-entities/{entityId}"},
	{OperationID: "WorldCoreController_replaceWorldRelationship", Service: "Realm Core", Method: "PUT", Path: "/api/realm/core/world-relationships/{relationshipId}"},
	{OperationID: "WorldPublicController_getWorld", Service: "World", Method: "GET", Path: "/api/world/by-id/{worldId}"},
	{OperationID: "WorldPublicController_getWorldDetailWithCharacters", Service: "World", Method: "GET", Path: "/api/world/by-id/{worldId}/detail-with-characters"},
	{OperationID: "WorldPublicController_listWorldCharacters", Service: "World", Method: "GET", Path: "/api/world/by-id/{worldId}/characters"},
	{OperationID: "WorldPublicController_listWorlds", Service: "World", Method: "GET", Path: "/api/world"},
}

var RealmOperationByID = func() map[string]RealmOperationDescriptor {
	out := map[string]RealmOperationDescriptor{}
	for _, operation := range RealmOperations {
		out[operation.OperationID] = operation
	}
	return out
}()

type RealmGeneratedClient struct {
	core coreclient.Client
}

func NewRealmGeneratedClient(core coreclient.Client) RealmGeneratedClient {
	return RealmGeneratedClient{core: core}
}

func (c RealmGeneratedClient) Describe(operationID string) (RealmOperationDescriptor, error) {
	descriptor, ok := RealmOperationByID[operationID]
	if !ok {
		return RealmOperationDescriptor{}, fmt.Errorf("SDK_REALM_CONFIG_INVALID: unknown Realm operation %s", operationID)
	}
	return descriptor, nil
}

func (c RealmGeneratedClient) Operation(ctx context.Context, operationID string, body []byte, metadata sdkstypes.CoreMetadata, timeoutMS int64) ([]byte, error) {
	if _, err := c.Describe(operationID); err != nil {
		return nil, err
	}
	return c.core.Unary(ctx, sdkstypes.CoreUnaryRequest{Context: ctx, MethodID: operationID, Metadata: metadata, Body: body, TimeoutMS: timeoutMS})
}
