// Code generated by scripts/generate-platform-catalog.mjs. DO NOT EDIT.

package platformcatalog

type FactoryAIProfileRow struct {
	Alias                     string
	CapabilitySet             []string
	HostCapabilityProfileRefs []string
}

const FactoryAIProfileCatalogID = "platform_ai_profile_factory_catalog"
const FactoryAIProfileCatalogVersion = 1

var FactoryAIProfileRows = []FactoryAIProfileRow{
	{
		Alias:                     "cloud-first",
		CapabilitySet:             []string{"text.generate", "text.embed", "audio.synthesize", "audio.transcribe", "image.generate"},
		HostCapabilityProfileRefs: []string{"windows-amd64-cpu", "windows-amd64-nvidia-cuda", "darwin-arm64-metal"},
	},
	{
		Alias:                     "local-standard",
		CapabilitySet:             []string{"text.generate", "text.embed"},
		HostCapabilityProfileRefs: []string{"windows-amd64-cpu", "darwin-arm64-metal", "windows-amd64-nvidia-cuda"},
	},
	{
		Alias:                     "local-speech",
		CapabilitySet:             []string{"text.generate", "audio.transcribe", "audio.synthesize"},
		HostCapabilityProfileRefs: []string{"windows-amd64-cpu", "darwin-arm64-metal", "windows-amd64-nvidia-cuda"},
	},
	{
		Alias:                     "local-gpu",
		CapabilitySet:             []string{"text.generate", "audio.transcribe", "audio.synthesize", "image.generate"},
		HostCapabilityProfileRefs: []string{"windows-amd64-nvidia-cuda", "darwin-arm64-metal"},
	},
	{
		Alias:                     "hybrid-recommended",
		CapabilitySet:             []string{"text.generate", "text.embed", "audio.transcribe", "audio.synthesize", "image.generate", "video.generate"},
		HostCapabilityProfileRefs: []string{"windows-amd64-nvidia-cuda", "darwin-arm64-metal", "windows-amd64-cpu"},
	},
}
