// @generated by sdks/generators/generate.mjs
// DO NOT EDIT MANUALLY.

export enum AgentAutonomyMode {
  UNSPECIFIED = 0,
  OFF = 1,
  LOW = 2,
  MEDIUM = 3,
  HIGH = 4,
}

export enum AgentCanonicalMemoryBankMode {
  UNSPECIFIED = 0,
  BASELINE = 1,
  STANDARD = 2,
  UNAVAILABLE = 3,
}

export enum AgentCanonicalMemoryReviewReadiness {
  UNSPECIFIED = 0,
  ELIGIBLE = 1,
  WAITING_FOR_WINDOW = 2,
  EXECUTOR_UNAVAILABLE = 3,
  RECOVERABLE_RUN_BLOCKING = 4,
  BANK_UNAVAILABLE = 5,
}

export enum AgentEventType {
  UNSPECIFIED = 0,
  LIFECYCLE = 1,
  HOOK = 2,
  MEMORY = 3,
  BUDGET = 4,
  REPLICATION = 5,
  STATE = 6,
  PRESENTATION = 7,
  AVATAR_DEBUG = 8,
  PROACTIVE = 9,
}

export enum AgentExecutionState {
  UNSPECIFIED = 0,
  IDLE = 1,
  CHAT_ACTIVE = 2,
  LIFE_PENDING = 3,
  LIFE_RUNNING = 4,
  SUSPENDED = 5,
}

export enum AgentLifecycleStatus {
  UNSPECIFIED = 0,
  INITIALIZING = 1,
  ACTIVE = 2,
  SUSPENDED = 3,
  TERMINATING = 4,
  TERMINATED = 5,
}

export enum AgentPresentationBackendKind {
  UNSPECIFIED = 0,
  VRM = 1,
  LIVE2D = 2,
  SPRITE2D = 3,
  CANVAS2D = 4,
  VIDEO = 5,
}

export enum AgentPresentationEventFamily {
  UNSPECIFIED = 0,
  ACTIVITY_REQUESTED = 1,
  MOTION_REQUESTED = 2,
  EXPRESSION_REQUESTED = 3,
  POSE_REQUESTED = 4,
  POSE_CLEARED = 5,
  LOOKAT_REQUESTED = 6,
  VOICE_PLAYBACK_REQUESTED = 7,
  VOICE_STREAM_CHUNK_AVAILABLE = 8,
  VOICE_PLAYBACK_TERMINAL = 9,
}

export enum AgentProactiveDeliveryChannel {
  UNSPECIFIED = 0,
  IN_APP_SURFACE = 1,
  NOTIFICATION_NOT_ADMITTED = 2,
}

export enum AgentProactiveEffectClass {
  UNSPECIFIED = 0,
  IN_APP_COMPANION_SURFACE = 1,
}

export enum AgentProactiveEventFamily {
  UNSPECIFIED = 0,
  SUGGESTED = 1,
  DELIVERED = 2,
  SUPPRESSED = 3,
}

export enum AgentProactiveFrequencyCapState {
  UNSPECIFIED = 0,
  WITHIN_CAP = 1,
  CAPPED = 2,
  NOT_CONFIGURED = 3,
}

export enum AgentProactiveOptInState {
  UNSPECIFIED = 0,
  OFF = 1,
  PENDING = 2,
  GRANTED = 3,
  DENIED = 4,
  REVOKED = 5,
  EXPIRED = 6,
  MISSING = 7,
}

export enum AgentProactiveQuietHoursState {
  UNSPECIFIED = 0,
  INACTIVE = 1,
  ACTIVE = 2,
  NOT_CONFIGURED = 3,
}

export enum AgentProactiveSuppressionReason {
  UNSPECIFIED = 0,
  QUIET_HOURS_ACTIVE = 1,
  FREQUENCY_CAP_EXCEEDED = 2,
  PERMISSION_DENIED = 3,
  PERMISSION_REVOKED = 4,
  PERMISSION_MISSING = 5,
  PERMISSION_EXPIRED = 6,
  AUTONOMY_OFF = 7,
  BUDGET_EXHAUSTED = 8,
  SCHEDULER_DENIED = 9,
  HOOK_CONFLICT = 10,
  RUNTIME_UNAVAILABLE = 11,
  UNSUPPORTED_DELIVERY_CHANNEL = 12,
  MISSING_AUDIT_REF = 13,
}

export enum AgentProactiveTriggerSource {
  UNSPECIFIED = 0,
  LIFE_TRACK_CADENCE = 1,
  HOOK_INTENT = 2,
}

export enum AgentStateEventFamily {
  UNSPECIFIED = 0,
  STATUS_TEXT_CHANGED = 1,
  EXECUTION_STATE_CHANGED = 2,
  EMOTION_CHANGED = 3,
  POSTURE_CHANGED = 4,
}

export enum AgentTrackType {
  UNSPECIFIED = 0,
  CHAT = 1,
  LIFE = 2,
}

export enum AvatarDebugEventFamily {
  UNSPECIFIED = 0,
  PROBE_REQUESTED = 1,
  PROBE_RESULT = 2,
  REPLAY_LINKED = 3,
}

export enum AvatarDebugProbeKind {
  UNSPECIFIED = 0,
  PACKAGE_VALIDATION = 1,
  LAUNCH_READINESS = 2,
  BACKEND_LOAD = 3,
  CAPABILITY_PROFILE = 4,
  ROUTE_SUPPORT_MATRIX = 5,
  GENERATED_MOTION = 6,
  EMOTION_EXPRESSION = 7,
  SPEECH_LIPSYNC = 8,
  WINDOW_HIT_REGION = 9,
}

export enum AvatarDebugProbeStatus {
  UNSPECIFIED = 0,
  PASSED = 1,
  FAILED = 2,
  UNSUPPORTED = 3,
  BLOCKED = 4,
  INVALID = 5,
}

export enum AvatarDebugReplayRedactionState {
  UNSPECIFIED = 0,
  REDACTED = 1,
  VISIBLE = 2,
  FORBIDDEN = 3,
}

export enum AvatarDebugReplayVisibility {
  UNSPECIFIED = 0,
  DESKTOP_DEBUG_WORKBENCH = 1,
  SDK_DIAGNOSTICS = 2,
  RUNTIME_AUDIT_ONLY = 3,
}

export enum AvatarDebugRequestedBy {
  UNSPECIFIED = 0,
  DESKTOP_DEBUG_WORKBENCH = 1,
  RUNTIME_POLICY = 2,
}

export enum CompanionParticipationStatus {
  UNSPECIFIED = 0,
  IDLE = 1,
  ADMISSION_PENDING = 2,
  BLOCKED = 3,
  RUNNING = 4,
  CANDIDATE_READY = 5,
  COMMITTED_BY_OWNER = 6,
  FAILED = 7,
  CANCELED = 8,
}

export enum CompanionParticipationSurfaceKind {
  UNSPECIFIED = 0,
  AVATAR_COMPANION = 1,
  DESKTOP_COMPANION_PANEL = 2,
  AVATAR_DEBUG_WORKBENCH = 3,
}

export enum CompanionParticipationTriggerSource {
  UNSPECIFIED = 0,
  USER_EXPLICIT = 1,
  SCHEDULED_PROACTIVE = 2,
  DOMAIN_EVENT = 3,
}

export enum ConversationAnchorStatus {
  UNSPECIFIED = 0,
  ACTIVE = 1,
  CLOSED = 2,
}

export enum DelegatedApprovalDecision {
  UNSPECIFIED = 0,
  APPROVED_ONCE = 1,
  REJECTED = 2,
  APPROVED_FOR_SESSION = 3,
  POLICY_BLOCKED = 4,
  EXPIRED = 5,
}

export enum DelegatedApprovalMode {
  UNSPECIFIED = 0,
  RUNTIME_POLICY = 1,
  REQUIRE_USER = 2,
  DISABLED = 3,
}

export enum DelegatedApprovalRequestState {
  UNSPECIFIED = 0,
  PENDING = 1,
  APPROVED_ONCE = 2,
  REJECTED = 3,
  EXPIRED = 4,
  APPROVED_FOR_SESSION = 5,
  POLICY_BLOCKED = 6,
}

export enum DelegatedProviderKind {
  UNSPECIFIED = 0,
  MCP_TOOL_PROVIDER = 1,
  REMOTE_AGENT_SEAM = 2,
  RUNTIME_NATIVE_PROVIDER = 3,
  CONTROLLED_TEST_PROVIDER = 4,
}

export enum DelegatedProviderState {
  UNSPECIFIED = 0,
  REGISTERED = 1,
  DISCOVERING = 2,
  READY = 3,
  DEGRADED = 4,
  DISABLED = 5,
  QUARANTINED = 6,
  REMOVED = 7,
}

export enum DelegatedProviderTrustTier {
  UNSPECIFIED = 0,
  CONTROLLED_LOCAL = 1,
  USER_ADDED_REVIEWED = 2,
  ORG_MANAGED = 3,
  BLOCKED = 4,
}

export enum DelegatedReplayOutcome {
  UNSPECIFIED = 0,
  RECONSTRUCTED = 1,
  PARTIAL_REDACTED = 2,
  PARTIAL_MISSING_EVIDENCE = 3,
  BLOCKED_BY_POLICY = 4,
  INVALID_LINEAGE = 5,
}

export enum DelegatedTraceStageKind {
  UNSPECIFIED = 0,
  REQUEST = 1,
  GATEWAY_EVIDENCE = 2,
  FIREWALL_VERDICT = 3,
  APPROVAL_DECISION = 4,
  RUNTIME_DECISION = 5,
  PROJECTION_DISPOSITION = 6,
}

export enum DelegatedTransportKind {
  UNSPECIFIED = 0,
  STDIO_COMMAND = 1,
}

export enum HookAdmissionState {
  UNSPECIFIED = 0,
  PROPOSED = 1,
  PENDING = 2,
  REJECTED = 3,
  RUNNING = 4,
  COMPLETED = 5,
  FAILED = 6,
  CANCELED = 7,
  RESCHEDULED = 8,
}

export enum HookEffect {
  UNSPECIFIED = 0,
  FOLLOW_UP_TURN = 1,
}

export enum HookTriggerFamily {
  UNSPECIFIED = 0,
  TIME = 1,
  EVENT = 2,
}

export enum ParticipationCapabilityScope {
  UNSPECIFIED = 0,
  CANONICAL_AGENT_SCOPE = 1,
  PROFILE_LIMITED = 2,
  DOMAIN_LIMITED = 3,
  DIAGNOSTIC_READ_ONLY = 4,
  EXTERNAL_GATEWAY_LIMITED = 5,
  NONE = 6,
}

export enum ParticipationExecutionConcurrency {
  UNSPECIFIED = 0,
  CANONICAL_CHAT_BUDGET = 1,
  PER_AGENT_PARTICIPATION_QUEUE = 2,
  PROFILE_ISOLATED_BUDGET = 3,
  DOMAIN_TRIGGER_QUEUE = 4,
  REJECT_WHILE_ACTIVE = 5,
  GATEWAY_BUDGET_QUEUE = 6,
  LOW_PRIORITY_CANCELABLE = 7,
}

export enum ParticipationExecutionOwner {
  UNSPECIFIED = 0,
  RUNTIME = 1,
  EXTERNAL_RUNTIME_VIA_ADMITTED_GATEWAY = 2,
  NOT_ADMITTED = 3,
}

export enum ParticipationExternalProtocolKind {
  UNSPECIFIED = 0,
  MCP = 1,
  A2A = 2,
}

export enum ParticipationIdentitySource {
  UNSPECIFIED = 0,
  USER_OWNED_NIMI_AGENT = 1,
  EXTERNAL_A2A_AGENT = 2,
  MCP_BACKED_AI_CAPABILITY = 3,
  SANDBOX_PROJECTION = 4,
  NPC_WORLD_ACTOR = 5,
}

export enum ParticipationInputTrust {
  UNSPECIFIED = 0,
  TRUSTED_USER = 1,
  UNTRUSTED_MULTI_PARTY_TRANSCRIPT = 2,
  SANDBOX_SCRIPT = 3,
  EXTERNAL_A2A_PAYLOAD = 4,
  TOOL_PROVIDER_PAYLOAD = 5,
  WORLD_CONTEXT = 6,
  DIAGNOSTIC_INPUT = 7,
}

export enum ParticipationMemoryReadScope {
  UNSPECIFIED = 0,
  CANONICAL_OWNER_POLICY = 1,
  DYADIC_PRIVATE_ALLOWED = 2,
  DYADIC_PRIVATE_EXCLUDED = 3,
  PUBLIC_SHARED_ONLY = 4,
  DOMAIN_SHARED_ONLY = 5,
  NO_MEMORY_READ = 6,
}

export enum ParticipationMemoryWriteDefault {
  UNSPECIFIED = 0,
  CANONICAL_WRITE_ALLOWED = 1,
  WRITE_NONE = 2,
  PROMOTION_GATED = 3,
}

export enum ParticipationOutputDestination {
  UNSPECIFIED = 0,
  CANONICAL_CHAT = 1,
  REALM_GROUP_MESSAGE_CANDIDATE = 2,
  SCENARIO_TURN_CANDIDATE = 3,
  WORLD_EVENT_CANDIDATE = 4,
  EXTERNAL_REPLY_CANDIDATE = 5,
  DIAGNOSTIC_CANDIDATE = 6,
  EPHEMERAL = 7,
}

export enum ParticipationProfileKind {
  UNSPECIFIED = 0,
  CANONICAL_AGENT_CHAT = 1,
  REALM_GROUP_AGENT = 2,
  SCENARIO_SANDBOX = 3,
  OASIS_WORLD_PARTICIPATION = 4,
  EXTERNAL_AGENT_ENTRY = 5,
  DEBUG_OR_PROBE = 6,
}

export enum ParticipationPromotionPosture {
  UNSPECIFIED = 0,
  NOT_ALLOWED = 1,
  EXPLICIT_CANDIDATE = 2,
  EXPLICIT_COMMIT_FLOW = 3,
  EXISTING_CANONICAL_POLICY = 4,
}

export enum ParticipationReplayOutcome {
  UNSPECIFIED = 0,
  COMPLETED = 1,
  PARTIAL_REDACTED = 2,
  FAILED = 3,
}

export enum ParticipationStatus {
  UNSPECIFIED = 0,
  ADMISSION_PENDING = 1,
  BLOCKED = 2,
  RUNNING = 3,
  CANDIDATE_READY = 4,
  COMMITTED_BY_OWNER = 5,
  FAILED = 6,
  CANCELED = 7,
}

export enum ParticipationTranscriptOwner {
  UNSPECIFIED = 0,
  RUNTIME = 1,
  REALM = 2,
  SCENARIO_MODULE = 3,
  OASIS_WORLD_DOMAIN = 4,
  EXTERNAL_DOMAIN = 5,
  EPHEMERAL = 6,
}

export enum ParticipationVerdictDecision {
  UNSPECIFIED = 0,
  ALLOW = 1,
  DENY = 2,
}

export enum RealmGroupMessageCandidateCommitDisposition {
  UNSPECIFIED = 0,
  MESSAGE_CANDIDATE = 1,
  REFUSAL_CANDIDATE = 2,
}

export enum RuntimeAgentAIConfigReadinessState {
  RUNTIME_AGENT_AI_CONFIG_READINESS_STATE_UNSPECIFIED = 0,
  RUNTIME_AGENT_AI_CONFIG_READINESS_STATE_READY = 1,
  RUNTIME_AGENT_AI_CONFIG_READINESS_STATE_NOT_CONFIGURED = 2,
  RUNTIME_AGENT_AI_CONFIG_READINESS_STATE_UNAVAILABLE = 3,
}
