// @generated by sdks/generators/generate.mjs
// DO NOT EDIT MANUALLY.

export enum GpuMemoryModel {
  UNSPECIFIED = 0,
  DISCRETE = 1,
  UNIFIED = 2,
}

export enum LocalAppGrantState {
  UNSPECIFIED = 0,
  NO_GRANT = 1,
  PENDING = 2,
  GRANTED = 3,
  DENIED = 4,
  EXPIRED = 5,
  REVOKED = 6,
  SUPERSEDED = 7,
}

export enum LocalAppSessionState {
  UNSPECIFIED = 0,
  READY = 1,
  RUNTIME_UNAVAILABLE = 2,
  REVOKED = 3,
  ACCOUNT_CHANGED = 4,
  PROCESS_REPLACED = 5,
}

export enum LocalAppTrustClass {
  UNSPECIFIED = 0,
  VERIFIED = 1,
  USER_IMPORTED = 2,
  LOCAL_DEVELOPMENT = 3,
}

export enum LocalAssetKind {
  UNSPECIFIED = 0,
  CHAT = 1,
  IMAGE = 2,
  VIDEO = 3,
  TTS = 4,
  STT = 5,
  EMBEDDING = 6,
  VAE = 10,
  CLIP = 11,
  LORA = 12,
  CONTROLNET = 13,
  AUXILIARY = 14,
}

export enum LocalAssetStatus {
  UNSPECIFIED = 0,
  INSTALLED = 1,
  ACTIVE = 2,
  UNHEALTHY = 3,
  REMOVED = 4,
}

export enum LocalBundleState {
  UNSPECIFIED = 0,
  RESOLVING = 1,
  READY = 2,
  DEGRADED = 3,
  INVALID = 4,
  REMOVED = 5,
}

export enum LocalDevelopmentAuthorizationState {
  UNSPECIFIED = 0,
  CONFIRMATION_REQUIRED = 1,
  ACTIVE = 2,
  REAPPROVAL_REQUIRED = 3,
  DENIED = 4,
  REVOKED = 5,
  DORMANT = 6,
}

export enum LocalDevelopmentDecision {
  UNSPECIFIED = 0,
  DENY = 1,
  ALLOW_RUN_ONCE = 2,
  ALLOW_REMEMBER_PROJECT = 3,
}

export enum LocalDevelopmentShellKind {
  UNSPECIFIED = 0,
  ELECTRON = 1,
  TAURI = 2,
}

export enum LocalDevelopmentSummaryAvailability {
  UNSPECIFIED = 0,
  AVAILABLE = 1,
  UNAVAILABLE = 2,
}

export enum LocalEngineRuntimeMode {
  UNSPECIFIED = 0,
  SUPERVISED = 1,
  ATTACHED_ENDPOINT = 2,
}

export enum LocalEngineStatus {
  UNSPECIFIED = 0,
  STOPPED = 1,
  STARTING = 2,
  HEALTHY = 3,
  UNHEALTHY = 4,
}

export enum LocalExecutionEntryKind {
  UNSPECIFIED = 0,
  MODEL = 1,
  SERVICE = 2,
  NODE = 3,
}

export enum LocalHostSupportClass {
  UNSPECIFIED = 0,
  SUPPORTED_SUPERVISED = 1,
  ATTACHED_ONLY = 2,
  UNSUPPORTED = 3,
}

export enum LocalProfileEntryKind {
  UNSPECIFIED = 0,
  SERVICE = 3,
  NODE = 4,
  ASSET = 5,
}

export enum LocalRecommendationBaseline {
  UNSPECIFIED = 0,
  IMAGE_DEFAULT_V1 = 1,
  VIDEO_DEFAULT_V1 = 2,
}

export enum LocalRecommendationConfidence {
  UNSPECIFIED = 0,
  HIGH = 1,
  MEDIUM = 2,
  LOW = 3,
}

export enum LocalRecommendationFeedCacheState {
  UNSPECIFIED = 0,
  FRESH = 1,
  STALE = 2,
  EMPTY = 3,
}

export enum LocalRecommendationFeedCapability {
  UNSPECIFIED = 0,
  CHAT = 1,
  IMAGE = 2,
  VIDEO = 3,
}

export enum LocalRecommendationFeedSource {
  UNSPECIFIED = 0,
  MODEL_INDEX = 1,
}

export enum LocalRecommendationFormat {
  UNSPECIFIED = 0,
  GGUF = 1,
  SAFETENSORS = 2,
}

export enum LocalRecommendationSource {
  UNSPECIFIED = 0,
  LLMFIT = 1,
  MEDIA_FIT = 2,
}

export enum LocalRecommendationTier {
  UNSPECIFIED = 0,
  RECOMMENDED = 1,
  RUNNABLE = 2,
  TIGHT = 3,
  NOT_RECOMMENDED = 4,
}

export enum LocalServiceStatus {
  UNSPECIFIED = 0,
  INSTALLED = 1,
  ACTIVE = 2,
  UNHEALTHY = 3,
  REMOVED = 4,
}

export enum LocalWarmState {
  UNSPECIFIED = 0,
  COLD = 1,
  WARMING = 2,
  READY = 3,
  FAILED = 4,
}

export enum MemoryBankScope {
  UNSPECIFIED = 0,
  AGENT_CORE = 1,
  AGENT_DYADIC = 2,
  WORLD_SHARED = 3,
  APP_PRIVATE = 4,
  WORKSPACE_PRIVATE = 5,
}

export enum MemoryCanonicalClass {
  UNSPECIFIED = 0,
  NONE = 1,
  PUBLIC_SHARED = 2,
  WORLD_SHARED = 3,
  DYADIC = 4,
}

export enum MemoryDistanceMetric {
  UNSPECIFIED = 0,
  COSINE = 1,
  EUCLIDEAN = 2,
}

export enum MemoryEventType {
  UNSPECIFIED = 0,
  BANK_CREATED = 1,
  BANK_DELETED = 2,
  RECORD_RETAINED = 3,
  RECORD_DELETED = 4,
  REFLECTION_COMPLETED = 5,
  REPLICATION_UPDATED = 6,
}

export enum MemoryMigrationPolicy {
  UNSPECIFIED = 0,
  REINDEX = 1,
  FREEZE = 2,
}

export enum MemoryRecordKind {
  UNSPECIFIED = 0,
  EPISODIC = 1,
  SEMANTIC = 2,
  OBSERVATIONAL = 3,
}

export enum MemoryReplicationOutcome {
  UNSPECIFIED = 0,
  PENDING = 1,
  SYNCED = 2,
  CONFLICT = 3,
  INVALIDATED = 4,
}

export enum MergeStrategy {
  UNSPECIFIED = 0,
  ALL = 1,
  ANY = 2,
  N_OF_M = 3,
}

export enum ModelCatalogProviderSource {
  UNSPECIFIED = 0,
  BUILTIN = 1,
  CUSTOM = 2,
  REMOTE = 3,
  OVERRIDDEN = 4,
}

export enum ModelHealthStatus {
  UNSPECIFIED = 0,
  HEALTHY = 1,
  DEGRADED = 2,
  UNSUPPORTED = 3,
  UNREACHABLE = 4,
}

export enum ModelStatus {
  UNSPECIFIED = 0,
  INSTALLED = 1,
  PULLING = 2,
  FAILED = 3,
  REMOVED = 4,
}

export enum RuntimeHealthStatus {
  UNSPECIFIED = 0,
  STOPPED = 1,
  STARTING = 2,
  READY = 3,
  DEGRADED = 4,
  STOPPING = 5,
}
