/* Pre-seeded scenario — the "simulated memory" of the cradle.
 *
 * Decision (locked with the product owner): the prototype does not persist
 * anything. Continuity is faked honestly — the scenario pre-seeds prior
 * history (conversations, grants, footprints) so the LocalAgent projection
 * appears continuous. Every byte below is fictional demo content.
 */

import type { Scenario } from './types';

export const SCENARIO: Scenario = {
  persona: {
    name: '林澈',
    id: 'u_7f3a',
    role: '生态居民 · 早期体验者',
  },
  localAgentPresentation: {
    name: 'Nimi',
    kind: 'Realm Character Source LocalAgent',
    mode: 'Runtime Agent Service 执行',
  },
  worlds: [
    {
      id: 'starport',
      name: '星港',
      en: 'Starport',
      kind: '社交场景',
      presence: '12 位居民在场',
      hue: '#45b8d6',
      blurb: '生态居民的公共停泊港。大厅、集市与临时聚会的默认集合点。',
    },
    {
      id: 'echo-vale',
      name: '回声谷',
      en: 'Echo Vale',
      kind: '游戏世界',
      presence: '赛季进行中',
      hue: '#8b7cf6',
      blurb: '声音即地形的探索世界。上季你完成了「低语回廊」的三段回声解谜。',
    },
    {
      id: 'atelier',
      name: '工坊',
      en: 'Atelier',
      kind: '服务场所',
      presence: '预约制',
      hue: '#d97706',
      blurb: '把想法做成实物的协作空间。你预约的「头像实体化」服务排期中。',
    },
  ],
  seededGrants: [
    {
      id: 'g-world-write',
      title: '生态足迹写入',
      scope: 'Desktop → 生态共享 · 可写足迹、可被其他应用读取',
      from: 'Desktop',
      to: '生态共享',
      meta: '2 分钟前更新',
      tags: ['写入', '当前世界', '长期有效'],
      receipt: {
        access: '写入',
        range: '生态共享 · 可被其他应用读取',
        validity: '长期有效',
        expiry: '',
        restriction: '无',
        lastUsed: '2 分钟前',
      },
      status: 'active',
      seeded: true,
    },
    {
      id: 'g-presence-read',
      title: '在场状态读取',
      scope: 'Zhiyu → 生态共享 · 只读你在各世界的在场状态',
      from: 'Zhiyu',
      to: '生态共享',
      meta: '2 分钟前更新',
      tags: ['只读', '当前世界', '2 天有效', '不写入长期记忆'],
      receipt: {
        access: '只读',
        range: '仅当前世界',
        validity: '2 天',
        expiry: '模拟时间 · 2 天后到期',
        restriction: '不写入长期记忆',
        lastUsed: '2 分钟前',
      },
      status: 'active',
      seeded: true,
    },
    {
      id: 'g-local-agent-context-projection',
      title: 'context 携带',
      scope: 'Nimi · Desktop → Zhiyu · 仅本次会话摘要的只读投影，可撤销',
      from: 'Nimi (LocalAgent)',
      to: 'Zhiyu',
      meta: '上次会话结束',
      tags: ['只读', '本次会话', '不写入长期记忆'],
      receipt: {
        access: '只读',
        range: '仅本次会话摘要的只读投影',
        validity: '本次会话',
        expiry: '已随上次会话结束失效',
        restriction: '不写入长期记忆',
        lastUsed: '昨天',
      },
      status: 'revoked',
      seeded: false,
    },
  ],
  seededLedger: [
    {
      id: '0:op:090',
      epoch: 1,
      kind: 'system',
      title: 'Runtime 会话建立',
      detail: '身份 u_7f3a 载入，Runtime 投影 LocalAgent Nimi 的在场状态。',
      actors: ['Runtime', 'Nimi', 'Desktop'],
      result: 'info',
      at: '17:30',
      history: true,
    },
    {
      id: '0:op:096',
      epoch: 1,
      kind: 'delegation',
      title: '写入生态足迹',
      detail: '你允许 Desktop 写入你的生态足迹。',
      actors: ['林澈', 'Desktop'],
      tags: ['林澈', 'Desktop', '生态共享', '长期'],
      result: 'committed',
      at: '17:42',
      history: true,
    },
    {
      id: '0:op:118',
      epoch: 1,
      kind: 'flow',
      title: '读取居民列表',
      detail: 'Zhiyu 查询星港的在场居民列表。',
      actors: ['Zhiyu', '星港'],
      tags: ['Zhiyu', '星港', '只读'],
      result: 'committed',
      at: '18:20',
      history: true,
    },
    {
      id: '1:op:005',
      epoch: 1,
      kind: 'delegation',
      title: '写入生态足迹',
      detail: '你允许 Desktop 向生态共享写入足迹。',
      actors: ['Desktop', '生态足迹写入'],
      tags: ['林澈', 'Desktop', '生态共享', '本次会话'],
      result: 'pending',
      at: 'T+00:05',
    },
    {
      id: '1:op:008',
      epoch: 1,
      kind: 'flow',
      title: '写入生态足迹',
      detail: 'Desktop 提交了一条生态足迹：抵达星港大厅。',
      actors: ['Desktop', '星港'],
      tags: ['Desktop', '生态共享', '本次会话'],
      result: 'committed',
      at: 'T+00:08',
    },
    {
      id: '1:op:011',
      epoch: 1,
      kind: 'delegation',
      title: '读取在场状态',
      detail: '你允许 Zhiyu 只读取你在当前世界的在场状态。',
      actors: ['Desktop', 'Zhiyu'],
      tags: ['林澈', 'Zhiyu', '当前世界', '只读'],
      result: 'committed',
      at: 'T+00:11',
    },
  ],
  seededChat: [
    {
      id: 'm1',
      who: 'agent',
      text: '欢迎回来。上次我们在回声谷的「低语回廊」停下——第三段回声还差最后一步。',
      at: 'T+00:04',
    },
    {
      id: 'm2',
      who: 'user',
      text: '我记得。那个谜题的提示是不是藏在星港的集市里？',
      at: 'T+00:06',
    },
    {
      id: 'm3',
      who: 'agent',
      text: '对，集市的回声商贩。我建议先把回声谷收录进你的生态足迹，这样 Lab 的世界巡游也能看到它。',
      at: 'T+00:07',
    },
    {
      id: 'm4',
      who: 'user',
      text: '好主意。另外等会儿我想在 Zhiyu 里整理一下解谜思路。',
      at: 'T+00:09',
    },
  ],
  seededFootprints: [
    { worldId: 'starport', note: '抵达星港大厅', at: 'T+00:08' },
  ],
  carrySummary: {
    title: '会话摘要 · 回声谷解谜计划',
    body: '目标：完成「低语回廊」第三段回声。线索：星港集市的回声商贩。下一步：把谷内地形按声源方位重排，再回星港核对提示。',
  },
  openingOpSeq: 12,
};
