/* eslint-disable */
// AUTO-GENERATED FACADE from realm/generated/index.ts. DO NOT EDIT BY HAND.

export type { ApiRequestOptions } from './generated/core/ApiRequestOptions';
export { request as openApiRequest } from './generated/core/request';
export { ApiError } from './generated/core/ApiError';
export { CancelablePromise, CancelError } from './generated/core/CancelablePromise';
export { OpenAPI } from './generated/core/OpenAPI';
export type { OpenAPIConfig } from './generated/core/OpenAPI';
export { AccountRole } from './generated/models/AccountRole';
export { AccountStatus } from './generated/models/AccountStatus';
export type { ActivateAgentDto } from './generated/models/ActivateAgentDto';
export { AddCheckpointDto } from './generated/models/AddCheckpointDto';
export type { AgentAppearanceDto } from './generated/models/AgentAppearanceDto';
export type { AgentBiologicalDto } from './generated/models/AgentBiologicalDto';
export { AgentCategory } from './generated/models/AgentCategory';
export { AgentCommunicationDto } from './generated/models/AgentCommunicationDto';
export type { AgentDnaDto } from './generated/models/AgentDnaDto';
export type { AgentIdentityDto } from './generated/models/AgentIdentityDto';
export type { AgentMetadataDto } from './generated/models/AgentMetadataDto';
export { AgentOrigin } from './generated/models/AgentOrigin';
export type { AgentOriginDto } from './generated/models/AgentOriginDto';
export { AgentOwnershipType } from './generated/models/AgentOwnershipType';
export type { AgentPersonalityDto } from './generated/models/AgentPersonalityDto';
export type { AgentProfileDto } from './generated/models/AgentProfileDto';
export { AgentRelationType } from './generated/models/AgentRelationType';
export { AgentState } from './generated/models/AgentState';
export type { AgentVisibilitySettingsDto } from './generated/models/AgentVisibilitySettingsDto';
export type { AgentVoiceConfigDto } from './generated/models/AgentVoiceConfigDto';
export { AgentWakeStrategy } from './generated/models/AgentWakeStrategy';
export type { AggregateMetricsDto } from './generated/models/AggregateMetricsDto';
export { ApiKeyType } from './generated/models/ApiKeyType';
export type { ApproveRequestDto } from './generated/models/ApproveRequestDto';
export type { AuthTokensDto } from './generated/models/AuthTokensDto';
export type { BatchCreateAgentsRequestDto } from './generated/models/BatchCreateAgentsRequestDto';
export { BatchUpsertWorldEventsDto } from './generated/models/BatchUpsertWorldEventsDto';
export type { BatchUpsertWorldLorebooksDto } from './generated/models/BatchUpsertWorldLorebooksDto';
export type { BindEmailDto } from './generated/models/BindEmailDto';
export type { CanWithdrawDto } from './generated/models/CanWithdrawDto';
export type { CausalChainDto } from './generated/models/CausalChainDto';
export { CausalityModelDto } from './generated/models/CausalityModelDto';
export type { ChangeEmailDto } from './generated/models/ChangeEmailDto';
export type { ChatEventEnvelopeDto } from './generated/models/ChatEventEnvelopeDto';
export { ChatSyncResultDto } from './generated/models/ChatSyncResultDto';
export type { ChatSyncSnapshotDto } from './generated/models/ChatSyncSnapshotDto';
export type { ChatViewDto } from './generated/models/ChatViewDto';
export type { CollapseGapDto } from './generated/models/CollapseGapDto';
export type { ConnectDashboardLinkDto } from './generated/models/ConnectDashboardLinkDto';
export type { ConnectOnboardingResponseDto } from './generated/models/ConnectOnboardingResponseDto';
export type { ConsensusMetricDetailDto } from './generated/models/ConsensusMetricDetailDto';
export { ContentRatingString } from './generated/models/ContentRatingString';
export type { CreateAgentDto } from './generated/models/CreateAgentDto';
export type { CreateAgentResponseDto } from './generated/models/CreateAgentResponseDto';
export type { CreateApiKeyDto } from './generated/models/CreateApiKeyDto';
export { CreateBranchDto } from './generated/models/CreateBranchDto';
export type { CreateConnectOnboardingDto } from './generated/models/CreateConnectOnboardingDto';
export type { CreateKeyEventDto } from './generated/models/CreateKeyEventDto';
export type { CreateMutationProposalDto } from './generated/models/CreateMutationProposalDto';
export type { CreateNarrativeSpineEventDto } from './generated/models/CreateNarrativeSpineEventDto';
export type { CreatePortalSessionDto } from './generated/models/CreatePortalSessionDto';
export type { CreatePostDto } from './generated/models/CreatePostDto';
export type { CreatePostMediaDto } from './generated/models/CreatePostMediaDto';
export type { CreateRelationshipDto } from './generated/models/CreateRelationshipDto';
export { CreateReportDto } from './generated/models/CreateReportDto';
export type { CreateReviewDto } from './generated/models/CreateReviewDto';
export { CreateSatelliteDto } from './generated/models/CreateSatelliteDto';
export type { CreateSnapshotDto } from './generated/models/CreateSnapshotDto';
export type { CreateSparkCheckoutDto } from './generated/models/CreateSparkCheckoutDto';
export type { CreateSubscriptionCheckoutDto } from './generated/models/CreateSubscriptionCheckoutDto';
export { CreateSyntheticMemoryDto } from './generated/models/CreateSyntheticMemoryDto';
export { CreateTransitDto } from './generated/models/CreateTransitDto';
export type { CreateWithdrawalDto } from './generated/models/CreateWithdrawalDto';
export { CreateWorldDraftDto } from './generated/models/CreateWorldDraftDto';
export type { CreateWorldDto } from './generated/models/CreateWorldDto';
export type { CreatorCapabilitiesResponseDto } from './generated/models/CreatorCapabilitiesResponseDto';
export type { CreatorModControlAuditIngestRequestDto } from './generated/models/CreatorModControlAuditIngestRequestDto';
export { CreatorModControlAuditRecordDto } from './generated/models/CreatorModControlAuditRecordDto';
export type { CreatorModControlGrantIssueRequestDto } from './generated/models/CreatorModControlGrantIssueRequestDto';
export type { CreatorModControlGrantValidateRequestDto } from './generated/models/CreatorModControlGrantValidateRequestDto';
export { CreatorModControlManifestVerifyRequestDto } from './generated/models/CreatorModControlManifestVerifyRequestDto';
export { CreatorModControlSignatureVerifyRequestDto } from './generated/models/CreatorModControlSignatureVerifyRequestDto';
export type { CurrencyBalancesDto } from './generated/models/CurrencyBalancesDto';
export type { CurrencyTransactionDto } from './generated/models/CurrencyTransactionDto';
export type { CurrencyTransactionHistoryDto } from './generated/models/CurrencyTransactionHistoryDto';
export type { CursorPageMetaDto } from './generated/models/CursorPageMetaDto';
export { DesktopChatRouteRequestDto } from './generated/models/DesktopChatRouteRequestDto';
export { DesktopChatRouteResultDto } from './generated/models/DesktopChatRouteResultDto';
export type { DetectedGapDto } from './generated/models/DetectedGapDto';
export type { DirectUploadResponseDto } from './generated/models/DirectUploadResponseDto';
export { DnaPrimaryType } from './generated/models/DnaPrimaryType';
export { DnaSecondaryTrait } from './generated/models/DnaSecondaryTrait';
export type { EditMessageInputDto } from './generated/models/EditMessageInputDto';
export type { EmailOtpRequestDto } from './generated/models/EmailOtpRequestDto';
export type { EmailOtpResponseDto } from './generated/models/EmailOtpResponseDto';
export type { EmailOtpVerifyDto } from './generated/models/EmailOtpVerifyDto';
export type { FeedPageMetaDto } from './generated/models/FeedPageMetaDto';
export type { FeedResponseDto } from './generated/models/FeedResponseDto';
export { ForceActionDto } from './generated/models/ForceActionDto';
export { Gender } from './generated/models/Gender';
export type { GiftCatalogItemDto } from './generated/models/GiftCatalogItemDto';
export { GiftStatus } from './generated/models/GiftStatus';
export type { GiftTransactionDto } from './generated/models/GiftTransactionDto';
export type { GiftTransactionRichDto } from './generated/models/GiftTransactionRichDto';
export { GravityFieldDto } from './generated/models/GravityFieldDto';
export type { GrowthProjectionDto } from './generated/models/GrowthProjectionDto';
export type { InjectEventResponseDto } from './generated/models/InjectEventResponseDto';
export { InjectWorldEventDto } from './generated/models/InjectWorldEventDto';
export type { ListChatsResultDto } from './generated/models/ListChatsResultDto';
export type { ListMessagesResultDto } from './generated/models/ListMessagesResultDto';
export type { MarkNotificationsReadInputDto } from './generated/models/MarkNotificationsReadInputDto';
export type { MemoryStatsResponseDto } from './generated/models/MemoryStatsResponseDto';
export { MessageType } from './generated/models/MessageType';
export type { MessageViewDto } from './generated/models/MessageViewDto';
export { ModerationStatusString } from './generated/models/ModerationStatusString';
export { MutationProposalDetailDto } from './generated/models/MutationProposalDetailDto';
export { NarrativeSpineBranchDetailDto } from './generated/models/NarrativeSpineBranchDetailDto';
export type { NarrativeSpineDetailDto } from './generated/models/NarrativeSpineDetailDto';
export { NarrativeSpineEventDetailDto } from './generated/models/NarrativeSpineEventDetailDto';
export type { NotificationActivityDto } from './generated/models/NotificationActivityDto';
export type { NotificationActorDto } from './generated/models/NotificationActorDto';
export type { NotificationChannelsDto } from './generated/models/NotificationChannelsDto';
export { NotificationDto } from './generated/models/NotificationDto';
export type { NotificationGiftsDto } from './generated/models/NotificationGiftsDto';
export type { NotificationListResultDto } from './generated/models/NotificationListResultDto';
export type { NotificationTargetDto } from './generated/models/NotificationTargetDto';
export type { OAuthLoginDto } from './generated/models/OAuthLoginDto';
export { OAuthLoginResultDto } from './generated/models/OAuthLoginResultDto';
export { OAuthProvider } from './generated/models/OAuthProvider';
export type { Object } from './generated/models/Object';
export type { PasswordLoginDto } from './generated/models/PasswordLoginDto';
export type { PasswordRegisterDto } from './generated/models/PasswordRegisterDto';
export { PermissionCheckResponseDto } from './generated/models/PermissionCheckResponseDto';
export type { PortalSessionDto } from './generated/models/PortalSessionDto';
export type { PostDto } from './generated/models/PostDto';
export type { PostMediaDto } from './generated/models/PostMediaDto';
export { PostMediaType } from './generated/models/PostMediaType';
export type { PostSearchResponseDto } from './generated/models/PostSearchResponseDto';
export type { PostTrimDto } from './generated/models/PostTrimDto';
export type { PowerSystemDto } from './generated/models/PowerSystemDto';
export type { ProposedChangeDto } from './generated/models/ProposedChangeDto';
export type { PublicFilterDto } from './generated/models/PublicFilterDto';
export type { PublishWorldDraftDto } from './generated/models/PublishWorldDraftDto';
export type { PublishWorldDraftResultDto } from './generated/models/PublishWorldDraftResultDto';
export type { ReceivedGiftsResponseDto } from './generated/models/ReceivedGiftsResponseDto';
export type { RefreshTokenDto } from './generated/models/RefreshTokenDto';
export type { RejectGiftDto } from './generated/models/RejectGiftDto';
export type { RejectRequestDto } from './generated/models/RejectRequestDto';
export type { RelationshipResponseDto } from './generated/models/RelationshipResponseDto';
export type { RemoveAgentRelationshipDto } from './generated/models/RemoveAgentRelationshipDto';
export { ReportReason } from './generated/models/ReportReason';
export type { ReportResponseDto } from './generated/models/ReportResponseDto';
export type { RevenueDistributionPreviewDto } from './generated/models/RevenueDistributionPreviewDto';
export type { RevenueShareConfigDto } from './generated/models/RevenueShareConfigDto';
export type { ReviewDto } from './generated/models/ReviewDto';
export { ReviewProposalDto } from './generated/models/ReviewProposalDto';
export { ReviewRating } from './generated/models/ReviewRating';
export type { ReviewStatsDto } from './generated/models/ReviewStatsDto';
export type { RuleValidationResponseDto } from './generated/models/RuleValidationResponseDto';
export { SatelliteDetailDto } from './generated/models/SatelliteDetailDto';
export { SatelliteMetadataDto } from './generated/models/SatelliteMetadataDto';
export type { SceneContextDto } from './generated/models/SceneContextDto';
export type { SearchPostDto } from './generated/models/SearchPostDto';
export type { SearchPostMediaDto } from './generated/models/SearchPostMediaDto';
export type { SelectAvatarDto } from './generated/models/SelectAvatarDto';
export type { SendGiftDto } from './generated/models/SendGiftDto';
export type { SendMessageInputDto } from './generated/models/SendMessageInputDto';
export type { SetAgentRelationshipDto } from './generated/models/SetAgentRelationshipDto';
export type { SocialProfileDto } from './generated/models/SocialProfileDto';
export type { SoulPrimeDto } from './generated/models/SoulPrimeDto';
export { SpaceTopologyDto } from './generated/models/SpaceTopologyDto';
export type { SparkCheckoutSessionDto } from './generated/models/SparkCheckoutSessionDto';
export type { SparkPackageDto } from './generated/models/SparkPackageDto';
export { SpineEventPayloadDto } from './generated/models/SpineEventPayloadDto';
export type { StartChatInputDto } from './generated/models/StartChatInputDto';
export type { StartChatResultDto } from './generated/models/StartChatResultDto';
export { StripeConnectStatus } from './generated/models/StripeConnectStatus';
export type { StripeConnectStatusDto } from './generated/models/StripeConnectStatusDto';
export type { SubscriptionCheckoutSessionDto } from './generated/models/SubscriptionCheckoutSessionDto';
export type { SubscriptionDto } from './generated/models/SubscriptionDto';
export { SubscriptionTier } from './generated/models/SubscriptionTier';
export type { SubscriptionTierConfigDto } from './generated/models/SubscriptionTierConfigDto';
export type { TierDetailDto } from './generated/models/TierDetailDto';
export { TimeGapDetailDto } from './generated/models/TimeGapDetailDto';
export type { TimeGapDurationDto } from './generated/models/TimeGapDurationDto';
export { TimeModelDto } from './generated/models/TimeModelDto';
export { TransitCheckpointDto } from './generated/models/TransitCheckpointDto';
export { TransitDetailDto } from './generated/models/TransitDetailDto';
export type { TransitSessionDataDto } from './generated/models/TransitSessionDataDto';
export { TranslateRequestDto } from './generated/models/TranslateRequestDto';
export type { TranslateResponseDto } from './generated/models/TranslateResponseDto';
export type { UpdateAgentDnaDto } from './generated/models/UpdateAgentDnaDto';
export type { UpdateAgentVisibilityDto } from './generated/models/UpdateAgentVisibilityDto';
export type { UpdateNarrativeSpineEventDto } from './generated/models/UpdateNarrativeSpineEventDto';
export type { UpdatePasswordRequestDto } from './generated/models/UpdatePasswordRequestDto';
export type { UpdatePostDto } from './generated/models/UpdatePostDto';
export type { UpdateRelationshipDto } from './generated/models/UpdateRelationshipDto';
export type { UpdateSessionDataDto } from './generated/models/UpdateSessionDataDto';
export type { UpdateSoulPrimeDto } from './generated/models/UpdateSoulPrimeDto';
export type { UpdateUserDto } from './generated/models/UpdateUserDto';
export type { UpdateUserNotificationSettingsDto } from './generated/models/UpdateUserNotificationSettingsDto';
export type { UpdateUserProfileDto } from './generated/models/UpdateUserProfileDto';
export type { UpdateUserSettingsDto } from './generated/models/UpdateUserSettingsDto';
export { UpdateWorldDraftDto } from './generated/models/UpdateWorldDraftDto';
export type { UpdateWorldMaintenanceDto } from './generated/models/UpdateWorldMaintenanceDto';
export type { UpdateWorldRulesDto } from './generated/models/UpdateWorldRulesDto';
export type { UserCapabilitiesDto } from './generated/models/UserCapabilitiesDto';
export type { UserLiteDto } from './generated/models/UserLiteDto';
export type { UserNotificationSettingsDto } from './generated/models/UserNotificationSettingsDto';
export type { UserPrivateDto } from './generated/models/UserPrivateDto';
export type { UserProfileDto } from './generated/models/UserProfileDto';
export type { UserSearchResponseDto } from './generated/models/UserSearchResponseDto';
export type { UserSettingsDto } from './generated/models/UserSettingsDto';
export type { UserStatsDto } from './generated/models/UserStatsDto';
export type { UserTierSummaryDto } from './generated/models/UserTierSummaryDto';
export type { UserWalletDto } from './generated/models/UserWalletDto';
export type { UserWalletListResponseDto } from './generated/models/UserWalletListResponseDto';
export type { ValidateContextDto } from './generated/models/ValidateContextDto';
export type { ValidateRulesDto } from './generated/models/ValidateRulesDto';
export { VerificationTier } from './generated/models/VerificationTier';
export { VerifySyntheticMemoryDto } from './generated/models/VerifySyntheticMemoryDto';
export { Visibility } from './generated/models/Visibility';
export type { WalletBindDto } from './generated/models/WalletBindDto';
export type { WalletChallengeDto } from './generated/models/WalletChallengeDto';
export type { WalletChallengeResponseDto } from './generated/models/WalletChallengeResponseDto';
export type { WalletLoginDto } from './generated/models/WalletLoginDto';
export type { WalletPrepareBindDto } from './generated/models/WalletPrepareBindDto';
export type { WalletPrepareBindResponseDto } from './generated/models/WalletPrepareBindResponseDto';
export type { WithdrawalConfigDto } from './generated/models/WithdrawalConfigDto';
export type { WithdrawalDto } from './generated/models/WithdrawalDto';
export type { WithdrawalHistoryDto } from './generated/models/WithdrawalHistoryDto';
export { WithdrawalStatus } from './generated/models/WithdrawalStatus';
export type { WithdrawalSummaryDto } from './generated/models/WithdrawalSummaryDto';
export { WorldAccessRecordDto } from './generated/models/WorldAccessRecordDto';
export type { WorldAccessSummaryDto } from './generated/models/WorldAccessSummaryDto';
export { WorldDetailDto } from './generated/models/WorldDetailDto';
export { WorldDraftDetailDto } from './generated/models/WorldDraftDetailDto';
export { WorldDraftSummaryDto } from './generated/models/WorldDraftSummaryDto';
export type { WorldDraftSummaryListDto } from './generated/models/WorldDraftSummaryListDto';
export { WorldEventDetailDto } from './generated/models/WorldEventDetailDto';
export type { WorldEventEvidenceRefDto } from './generated/models/WorldEventEvidenceRefDto';
export type { WorldEventEvidenceRefInputDto } from './generated/models/WorldEventEvidenceRefInputDto';
export type { WorldEventGraphSummaryDto } from './generated/models/WorldEventGraphSummaryDto';
export type { WorldEventListDto } from './generated/models/WorldEventListDto';
export { WorldEventUpsertDto } from './generated/models/WorldEventUpsertDto';
export { WorldLandingDecisionDto } from './generated/models/WorldLandingDecisionDto';
export { WorldLevelAuditEventDto } from './generated/models/WorldLevelAuditEventDto';
export type { WorldLorebookDetailDto } from './generated/models/WorldLorebookDetailDto';
export type { WorldLorebookListDto } from './generated/models/WorldLorebookListDto';
export type { WorldLorebookUpsertDto } from './generated/models/WorldLorebookUpsertDto';
export type { WorldMaintenanceDto } from './generated/models/WorldMaintenanceDto';
export type { WorldMutationListDto } from './generated/models/WorldMutationListDto';
export { WorldMutationSummaryDto } from './generated/models/WorldMutationSummaryDto';
export { WorldPatchDto } from './generated/models/WorldPatchDto';
export { WorldSummaryDto } from './generated/models/WorldSummaryDto';
export type { WorldSummaryListDto } from './generated/models/WorldSummaryListDto';
export { WorldviewDetailDto } from './generated/models/WorldviewDetailDto';
export type { WorldviewEventDto } from './generated/models/WorldviewEventDto';
export { WorldviewPatchDto } from './generated/models/WorldviewPatchDto';
export type { WorldviewSnapshotDto } from './generated/models/WorldviewSnapshotDto';
export { AgentNsfwConsentService } from './generated/services/AgentNsfwConsentService';
export { AgentsService } from './generated/services/AgentsService';
export { AuthService } from './generated/services/AuthService';
export { CreatorService } from './generated/services/CreatorService';
export { CreatorModsControlPlaneService } from './generated/services/CreatorModsControlPlaneService';
export { DesktopService } from './generated/services/DesktopService';
export { EconomyCurrencyGiftsService } from './generated/services/EconomyCurrencyGiftsService';
export { ExploreService } from './generated/services/ExploreService';
export { GovernanceService } from './generated/services/GovernanceService';
export { HumanChatService } from './generated/services/HumanChatService';
export { HumanNsfwConsentService } from './generated/services/HumanNsfwConsentService';
export { InvitationsService } from './generated/services/InvitationsService';
export { MeService } from './generated/services/MeService';
export { MediaService } from './generated/services/MediaService';
export { NarrativeSpineService } from './generated/services/NarrativeSpineService';
export { NotificationService } from './generated/services/NotificationService';
export { PostService } from './generated/services/PostService';
export { RelationshipsMetaGraphService } from './generated/services/RelationshipsMetaGraphService';
export { ReviewsEconomyTrustService } from './generated/services/ReviewsEconomyTrustService';
export { SatelliteNarrativeService } from './generated/services/SatelliteNarrativeService';
export { SearchService } from './generated/services/SearchService';
export { SoulEvolutionService } from './generated/services/SoulEvolutionService';
export { TimeGapNarrativeService } from './generated/services/TimeGapNarrativeService';
export { TransitsService } from './generated/services/TransitsService';
export { TranslationService } from './generated/services/TranslationService';
export { UserService } from './generated/services/UserService';
export { WorldControlService } from './generated/services/WorldControlService';
export { WorldRulesService } from './generated/services/WorldRulesService';
export { WorldsService } from './generated/services/WorldsService';

// Naming-normalized facade exports (do not expose legacy names).
export { Me2FaService as MeTwoFactorService } from './generated/services/Me2FaService';
export { SocialV1DefaultVisibilityService as SocialDefaultVisibilityService } from './generated/services/SocialV1DefaultVisibilityService';
export { SocialFourDimensionalAttributesService as SocialAttributesService } from './generated/services/SocialFourDimensionalAttributesService';
export type { Auth2faVerifyDto as AuthTwoFactorVerifyInput } from './generated/models/Auth2faVerifyDto';
export type { Me2faVerifyDto as MeTwoFactorVerifyInput } from './generated/models/Me2faVerifyDto';
export type { Me2faPrepareResponseDto as MeTwoFactorPrepareOutput } from './generated/models/Me2faPrepareResponseDto';
