/*
 * @generated by scripts/generate-platform-catalog.mjs
 * Source: config/platform-ai-profile-factory-catalog.yaml
 *
 * This file is a packaged Platform catalog projection for Rust host consumers.
 * It is not a canonical row source.
 */

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformAIProfileFactoryRow {
    pub alias: &'static str,
    pub privacy_posture: &'static str,
    pub compute_posture: &'static str,
    pub capability_set: &'static [&'static str],
    pub routing_policy: &'static str,
    pub host_capability_profile_refs: &'static [&'static str],
    pub local_compute_pack_refs: &'static [&'static str],
    pub dependency_family_refs: &'static [&'static str],
    pub materialization_confirmation_required: bool,
    pub applicable_scopes: &'static [&'static str],
    pub first_run_install_levels: &'static [&'static str],
    pub source_rule: &'static str,
}

pub const PLATFORM_AI_PROFILE_FACTORY_CATALOG_ID: &str = "platform_ai_profile_factory_catalog";
pub const PLATFORM_AI_PROFILE_FACTORY_CATALOG_VERSION: u32 = 1;
pub const PLATFORM_AI_PROFILE_SELECTION_POLICY_REF: &str = "P-AIPS-004";

pub const PLATFORM_AI_PROFILE_FACTORY_ROWS: &[PlatformAIProfileFactoryRow] = &[
    PlatformAIProfileFactoryRow {
        alias: "cloud-first",
        privacy_posture: "cloud-ok",
        compute_posture: "cloud-only",
        capability_set: &[
            "text.generate",
            "text.generate.vision",
            "text.embed",
            "audio.synthesize",
            "audio.transcribe",
            "image.generate",
            "image.edit",
        ],
        routing_policy: "cloud-first",
        host_capability_profile_refs: &[
            "windows-amd64-cpu",
            "windows-amd64-nvidia-cuda",
            "darwin-arm64-metal",
        ],
        local_compute_pack_refs: &[],
        dependency_family_refs: &[],
        materialization_confirmation_required: false,
        applicable_scopes: &["first-party-app", "scope-bound-apply"],
        first_run_install_levels: &[],
        source_rule: "P-AIPS-002",
    },
    PlatformAIProfileFactoryRow {
        alias: "local-standard",
        privacy_posture: "local-preferred",
        compute_posture: "cpu-only",
        capability_set: &["text.generate", "text.embed"],
        routing_policy: "local-first",
        host_capability_profile_refs: &[
            "windows-amd64-cpu",
            "darwin-arm64-metal",
            "windows-amd64-nvidia-cuda",
        ],
        local_compute_pack_refs: &["local-text"],
        dependency_family_refs: &["native-engine-package.llama", "model.asset"],
        materialization_confirmation_required: true,
        applicable_scopes: &["first-party-app", "scope-bound-apply"],
        first_run_install_levels: &[],
        source_rule: "P-AIPS-002",
    },
    PlatformAIProfileFactoryRow {
        alias: "local-speech-ready",
        privacy_posture: "local-preferred",
        compute_posture: "cpu-only",
        capability_set: &["text.generate", "audio.transcribe", "audio.synthesize"],
        routing_policy: "local-first",
        host_capability_profile_refs: &[
            "windows-amd64-cpu",
            "darwin-arm64-metal",
            "windows-amd64-nvidia-cuda",
        ],
        local_compute_pack_refs: &["local-text", "local-speech"],
        dependency_family_refs: &[
            "native-engine-package.llama",
            "python.tool.uv",
            "python.runtime",
            "python.venv",
            "python.package-set",
            "model.asset",
        ],
        materialization_confirmation_required: true,
        applicable_scopes: &["first-run", "first-party-app", "scope-bound-apply"],
        first_run_install_levels: &["minimal", "recommended"],
        source_rule: "P-AIPS-002",
    },
    PlatformAIProfileFactoryRow {
        alias: "local-gpu",
        privacy_posture: "local-preferred",
        compute_posture: "cuda-capable",
        capability_set: &[
            "text.generate",
            "text.generate.vision",
            "audio.transcribe",
            "audio.synthesize",
            "image.generate",
            "image.edit",
        ],
        routing_policy: "local-first",
        host_capability_profile_refs: &["windows-amd64-nvidia-cuda", "darwin-arm64-metal"],
        local_compute_pack_refs: &[
            "local-text",
            "local-speech",
            "local-image-native",
            "local-gpu-support",
        ],
        dependency_family_refs: &[
            "accelerator.cuda.runtime",
            "native-engine-package.llama",
            "native-engine-package.stablediffusion-ggml",
            "python.tool.uv",
            "python.runtime",
            "python.venv",
            "python.package-set",
            "python.torch-wheel",
            "model.asset",
            "model.companion-asset",
        ],
        materialization_confirmation_required: true,
        applicable_scopes: &["first-run", "first-party-app", "scope-bound-apply"],
        first_run_install_levels: &["recommended"],
        source_rule: "P-AIPS-002",
    },
    PlatformAIProfileFactoryRow {
        alias: "hybrid-recommended",
        privacy_posture: "cloud-ok",
        compute_posture: "cuda-capable",
        capability_set: &[
            "text.generate",
            "text.generate.vision",
            "text.embed",
            "audio.transcribe",
            "audio.synthesize",
            "image.generate",
            "image.edit",
            "video.generate",
        ],
        routing_policy: "hybrid-explicit",
        host_capability_profile_refs: &[
            "windows-amd64-nvidia-cuda",
            "darwin-arm64-metal",
            "windows-amd64-cpu",
        ],
        local_compute_pack_refs: &["local-text", "local-speech", "local-image-native"],
        dependency_family_refs: &[
            "native-engine-package.llama",
            "native-engine-package.stablediffusion-ggml",
            "python.tool.uv",
            "python.runtime",
            "python.venv",
            "python.package-set",
            "model.asset",
            "model.companion-asset",
        ],
        materialization_confirmation_required: true,
        applicable_scopes: &["first-party-app", "scope-bound-apply"],
        first_run_install_levels: &[],
        source_rule: "P-AIPS-002",
    },
];

pub fn resolve_factory_ai_profile_alias(
    alias: &str,
) -> Option<&'static PlatformAIProfileFactoryRow> {
    let normalized = alias.trim();
    if normalized.is_empty() {
        return None;
    }
    PLATFORM_AI_PROFILE_FACTORY_ROWS
        .iter()
        .find(|row| row.alias == normalized)
}

pub fn verify_first_run_factory_ai_profile(
    alias: &str,
    install_level: &str,
) -> Result<&'static PlatformAIProfileFactoryRow, String> {
    let normalized_level = install_level.trim();
    let Some(row) = resolve_factory_ai_profile_alias(alias) else {
        return Err(format!(
            "selected aiProfileAlias is not admitted in Platform factory catalog: {}",
            alias.trim()
        ));
    };
    if !row.applicable_scopes.contains(&"first-run") {
        return Err(format!(
            "aiProfileAlias is not admitted for first-run: {}",
            row.alias
        ));
    }
    if !row.first_run_install_levels.contains(&normalized_level) {
        return Err(format!(
            "aiProfileAlias {} is not admitted for first-run install level {}",
            row.alias, normalized_level
        ));
    }
    if row.compute_posture == "cloud-only"
        || row.routing_policy == "cloud-first"
        || row.routing_policy == "hybrid-explicit"
        || row.capability_set.contains(&"video.generate")
    {
        return Err(format!(
            "aiProfileAlias {} is not an admitted local first-run baseline",
            row.alias
        ));
    }
    Ok(row)
}
