/*
 * @generated by scripts/generate-platform-catalog.mjs
 * Source: .nimi/spec/platform/kernel/tables/nimi-app-registry.yaml
 * Source: .nimi/spec/platform/kernel/tables/nimi-app-release-descriptors.yaml
 *
 * This file is a packaged Platform Nimi App registry + release descriptor
 * catalog projection for Rust host registry.json projection writers.
 * It is not a canonical row source.
 */

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformNimiAppRegistryRow {
    pub app_id: &'static str,
    pub app_kind: &'static str,
    pub display_name: &'static str,
    pub publisher: &'static str,
    pub trust_tier: &'static str,
    pub ordinary_visibility: &'static str,
    pub release_descriptor_ref: &'static str,
    pub install_storage_policy_ref: &'static str,
    pub admission_status: &'static str,
    pub source_rule: &'static str,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct PlatformNimiAppReleaseDescriptorRow {
    pub descriptor_id: &'static str,
    pub app_id: &'static str,
    pub version: &'static str,
    pub descriptor_class: &'static str,
    pub source_kind: &'static str,
    pub sha256: &'static str,
    pub package_kind: &'static str,
    pub storage_policy_ref: &'static str,
    pub digest_algorithm: &'static str,
    pub mutable_source_allowed: bool,
    pub admission_path: &'static str,
    pub install_digest_verification_required: &'static str,
    pub source_rule: &'static str,
}

pub const PLATFORM_NIMI_APP_REGISTRY_CATALOG_ID: &str = "platform_nimi_app_registry";
pub const PLATFORM_NIMI_APP_REGISTRY_CATALOG_VERSION: u32 = 1;

pub const PLATFORM_NIMI_APP_REGISTRY_ROWS: &[PlatformNimiAppRegistryRow] =
    &[PlatformNimiAppRegistryRow {
        app_id: "nimi.avatar",
        app_kind: "nimi-app",
        display_name: "Avatar",
        publisher: "nimi-first-party",
        trust_tier: "nimi-first-party",
        ordinary_visibility: "hidden-internal",
        release_descriptor_ref: "nimi.avatar.bundled-with-nimi",
        install_storage_policy_ref: "nimi-data-app-roots",
        admission_status: "gated_by_avatar_master_gate",
        source_rule: "P-NAPP-011",
    }];

pub const PLATFORM_NIMI_APP_RELEASE_DESCRIPTOR_ROWS: &[PlatformNimiAppReleaseDescriptorRow] =
    &[PlatformNimiAppReleaseDescriptorRow {
        descriptor_id: "nimi.avatar.bundled-with-nimi",
        app_id: "nimi.avatar",
        version: "bundled-with-current-nimi-release",
        descriptor_class: "bundled-with-nimi",
        source_kind: "nimi-bundle",
        sha256: "inherited-from-atomic-nimi-release-manifest",
        package_kind: "nimi-app",
        storage_policy_ref: "nimi-data-app-roots",
        digest_algorithm: "sha256",
        mutable_source_allowed: false,
        admission_path: "first-party-bundled-release",
        install_digest_verification_required: "inherited_from_atomic_bundle",
        source_rule: "P-NAPP-014",
    }];

pub fn resolve_release_descriptor(
    descriptor_id: &str,
) -> Option<&'static PlatformNimiAppReleaseDescriptorRow> {
    let normalized = descriptor_id.trim();
    if normalized.is_empty() {
        return None;
    }
    PLATFORM_NIMI_APP_RELEASE_DESCRIPTOR_ROWS
        .iter()
        .find(|row| row.descriptor_id == normalized)
}
