import {
  admitProductReadyForUse,
  focusMainWindow,
  getDesktopStorageDirs,
  getProductControlRecord,
  getRuntimeBridgeStatus,
  getRuntimeAccountSessionStatus,
  subscribeRuntimeAccountSessionEvents,
  getRuntimeDefaults,
  hasElectronInvoke,
  getSystemResourceSnapshot,
  logRendererEvent,
  oauthListenForCode,
  openExternalUrl,
  proxyHttp,
  restartRuntimeBridge,
  startRuntimeBridge,
  startWindowDrag,
  syncMenuBarRuntimeHealth,
  pickProductDataRootDirectory,
  selectProductDataRoot,
  planNimiDataCleanup,
  executeNimiDataCleanup,
  exportDesktopLogs,
  ensureProductControlRecordCreated,
  desktopManagedConnectorCredentialAcquisitionHost,
  toRendererLogMessage,
} from './bridge/runtime-bridge';
import type {
  OpenExternalUrlResult,
  OauthListenForCodePayload,
  OauthListenForCodeResult,
  RendererLogMessage,
  MenuBarRuntimeHealthSyncPayload,
  RuntimeBridgeDaemonStatus,
  DesktopAccountSessionState,
  DesktopAccountSessionStatus,
  DesktopAccountSessionEvent,
  RuntimeDefaults,
  NimiProductControlRecord,
  NimiProductControlRecordProjection,
  NimiProductControlState,
  NimiDataCleanupPlan,
  NimiDataCleanupOutcome,
  LogsExportResult,
  SystemResourceSnapshot,
  DesktopStorageDirs,
} from './bridge/runtime-bridge';

export type {
  OpenExternalUrlResult,
  OauthListenForCodePayload,
  OauthListenForCodeResult,
  RendererLogMessage,
  MenuBarRuntimeHealthSyncPayload,
  RuntimeBridgeDaemonStatus,
  DesktopAccountSessionState,
  DesktopAccountSessionStatus,
  DesktopAccountSessionEvent,
  RuntimeDefaults,
  NimiProductControlRecord,
  NimiProductControlRecordProjection,
  NimiProductControlState,
  NimiDataCleanupPlan,
  NimiDataCleanupOutcome,
  LogsExportResult,
  SystemResourceSnapshot,
  DesktopStorageDirs,
};

export { logRendererEvent, syncMenuBarRuntimeHealth, toRendererLogMessage };

export const desktopBridge = {
  hasElectronInvoke,
  getRuntimeBridgeStatus,
  getRuntimeAccountSessionStatus,
  subscribeRuntimeAccountSessionEvents,
  getSystemResourceSnapshot,
  startRuntimeBridge,
  restartRuntimeBridge,
  getRuntimeDefaults,
  getProductControlRecord,
  ensureProductControlRecordCreated,
  getDesktopStorageDirs,
  pickProductDataRootDirectory,
  selectProductDataRoot,
  admitProductReadyForUse,
  planNimiDataCleanup,
  executeNimiDataCleanup,
  exportDesktopLogs,
  proxyHttp,
  desktopManagedConnectorCredentialAcquisitionHost,
  openExternalUrl,
  oauthListenForCode,
  focusMainWindow,
  syncMenuBarRuntimeHealth,
  startWindowDrag,
  logRendererEvent,
};
