// Code generated by scripts/generate-bundled-avatar-runtime-profile.mjs; DO NOT EDIT.
// Source: .nimi/spec/runtime/kernel/tables/bundled-avatar-runtime-profile.yaml

pub const BUNDLED_AVATAR_APP_ID: &str = "nimi.avatar";
pub const BUNDLED_AVATAR_NATIVE_PROFILE_MARKER: &str = "avatar-v1";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum BundledAvatarMethodKind {
    Unary,
    ServerStream,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct BundledAvatarMethodProfile {
    pub method_id: &'static str,
    pub kind: BundledAvatarMethodKind,
    pub capability: &'static str,
}

pub fn bundled_avatar_method_profile(method_id: &str) -> Option<BundledAvatarMethodProfile> {
    match method_id {
        "/nimi.runtime.v1.RuntimeAuditService/GetRuntimeHealth" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAuditService/GetRuntimeHealth",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.health.read",
        }),
        "/nimi.runtime.v1.RuntimeAccountService/GetAccountSessionStatus" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAccountService/GetAccountSessionStatus",
            kind: BundledAvatarMethodKind::Unary,
            capability: "account.session.read",
        }),
        "/nimi.runtime.v1.RuntimeAccountService/SubscribeAccountSessionEvents" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAccountService/SubscribeAccountSessionEvents",
            kind: BundledAvatarMethodKind::ServerStream,
            capability: "account.session.read",
        }),
        "/nimi.runtime.v1.RuntimeAccountService/InvokeRealmUnary" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAccountService/InvokeRealmUnary",
            kind: BundledAvatarMethodKind::Unary,
            capability: "account.realm.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/ListAgents" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/ListAgents",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/GetAgent" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/GetAgent",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/ResolveAvatarLiveInstanceBinding" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/ResolveAvatarLiveInstanceBinding",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/RegisterAvatarLiveInstanceBinding" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/RegisterAvatarLiveInstanceBinding",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/OpenConversationAnchor" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/OpenConversationAnchor",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/GetConversationAnchorSnapshot" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/GetConversationAnchorSnapshot",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/GetPublicChatSessionSnapshot" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/GetPublicChatSessionSnapshot",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/GetCompanionParticipationProjection" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/GetCompanionParticipationProjection",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.companion_participation.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/RequestCompanionParticipation" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/RequestCompanionParticipation",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.companion_participation.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/CancelCompanionParticipation" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/CancelCompanionParticipation",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.companion_participation.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/OpenCompanionParticipationReplay" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/OpenCompanionParticipationReplay",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.companion_participation.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/InterruptAgentVoicePlayback" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/InterruptAgentVoicePlayback",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.turn.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/GetAvatarDebugSnapshot" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/GetAvatarDebugSnapshot",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.avatar_debug.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/RequestAvatarDebugProbe" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/RequestAvatarDebugProbe",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.avatar_debug.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/SubmitAvatarDebugProbeResult" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/SubmitAvatarDebugProbeResult",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.avatar_debug.write",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/ListAvatarDebugProbeResults" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/ListAvatarDebugProbeResults",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.avatar_debug.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/GetAvatarDebugReplay" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/GetAvatarDebugReplay",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.avatar_debug.read",
        }),
        "/nimi.runtime.v1.RuntimeArtifactService/ReadArtifactBytes" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeArtifactService/ReadArtifactBytes",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.artifact.read",
        }),
        "/nimi.runtime.v1.RuntimeAiService/SubmitScenarioJob" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAiService/SubmitScenarioJob",
            kind: BundledAvatarMethodKind::Unary,
            capability: "ai.spend.meter",
        }),
        "/nimi.runtime.v1.RuntimeAiService/GetScenarioJob" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAiService/GetScenarioJob",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.ai.scenario.read",
        }),
        "/nimi.runtime.v1.RuntimeAiService/CancelScenarioJob" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAiService/CancelScenarioJob",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.ai.scenario.write",
        }),
        "/nimi.runtime.v1.RuntimeAiService/GetScenarioArtifacts" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAiService/GetScenarioArtifacts",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.ai.scenario.read",
        }),
        "/nimi.runtime.v1.RuntimeAiService/SubscribeScenarioJobEvents" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAiService/SubscribeScenarioJobEvents",
            kind: BundledAvatarMethodKind::ServerStream,
            capability: "runtime.ai.scenario.read",
        }),
        "/nimi.runtime.v1.RuntimeAppService/SendAppMessage" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAppService/SendAppMessage",
            kind: BundledAvatarMethodKind::Unary,
            capability: "runtime.agent.turn.write",
        }),
        "/nimi.runtime.v1.RuntimeAppService/SubscribeAppMessages" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAppService/SubscribeAppMessages",
            kind: BundledAvatarMethodKind::ServerStream,
            capability: "runtime.agent.turn.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/SubscribeAgentEvents" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/SubscribeAgentEvents",
            kind: BundledAvatarMethodKind::ServerStream,
            capability: "runtime.agent.read",
        }),
        "/nimi.runtime.v1.RuntimeAgentService/SubscribeAgentVoiceStream" => Some(BundledAvatarMethodProfile {
            method_id: "/nimi.runtime.v1.RuntimeAgentService/SubscribeAgentVoiceStream",
            kind: BundledAvatarMethodKind::ServerStream,
            capability: "runtime.agent.turn.read",
        }),
        _ => None,
    }
}
