// Auto-derived from the recovered desktop en locale bundles (55-ModelConfig.json,
// 54-Tester.json) so the kit model-config editors render real labels instead of
// raw i18n keys. Regenerate from the locale source rather than hand-editing.

export const testerModelConfigCopy: Record<string, string> = {
  "ModelConfig.profile.sectionTitle": "Profile",
  "ModelConfig.profile.summaryLabel": "AI Profile",
  "ModelConfig.profile.emptySummaryLabel": "No profile applied",
  "ModelConfig.profile.applyButtonLabel": "Apply profile",
  "ModelConfig.profile.changeButtonLabel": "Change",
  "ModelConfig.profile.manageButtonTitle": "Manage profiles",
  "ModelConfig.profile.modalTitle": "Apply AI Profile",
  "ModelConfig.profile.modalHint": "Selecting a profile will overwrite all current capability bindings. This action cannot be undone.",
  "ModelConfig.profile.loadingLabel": "Loading profiles...",
  "ModelConfig.profile.emptyLabel": "No profiles available.",
  "ModelConfig.profile.currentBadgeLabel": "Current",
  "ModelConfig.profile.cancelLabel": "Cancel",
  "ModelConfig.profile.confirmLabel": "Confirm & Apply",
  "ModelConfig.profile.applyingLabel": "Applying...",
  "ModelConfig.profile.reloadLabel": "Reload",
  "ModelConfig.profile.importLabel": "Import AI Profile",
  "ModelConfig.profile.previewTitle": "Review changes",
  "ModelConfig.profile.previewHint": "Review the before and after configuration. Nothing is saved until you confirm.",
  "ModelConfig.profile.previewingLabel": "Computing preview...",
  "ModelConfig.profile.previewFirstApplyLabel": "This scope has no AI configuration yet — applying this profile creates it.",
  "ModelConfig.profile.previewNoChangeLabel": "This profile matches the current configuration. Applying it changes nothing.",
  "ModelConfig.profile.previewBeforeLabel": "Current",
  "ModelConfig.profile.previewAfterLabel": "After apply",
  "ModelConfig.profile.previewWarningsLabel": "Warnings",
  "ModelConfig.profile.previewConfirmLabel": "Confirm & Apply",
  "ModelConfig.profile.previewBackLabel": "Back",
  "ModelConfig.section.chat.title": "Chat",
  "ModelConfig.section.tts.title": "Text to speech",
  "ModelConfig.section.stt.title": "Speech to text",
  "ModelConfig.section.image.title": "Image",
  "ModelConfig.section.video.title": "Video",
  "ModelConfig.section.voice.title": "Voice",
  "ModelConfig.section.embed.title": "Embeddings",
  "ModelConfig.section.world.title": "World",
  "ModelConfig.capability.audioSynthesize.title": "Text to speech",
  "ModelConfig.capability.audioSynthesize.subtitle": "Generate speech audio from text",
  "ModelConfig.capability.audioSynthesize.detail": "Routes text-to-speech requests through the selected local or cloud speech model.",
  "ModelConfig.capability.audioTranscribe.title": "Speech to text",
  "ModelConfig.capability.audioTranscribe.subtitle": "Transcribe audio to text",
  "ModelConfig.capability.audioTranscribe.detail": "Routes transcription requests through the selected speech recognition model.",
  "ModelConfig.capability.imageEdit.title": "Image edit",
  "ModelConfig.capability.imageEdit.subtitle": "Edit images with a prompt",
  "ModelConfig.capability.imageGenerate.title": "Image generation",
  "ModelConfig.capability.imageGenerate.subtitle": "Generate images from prompts",
  "ModelConfig.capability.textEmbed.title": "Embeddings",
  "ModelConfig.capability.textEmbed.subtitle": "Generate vector embeddings",
  "ModelConfig.capability.textGenerate.title": "Chat",
  "ModelConfig.capability.textGenerate.subtitle": "Text generation",
  "ModelConfig.capability.textGenerateVision.title": "Vision chat",
  "ModelConfig.capability.textGenerateVision.subtitle": "Generate text from image and text input",
  "ModelConfig.capability.videoGenerate.title": "Video generation",
  "ModelConfig.capability.videoGenerate.subtitle": "Generate videos from prompts",
  "ModelConfig.capability.voiceWorkflowVoiceDesign.title": "Voice design",
  "ModelConfig.capability.voiceWorkflowVoiceDesign.subtitle": "Create a voice from instructions",
  "ModelConfig.capability.voiceWorkflowVoiceDesign.detail": "Routes text-to-voice asset creation through the selected voice design workflow model.",
  "ModelConfig.capability.voiceWorkflowVoiceClone.title": "Voice clone",
  "ModelConfig.capability.voiceWorkflowVoiceClone.subtitle": "Create a voice from reference audio",
  "ModelConfig.capability.voiceWorkflowVoiceClone.detail": "Routes reference-audio voice asset creation through the selected voice clone workflow model.",
  "ModelConfig.capability.worldGenerate.title": "World generation",
  "ModelConfig.capability.worldGenerate.subtitle": "Generate world scenes",
  "ModelConfig.editor.common.timeoutLabel": "Timeout",
  "ModelConfig.editor.common.defaultPlaceholder": "Default",
  "ModelConfig.editor.common.previewBadgeLabel": "Preview",
  "ModelConfig.editor.common.seedLabel": "Seed",
  "ModelConfig.editor.common.seedHint": "Leave empty to use the provider default.",
  "ModelConfig.editor.common.randomPlaceholder": "Random",
  "ModelConfig.editor.common.noneLabel": "None",
  "ModelConfig.editor.textGenerate.parametersLabel": "Parameters",
  "ModelConfig.editor.textGenerate.promptControlsLabel": "Prompt Controls",
  "ModelConfig.editor.textGenerate.toneLabel": "Tone",
  "ModelConfig.editor.textGenerate.lengthLabel": "Length",
  "ModelConfig.editor.textGenerate.tone.clear": "Clear",
  "ModelConfig.editor.textGenerate.tone.warm": "Warm",
  "ModelConfig.editor.textGenerate.tone.formal": "Formal",
  "ModelConfig.editor.textGenerate.tone.short": "Short",
  "ModelConfig.editor.textGenerate.length.short": "Short",
  "ModelConfig.editor.textGenerate.length.medium": "Medium",
  "ModelConfig.editor.textGenerate.length.detailed": "Detailed",
  "ModelConfig.editor.textGenerate.generationDefaultsLabel": "Generation Defaults",
  "ModelConfig.editor.textGenerate.responseControlsLabel": "Response Controls",
  "ModelConfig.editor.textGenerate.advancedLabel": "Advanced Settings",
  "ModelConfig.editor.textGenerate.temperatureLabel": "Temperature",
  "ModelConfig.editor.textGenerate.topPLabel": "Top P",
  "ModelConfig.editor.textGenerate.topKLabel": "Top K",
  "ModelConfig.editor.textGenerate.maxTokensLabel": "Max Tokens",
  "ModelConfig.editor.textGenerate.stopSequencesLabel": "Stop Sequences",
  "ModelConfig.editor.textGenerate.stopSequencesHint": "Up to {{max}} sequences, one per line.",
  "ModelConfig.editor.textGenerate.stopSequencesPlaceholder": "Type and press enter…",
  "ModelConfig.editor.textGenerate.presencePenaltyLabel": "Presence Penalty",
  "ModelConfig.editor.textGenerate.frequencyPenaltyLabel": "Frequency Penalty",
  "ModelConfig.editor.audioSynthesize.parametersLabel": "Parameters",
  "ModelConfig.editor.audioSynthesize.voiceSectionLabel": "Voice",
  "ModelConfig.editor.audioSynthesize.audioTuningSectionLabel": "Audio Tuning",
  "ModelConfig.editor.audioSynthesize.outputSectionLabel": "Output",
  "ModelConfig.editor.audioSynthesize.voiceRefLabel": "Voice reference",
  "ModelConfig.editor.audioSynthesize.voiceRefHint": "Preset voice, custom voice asset, or provider voice reference.",
  "ModelConfig.editor.audioSynthesize.speakingRateLabel": "Speaking Rate",
  "ModelConfig.editor.audioSynthesize.volumeLabel": "Volume",
  "ModelConfig.editor.audioSynthesize.pitchSemitonesLabel": "Pitch (semitones)",
  "ModelConfig.editor.audioSynthesize.languageHintLabel": "Language Hint",
  "ModelConfig.editor.audioSynthesize.languageHintHint": "BCP-47 tag, e.g. en-US.",
  "ModelConfig.editor.audioSynthesize.responseFormatLabel": "Response Format",
  "ModelConfig.editor.audioTranscribe.parametersLabel": "Parameters",
  "ModelConfig.editor.audioTranscribe.languageLabel": "Language",
  "ModelConfig.editor.audioTranscribe.languageHint": "BCP-47 language hint, such as en or zh-CN.",
  "ModelConfig.editor.audioTranscribe.responseFormatLabel": "Response format",
  "ModelConfig.editor.audioTranscribe.speakerCountLabel": "Speakers",
  "ModelConfig.editor.audioTranscribe.promptLabel": "Prompt",
  "ModelConfig.editor.audioTranscribe.timestampsLabel": "Timestamps",
  "ModelConfig.editor.audioTranscribe.diarizationLabel": "Diarization",
  "ModelConfig.editor.audioTranscribe.promptPlaceholder": "Optional vocabulary or context",
  "ModelConfig.editor.voiceWorkflow.parametersLabel": "Parameters",
  "ModelConfig.editor.voiceWorkflow.cloneParametersLabel": "Voice clone parameters",
  "ModelConfig.editor.voiceWorkflow.designParametersLabel": "Voice design parameters",
  "ModelConfig.editor.voiceWorkflow.referenceAssetLabel": "Reference voice",
  "ModelConfig.editor.voiceWorkflow.referenceAssetHint": "Use an existing local voice asset when available.",
  "ModelConfig.editor.voiceWorkflow.referenceTextLabel": "Reference text",
  "ModelConfig.editor.voiceWorkflow.voiceDesignPromptLabel": "Design prompt",
  "ModelConfig.editor.voiceWorkflow.voiceDesignPromptHint": "Describe the voice style to generate.",
  "ModelConfig.editor.voiceWorkflow.previewTextLabel": "Preview text",
  "ModelConfig.editor.voiceWorkflow.languageLabel": "Language",
  "ModelConfig.editor.voiceWorkflow.preferredNameLabel": "Preferred name",
  "ModelConfig.editor.voiceWorkflow.durationLabel": "Duration",
  "ModelConfig.editor.voiceWorkflow.referenceTextPlaceholder": "Optional transcript for the reference audio",
  "ModelConfig.editor.voiceWorkflow.voiceDesignPromptPlaceholder": "Warm, natural, conversational voice",
  "ModelConfig.editor.voiceWorkflow.previewTextPlaceholder": "Text used to audition the designed voice",
  "ModelConfig.editor.voiceWorkflow.languagePlaceholder": "Language (optional)",
  "ModelConfig.editor.voiceWorkflow.preferredNamePlaceholder": "Preferred voice asset name",
  "ModelConfig.editor.voiceWorkflow.referenceAssetPlaceholder": "Select a voice asset",
  "ModelConfig.editor.image.companionModelsLabel": "Companion models",
  "ModelConfig.editor.image.parametersLabel": "Parameters",
  "ModelConfig.editor.image.sizeLabel": "Size",
  "ModelConfig.editor.image.responseFormatLabel": "Response format",
  "ModelConfig.editor.image.stepsLabel": "Steps",
  "ModelConfig.editor.image.cfgScaleLabel": "CFG scale",
  "ModelConfig.editor.image.samplerLabel": "Sampler",
  "ModelConfig.editor.image.schedulerLabel": "Scheduler",
  "ModelConfig.editor.image.customOptionsLabel": "Custom options",
  "ModelConfig.editor.image.customOptionsHint": "Advanced provider-specific options, one per line.",
  "ModelConfig.editor.image.oneOptionPerLinePlaceholder": "key=value, one per line",
  "ModelConfig.editor.video.parametersLabel": "Parameters",
  "ModelConfig.editor.video.modeLabel": "Mode",
  "ModelConfig.editor.video.ratioLabel": "Ratio",
  "ModelConfig.editor.video.durationLabel": "Duration",
  "ModelConfig.editor.video.durationHint": "Duration in seconds.",
  "ModelConfig.editor.video.resolutionLabel": "Resolution",
  "ModelConfig.editor.video.fpsLabel": "FPS",
  "ModelConfig.editor.video.cameraFixedLabel": "Fixed camera",
  "ModelConfig.editor.video.generateAudioLabel": "Generate audio",
  "ModelConfig.hub.title": "AI Models",
  "ModelConfig.hub.backLabel": "Back",
  "ModelConfig.hub.aggregateReady": "{{count}} ready",
  "ModelConfig.hub.aggregateAttention": "{{count}} need attention",
  "ModelConfig.hub.aggregateNeutral": "{{count}} unset",
  "ModelConfig.hub.aggregateEmpty": "No capabilities configured",
  "ModelConfig.hub.detailTitleFormat": "{{section}} Configuration",
  "ModelConfig.hub.activeModelLabel": "Active Model",
  "ModelConfig.hub.detailStatusReady": "Runtime Ready",
  "ModelConfig.hub.detailStatusAttention": "Needs Setup",
  "ModelConfig.hub.detailStatusNeutral": "Not Configured",
  "Tester.settings.title": "AI Tester Settings",
  "Tester.settings.back": "Back",
  "Tester.settings.detailSubtitle": "Configure models and defaults",
  "Tester.settings.generalGroup": "General",
  "Tester.settings.reset": "Reset",
  "Tester.settings.save": "Save Changes"
};
