import { RuntimeMethodIds } from '../method-ids';
import { Ack } from '../generated/runtime/v1/common';
import {
  ApplyProfileRequest,
  ApplyProfileResponse,
  AdmitProductControlReadyForUseRequest,
  AppendInferenceAuditRequest,
  AppendRuntimeAuditRequest,
  CancelLocalEnvironmentDependencyJobRequest,
  CancelLocalEnvironmentDependencyJobResponse,
  CheckLocalAssetHealthRequest,
  CheckLocalAssetHealthResponse,
  CheckLocalServiceHealthRequest,
  CheckLocalServiceHealthResponse,
  CollectDeviceProfileRequest,
  CollectDeviceProfileResponse,
  CompleteProductControlFirstRunDeviceEnvironmentScanRequest,
  EnsureProductControlRecordCreatedRequest,
  GetRecommendationFeedRequest,
  GetRecommendationFeedResponse,
  GetProductControlRecordRequest,
  GetProductControlSelectedDataRootRequest,
  CancelLocalTransferRequest,
  CancelLocalTransferResponse,
  ImportLocalAssetRequest,
  ImportLocalAssetResponse,
  ImportLocalAssetFileRequest,
  ImportLocalAssetFileResponse,
  ImportLocalAssetBundleRequest,
  ImportLocalAssetBundleResponse,
  InstallLocalServiceRequest,
  InstallLocalServiceResponse,
  InstallModelFromPlanRequest,
  InstallModelFromPlanResponse,
  InstallVerifiedAssetRequest,
  InstallVerifiedAssetResponse,
  ListCatalogVariantsRequest,
  ListCatalogVariantsResponse,
  ListLocalAssetsRequest,
  ListLocalAssetsResponse,
  ListLocalAuditsRequest,
  ListLocalAuditsResponse,
  ListLocalEnvironmentDependencyJobsRequest,
  ListLocalEnvironmentDependencyJobsResponse,
  ListLocalEnvironmentSelectedSourcesRequest,
  ListLocalEnvironmentSelectedSourcesResponse,
  ListLocalServicesRequest,
  ListLocalServicesResponse,
  ListLocalTransfersRequest,
  ListLocalTransfersResponse,
  ListNodeCatalogRequest,
  ListNodeCatalogResponse,
  ListVerifiedAssetsRequest,
  ListVerifiedAssetsResponse,
  PauseLocalTransferRequest,
  PauseLocalTransferResponse,
  ProductControlProjectionJson,
  ReconcileProductControlFirstRunSetupStateRequest,
  RecordProductControlAccountDefaultProfileEvidenceRequest,
  RecordProductControlFirstRunLocalAiReadyEvidenceRequest,
  RemoveLocalAssetRequest,
  RemoveLocalAssetResponse,
  RemoveLocalServiceRequest,
  RemoveLocalServiceResponse,
  RepairLocalEnvironmentDependencyRequest,
  RepairLocalEnvironmentDependencyResponse,
  RescanLocalAssetBundleRequest,
  RescanLocalAssetBundleResponse,
  ResolveLocalEnvironmentActivationGateRequest,
  ResolveLocalEnvironmentActivationGateResponse,
  ResolveLocalEnvironmentPlanRequest,
  ResolveLocalEnvironmentPlanResponse,
  MintRuntimeBaselineReadinessRequest,
  MintRuntimeBaselineReadinessResponse,
  ResolveRuntimeBaselineReadinessRequest,
  ResolveRuntimeBaselineReadinessResponse,
  MintFirstRunExecutionEvidenceRequest,
  MintFirstRunExecutionEvidenceResponse,
  ResolveFirstRunExecutionEvidenceRequest,
  ResolveFirstRunExecutionEvidenceResponse,
  ResolveModelInstallPlanRequest,
  ResolveModelInstallPlanResponse,
  ResolveProfileRequest,
  ResolveProfileResponse,
  ResumeLocalTransferRequest,
  ResumeLocalTransferResponse,
  RetryLocalEnvironmentDependencyJobRequest,
  RetryLocalEnvironmentDependencyJobResponse,
  ScanUnregisteredAssetsRequest,
  ScanUnregisteredAssetsResponse,
  ScaffoldOrphanAssetRequest,
  ScaffoldOrphanAssetResponse,
  SearchCatalogModelsRequest,
  SearchCatalogModelsResponse,
  SelectProductControlDataRootRequest,
  SetProductControlFirstRunInstallLevelRequest,
  StartLocalAssetRequest,
  StartLocalAssetResponse,
  StartLocalEnvironmentDependencyJobRequest,
  StartLocalEnvironmentDependencyJobResponse,
  StartLocalServiceRequest,
  StartLocalServiceResponse,
  StopLocalAssetRequest,
  StopLocalAssetResponse,
  StopLocalServiceRequest,
  StopLocalServiceResponse,
  WarmLocalAssetRequest,
  WarmLocalAssetResponse,
} from '../generated/runtime/v1/local_runtime';
import {
  EnsureEngineRequest,
  EnsureEngineResponse,
  GetEngineStatusRequest,
  GetEngineStatusResponse,
  ListEnginesRequest,
  ListEnginesResponse,
  StartEngineRequest,
  StartEngineResponse,
  StopEngineRequest,
  StopEngineResponse,
} from '../generated/runtime/v1/local_runtime_engine';
import type { RuntimeUnaryMethodCodecMap } from './method-codecs-types';

export const runtimeUnaryMethodCodecsLocal: Partial<RuntimeUnaryMethodCodecMap> = {
  [RuntimeMethodIds.local.listLocalAssets]: {
    requestType: ListLocalAssetsRequest,
    responseType: ListLocalAssetsResponse,
  },
  [RuntimeMethodIds.local.listVerifiedAssets]: {
    requestType: ListVerifiedAssetsRequest,
    responseType: ListVerifiedAssetsResponse,
  },
  [RuntimeMethodIds.local.searchCatalogModels]: {
    requestType: SearchCatalogModelsRequest,
    responseType: SearchCatalogModelsResponse,
  },
  [RuntimeMethodIds.local.listCatalogVariants]: {
    requestType: ListCatalogVariantsRequest,
    responseType: ListCatalogVariantsResponse,
  },
  [RuntimeMethodIds.local.getRecommendationFeed]: {
    requestType: GetRecommendationFeedRequest,
    responseType: GetRecommendationFeedResponse,
  },
  [RuntimeMethodIds.local.resolveModelInstallPlan]: {
    requestType: ResolveModelInstallPlanRequest,
    responseType: ResolveModelInstallPlanResponse,
  },
  [RuntimeMethodIds.local.installModelFromPlan]: {
    requestType: InstallModelFromPlanRequest,
    responseType: InstallModelFromPlanResponse,
  },
  [RuntimeMethodIds.local.installVerifiedAsset]: {
    requestType: InstallVerifiedAssetRequest,
    responseType: InstallVerifiedAssetResponse,
  },
  [RuntimeMethodIds.local.importLocalAsset]: {
    requestType: ImportLocalAssetRequest,
    responseType: ImportLocalAssetResponse,
  },
  [RuntimeMethodIds.local.importLocalAssetFile]: {
    requestType: ImportLocalAssetFileRequest,
    responseType: ImportLocalAssetFileResponse,
  },
  [RuntimeMethodIds.local.importLocalAssetBundle]: {
    requestType: ImportLocalAssetBundleRequest,
    responseType: ImportLocalAssetBundleResponse,
  },
  [RuntimeMethodIds.local.rescanLocalAssetBundle]: {
    requestType: RescanLocalAssetBundleRequest,
    responseType: RescanLocalAssetBundleResponse,
  },
  [RuntimeMethodIds.local.listLocalTransfers]: {
    requestType: ListLocalTransfersRequest,
    responseType: ListLocalTransfersResponse,
  },
  [RuntimeMethodIds.local.pauseLocalTransfer]: {
    requestType: PauseLocalTransferRequest,
    responseType: PauseLocalTransferResponse,
  },
  [RuntimeMethodIds.local.resumeLocalTransfer]: {
    requestType: ResumeLocalTransferRequest,
    responseType: ResumeLocalTransferResponse,
  },
  [RuntimeMethodIds.local.cancelLocalTransfer]: {
    requestType: CancelLocalTransferRequest,
    responseType: CancelLocalTransferResponse,
  },
  [RuntimeMethodIds.local.scanUnregisteredAssets]: {
    requestType: ScanUnregisteredAssetsRequest,
    responseType: ScanUnregisteredAssetsResponse,
  },
  [RuntimeMethodIds.local.scaffoldOrphanAsset]: {
    requestType: ScaffoldOrphanAssetRequest,
    responseType: ScaffoldOrphanAssetResponse,
  },
  [RuntimeMethodIds.local.removeLocalAsset]: {
    requestType: RemoveLocalAssetRequest,
    responseType: RemoveLocalAssetResponse,
  },
  [RuntimeMethodIds.local.startLocalAsset]: {
    requestType: StartLocalAssetRequest,
    responseType: StartLocalAssetResponse,
  },
  [RuntimeMethodIds.local.stopLocalAsset]: {
    requestType: StopLocalAssetRequest,
    responseType: StopLocalAssetResponse,
  },
  [RuntimeMethodIds.local.checkLocalAssetHealth]: {
    requestType: CheckLocalAssetHealthRequest,
    responseType: CheckLocalAssetHealthResponse,
  },
  [RuntimeMethodIds.local.warmLocalAsset]: {
    requestType: WarmLocalAssetRequest,
    responseType: WarmLocalAssetResponse,
  },
  [RuntimeMethodIds.local.collectDeviceProfile]: {
    requestType: CollectDeviceProfileRequest,
    responseType: CollectDeviceProfileResponse,
  },
  [RuntimeMethodIds.local.resolveProfile]: {
    requestType: ResolveProfileRequest,
    responseType: ResolveProfileResponse,
  },
  [RuntimeMethodIds.local.applyProfile]: {
    requestType: ApplyProfileRequest,
    responseType: ApplyProfileResponse,
  },
  [RuntimeMethodIds.local.listLocalServices]: {
    requestType: ListLocalServicesRequest,
    responseType: ListLocalServicesResponse,
  },
  [RuntimeMethodIds.local.installLocalService]: {
    requestType: InstallLocalServiceRequest,
    responseType: InstallLocalServiceResponse,
  },
  [RuntimeMethodIds.local.startLocalService]: {
    requestType: StartLocalServiceRequest,
    responseType: StartLocalServiceResponse,
  },
  [RuntimeMethodIds.local.stopLocalService]: {
    requestType: StopLocalServiceRequest,
    responseType: StopLocalServiceResponse,
  },
  [RuntimeMethodIds.local.checkLocalServiceHealth]: {
    requestType: CheckLocalServiceHealthRequest,
    responseType: CheckLocalServiceHealthResponse,
  },
  [RuntimeMethodIds.local.removeLocalService]: {
    requestType: RemoveLocalServiceRequest,
    responseType: RemoveLocalServiceResponse,
  },
  [RuntimeMethodIds.local.listNodeCatalog]: {
    requestType: ListNodeCatalogRequest,
    responseType: ListNodeCatalogResponse,
  },
  [RuntimeMethodIds.local.listLocalAudits]: {
    requestType: ListLocalAuditsRequest,
    responseType: ListLocalAuditsResponse,
  },
  [RuntimeMethodIds.local.appendInferenceAudit]: {
    requestType: AppendInferenceAuditRequest,
    responseType: Ack,
  },
  [RuntimeMethodIds.local.appendRuntimeAudit]: {
    requestType: AppendRuntimeAuditRequest,
    responseType: Ack,
  },
  [RuntimeMethodIds.local.listEngines]: {
    requestType: ListEnginesRequest,
    responseType: ListEnginesResponse,
  },
  [RuntimeMethodIds.local.ensureEngine]: {
    requestType: EnsureEngineRequest,
    responseType: EnsureEngineResponse,
  },
  [RuntimeMethodIds.local.startEngine]: {
    requestType: StartEngineRequest,
    responseType: StartEngineResponse,
  },
  [RuntimeMethodIds.local.stopEngine]: {
    requestType: StopEngineRequest,
    responseType: StopEngineResponse,
  },
  [RuntimeMethodIds.local.getEngineStatus]: {
    requestType: GetEngineStatusRequest,
    responseType: GetEngineStatusResponse,
  },
  [RuntimeMethodIds.local.resolveLocalEnvironmentPlan]: {
    requestType: ResolveLocalEnvironmentPlanRequest,
    responseType: ResolveLocalEnvironmentPlanResponse,
  },
  [RuntimeMethodIds.local.listLocalEnvironmentSelectedSources]: {
    requestType: ListLocalEnvironmentSelectedSourcesRequest,
    responseType: ListLocalEnvironmentSelectedSourcesResponse,
  },
  [RuntimeMethodIds.local.listLocalEnvironmentDependencyJobs]: {
    requestType: ListLocalEnvironmentDependencyJobsRequest,
    responseType: ListLocalEnvironmentDependencyJobsResponse,
  },
  [RuntimeMethodIds.local.resolveLocalEnvironmentActivationGate]: {
    requestType: ResolveLocalEnvironmentActivationGateRequest,
    responseType: ResolveLocalEnvironmentActivationGateResponse,
  },
  [RuntimeMethodIds.local.mintRuntimeBaselineReadiness]: {
    requestType: MintRuntimeBaselineReadinessRequest,
    responseType: MintRuntimeBaselineReadinessResponse,
  },
  [RuntimeMethodIds.local.resolveRuntimeBaselineReadiness]: {
    requestType: ResolveRuntimeBaselineReadinessRequest,
    responseType: ResolveRuntimeBaselineReadinessResponse,
  },
  [RuntimeMethodIds.local.mintFirstRunExecutionEvidence]: {
    requestType: MintFirstRunExecutionEvidenceRequest,
    responseType: MintFirstRunExecutionEvidenceResponse,
  },
  [RuntimeMethodIds.local.resolveFirstRunExecutionEvidence]: {
    requestType: ResolveFirstRunExecutionEvidenceRequest,
    responseType: ResolveFirstRunExecutionEvidenceResponse,
  },
  [RuntimeMethodIds.local.getProductControlRecord]: {
    requestType: GetProductControlRecordRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.getProductControlSelectedDataRoot]: {
    requestType: GetProductControlSelectedDataRootRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.ensureProductControlRecordCreated]: {
    requestType: EnsureProductControlRecordCreatedRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.selectProductControlDataRoot]: {
    requestType: SelectProductControlDataRootRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.setProductControlFirstRunInstallLevel]: {
    requestType: SetProductControlFirstRunInstallLevelRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.completeProductControlFirstRunDeviceEnvironmentScan]: {
    requestType: CompleteProductControlFirstRunDeviceEnvironmentScanRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.admitProductControlReadyForUse]: {
    requestType: AdmitProductControlReadyForUseRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.recordProductControlAccountDefaultProfileEvidence]: {
    requestType: RecordProductControlAccountDefaultProfileEvidenceRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.recordProductControlFirstRunLocalAiReadyEvidence]: {
    requestType: RecordProductControlFirstRunLocalAiReadyEvidenceRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.reconcileProductControlFirstRunSetupState]: {
    requestType: ReconcileProductControlFirstRunSetupStateRequest,
    responseType: ProductControlProjectionJson,
  },
  [RuntimeMethodIds.local.startLocalEnvironmentDependencyJob]: {
    requestType: StartLocalEnvironmentDependencyJobRequest,
    responseType: StartLocalEnvironmentDependencyJobResponse,
  },
  [RuntimeMethodIds.local.cancelLocalEnvironmentDependencyJob]: {
    requestType: CancelLocalEnvironmentDependencyJobRequest,
    responseType: CancelLocalEnvironmentDependencyJobResponse,
  },
  [RuntimeMethodIds.local.retryLocalEnvironmentDependencyJob]: {
    requestType: RetryLocalEnvironmentDependencyJobRequest,
    responseType: RetryLocalEnvironmentDependencyJobResponse,
  },
  [RuntimeMethodIds.local.repairLocalEnvironmentDependency]: {
    requestType: RepairLocalEnvironmentDependencyRequest,
    responseType: RepairLocalEnvironmentDependencyResponse,
  },
} satisfies Partial<RuntimeUnaryMethodCodecMap>;
