export enum AvatarDebugProbeKind {
  UNSPECIFIED = 0,
  PACKAGE_VALIDATION = 1,
  LAUNCH_READINESS = 2,
  BACKEND_LOAD = 3,
  CAPABILITY_PROFILE = 4,
  ROUTE_SUPPORT_MATRIX = 5,
  GENERATED_MOTION = 6,
  EMOTION_EXPRESSION = 7,
  SPEECH_LIPSYNC = 8,
  WINDOW_HIT_REGION = 9,
}
