// Code generated by scripts/generate-runtime-connector-auth-profiles.mjs. DO NOT EDIT.

export type ConnectorAuthProfileSpec = {
  id: string;
  authKind: 'oauth_managed';
  allowedProviders: readonly string[];
  headerBehavior: 'none' | 'codex_oauth' | 'anthropic';
  sourceRule: string;
};

export const CONNECTOR_AUTH_PROFILES: Record<string, ConnectorAuthProfileSpec> = {
  "anthropic": {
    id: "anthropic",
    authKind: "oauth_managed",
    allowedProviders: ["anthropic"],
    headerBehavior: "anthropic",
    sourceRule: "K-CONN-002",
  },
  "openai_codex": {
    id: "openai_codex",
    authKind: "oauth_managed",
    allowedProviders: ["openai_codex"],
    headerBehavior: "codex_oauth",
    sourceRule: "K-CONN-002",
  },
  "qwen_oauth": {
    id: "qwen_oauth",
    authKind: "oauth_managed",
    allowedProviders: ["openai_compatible"],
    headerBehavior: "none",
    sourceRule: "K-CONN-002",
  },
};
