export const RuntimeMethodIds = {
  auth: {
    registerApp: '/nimi.runtime.v1.RuntimeAuthService/RegisterApp',
    openSession: '/nimi.runtime.v1.RuntimeAuthService/OpenSession',
    refreshSession: '/nimi.runtime.v1.RuntimeAuthService/RefreshSession',
    revokeSession: '/nimi.runtime.v1.RuntimeAuthService/RevokeSession',
    registerExternalPrincipal: '/nimi.runtime.v1.RuntimeAuthService/RegisterExternalPrincipal',
    openExternalPrincipalSession: '/nimi.runtime.v1.RuntimeAuthService/OpenExternalPrincipalSession',
    revokeExternalPrincipalSession: '/nimi.runtime.v1.RuntimeAuthService/RevokeExternalPrincipalSession',
  },
  appAuth: {
    authorizeExternalPrincipal: '/nimi.runtime.v1.RuntimeGrantService/AuthorizeExternalPrincipal',
    validateToken: '/nimi.runtime.v1.RuntimeGrantService/ValidateAppAccessToken',
    revokeToken: '/nimi.runtime.v1.RuntimeGrantService/RevokeAppAccessToken',
    issueDelegatedToken: '/nimi.runtime.v1.RuntimeGrantService/IssueDelegatedAccessToken',
    listTokenChain: '/nimi.runtime.v1.RuntimeGrantService/ListTokenChain',
  },
  ai: {
    executeScenario: '/nimi.runtime.v1.RuntimeAiService/ExecuteScenario',
    streamScenario: '/nimi.runtime.v1.RuntimeAiService/StreamScenario',
    submitScenarioJob: '/nimi.runtime.v1.RuntimeAiService/SubmitScenarioJob',
    getScenarioJob: '/nimi.runtime.v1.RuntimeAiService/GetScenarioJob',
    cancelScenarioJob: '/nimi.runtime.v1.RuntimeAiService/CancelScenarioJob',
    subscribeScenarioJobEvents: '/nimi.runtime.v1.RuntimeAiService/SubscribeScenarioJobEvents',
    getScenarioArtifacts: '/nimi.runtime.v1.RuntimeAiService/GetScenarioArtifacts',
    listScenarioProfiles: '/nimi.runtime.v1.RuntimeAiService/ListScenarioProfiles',
    getVoiceAsset: '/nimi.runtime.v1.RuntimeAiService/GetVoiceAsset',
    listVoiceAssets: '/nimi.runtime.v1.RuntimeAiService/ListVoiceAssets',
    deleteVoiceAsset: '/nimi.runtime.v1.RuntimeAiService/DeleteVoiceAsset',
    listPresetVoices: '/nimi.runtime.v1.RuntimeAiService/ListPresetVoices',
  },
  workflow: {
    submit: '/nimi.runtime.v1.RuntimeWorkflowService/SubmitWorkflow',
    get: '/nimi.runtime.v1.RuntimeWorkflowService/GetWorkflow',
    cancel: '/nimi.runtime.v1.RuntimeWorkflowService/CancelWorkflow',
    subscribeEvents: '/nimi.runtime.v1.RuntimeWorkflowService/SubscribeWorkflowEvents',
  },
  model: {
    list: '/nimi.runtime.v1.RuntimeModelService/ListModels',
    pull: '/nimi.runtime.v1.RuntimeModelService/PullModel',
    remove: '/nimi.runtime.v1.RuntimeModelService/RemoveModel',
    checkHealth: '/nimi.runtime.v1.RuntimeModelService/CheckModelHealth',
  },
  localRuntime: {
    listLocalModels: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListLocalModels',
    listLocalArtifacts: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListLocalArtifacts',
    listVerifiedModels: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListVerifiedModels',
    listVerifiedArtifacts: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListVerifiedArtifacts',
    searchCatalogModels: '/nimi.runtime.v1.RuntimeLocalRuntimeService/SearchCatalogModels',
    resolveModelInstallPlan: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ResolveModelInstallPlan',
    installLocalModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/InstallLocalModel',
    installVerifiedModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/InstallVerifiedModel',
    installVerifiedArtifact: '/nimi.runtime.v1.RuntimeLocalRuntimeService/InstallVerifiedArtifact',
    importLocalModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ImportLocalModel',
    importLocalArtifact: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ImportLocalArtifact',
    removeLocalModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/RemoveLocalModel',
    removeLocalArtifact: '/nimi.runtime.v1.RuntimeLocalRuntimeService/RemoveLocalArtifact',
    startLocalModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/StartLocalModel',
    stopLocalModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/StopLocalModel',
    checkLocalModelHealth: '/nimi.runtime.v1.RuntimeLocalRuntimeService/CheckLocalModelHealth',
    warmLocalModel: '/nimi.runtime.v1.RuntimeLocalRuntimeService/WarmLocalModel',
    collectDeviceProfile: '/nimi.runtime.v1.RuntimeLocalRuntimeService/CollectDeviceProfile',
    resolveDependencies: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ResolveDependencies',
    applyDependencies: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ApplyDependencies',
    listLocalServices: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListLocalServices',
    installLocalService: '/nimi.runtime.v1.RuntimeLocalRuntimeService/InstallLocalService',
    startLocalService: '/nimi.runtime.v1.RuntimeLocalRuntimeService/StartLocalService',
    stopLocalService: '/nimi.runtime.v1.RuntimeLocalRuntimeService/StopLocalService',
    checkLocalServiceHealth: '/nimi.runtime.v1.RuntimeLocalRuntimeService/CheckLocalServiceHealth',
    removeLocalService: '/nimi.runtime.v1.RuntimeLocalRuntimeService/RemoveLocalService',
    listNodeCatalog: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListNodeCatalog',
    listLocalAudits: '/nimi.runtime.v1.RuntimeLocalRuntimeService/ListLocalAudits',
    appendInferenceAudit: '/nimi.runtime.v1.RuntimeLocalRuntimeService/AppendInferenceAudit',
    appendRuntimeAudit: '/nimi.runtime.v1.RuntimeLocalRuntimeService/AppendRuntimeAudit',
  },
  knowledge: {
    buildIndex: '/nimi.runtime.v1.RuntimeKnowledgeService/BuildIndex',
    searchIndex: '/nimi.runtime.v1.RuntimeKnowledgeService/SearchIndex',
    deleteIndex: '/nimi.runtime.v1.RuntimeKnowledgeService/DeleteIndex',
  },
  app: {
    sendAppMessage: '/nimi.runtime.v1.RuntimeAppService/SendAppMessage',
    subscribeAppMessages: '/nimi.runtime.v1.RuntimeAppService/SubscribeAppMessages',
  },
  connector: {
    createConnector: '/nimi.runtime.v1.RuntimeConnectorService/CreateConnector',
    getConnector: '/nimi.runtime.v1.RuntimeConnectorService/GetConnector',
    listConnectors: '/nimi.runtime.v1.RuntimeConnectorService/ListConnectors',
    updateConnector: '/nimi.runtime.v1.RuntimeConnectorService/UpdateConnector',
    deleteConnector: '/nimi.runtime.v1.RuntimeConnectorService/DeleteConnector',
    testConnector: '/nimi.runtime.v1.RuntimeConnectorService/TestConnector',
    listConnectorModels: '/nimi.runtime.v1.RuntimeConnectorService/ListConnectorModels',
    listProviderCatalog: '/nimi.runtime.v1.RuntimeConnectorService/ListProviderCatalog',
    listModelCatalogProviders: '/nimi.runtime.v1.RuntimeConnectorService/ListModelCatalogProviders',
    upsertModelCatalogProvider: '/nimi.runtime.v1.RuntimeConnectorService/UpsertModelCatalogProvider',
    deleteModelCatalogProvider: '/nimi.runtime.v1.RuntimeConnectorService/DeleteModelCatalogProvider',
  },
  scriptWorker: {
    execute: '/nimi.runtime.v1.ScriptWorkerService/Execute',
  },
  audit: {
    listAuditEvents: '/nimi.runtime.v1.RuntimeAuditService/ListAuditEvents',
    exportAuditEvents: '/nimi.runtime.v1.RuntimeAuditService/ExportAuditEvents',
    listUsageStats: '/nimi.runtime.v1.RuntimeAuditService/ListUsageStats',
    getRuntimeHealth: '/nimi.runtime.v1.RuntimeAuditService/GetRuntimeHealth',
    listAIProviderHealth: '/nimi.runtime.v1.RuntimeAuditService/ListAIProviderHealth',
    subscribeAIProviderHealthEvents: '/nimi.runtime.v1.RuntimeAuditService/SubscribeAIProviderHealthEvents',
    subscribeRuntimeHealthEvents: '/nimi.runtime.v1.RuntimeAuditService/SubscribeRuntimeHealthEvents',
  },
} as const;

export const RuntimeAllowlistedMethodIds: readonly string[] = Object.freeze(
  Object.values(RuntimeMethodIds)
    .flatMap((serviceMethods) => Object.values(serviceMethods)),
);

export const RuntimeStreamMethodIds: readonly string[] = Object.freeze([
  RuntimeMethodIds.ai.streamScenario,
  RuntimeMethodIds.ai.subscribeScenarioJobEvents,
  RuntimeMethodIds.workflow.subscribeEvents,
  RuntimeMethodIds.app.subscribeAppMessages,
  RuntimeMethodIds.audit.exportAuditEvents,
  RuntimeMethodIds.audit.subscribeAIProviderHealthEvents,
  RuntimeMethodIds.audit.subscribeRuntimeHealthEvents,
]);

export const RuntimeWriteMethodIds: readonly string[] = Object.freeze([
  RuntimeMethodIds.auth.registerApp,
  RuntimeMethodIds.auth.openSession,
  RuntimeMethodIds.auth.refreshSession,
  RuntimeMethodIds.auth.revokeSession,
  RuntimeMethodIds.auth.registerExternalPrincipal,
  RuntimeMethodIds.auth.openExternalPrincipalSession,
  RuntimeMethodIds.auth.revokeExternalPrincipalSession,
  RuntimeMethodIds.appAuth.authorizeExternalPrincipal,
  RuntimeMethodIds.appAuth.revokeToken,
  RuntimeMethodIds.appAuth.issueDelegatedToken,
  RuntimeMethodIds.ai.executeScenario,
  RuntimeMethodIds.ai.streamScenario,
  RuntimeMethodIds.ai.submitScenarioJob,
  RuntimeMethodIds.ai.cancelScenarioJob,
  RuntimeMethodIds.ai.deleteVoiceAsset,
  RuntimeMethodIds.workflow.submit,
  RuntimeMethodIds.workflow.cancel,
  RuntimeMethodIds.model.pull,
  RuntimeMethodIds.model.remove,
  RuntimeMethodIds.localRuntime.installLocalModel,
  RuntimeMethodIds.localRuntime.installVerifiedModel,
  RuntimeMethodIds.localRuntime.importLocalModel,
  RuntimeMethodIds.localRuntime.removeLocalModel,
  RuntimeMethodIds.localRuntime.startLocalModel,
  RuntimeMethodIds.localRuntime.stopLocalModel,
  RuntimeMethodIds.localRuntime.applyDependencies,
  RuntimeMethodIds.localRuntime.installLocalService,
  RuntimeMethodIds.localRuntime.startLocalService,
  RuntimeMethodIds.localRuntime.stopLocalService,
  RuntimeMethodIds.localRuntime.removeLocalService,
  RuntimeMethodIds.localRuntime.appendInferenceAudit,
  RuntimeMethodIds.localRuntime.appendRuntimeAudit,
  RuntimeMethodIds.connector.createConnector,
  RuntimeMethodIds.connector.updateConnector,
  RuntimeMethodIds.connector.deleteConnector,
  RuntimeMethodIds.knowledge.buildIndex,
  RuntimeMethodIds.knowledge.deleteIndex,
  RuntimeMethodIds.app.sendAppMessage,
  RuntimeMethodIds.audit.exportAuditEvents,
  RuntimeMethodIds.scriptWorker.execute,
]);

export const RuntimeLocalRuntimeAnonymousMethodIds: readonly string[] = Object.freeze([
  RuntimeMethodIds.localRuntime.listLocalModels,
  RuntimeMethodIds.localRuntime.listVerifiedModels,
  RuntimeMethodIds.localRuntime.searchCatalogModels,
  RuntimeMethodIds.localRuntime.resolveModelInstallPlan,
  RuntimeMethodIds.localRuntime.checkLocalModelHealth,
  RuntimeMethodIds.localRuntime.warmLocalModel,
  RuntimeMethodIds.localRuntime.collectDeviceProfile,
  RuntimeMethodIds.localRuntime.resolveDependencies,
  RuntimeMethodIds.localRuntime.listLocalServices,
  RuntimeMethodIds.localRuntime.checkLocalServiceHealth,
  RuntimeMethodIds.localRuntime.listNodeCatalog,
  RuntimeMethodIds.localRuntime.listLocalAudits,
]);

export function isRuntimeStreamMethod(methodId: string): boolean {
  return RuntimeStreamMethodIds.includes(methodId);
}

export function isRuntimeWriteMethod(methodId: string): boolean {
  return RuntimeWriteMethodIds.includes(methodId);
}

export function isRuntimeLocalRuntimeAnonymousMethod(methodId: string): boolean {
  return RuntimeLocalRuntimeAnonymousMethodIds.includes(methodId);
}
