export const RuntimeMethodIds = {
  auth: {
    registerApp: '/nimi.runtime.v1.RuntimeAuthService/RegisterApp',
    openSession: '/nimi.runtime.v1.RuntimeAuthService/OpenSession',
    refreshSession: '/nimi.runtime.v1.RuntimeAuthService/RefreshSession',
    revokeSession: '/nimi.runtime.v1.RuntimeAuthService/RevokeSession',
    registerExternalPrincipal: '/nimi.runtime.v1.RuntimeAuthService/RegisterExternalPrincipal',
    openExternalPrincipalSession: '/nimi.runtime.v1.RuntimeAuthService/OpenExternalPrincipalSession',
    revokeExternalPrincipalSession: '/nimi.runtime.v1.RuntimeAuthService/RevokeExternalPrincipalSession',
  },
  appAuth: {
    authorizeExternalPrincipal: '/nimi.runtime.v1.RuntimeGrantService/AuthorizeExternalPrincipal',
    validateToken: '/nimi.runtime.v1.RuntimeGrantService/ValidateAppAccessToken',
    revokeToken: '/nimi.runtime.v1.RuntimeGrantService/RevokeAppAccessToken',
    issueDelegatedToken: '/nimi.runtime.v1.RuntimeGrantService/IssueDelegatedAccessToken',
    listTokenChain: '/nimi.runtime.v1.RuntimeGrantService/ListTokenChain',
  },
  ai: {
    executeScenario: '/nimi.runtime.v1.RuntimeAiService/ExecuteScenario',
    streamScenario: '/nimi.runtime.v1.RuntimeAiService/StreamScenario',
    submitScenarioJob: '/nimi.runtime.v1.RuntimeAiService/SubmitScenarioJob',
    getScenarioJob: '/nimi.runtime.v1.RuntimeAiService/GetScenarioJob',
    cancelScenarioJob: '/nimi.runtime.v1.RuntimeAiService/CancelScenarioJob',
    subscribeScenarioJobEvents: '/nimi.runtime.v1.RuntimeAiService/SubscribeScenarioJobEvents',
    getScenarioArtifacts: '/nimi.runtime.v1.RuntimeAiService/GetScenarioArtifacts',
    listScenarioProfiles: '/nimi.runtime.v1.RuntimeAiService/ListScenarioProfiles',
    getVoiceAsset: '/nimi.runtime.v1.RuntimeAiService/GetVoiceAsset',
    listVoiceAssets: '/nimi.runtime.v1.RuntimeAiService/ListVoiceAssets',
    deleteVoiceAsset: '/nimi.runtime.v1.RuntimeAiService/DeleteVoiceAsset',
    listPresetVoices: '/nimi.runtime.v1.RuntimeAiService/ListPresetVoices',
  },
  aiRealtime: {
    openRealtimeSession: '/nimi.runtime.v1.RuntimeAiRealtimeService/OpenRealtimeSession',
    appendRealtimeInput: '/nimi.runtime.v1.RuntimeAiRealtimeService/AppendRealtimeInput',
    readRealtimeEvents: '/nimi.runtime.v1.RuntimeAiRealtimeService/ReadRealtimeEvents',
    closeRealtimeSession: '/nimi.runtime.v1.RuntimeAiRealtimeService/CloseRealtimeSession',
  },
  workflow: {
    submit: '/nimi.runtime.v1.RuntimeWorkflowService/SubmitWorkflow',
    get: '/nimi.runtime.v1.RuntimeWorkflowService/GetWorkflow',
    cancel: '/nimi.runtime.v1.RuntimeWorkflowService/CancelWorkflow',
    subscribeEvents: '/nimi.runtime.v1.RuntimeWorkflowService/SubscribeWorkflowEvents',
  },
  model: {
    list: '/nimi.runtime.v1.RuntimeModelService/ListModels',
    pull: '/nimi.runtime.v1.RuntimeModelService/PullModel',
    remove: '/nimi.runtime.v1.RuntimeModelService/RemoveModel',
    checkHealth: '/nimi.runtime.v1.RuntimeModelService/CheckModelHealth',
  },
  local: {
    listLocalModels: '/nimi.runtime.v1.RuntimeLocalService/ListLocalModels',
    listLocalArtifacts: '/nimi.runtime.v1.RuntimeLocalService/ListLocalArtifacts',
    listVerifiedModels: '/nimi.runtime.v1.RuntimeLocalService/ListVerifiedModels',
    listVerifiedArtifacts: '/nimi.runtime.v1.RuntimeLocalService/ListVerifiedArtifacts',
    searchCatalogModels: '/nimi.runtime.v1.RuntimeLocalService/SearchCatalogModels',
    resolveModelInstallPlan: '/nimi.runtime.v1.RuntimeLocalService/ResolveModelInstallPlan',
    installLocalModel: '/nimi.runtime.v1.RuntimeLocalService/InstallLocalModel',
    installVerifiedModel: '/nimi.runtime.v1.RuntimeLocalService/InstallVerifiedModel',
    installVerifiedArtifact: '/nimi.runtime.v1.RuntimeLocalService/InstallVerifiedArtifact',
    importLocalModel: '/nimi.runtime.v1.RuntimeLocalService/ImportLocalModel',
    importLocalArtifact: '/nimi.runtime.v1.RuntimeLocalService/ImportLocalArtifact',
    removeLocalModel: '/nimi.runtime.v1.RuntimeLocalService/RemoveLocalModel',
    removeLocalArtifact: '/nimi.runtime.v1.RuntimeLocalService/RemoveLocalArtifact',
    startLocalModel: '/nimi.runtime.v1.RuntimeLocalService/StartLocalModel',
    stopLocalModel: '/nimi.runtime.v1.RuntimeLocalService/StopLocalModel',
    checkLocalModelHealth: '/nimi.runtime.v1.RuntimeLocalService/CheckLocalModelHealth',
    warmLocalModel: '/nimi.runtime.v1.RuntimeLocalService/WarmLocalModel',
    collectDeviceProfile: '/nimi.runtime.v1.RuntimeLocalService/CollectDeviceProfile',
    resolveProfile: '/nimi.runtime.v1.RuntimeLocalService/ResolveProfile',
    applyProfile: '/nimi.runtime.v1.RuntimeLocalService/ApplyProfile',
    listLocalServices: '/nimi.runtime.v1.RuntimeLocalService/ListLocalServices',
    installLocalService: '/nimi.runtime.v1.RuntimeLocalService/InstallLocalService',
    startLocalService: '/nimi.runtime.v1.RuntimeLocalService/StartLocalService',
    stopLocalService: '/nimi.runtime.v1.RuntimeLocalService/StopLocalService',
    checkLocalServiceHealth: '/nimi.runtime.v1.RuntimeLocalService/CheckLocalServiceHealth',
    removeLocalService: '/nimi.runtime.v1.RuntimeLocalService/RemoveLocalService',
    listNodeCatalog: '/nimi.runtime.v1.RuntimeLocalService/ListNodeCatalog',
    listLocalAudits: '/nimi.runtime.v1.RuntimeLocalService/ListLocalAudits',
    appendInferenceAudit: '/nimi.runtime.v1.RuntimeLocalService/AppendInferenceAudit',
    appendRuntimeAudit: '/nimi.runtime.v1.RuntimeLocalService/AppendRuntimeAudit',
    listEngines: '/nimi.runtime.v1.RuntimeLocalService/ListEngines',
    ensureEngine: '/nimi.runtime.v1.RuntimeLocalService/EnsureEngine',
    startEngine: '/nimi.runtime.v1.RuntimeLocalService/StartEngine',
    stopEngine: '/nimi.runtime.v1.RuntimeLocalService/StopEngine',
    getEngineStatus: '/nimi.runtime.v1.RuntimeLocalService/GetEngineStatus',
  },
  knowledge: {
    buildIndex: '/nimi.runtime.v1.RuntimeKnowledgeService/BuildIndex',
    searchIndex: '/nimi.runtime.v1.RuntimeKnowledgeService/SearchIndex',
    deleteIndex: '/nimi.runtime.v1.RuntimeKnowledgeService/DeleteIndex',
  },
  app: {
    sendAppMessage: '/nimi.runtime.v1.RuntimeAppService/SendAppMessage',
    subscribeAppMessages: '/nimi.runtime.v1.RuntimeAppService/SubscribeAppMessages',
  },
  connector: {
    createConnector: '/nimi.runtime.v1.RuntimeConnectorService/CreateConnector',
    getConnector: '/nimi.runtime.v1.RuntimeConnectorService/GetConnector',
    listConnectors: '/nimi.runtime.v1.RuntimeConnectorService/ListConnectors',
    updateConnector: '/nimi.runtime.v1.RuntimeConnectorService/UpdateConnector',
    deleteConnector: '/nimi.runtime.v1.RuntimeConnectorService/DeleteConnector',
    testConnector: '/nimi.runtime.v1.RuntimeConnectorService/TestConnector',
    listConnectorModels: '/nimi.runtime.v1.RuntimeConnectorService/ListConnectorModels',
    listProviderCatalog: '/nimi.runtime.v1.RuntimeConnectorService/ListProviderCatalog',
    listModelCatalogProviders: '/nimi.runtime.v1.RuntimeConnectorService/ListModelCatalogProviders',
    upsertModelCatalogProvider: '/nimi.runtime.v1.RuntimeConnectorService/UpsertModelCatalogProvider',
    deleteModelCatalogProvider: '/nimi.runtime.v1.RuntimeConnectorService/DeleteModelCatalogProvider',
    listCatalogProviderModels: '/nimi.runtime.v1.RuntimeConnectorService/ListCatalogProviderModels',
    getCatalogModelDetail: '/nimi.runtime.v1.RuntimeConnectorService/GetCatalogModelDetail',
    upsertCatalogModelOverlay: '/nimi.runtime.v1.RuntimeConnectorService/UpsertCatalogModelOverlay',
    deleteCatalogModelOverlay: '/nimi.runtime.v1.RuntimeConnectorService/DeleteCatalogModelOverlay',
  },
  audit: {
    listAuditEvents: '/nimi.runtime.v1.RuntimeAuditService/ListAuditEvents',
    exportAuditEvents: '/nimi.runtime.v1.RuntimeAuditService/ExportAuditEvents',
    listUsageStats: '/nimi.runtime.v1.RuntimeAuditService/ListUsageStats',
    getRuntimeHealth: '/nimi.runtime.v1.RuntimeAuditService/GetRuntimeHealth',
    listAIProviderHealth: '/nimi.runtime.v1.RuntimeAuditService/ListAIProviderHealth',
    subscribeAIProviderHealthEvents: '/nimi.runtime.v1.RuntimeAuditService/SubscribeAIProviderHealthEvents',
    subscribeRuntimeHealthEvents: '/nimi.runtime.v1.RuntimeAuditService/SubscribeRuntimeHealthEvents',
  },
} as const;

export const RuntimeAllowlistedMethodIds: readonly string[] = Object.freeze(
  Object.values(RuntimeMethodIds)
    .flatMap((serviceMethods) => Object.values(serviceMethods)),
);

export const RuntimeStreamMethodIds: readonly string[] = Object.freeze([
  RuntimeMethodIds.ai.streamScenario,
  RuntimeMethodIds.ai.subscribeScenarioJobEvents,
  RuntimeMethodIds.aiRealtime.readRealtimeEvents,
  RuntimeMethodIds.workflow.subscribeEvents,
  RuntimeMethodIds.app.subscribeAppMessages,
  RuntimeMethodIds.audit.exportAuditEvents,
  RuntimeMethodIds.audit.subscribeAIProviderHealthEvents,
  RuntimeMethodIds.audit.subscribeRuntimeHealthEvents,
]);

export const RuntimeWriteMethodIds: readonly string[] = Object.freeze([
  RuntimeMethodIds.auth.registerApp,
  RuntimeMethodIds.auth.openSession,
  RuntimeMethodIds.auth.refreshSession,
  RuntimeMethodIds.auth.revokeSession,
  RuntimeMethodIds.auth.registerExternalPrincipal,
  RuntimeMethodIds.auth.openExternalPrincipalSession,
  RuntimeMethodIds.auth.revokeExternalPrincipalSession,
  RuntimeMethodIds.appAuth.authorizeExternalPrincipal,
  RuntimeMethodIds.appAuth.revokeToken,
  RuntimeMethodIds.appAuth.issueDelegatedToken,
  RuntimeMethodIds.ai.executeScenario,
  RuntimeMethodIds.ai.streamScenario,
  RuntimeMethodIds.ai.submitScenarioJob,
  RuntimeMethodIds.ai.cancelScenarioJob,
  RuntimeMethodIds.ai.deleteVoiceAsset,
  RuntimeMethodIds.aiRealtime.openRealtimeSession,
  RuntimeMethodIds.aiRealtime.appendRealtimeInput,
  RuntimeMethodIds.aiRealtime.closeRealtimeSession,
  RuntimeMethodIds.workflow.submit,
  RuntimeMethodIds.workflow.cancel,
  RuntimeMethodIds.model.pull,
  RuntimeMethodIds.model.remove,
  RuntimeMethodIds.local.installLocalModel,
  RuntimeMethodIds.local.installVerifiedModel,
  RuntimeMethodIds.local.installVerifiedArtifact,
  RuntimeMethodIds.local.importLocalModel,
  RuntimeMethodIds.local.importLocalArtifact,
  RuntimeMethodIds.local.removeLocalModel,
  RuntimeMethodIds.local.removeLocalArtifact,
  RuntimeMethodIds.local.startLocalModel,
  RuntimeMethodIds.local.stopLocalModel,
  RuntimeMethodIds.local.applyProfile,
  RuntimeMethodIds.local.installLocalService,
  RuntimeMethodIds.local.startLocalService,
  RuntimeMethodIds.local.stopLocalService,
  RuntimeMethodIds.local.removeLocalService,
  RuntimeMethodIds.local.appendInferenceAudit,
  RuntimeMethodIds.local.appendRuntimeAudit,
  RuntimeMethodIds.local.ensureEngine,
  RuntimeMethodIds.local.startEngine,
  RuntimeMethodIds.local.stopEngine,
  RuntimeMethodIds.connector.createConnector,
  RuntimeMethodIds.connector.updateConnector,
  RuntimeMethodIds.connector.deleteConnector,
  RuntimeMethodIds.connector.upsertModelCatalogProvider,
  RuntimeMethodIds.connector.deleteModelCatalogProvider,
  RuntimeMethodIds.connector.upsertCatalogModelOverlay,
  RuntimeMethodIds.connector.deleteCatalogModelOverlay,
  RuntimeMethodIds.knowledge.buildIndex,
  RuntimeMethodIds.knowledge.deleteIndex,
  RuntimeMethodIds.app.sendAppMessage,
  RuntimeMethodIds.audit.exportAuditEvents,
]);

export const RuntimeLocalAnonymousMethodIds: readonly string[] = Object.freeze([
  RuntimeMethodIds.local.listLocalModels,
  RuntimeMethodIds.local.listLocalArtifacts,
  RuntimeMethodIds.local.listVerifiedModels,
  RuntimeMethodIds.local.listVerifiedArtifacts,
  RuntimeMethodIds.local.searchCatalogModels,
  RuntimeMethodIds.local.resolveModelInstallPlan,
  RuntimeMethodIds.local.checkLocalModelHealth,
  RuntimeMethodIds.local.warmLocalModel,
  RuntimeMethodIds.local.collectDeviceProfile,
  RuntimeMethodIds.local.resolveProfile,
  RuntimeMethodIds.local.listLocalServices,
  RuntimeMethodIds.local.checkLocalServiceHealth,
  RuntimeMethodIds.local.listNodeCatalog,
  RuntimeMethodIds.local.listLocalAudits,
]);

export function isRuntimeStreamMethod(methodId: string): boolean {
  return RuntimeStreamMethodIds.includes(methodId);
}

export function isRuntimeWriteMethod(methodId: string): boolean {
  return RuntimeWriteMethodIds.includes(methodId);
}

export function isRuntimeLocalAnonymousMethod(methodId: string): boolean {
  return RuntimeLocalAnonymousMethodIds.includes(methodId);
}
