// Code generated by scripts/generate-first-party-protected-runtime-profiles.mjs; DO NOT EDIT.
// Source: config/runtime-first-party-protected-runtime-profiles.yaml

export const NIMI_ELECTRON_BUNDLED_AVATAR_PROFILE_ID = 'bundled_avatar_v1' as const;
export const NIMI_ELECTRON_BUNDLED_AVATAR_APP_ID = "nimi.avatar" as const;
export const NIMI_ELECTRON_BUNDLED_AVATAR_APP_INSTANCE_ID = "nimi.avatar" as const;
export const NIMI_ELECTRON_BUNDLED_AVATAR_DEVICE_ID = "avatar-native-host" as const;

export const NIMI_ELECTRON_BUNDLED_AVATAR_METHODS = {
  "/nimi.runtime.v1.RuntimeAuthService/OpenLocalAppSession": { kind: "unary", capability: "" },
  "/nimi.runtime.v1.RuntimeAuthService/RenewLocalAppSession": { kind: "unary", capability: "" },
  "/nimi.runtime.v1.RuntimeAccountService/InvokeRealmUnary": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAgentService/GetAgentPresentationAsset": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAppService/ReadLocalAppStorageJson": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/WriteLocalAppStorageJson": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/RemoveLocalAppStorageJson": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/StatLocalAppAsset": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/ListLocalAppAssets": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/WriteLocalAppAsset": { kind: "server_stream", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/ReadLocalAppAsset": { kind: "server_stream", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/RemoveLocalAppAsset": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/MoveLocalAppAsset": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/RevealLocalAppAsset": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeAppService/AdoptLocalAppArtifact": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/GetAppAIConfig": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/OverwriteAppAIConfig": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/ListAppAIConfigOptions": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/GenerateLocalAppTextCandidate": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/StreamLocalAppTextTurn": { kind: "server_stream", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/ExecuteLocalAppScenario": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/SubmitLocalAppScenarioJob": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/GetLocalAppScenarioJob": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/SubscribeLocalAppScenarioJobEvents": { kind: "server_stream", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/CancelLocalAppScenarioJob": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/ReadLocalAppArtifact": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/UploadLocalAppArtifact": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiService/ListLocalAppVoiceAssets": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppAgentManagerSnapshot": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppSharedLocalAgentAIConfig": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/OverwriteLocalAppSharedLocalAgentAIConfig": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/ListLocalAppSharedLocalAgentAIConfigOptions": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppAgentAutonomySnapshot": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/UpdateLocalAppAgentAutonomy": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppAgentPresentationSnapshot": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/CommitLocalAppAgentPresentation": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/InspectLocalAppAgentMemory": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/CorrectLocalAppAgentMemory": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/ForgetLocalAppAgentMemory": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/SetLocalAppAgentMemoryEnabled": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/DeleteAllLocalAppAgentMemory": { kind: "unary", capability: "agent.configure" },
  "/nimi.runtime.v1.RuntimeAgentService/ListLocalAppAgentReferences": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/OpenLocalAppConversation": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/SendLocalAppConversationTurn": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/UploadLocalAppConversationAttachment": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/ReadLocalAppConversationArtifact": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/TranscribeLocalAppConversationVoice": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/RenderLocalAppConversationVoice": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/InterruptLocalAppConversationTurn": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/SubscribeLocalAppConversationEvents": { kind: "server_stream", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppConversationSnapshot": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppEmbodimentSnapshot": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/SubscribeLocalAppEmbodimentEvents": { kind: "server_stream", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAiRealtimeService/OpenRealtimeSession": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiRealtimeService/AppendRealtimeInput": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiRealtimeService/SubmitRealtimeOwnerControl": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiRealtimeService/ReadRealtimeEvents": { kind: "server_stream", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiRealtimeService/InterruptRealtimeOutput": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAiRealtimeService/CloseRealtimeSession": { kind: "unary", capability: "runtime.consume" },
  "/nimi.runtime.v1.RuntimeAgentService/OpenLocalAppAgentRealtime": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/AppendLocalAppAgentRealtimeInput": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/SubscribeLocalAppAgentRealtimeEvents": { kind: "server_stream", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/GetLocalAppAgentRealtimeStatus": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/InterruptLocalAppAgentRealtimeOutput": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeAgentService/CloseLocalAppAgentRealtime": { kind: "unary", capability: "agent.local" },
  "/nimi.runtime.v1.RuntimeRealmRealtimeService/ListRealmChats": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeRealmRealtimeService/OpenRealmRealtimeChannel": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeRealmRealtimeService/SubscribeRealmRealtimeEvents": { kind: "server_stream", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeRealmRealtimeService/AckRealmRealtimeEvents": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeRealmRealtimeService/CloseRealmRealtimeSubscription": { kind: "unary", capability: "realm.data" },
  "/nimi.runtime.v1.RuntimeRealmRealtimeService/CloseRealmRealtimeChannel": { kind: "unary", capability: "realm.data" },
} as const;

export type NimiElectronBundledAvatarMethodId = keyof typeof NIMI_ELECTRON_BUNDLED_AVATAR_METHODS;

export function isNimiElectronBundledAvatarUnaryMethod(methodId: string): methodId is NimiElectronBundledAvatarMethodId {
  return NIMI_ELECTRON_BUNDLED_AVATAR_METHODS[methodId as NimiElectronBundledAvatarMethodId]?.kind === 'unary';
}

export function isNimiElectronBundledAvatarServerStreamMethod(methodId: string): methodId is NimiElectronBundledAvatarMethodId {
  return NIMI_ELECTRON_BUNDLED_AVATAR_METHODS[methodId as NimiElectronBundledAvatarMethodId]?.kind === 'server_stream';
}
