import React from 'react';
import { getPlatformClient } from '@nimiplatform/sdk';
import { useAppStore } from '@renderer/app-shell/providers/app-store.js';

async function publishTake(input: {
  audioBuffer: ArrayBuffer;
  title: string;
  description: string;
  tags: string[];
  duration: number | undefined;
  onStatus: (status: 'uploading' | 'creating' | 'done' | 'error', error?: string) => void;
  onPostId: (postId: string) => void;
}): Promise<void> {
  let client;
  try {
    client = getPlatformClient();
  } catch {
    input.onStatus('error', 'Realm client is not initialized.');
    return;
  }

  try {
    input.onStatus('uploading');

    const upload = await client.domains.media.createAudioDirectUpload({ mimeType: 'audio/mpeg' });

    const audioBlob = new Blob([input.audioBuffer], { type: 'audio/mpeg' });
    const uploadResponse = await fetch(upload.uploadUrl, {
      method: 'PUT',
      body: audioBlob,
      headers: { 'Content-Type': 'audio/mpeg' },
    });

    if (!uploadResponse.ok) {
      input.onStatus('error', `Audio upload failed: ${uploadResponse.status} ${uploadResponse.statusText}`);
      return;
    }

    input.onStatus('creating');

    const post = (await client.domains.media.createPost({
      caption: input.description || input.title,
      media: [
        {
          type: 'AUDIO' as const,
          assetId: upload.assetId,
          duration: input.duration,
        },
      ],
      tags: input.tags.length > 0 ? input.tags : undefined,
    })) as { id: string };

    input.onPostId(post.id);
    input.onStatus('done');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    input.onStatus('error', message);
  }
}

export function PublishPanel() {
  const takes = useAppStore((state) => state.takes);
  const selectedTakeId = useAppStore((state) => state.selectedTakeId);
  const brief = useAppStore((state) => state.brief);
  const audioBuffers = useAppStore((state) => state.audioBuffers);
  const realmConfigured = useAppStore((state) => state.realmConfigured);
  const realmAuthenticated = useAppStore((state) => state.realmAuthenticated);

  const draftPost = useAppStore((state) => state.draftPost);
  const provenanceConfirmed = useAppStore((state) => state.provenanceConfirmed);
  const publishStatus = useAppStore((state) => state.publishStatus);
  const publishError = useAppStore((state) => state.publishError);
  const publishedPostId = useAppStore((state) => state.publishedPostId);

  const setDraftPost = useAppStore((state) => state.setDraftPost);
  const setProvenanceConfirmed = useAppStore((state) => state.setProvenanceConfirmed);
  const setPublishStatus = useAppStore((state) => state.setPublishStatus);
  const setPublishedPostId = useAppStore((state) => state.setPublishedPostId);

  const selectedTake = takes.find((take) => take.takeId === selectedTakeId);

  if (!selectedTake) {
    return null;
  }

  const effectiveTitle = draftPost?.title || brief?.title || selectedTake.title;
  const effectiveDescription = draftPost?.description || brief?.description || '';
  const effectiveTags = draftPost?.tags ?? [];

  const audioBuffer = selectedTakeId ? audioBuffers.get(selectedTakeId) : undefined;

  const hasBlocker = !realmConfigured || !realmAuthenticated;
  const blockedReason = !realmConfigured
    ? 'Realm is not configured. Set VITE_NIMI_REALM_BASE_URL and VITE_NIMI_REALM_ACCESS_TOKEN.'
    : !realmAuthenticated
      ? 'Realm is configured but authentication is not available.'
      : null;

  const canPublish =
    !hasBlocker &&
    provenanceConfirmed &&
    audioBuffer != null &&
    publishStatus !== 'uploading' &&
    publishStatus !== 'creating' &&
    publishStatus !== 'done';

  const sourceLabel = selectedTake.origin === 'prompt'
    ? 'AI-generated from a text prompt'
    : selectedTake.origin === 'reference'
      ? 'AI-generated with uploaded reference audio'
      : `AI-generated by ${selectedTake.origin} from an existing take`;

  const isPublishing = publishStatus === 'uploading' || publishStatus === 'creating';
  const buttonLabel = isPublishing
    ? publishStatus === 'uploading' ? 'Uploading audio...' : 'Creating post...'
    : publishStatus === 'done'
      ? 'Published'
      : hasBlocker
        ? 'Publish Blocked'
        : !audioBuffer
          ? 'No audio buffer'
          : 'Publish to Realm';

  function handlePublish() {
    if (!canPublish || !audioBuffer) return;

    publishTake({
      audioBuffer,
      title: effectiveTitle,
      description: effectiveDescription,
      tags: effectiveTags,
      duration: undefined,
      onStatus: (status, error) => setPublishStatus(status, error),
      onPostId: (postId) => setPublishedPostId(postId),
    });
  }

  return (
    <div className="space-y-4">
      <h2 className="text-sm font-semibold text-zinc-300 uppercase tracking-wider">Publish</h2>

      {blockedReason && (
        <div className="rounded-md border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-xs text-amber-300">
          {blockedReason}
        </div>
      )}

      {publishStatus === 'error' && publishError && (
        <div className="rounded-md border border-red-500/20 bg-red-500/10 px-3 py-2 text-xs text-red-300">
          {publishError}
          <button
            className="ml-2 underline"
            onClick={() => setPublishStatus('idle')}
            type="button"
          >
            Dismiss
          </button>
        </div>
      )}

      {publishStatus === 'done' && publishedPostId && (
        <div className="rounded-md border border-emerald-500/20 bg-emerald-500/10 px-3 py-2 text-xs text-emerald-300">
          Published successfully. Post ID: <span className="font-mono">{publishedPostId}</span>
        </div>
      )}

      <div className="space-y-3">
        <div className="space-y-1">
          <label className="text-xs font-medium text-zinc-400">Title</label>
          <input
            className="w-full bg-zinc-900 border border-zinc-700 rounded-md px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-zinc-500"
            value={effectiveTitle}
            onChange={(event) =>
              setDraftPost({
                title: event.target.value,
                description: effectiveDescription,
                tags: effectiveTags,
              })
            }
            placeholder="Song title"
          />
        </div>

        <div className="space-y-1">
          <label className="text-xs font-medium text-zinc-400">Description</label>
          <textarea
            className="w-full h-16 bg-zinc-900 border border-zinc-700 rounded-md px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 resize-none focus:outline-none focus:border-zinc-500"
            value={effectiveDescription}
            onChange={(event) =>
              setDraftPost({
                title: effectiveTitle,
                description: event.target.value,
                tags: effectiveTags,
              })
            }
            placeholder="Describe your song..."
          />
        </div>

        <div className="space-y-1">
          <label className="text-xs font-medium text-zinc-400">Tags</label>
          <input
            className="w-full bg-zinc-900 border border-zinc-700 rounded-md px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-zinc-500"
            value={effectiveTags.join(', ')}
            onChange={(event) =>
              setDraftPost({
                title: effectiveTitle,
                description: effectiveDescription,
                tags: event.target.value.split(',').map((t) => t.trim()).filter(Boolean),
              })
            }
            placeholder="comma separated tags"
          />
        </div>

        <div className="p-2 rounded-md bg-zinc-900 border border-zinc-800 space-y-2">
          <p className="text-xs text-zinc-400">
            Publish master: <span className="text-zinc-300">{selectedTake.title}</span>
          </p>
          <p className="text-xs text-zinc-400">
            Source: <span className="text-zinc-300">{sourceLabel}</span>
          </p>
          {selectedTake.parentTakeId && (
            <p className="text-[10px] text-zinc-500">
              Parent take: {takes.find((take) => take.takeId === selectedTake.parentTakeId)?.title ?? selectedTake.parentTakeId}
            </p>
          )}
          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={provenanceConfirmed}
              onChange={(event) => setProvenanceConfirmed(event.target.checked)}
              className="mt-0.5 rounded border-zinc-600 bg-zinc-900"
            />
            <span className="text-xs text-zinc-400">
              I confirm the source material is original or I have the right to publish it.
            </span>
          </label>
        </div>
      </div>

      <button
        className={`w-full px-4 py-2 text-sm font-medium rounded-lg ${
          canPublish
            ? 'bg-emerald-600 hover:bg-emerald-500 text-white cursor-pointer'
            : 'bg-zinc-800 text-zinc-400 cursor-not-allowed'
        }`}
        disabled={!canPublish}
        onClick={handlePublish}
        type="button"
      >
        {isPublishing && (
          <span className="inline-block w-3 h-3 mr-2 border-2 border-zinc-400 border-t-transparent rounded-full animate-spin" />
        )}
        {buttonLabel}
      </button>
    </div>
  );
}
