import React, { useEffect, useCallback } from 'react';
import { getPlatformClient } from '@nimiplatform/sdk';
import { useAppStore } from '@renderer/app-shell/providers/app-store.js';
import { OtButton, OtInput, OtTextarea, OtTagInput } from './ui-primitives.js';
import { Waveform } from './waveform.js';

async function publishTake(input: {
  audioBuffer: ArrayBuffer;
  title: string;
  description: string;
  tags: string[];
  duration: number | undefined;
  onStatus: (status: 'uploading' | 'creating' | 'done' | 'error', error?: string) => void;
  onPostId: (postId: string) => void;
}): Promise<void> {
  let client;
  try {
    client = getPlatformClient();
  } catch {
    input.onStatus('error', 'Realm client is not initialized.');
    return;
  }

  try {
    input.onStatus('uploading');

    const upload = await client.domains.media.createAudioDirectUpload({ mimeType: 'audio/mpeg' });

    const audioBlob = new Blob([input.audioBuffer], { type: 'audio/mpeg' });
    const uploadResponse = await fetch(upload.uploadUrl, {
      method: 'PUT',
      body: audioBlob,
      headers: { 'Content-Type': 'audio/mpeg' },
    });

    if (!uploadResponse.ok) {
      input.onStatus('error', `Audio upload failed: ${uploadResponse.status} ${uploadResponse.statusText}`);
      return;
    }

    input.onStatus('creating');

    const post = (await client.domains.media.createPost({
      caption: input.description || input.title,
      media: [
        {
          type: 'AUDIO' as const,
          assetId: upload.assetId,
          duration: input.duration,
        },
      ],
      tags: input.tags.length > 0 ? input.tags : undefined,
    })) as { id: string };

    input.onPostId(post.id);
    input.onStatus('done');
  } catch (error) {
    const message = error instanceof Error ? error.message : String(error);
    input.onStatus('error', message);
  }
}

/* ─── Mini Preview Waveform ─── */

function PreviewWaveform({ buffer }: { buffer: ArrayBuffer }) {
  const [decoded, setDecoded] = React.useState<AudioBuffer | null>(null);

  useEffect(() => {
    const ctx = new AudioContext();
    ctx.decodeAudioData(buffer.slice(0))
      .then((d) => setDecoded(d))
      .catch(() => setDecoded(null));
    return () => { void ctx.close(); };
  }, [buffer]);

  if (!decoded) return null;

  return (
    <Waveform
      buffer={decoded}
      currentTime={0}
      duration={decoded.duration}
      trimStart={null}
      trimEnd={null}
      onSeek={() => {}}
      mini
    />
  );
}

/* ─── PublishModal ─── */

export function PublishModal({ open, onClose }: { open: boolean; onClose: () => void }) {
  const takes = useAppStore((state) => state.takes);
  const selectedTakeId = useAppStore((state) => state.selectedTakeId);
  const brief = useAppStore((state) => state.brief);
  const audioBuffers = useAppStore((state) => state.audioBuffers);
  const realmConfigured = useAppStore((state) => state.realmConfigured);
  const realmAuthenticated = useAppStore((state) => state.realmAuthenticated);

  const draftPost = useAppStore((state) => state.draftPost);
  const provenanceConfirmed = useAppStore((state) => state.provenanceConfirmed);
  const publishStatus = useAppStore((state) => state.publishStatus);
  const publishError = useAppStore((state) => state.publishError);
  const publishedPostId = useAppStore((state) => state.publishedPostId);

  const setDraftPost = useAppStore((state) => state.setDraftPost);
  const setProvenanceConfirmed = useAppStore((state) => state.setProvenanceConfirmed);
  const setPublishStatus = useAppStore((state) => state.setPublishStatus);
  const setPublishedPostId = useAppStore((state) => state.setPublishedPostId);

  const selectedTake = takes.find((take) => take.takeId === selectedTakeId);

  // Esc to close
  useEffect(() => {
    if (!open) return;
    const onKey = (e: KeyboardEvent) => {
      if (e.key === 'Escape') onClose();
    };
    window.addEventListener('keydown', onKey);
    return () => window.removeEventListener('keydown', onKey);
  }, [open, onClose]);

  const effectiveTitle = draftPost?.title || brief?.title || selectedTake?.title || '';
  const effectiveDescription = draftPost?.description || brief?.description || '';
  const effectiveTags = draftPost?.tags ?? [];

  const audioBuffer = selectedTakeId ? audioBuffers.get(selectedTakeId) : undefined;

  const hasBlocker = !realmConfigured || !realmAuthenticated;

  const canPublish =
    !hasBlocker &&
    provenanceConfirmed &&
    audioBuffer != null &&
    publishStatus !== 'uploading' &&
    publishStatus !== 'creating' &&
    publishStatus !== 'done';

  const isPublishing = publishStatus === 'uploading' || publishStatus === 'creating';

  const sourceLabel = selectedTake
    ? selectedTake.origin === 'prompt'
      ? 'AI-generated from a text prompt'
      : selectedTake.origin === 'reference'
        ? 'AI-generated with uploaded reference audio'
        : `AI-generated by ${selectedTake.origin} from an existing take`
    : '';

  const handlePublish = useCallback(() => {
    if (!canPublish || !audioBuffer) return;

    publishTake({
      audioBuffer,
      title: effectiveTitle,
      description: effectiveDescription,
      tags: effectiveTags,
      duration: undefined,
      onStatus: (status, error) => setPublishStatus(status, error),
      onPostId: (postId) => setPublishedPostId(postId),
    });
  }, [canPublish, audioBuffer, effectiveTitle, effectiveDescription, effectiveTags, setPublishStatus, setPublishedPostId]);

  if (!open || !selectedTake) return null;

  return (
    <div className="fixed inset-0 z-[60] flex items-center justify-center">
      {/* Overlay */}
      <div
        className="absolute inset-0 bg-ot-surface-0/60"
        style={{ backdropFilter: 'blur(8px)', WebkitBackdropFilter: 'blur(8px)' }}
        onClick={onClose}
      />

      {/* Modal */}
      <div
        className="relative max-w-[520px] w-full mx-4 bg-ot-surface-1 rounded-2xl shadow-panel overflow-hidden"
        style={{ animation: 'ot-modal-enter 300ms cubic-bezier(0.22, 1, 0.36, 1)' }}
      >
        {/* Header */}
        <div className="px-6 pt-6 pb-4">
          <h2 className="text-lg font-semibold text-ot-text-primary">Publish to Realm</h2>
        </div>

        {/* Take Preview */}
        <div className="mx-6 p-3 rounded-lg bg-ot-surface-2 space-y-2">
          {audioBuffer && <PreviewWaveform buffer={audioBuffer} />}
          <div className="flex items-center justify-between">
            <span className="text-sm font-medium text-ot-text-primary truncate">{selectedTake.title}</span>
            <span className={`ot-badge-origin ot-badge-origin--${selectedTake.origin}`}>{selectedTake.origin}</span>
          </div>
        </div>

        {/* Form */}
        <div className="px-6 py-4 space-y-4">
          {hasBlocker && (
            <div className="rounded-lg border border-ot-warning/20 bg-ot-warning/10 px-3 py-2 text-xs text-ot-warning">
              {!realmConfigured
                ? 'Realm is not configured. Set VITE_NIMI_REALM_BASE_URL and VITE_NIMI_REALM_ACCESS_TOKEN.'
                : 'Realm is configured but authentication is not available.'}
            </div>
          )}

          {publishStatus === 'error' && publishError && (
            <div className="rounded-lg border border-ot-error/20 bg-ot-error/10 px-3 py-2 text-xs text-ot-error">
              {publishError}
              <button
                className="ml-2 underline"
                onClick={() => setPublishStatus('idle')}
                type="button"
              >
                Dismiss
              </button>
            </div>
          )}

          {publishStatus === 'done' && publishedPostId && (
            <div className="rounded-lg border border-ot-success/20 bg-ot-success/10 px-3 py-2 text-xs text-ot-success flex items-center gap-2">
              <span>✨</span>
              Published! Post ID: <span className="font-mono">{publishedPostId}</span>
            </div>
          )}

          <div className="space-y-1">
            <label className="text-[11px] text-ot-text-tertiary uppercase tracking-[0.06em]">Title</label>
            <OtInput
              value={effectiveTitle}
              onChange={(event) =>
                setDraftPost({
                  title: event.target.value,
                  description: effectiveDescription,
                  tags: effectiveTags,
                })
              }
              placeholder="Song title"
            />
          </div>

          <div className="space-y-1">
            <label className="text-[11px] text-ot-text-tertiary uppercase tracking-[0.06em]">Description</label>
            <OtTextarea
              value={effectiveDescription}
              onChange={(event) =>
                setDraftPost({
                  title: effectiveTitle,
                  description: event.target.value,
                  tags: effectiveTags,
                })
              }
              placeholder="Describe your song..."
              style={{ minHeight: 64 }}
            />
          </div>

          <div className="space-y-1">
            <label className="text-[11px] text-ot-text-tertiary uppercase tracking-[0.06em]">Tags</label>
            <OtTagInput
              tags={effectiveTags}
              onChange={(tags) =>
                setDraftPost({
                  title: effectiveTitle,
                  description: effectiveDescription,
                  tags,
                })
              }
              placeholder="comma separated tags"
            />
          </div>

          {/* Provenance */}
          <div className="p-3 rounded-lg bg-ot-surface-2 border border-ot-surface-5 space-y-2">
            <p className="text-xs text-ot-text-secondary">
              Source: <span className="text-ot-text-primary">{sourceLabel}</span>
            </p>
            {selectedTake.parentTakeId && (
              <p className="text-[10px] text-ot-text-ghost">
                Parent: {takes.find((t) => t.takeId === selectedTake.parentTakeId)?.title ?? selectedTake.parentTakeId}
              </p>
            )}
            <label className="flex items-start gap-2 cursor-pointer">
              <input
                type="checkbox"
                checked={provenanceConfirmed}
                onChange={(event) => setProvenanceConfirmed(event.target.checked)}
                className="mt-0.5 accent-ot-violet-400"
              />
              <span className="text-xs text-ot-text-secondary">
                I confirm the source material is original or I have the right to publish it.
              </span>
            </label>
          </div>
        </div>

        {/* Footer */}
        <div className="px-6 pb-6 flex items-center justify-between">
          <OtButton variant="tertiary" onClick={onClose} type="button">
            Cancel
          </OtButton>
          <OtButton
            variant="primary"
            onClick={handlePublish}
            disabled={!canPublish}
            loading={isPublishing}
            type="button"
          >
            {isPublishing
              ? publishStatus === 'uploading' ? 'Uploading...' : 'Creating post...'
              : publishStatus === 'done'
                ? 'Published'
                : 'Publish Now'}
          </OtButton>
        </div>
      </div>
    </div>
  );
}
