import React, { useState } from 'react';
import { useAppStore } from '@renderer/app-shell/providers/app-store.js';

export function PublishPanel() {
  const takes = useAppStore((state) => state.takes);
  const selectedTakeId = useAppStore((state) => state.selectedTakeId);
  const brief = useAppStore((state) => state.brief);
  const realmConfigured = useAppStore((state) => state.realmConfigured);
  const realmAuthenticated = useAppStore((state) => state.realmAuthenticated);

  const selectedTake = takes.find((take) => take.takeId === selectedTakeId);

  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [tags, setTags] = useState('');
  const [provenanceConfirmed, setProvenanceConfirmed] = useState(false);

  if (!selectedTake) {
    return null;
  }

  const effectiveTitle = title || brief?.title || selectedTake.title;
  const effectiveDescription = description || brief?.description || '';
  const blockedReason = !realmConfigured
    ? 'Realm is not configured. Set VITE_NIMI_REALM_BASE_URL and VITE_NIMI_REALM_ACCESS_TOKEN to prepare publish metadata.'
    : !realmAuthenticated
      ? 'Realm is configured but authentication is not available.'
      : 'Publishing is blocked because Realm does not yet expose an audio media contract for song takes.';

  const sourceLabel = selectedTake.origin === 'prompt'
    ? 'AI-generated from a text prompt'
    : selectedTake.origin === 'reference'
      ? 'AI-generated with uploaded reference audio'
      : `AI-generated by ${selectedTake.origin} from an existing take`;

  return (
    <div className="space-y-4">
      <h2 className="text-sm font-semibold text-zinc-300 uppercase tracking-wider">Publish</h2>

      <div className="rounded-md border border-amber-500/20 bg-amber-500/10 px-3 py-2 text-xs text-amber-300">
        {blockedReason}
      </div>

      <div className="space-y-3">
        <div className="space-y-1">
          <label className="text-xs font-medium text-zinc-400">Title</label>
          <input
            className="w-full bg-zinc-900 border border-zinc-700 rounded-md px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-zinc-500"
            value={effectiveTitle}
            onChange={(event) => setTitle(event.target.value)}
            placeholder="Song title"
          />
        </div>

        <div className="space-y-1">
          <label className="text-xs font-medium text-zinc-400">Description</label>
          <textarea
            className="w-full h-16 bg-zinc-900 border border-zinc-700 rounded-md px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 resize-none focus:outline-none focus:border-zinc-500"
            value={effectiveDescription}
            onChange={(event) => setDescription(event.target.value)}
            placeholder="Describe your song..."
          />
        </div>

        <div className="space-y-1">
          <label className="text-xs font-medium text-zinc-400">Tags</label>
          <input
            className="w-full bg-zinc-900 border border-zinc-700 rounded-md px-3 py-1.5 text-sm text-zinc-100 placeholder:text-zinc-600 focus:outline-none focus:border-zinc-500"
            value={tags}
            onChange={(event) => setTags(event.target.value)}
            placeholder="comma separated tags"
          />
        </div>

        <div className="p-2 rounded-md bg-zinc-900 border border-zinc-800 space-y-2">
          <p className="text-xs text-zinc-400">
            Publish master: <span className="text-zinc-300">{selectedTake.title}</span>
          </p>
          <p className="text-xs text-zinc-400">
            Source: <span className="text-zinc-300">{sourceLabel}</span>
          </p>
          {selectedTake.parentTakeId && (
            <p className="text-[10px] text-zinc-500">
              Parent take: {takes.find((take) => take.takeId === selectedTake.parentTakeId)?.title ?? selectedTake.parentTakeId}
            </p>
          )}
          <label className="flex items-start gap-2 cursor-pointer">
            <input
              type="checkbox"
              checked={provenanceConfirmed}
              onChange={(event) => setProvenanceConfirmed(event.target.checked)}
              className="mt-0.5 rounded border-zinc-600 bg-zinc-900"
            />
            <span className="text-xs text-zinc-400">
              I confirm the source material is original or I have the right to publish it.
            </span>
          </label>
        </div>
      </div>

      <button
        className="w-full px-4 py-2 text-sm font-medium bg-zinc-800 text-zinc-400 rounded-lg cursor-not-allowed"
        disabled
        type="button"
      >
        Blocked on Realm Audio Media Support
      </button>
    </div>
  );
}
