// @generated by sdks/generators/generate.mjs
// DO NOT EDIT MANUALLY.

import { CoreClient } from '../core-client';
import type { CoreMetadata } from '../types';

export interface RealmOperationDescriptor {
  readonly operationId: string;
  readonly service: string;
  readonly method: string;
  readonly path: string | null;
}

export const REALM_OPERATIONS: readonly RealmOperationDescriptor[] = [
  {
    "operationId": "ackMyLocalAgentProvisionIntent",
    "service": "Me",
    "method": "POST",
    "path": "/api/human/me/local-agent-provision-intents/{intentId}/ack"
  },
  {
    "operationId": "ackMyLocalAgentTerminationIntent",
    "service": "Me",
    "method": "POST",
    "path": "/api/human/me/local-agent-termination-intents/{intentId}/ack"
  },
  {
    "operationId": "addFriend",
    "service": "User",
    "method": "POST",
    "path": "/api/human/accounts/{id}/friends"
  },
  {
    "operationId": "addGroupAgent",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats/{chatId}/agents"
  },
  {
    "operationId": "addGroupParticipant",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats/{chatId}/participants"
  },
  {
    "operationId": "AgentController_checkHandle",
    "service": "Agents",
    "method": "GET",
    "path": "/api/agent/handles/check"
  },
  {
    "operationId": "AgentController_create",
    "service": "Agents",
    "method": "POST",
    "path": "/api/agent"
  },
  {
    "operationId": "AgentController_delete",
    "service": "Agents",
    "method": "DELETE",
    "path": "/api/agent/accounts/{id}"
  },
  {
    "operationId": "AgentController_getRelationships",
    "service": "Agents",
    "method": "GET",
    "path": "/api/agent/accounts/{id}/relationships"
  },
  {
    "operationId": "AgentController_getVisibility",
    "service": "Agents",
    "method": "GET",
    "path": "/api/agent/accounts/{id}/visibility"
  },
  {
    "operationId": "AgentController_makePublic",
    "service": "Agents",
    "method": "POST",
    "path": "/api/agent/accounts/{id}/public"
  },
  {
    "operationId": "AgentController_removeRelationship",
    "service": "Agents",
    "method": "DELETE",
    "path": "/api/agent/accounts/{id}/relationships"
  },
  {
    "operationId": "AgentController_selectAvatar",
    "service": "Agents",
    "method": "POST",
    "path": "/api/agent/accounts/{id}/avatar"
  },
  {
    "operationId": "AgentController_setRelationship",
    "service": "Agents",
    "method": "POST",
    "path": "/api/agent/accounts/{id}/relationships"
  },
  {
    "operationId": "AgentController_updateDna",
    "service": "Agents",
    "method": "PATCH",
    "path": "/api/agent/accounts/{id}/dna"
  },
  {
    "operationId": "AgentController_updateVisibility",
    "service": "Agents",
    "method": "PATCH",
    "path": "/api/agent/accounts/{id}/visibility"
  },
  {
    "operationId": "AgentNsfwConsentController_updateAgentConsent",
    "service": "Agent NSFW Consent",
    "method": "PUT",
    "path": "/api/agent/accounts/{id}/visibility/nsfw-consent"
  },
  {
    "operationId": "AgentRulesController_archiveRule",
    "service": "Agent Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/agents/{agentId}/rules/{ruleId}/archive"
  },
  {
    "operationId": "AgentRulesController_createRule",
    "service": "Agent Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/agents/{agentId}/rules"
  },
  {
    "operationId": "AgentRulesController_deprecateRule",
    "service": "Agent Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/agents/{agentId}/rules/{ruleId}/deprecate"
  },
  {
    "operationId": "AgentRulesController_listRules",
    "service": "Agent Rules",
    "method": "GET",
    "path": "/api/world/by-id/{worldId}/agents/{agentId}/rules"
  },
  {
    "operationId": "AgentRulesController_updateRule",
    "service": "Agent Rules",
    "method": "PATCH",
    "path": "/api/world/by-id/{worldId}/agents/{agentId}/rules/{ruleId}"
  },
  {
    "operationId": "archiveBundle",
    "service": "Bundles",
    "method": "POST",
    "path": "/api/bundles/{bundleId}/archive"
  },
  {
    "operationId": "bindEmail",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/me/email"
  },
  {
    "operationId": "bindWallet",
    "service": "Me",
    "method": "POST",
    "path": "/api/human/me/wallets"
  },
  {
    "operationId": "blockUser",
    "service": "Me",
    "method": "POST",
    "path": "/api/human/me/blocks/{id}"
  },
  {
    "operationId": "changeEmail",
    "service": "Auth",
    "method": "PATCH",
    "path": "/api/auth/me/email"
  },
  {
    "operationId": "checkEmail",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/email/check"
  },
  {
    "operationId": "checkHandle",
    "service": "User",
    "method": "GET",
    "path": "/api/human/check-handle"
  },
  {
    "operationId": "cloneAsset",
    "service": "Assets",
    "method": "POST",
    "path": "/api/assets/{assetId}/clone"
  },
  {
    "operationId": "commitRealmGroupMessageCandidate",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats/{chatId}/agent-message-candidate-commits"
  },
  {
    "operationId": "createAsset",
    "service": "Assets",
    "method": "POST",
    "path": "/api/assets"
  },
  {
    "operationId": "createAudioDirectUpload",
    "service": "Resources",
    "method": "POST",
    "path": "/api/resources/audio/direct-upload"
  },
  {
    "operationId": "createBundle",
    "service": "Bundles",
    "method": "POST",
    "path": "/api/bundles"
  },
  {
    "operationId": "createGroup",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats"
  },
  {
    "operationId": "createImageDirectUpload",
    "service": "Resources",
    "method": "POST",
    "path": "/api/resources/images/direct-upload"
  },
  {
    "operationId": "createPost",
    "service": "Posts",
    "method": "POST",
    "path": "/api/world/posts"
  },
  {
    "operationId": "createTextResource",
    "service": "Resources",
    "method": "POST",
    "path": "/api/resources/texts"
  },
  {
    "operationId": "createVideoDirectUpload",
    "service": "Resources",
    "method": "POST",
    "path": "/api/resources/videos/direct-upload"
  },
  {
    "operationId": "CreatorController_batchCreateAgents",
    "service": "Creator",
    "method": "POST",
    "path": "/api/creator/agents/batch-create"
  },
  {
    "operationId": "CreatorController_createAgent",
    "service": "Creator",
    "method": "POST",
    "path": "/api/creator/agents"
  },
  {
    "operationId": "CreatorController_createKey",
    "service": "Creator",
    "method": "POST",
    "path": "/api/creator/keys"
  },
  {
    "operationId": "CreatorController_deleteAgent",
    "service": "Creator",
    "method": "DELETE",
    "path": "/api/creator/agents/{agentId}"
  },
  {
    "operationId": "CreatorController_getAgent",
    "service": "Creator",
    "method": "GET",
    "path": "/api/creator/agents/{agentId}"
  },
  {
    "operationId": "CreatorController_listAgents",
    "service": "Creator",
    "method": "GET",
    "path": "/api/creator/agents"
  },
  {
    "operationId": "CreatorController_listKeys",
    "service": "Creator",
    "method": "GET",
    "path": "/api/creator/keys"
  },
  {
    "operationId": "CreatorController_revokeKey",
    "service": "Creator",
    "method": "DELETE",
    "path": "/api/creator/keys/{id}"
  },
  {
    "operationId": "CreatorController_updateAgent",
    "service": "Creator",
    "method": "PATCH",
    "path": "/api/creator/agents/{agentId}"
  },
  {
    "operationId": "deletePost",
    "service": "Posts",
    "method": "DELETE",
    "path": "/api/world/posts/by-id/{id}"
  },
  {
    "operationId": "deleteResource",
    "service": "Resources",
    "method": "DELETE",
    "path": "/api/resources/{resourceId}"
  },
  {
    "operationId": "denyMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "POST",
    "path": "/api/human/me/permission-grants/by-id/{grantId}/deny"
  },
  {
    "operationId": "disable2Fa",
    "service": "Me2fa",
    "method": "POST",
    "path": "/api/auth/me/2fa/disable"
  },
  {
    "operationId": "EconomyController_acceptGift",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/gifts/{id}/accept"
  },
  {
    "operationId": "EconomyController_calculateWithdrawal",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/withdrawals/calculate"
  },
  {
    "operationId": "EconomyController_cancelSubscription",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/subscription/cancel"
  },
  {
    "operationId": "EconomyController_canWithdraw",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/withdrawals/can-withdraw"
  },
  {
    "operationId": "EconomyController_createConnectDashboard",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/connect/dashboard"
  },
  {
    "operationId": "EconomyController_createConnectOnboarding",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/connect/onboarding"
  },
  {
    "operationId": "EconomyController_createPortalSession",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/subscription/portal"
  },
  {
    "operationId": "EconomyController_createSparkCheckout",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/spark/checkout"
  },
  {
    "operationId": "EconomyController_createSubscriptionCheckout",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/subscription/checkout"
  },
  {
    "operationId": "EconomyController_createWithdrawal",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/withdrawals/create"
  },
  {
    "operationId": "EconomyController_getAgentOrigin",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/revenue-share/agent-origin/{agentId}"
  },
  {
    "operationId": "EconomyController_getBalances",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/balances"
  },
  {
    "operationId": "EconomyController_getConnectStatus",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/connect/status"
  },
  {
    "operationId": "EconomyController_getGemHistory",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/gem/history"
  },
  {
    "operationId": "EconomyController_getGiftCatalog",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/gifts/catalog"
  },
  {
    "operationId": "EconomyController_getReceivedGifts",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/gifts/received"
  },
  {
    "operationId": "EconomyController_getRevenueShareConfig",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/revenue-share/config"
  },
  {
    "operationId": "EconomyController_getSentGifts",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/gifts/sent"
  },
  {
    "operationId": "EconomyController_getSparkHistory",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/spark/history"
  },
  {
    "operationId": "EconomyController_getSparkPackages",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/spark/packages"
  },
  {
    "operationId": "EconomyController_getSubscription",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/subscription"
  },
  {
    "operationId": "EconomyController_getSubscriptionTiers",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/subscription/tiers"
  },
  {
    "operationId": "EconomyController_getWithdrawal",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/withdrawals/by-id/{id}"
  },
  {
    "operationId": "EconomyController_getWithdrawalConfig",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/withdrawals/config"
  },
  {
    "operationId": "EconomyController_getWithdrawalHistory",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/withdrawals/history"
  },
  {
    "operationId": "EconomyController_previewRevenueDistribution",
    "service": "Economy (Currency & Gifts)",
    "method": "GET",
    "path": "/api/economy/revenue-share/preview"
  },
  {
    "operationId": "EconomyController_rejectGift",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/gifts/{giftId}/reject"
  },
  {
    "operationId": "EconomyController_sendGift",
    "service": "Economy (Currency & Gifts)",
    "method": "POST",
    "path": "/api/economy/gifts/send"
  },
  {
    "operationId": "editGroupMessage",
    "service": "Group Chats",
    "method": "PATCH",
    "path": "/api/human/group-chats/{chatId}/messages/{messageId}"
  },
  {
    "operationId": "editMessage",
    "service": "Human Chats",
    "method": "PATCH",
    "path": "/api/human/chats/{chatId}/messages/{messageId}"
  },
  {
    "operationId": "enable2Fa",
    "service": "Me2fa",
    "method": "POST",
    "path": "/api/auth/me/2fa/enable"
  },
  {
    "operationId": "expireMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "POST",
    "path": "/api/human/me/permission-grants/by-id/{grantId}/expire"
  },
  {
    "operationId": "ExploreController_checkStatus",
    "service": "Explore",
    "method": "GET",
    "path": "/api/explore/status"
  },
  {
    "operationId": "finalizeResource",
    "service": "Resources",
    "method": "POST",
    "path": "/api/resources/{resourceId}/finalize"
  },
  {
    "operationId": "ForgeProductCatalogController_getAgentCandidates",
    "service": "Forge World Products",
    "method": "GET",
    "path": "/api/world-products/{slug}/agent-candidates"
  },
  {
    "operationId": "ForgeProductCatalogController_getCatalog",
    "service": "Forge World Products",
    "method": "GET",
    "path": "/api/world-products/catalog"
  },
  {
    "operationId": "ForgeProductCatalogController_getProduct",
    "service": "Forge World Products",
    "method": "GET",
    "path": "/api/world-products/{slug}"
  },
  {
    "operationId": "ForgeProductCatalogController_getProductShard",
    "service": "Forge World Products",
    "method": "GET",
    "path": "/api/world-products/{slug}/shards/{kind}"
  },
  {
    "operationId": "ForgeProductCatalogController_getProductShardIndex",
    "service": "Forge World Products",
    "method": "GET",
    "path": "/api/world-products/{slug}/shards"
  },
  {
    "operationId": "ForgeProductCatalogController_verifyProductShards",
    "service": "Forge World Products",
    "method": "GET",
    "path": "/api/world-products/{slug}/shards/integrity"
  },
  {
    "operationId": "getAgent",
    "service": "Agents",
    "method": "GET",
    "path": "/api/agent/accounts/{id}"
  },
  {
    "operationId": "getAgentByHandle",
    "service": "Agents",
    "method": "GET",
    "path": "/api/agent/handle/{handle}"
  },
  {
    "operationId": "getAsset",
    "service": "Assets",
    "method": "GET",
    "path": "/api/assets/{assetId}"
  },
  {
    "operationId": "getAuthJwks",
    "service": "Jwks",
    "method": "GET",
    "path": "/api/auth/jwks"
  },
  {
    "operationId": "getBundle",
    "service": "Bundles",
    "method": "GET",
    "path": "/api/bundles/{bundleId}"
  },
  {
    "operationId": "getChatById",
    "service": "Human Chats",
    "method": "GET",
    "path": "/api/human/chats/{chatId}"
  },
  {
    "operationId": "getCreatorWorldAgent",
    "service": "Agent / Creator World",
    "method": "GET",
    "path": "/api/me/creator/worlds/{worldId}/agents/{agentId}"
  },
  {
    "operationId": "getCreatorWorldAgentChatReadiness",
    "service": "Agent / Creator World",
    "method": "GET",
    "path": "/api/me/creator/worlds/{worldId}/agents/{agentId}/chat-readiness"
  },
  {
    "operationId": "getCreatorWorldAgentSettings",
    "service": "Agent / Creator World",
    "method": "GET",
    "path": "/api/me/creator/worlds/{worldId}/agents/{agentId}/settings"
  },
  {
    "operationId": "getExploreFeed",
    "service": "Explore",
    "method": "GET",
    "path": "/api/explore"
  },
  {
    "operationId": "getGroup",
    "service": "Group Chats",
    "method": "GET",
    "path": "/api/human/group-chats/{chatId}"
  },
  {
    "operationId": "getHomeFeed",
    "service": "Posts",
    "method": "GET",
    "path": "/api/world/posts"
  },
  {
    "operationId": "getMe",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me"
  },
  {
    "operationId": "getMutualFriends",
    "service": "User",
    "method": "GET",
    "path": "/api/human/accounts/{id}/mutual-friends"
  },
  {
    "operationId": "getMutualFriendsCount",
    "service": "User",
    "method": "GET",
    "path": "/api/human/accounts/{id}/mutual-friends/count"
  },
  {
    "operationId": "getMyAgentFriendLimit",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/friends/agent-limit"
  },
  {
    "operationId": "getMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "GET",
    "path": "/api/human/me/permission-grants/by-id/{grantId}"
  },
  {
    "operationId": "getMyAppPermissionGrantProjection",
    "service": "Me / Permission Grants",
    "method": "GET",
    "path": "/api/human/me/permission-grants/projection"
  },
  {
    "operationId": "getMyAppPermissionGrantStatus",
    "service": "Me / Permission Grants",
    "method": "GET",
    "path": "/api/human/me/permission-grants/status"
  },
  {
    "operationId": "getMyBlockedUsers",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/blocks"
  },
  {
    "operationId": "getMyCapabilities",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/capabilities"
  },
  {
    "operationId": "getMyCreatorEligibility",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/creator-eligibility"
  },
  {
    "operationId": "getMyNotificationSettings",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/notification-settings"
  },
  {
    "operationId": "getMyPendingFriendRequests",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/friends/pending"
  },
  {
    "operationId": "getMyPPConfig",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/pp-config"
  },
  {
    "operationId": "getMyRealmAgent",
    "service": "Me",
    "method": "GET",
    "path": "/api/me/agents/{agentId}"
  },
  {
    "operationId": "getMyRealmAgentSettings",
    "service": "Me",
    "method": "GET",
    "path": "/api/me/agents/{agentId}/settings"
  },
  {
    "operationId": "getMySettings",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/settings"
  },
  {
    "operationId": "getMyTiers",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/tiers"
  },
  {
    "operationId": "getMyWallets",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/wallets"
  },
  {
    "operationId": "getPost",
    "service": "Posts",
    "method": "GET",
    "path": "/api/world/posts/by-id/{id}"
  },
  {
    "operationId": "getPublicPost",
    "service": "Posts",
    "method": "GET",
    "path": "/api/world/posts/public/{id}"
  },
  {
    "operationId": "getResource",
    "service": "Resources",
    "method": "GET",
    "path": "/api/resources/{resourceId}"
  },
  {
    "operationId": "getUnreadCount",
    "service": "Notifications",
    "method": "GET",
    "path": "/api/human/notifications/unread-count"
  },
  {
    "operationId": "getUser",
    "service": "User",
    "method": "GET",
    "path": "/api/human/accounts/{id}"
  },
  {
    "operationId": "getUserByHandle",
    "service": "User",
    "method": "GET",
    "path": "/api/human/handle/{handle}"
  },
  {
    "operationId": "getUserFriends",
    "service": "User",
    "method": "GET",
    "path": "/api/human/accounts/{id}/friends"
  },
  {
    "operationId": "getWorldPosts",
    "service": "WorldPost",
    "method": "GET",
    "path": "/api/world/by-id/{worldId}/posts"
  },
  {
    "operationId": "getWorldScenes",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/scenes"
  },
  {
    "operationId": "grantMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "POST",
    "path": "/api/human/me/permission-grants/by-id/{grantId}/grant"
  },
  {
    "operationId": "HumanNsfwConsentController_canManageAgentNsfw",
    "service": "Human NSFW Consent",
    "method": "GET",
    "path": "/api/human/nsfw-consent/can-manage"
  },
  {
    "operationId": "HumanNsfwConsentController_checkConsent",
    "service": "Human NSFW Consent",
    "method": "GET",
    "path": "/api/human/nsfw-consent/check"
  },
  {
    "operationId": "HumanNsfwConsentController_getConsentStatus",
    "service": "Human NSFW Consent",
    "method": "GET",
    "path": "/api/human/nsfw-consent/status"
  },
  {
    "operationId": "HumanNsfwConsentController_updateUserConsent",
    "service": "Human NSFW Consent",
    "method": "PUT",
    "path": "/api/human/me/settings/nsfw-consent"
  },
  {
    "operationId": "introspectSession",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/sessions/introspect"
  },
  {
    "operationId": "InvitationController_generateCode",
    "service": "Invitations",
    "method": "POST",
    "path": "/api/invitations"
  },
  {
    "operationId": "InvitationController_listMyCodes",
    "service": "Invitations",
    "method": "GET",
    "path": "/api/invitations"
  },
  {
    "operationId": "InvitationController_verifyCode",
    "service": "Invitations",
    "method": "POST",
    "path": "/api/invitations/verify"
  },
  {
    "operationId": "issueRuntimeRealmGrant",
    "service": "Runtime Realm Grants",
    "method": "POST",
    "path": "/api/runtime/realm-grants/issue"
  },
  {
    "operationId": "likePost",
    "service": "Posts",
    "method": "POST",
    "path": "/api/world/posts/by-id/{postId}/like"
  },
  {
    "operationId": "linkOauth",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/oauth/link"
  },
  {
    "operationId": "listAssets",
    "service": "Assets",
    "method": "GET",
    "path": "/api/assets"
  },
  {
    "operationId": "listBundles",
    "service": "Bundles",
    "method": "GET",
    "path": "/api/bundles"
  },
  {
    "operationId": "listChats",
    "service": "Human Chats",
    "method": "GET",
    "path": "/api/human/chats"
  },
  {
    "operationId": "listCreatorWorldAgents",
    "service": "Agent / Creator World",
    "method": "GET",
    "path": "/api/me/creator/worlds/{worldId}/agents"
  },
  {
    "operationId": "listGroupMessages",
    "service": "Group Chats",
    "method": "GET",
    "path": "/api/human/group-chats/{chatId}/messages"
  },
  {
    "operationId": "listGroups",
    "service": "Group Chats",
    "method": "GET",
    "path": "/api/human/group-chats"
  },
  {
    "operationId": "listLikedPosts",
    "service": "Posts",
    "method": "GET",
    "path": "/api/world/posts/liked"
  },
  {
    "operationId": "listMessages",
    "service": "Human Chats",
    "method": "GET",
    "path": "/api/human/chats/{chatId}/messages"
  },
  {
    "operationId": "listMyAppPermissionGrants",
    "service": "Me / Permission Grants",
    "method": "GET",
    "path": "/api/human/me/permission-grants"
  },
  {
    "operationId": "listMyCreatorWorlds",
    "service": "World Control",
    "method": "GET",
    "path": "/api/me/creator/worlds"
  },
  {
    "operationId": "listMyFriendIds",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/friends"
  },
  {
    "operationId": "listMyFriendsWithDetails",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/friends/list"
  },
  {
    "operationId": "listMyLocalAgentProvisionIntents",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/local-agent-provision-intents"
  },
  {
    "operationId": "listMyLocalAgentTerminationIntents",
    "service": "Me",
    "method": "GET",
    "path": "/api/human/me/local-agent-termination-intents"
  },
  {
    "operationId": "listMyRealmAgents",
    "service": "Me",
    "method": "GET",
    "path": "/api/me/agents"
  },
  {
    "operationId": "listNotifications",
    "service": "Notifications",
    "method": "GET",
    "path": "/api/human/notifications"
  },
  {
    "operationId": "listOnlineUsers",
    "service": "User",
    "method": "GET",
    "path": "/api/human/online"
  },
  {
    "operationId": "listResources",
    "service": "Resources",
    "method": "GET",
    "path": "/api/resources"
  },
  {
    "operationId": "logout",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/logout"
  },
  {
    "operationId": "markChatRead",
    "service": "Human Chats",
    "method": "POST",
    "path": "/api/human/chats/{chatId}/read"
  },
  {
    "operationId": "markGroupRead",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats/{chatId}/read"
  },
  {
    "operationId": "markNotificationRead",
    "service": "Notifications",
    "method": "POST",
    "path": "/api/human/notifications/{notificationId}/read"
  },
  {
    "operationId": "markNotificationsRead",
    "service": "Notifications",
    "method": "POST",
    "path": "/api/human/notifications/read"
  },
  {
    "operationId": "oauthAuthorize",
    "service": "Auth",
    "method": "GET",
    "path": "/api/auth/oauth/authorize"
  },
  {
    "operationId": "oauthLogin",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/oauth/login"
  },
  {
    "operationId": "oauthToken",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/oauth/token"
  },
  {
    "operationId": "passwordLogin",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/password/login"
  },
  {
    "operationId": "passwordRegister",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/password/register"
  },
  {
    "operationId": "prepare2Fa",
    "service": "Me2fa",
    "method": "POST",
    "path": "/api/auth/me/2fa/prepare"
  },
  {
    "operationId": "prepareBindWallet",
    "service": "Me",
    "method": "POST",
    "path": "/api/human/me/wallets/prepare-bind"
  },
  {
    "operationId": "projectRuntimePayload",
    "service": "Runtime Projections",
    "method": "POST",
    "path": "/api/runtime/projections/project"
  },
  {
    "operationId": "publishBundle",
    "service": "Bundles",
    "method": "POST",
    "path": "/api/bundles/{bundleId}/publish"
  },
  {
    "operationId": "recallGroupMessage",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats/{chatId}/messages/{messageId}/recall"
  },
  {
    "operationId": "recallMessage",
    "service": "Human Chats",
    "method": "POST",
    "path": "/api/human/chats/{chatId}/messages/{messageId}/recall"
  },
  {
    "operationId": "refreshToken",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/refresh"
  },
  {
    "operationId": "RelationshipController_createRelationship",
    "service": "Relationships (Meta-Graph)",
    "method": "POST",
    "path": "/api/human/relationships"
  },
  {
    "operationId": "RelationshipController_deleteRelationship",
    "service": "Relationships (Meta-Graph)",
    "method": "DELETE",
    "path": "/api/human/relationships/{id}"
  },
  {
    "operationId": "RelationshipController_getMyRelationships",
    "service": "Relationships (Meta-Graph)",
    "method": "GET",
    "path": "/api/human/relationships/me"
  },
  {
    "operationId": "RelationshipController_updateRelationship",
    "service": "Relationships (Meta-Graph)",
    "method": "PATCH",
    "path": "/api/human/relationships/{id}"
  },
  {
    "operationId": "removeFriend",
    "service": "User",
    "method": "DELETE",
    "path": "/api/human/accounts/{id}/friends"
  },
  {
    "operationId": "removeGroupAgent",
    "service": "Group Chats",
    "method": "DELETE",
    "path": "/api/human/group-chats/{chatId}/agents/{agentAccountId}"
  },
  {
    "operationId": "removeGroupParticipant",
    "service": "Group Chats",
    "method": "DELETE",
    "path": "/api/human/group-chats/{chatId}/participants/{accountId}"
  },
  {
    "operationId": "ReportController_createReport",
    "service": "Governance",
    "method": "POST",
    "path": "/api/reports"
  },
  {
    "operationId": "requestAccountDeletion",
    "service": "MeAccountData",
    "method": "POST",
    "path": "/api/auth/me/account-deletion"
  },
  {
    "operationId": "requestDataExport",
    "service": "MeAccountData",
    "method": "POST",
    "path": "/api/auth/me/data-export"
  },
  {
    "operationId": "requestEmailOtp",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/email/otp/request"
  },
  {
    "operationId": "requestMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "POST",
    "path": "/api/human/me/permission-grants"
  },
  {
    "operationId": "ReviewController_createReview",
    "service": "Reviews (Economy/Trust)",
    "method": "POST",
    "path": "/api/economy/reviews"
  },
  {
    "operationId": "ReviewController_getReviews",
    "service": "Reviews (Economy/Trust)",
    "method": "GET",
    "path": "/api/economy/reviews"
  },
  {
    "operationId": "revokeMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "POST",
    "path": "/api/human/me/permission-grants/by-id/{grantId}/revoke"
  },
  {
    "operationId": "searchHumanUsers",
    "service": "User",
    "method": "GET",
    "path": "/api/human/search"
  },
  {
    "operationId": "searchIndexedUsers",
    "service": "Search",
    "method": "GET",
    "path": "/api/search/users"
  },
  {
    "operationId": "searchPosts",
    "service": "Search",
    "method": "GET",
    "path": "/api/search/posts"
  },
  {
    "operationId": "sendGroupMessage",
    "service": "Group Chats",
    "method": "POST",
    "path": "/api/human/group-chats/{chatId}/messages"
  },
  {
    "operationId": "sendMessage",
    "service": "Human Chats",
    "method": "POST",
    "path": "/api/human/chats/{chatId}/messages"
  },
  {
    "operationId": "startChat",
    "service": "Human Chats",
    "method": "POST",
    "path": "/api/human/chats"
  },
  {
    "operationId": "supersedeMyAppPermissionGrant",
    "service": "Me / Permission Grants",
    "method": "POST",
    "path": "/api/human/me/permission-grants/by-id/{grantId}/supersede"
  },
  {
    "operationId": "syncChatEvents",
    "service": "Human Chats",
    "method": "GET",
    "path": "/api/human/chats/{chatId}/sync"
  },
  {
    "operationId": "syncGroupEvents",
    "service": "Group Chats",
    "method": "GET",
    "path": "/api/human/group-chats/{chatId}/sync"
  },
  {
    "operationId": "TransitController_abandon",
    "service": "Transits",
    "method": "POST",
    "path": "/api/world/transit/{id}/abandon"
  },
  {
    "operationId": "TransitController_complete",
    "service": "Transits",
    "method": "POST",
    "path": "/api/world/transit/{id}/complete"
  },
  {
    "operationId": "TransitController_getActiveTransit",
    "service": "Transits",
    "method": "GET",
    "path": "/api/world/transit/active/{agentId}"
  },
  {
    "operationId": "TransitController_getTransit",
    "service": "Transits",
    "method": "GET",
    "path": "/api/world/transit/{id}"
  },
  {
    "operationId": "TransitController_listTransits",
    "service": "Transits",
    "method": "GET",
    "path": "/api/world/transit"
  },
  {
    "operationId": "translateText",
    "service": "Translation",
    "method": "POST",
    "path": "/api/translation/translate"
  },
  {
    "operationId": "unbindWallet",
    "service": "Me",
    "method": "DELETE",
    "path": "/api/human/me/wallets/{walletId}"
  },
  {
    "operationId": "unblockUser",
    "service": "Me",
    "method": "DELETE",
    "path": "/api/human/me/blocks/{id}"
  },
  {
    "operationId": "unlikePost",
    "service": "Posts",
    "method": "DELETE",
    "path": "/api/world/posts/by-id/{postId}/like"
  },
  {
    "operationId": "unlinkOauth",
    "service": "Auth",
    "method": "DELETE",
    "path": "/api/auth/oauth/{provider}"
  },
  {
    "operationId": "updateAsset",
    "service": "Assets",
    "method": "PATCH",
    "path": "/api/assets/{assetId}"
  },
  {
    "operationId": "updateBundle",
    "service": "Bundles",
    "method": "PATCH",
    "path": "/api/bundles/{bundleId}"
  },
  {
    "operationId": "updateCreatorWorldAgentProfileMedia",
    "service": "Agent / Creator World",
    "method": "PATCH",
    "path": "/api/me/creator/worlds/{worldId}/agents/{agentId}/profile-media"
  },
  {
    "operationId": "updateCreatorWorldAgentSettings",
    "service": "Agent / Creator World",
    "method": "PATCH",
    "path": "/api/me/creator/worlds/{worldId}/agents/{agentId}/settings"
  },
  {
    "operationId": "updateCreatorWorldAgentVoice",
    "service": "Agent / Creator World",
    "method": "PATCH",
    "path": "/api/me/creator/worlds/{worldId}/agents/{agentId}/voice"
  },
  {
    "operationId": "updateGroup",
    "service": "Group Chats",
    "method": "PATCH",
    "path": "/api/human/group-chats/{chatId}"
  },
  {
    "operationId": "updateGroupParticipantRole",
    "service": "Group Chats",
    "method": "PATCH",
    "path": "/api/human/group-chats/{chatId}/participants/{accountId}"
  },
  {
    "operationId": "updateMe",
    "service": "Me",
    "method": "PATCH",
    "path": "/api/human/me"
  },
  {
    "operationId": "updateMyHandle",
    "service": "Me",
    "method": "PATCH",
    "path": "/api/human/me/handle"
  },
  {
    "operationId": "updateMyNotificationSettings",
    "service": "Me",
    "method": "PATCH",
    "path": "/api/human/me/notification-settings"
  },
  {
    "operationId": "updateMyPPConfig",
    "service": "Me",
    "method": "PUT",
    "path": "/api/human/me/pp-config"
  },
  {
    "operationId": "updateMyRealmAgentSettings",
    "service": "Me",
    "method": "PATCH",
    "path": "/api/me/agents/{agentId}/settings"
  },
  {
    "operationId": "updateMySettings",
    "service": "Me",
    "method": "PATCH",
    "path": "/api/human/me/settings"
  },
  {
    "operationId": "updatePassword",
    "service": "Auth",
    "method": "PUT",
    "path": "/api/auth/me/password"
  },
  {
    "operationId": "updatePost",
    "service": "Posts",
    "method": "PATCH",
    "path": "/api/world/posts/by-id/{id}"
  },
  {
    "operationId": "updateResource",
    "service": "Resources",
    "method": "PATCH",
    "path": "/api/resources/{resourceId}"
  },
  {
    "operationId": "V1DefaultVisibilityController_applyAgentDefaults",
    "service": "Social - V1 Default Visibility",
    "method": "POST",
    "path": "/api/agent/visibility/defaults/apply/agent/{agentId}"
  },
  {
    "operationId": "V1DefaultVisibilityController_applyUserDefaults",
    "service": "Social - V1 Default Visibility",
    "method": "POST",
    "path": "/api/agent/visibility/defaults/apply/user/{userId}"
  },
  {
    "operationId": "V1DefaultVisibilityController_getDefaultForScope",
    "service": "Social - V1 Default Visibility",
    "method": "GET",
    "path": "/api/agent/visibility/defaults/defaults/{entityType}/{scope}"
  },
  {
    "operationId": "V1DefaultVisibilityController_getDefaultVisibility",
    "service": "Social - V1 Default Visibility",
    "method": "GET",
    "path": "/api/agent/visibility/defaults/defaults/{entityType}"
  },
  {
    "operationId": "V1DefaultVisibilityController_validateAgentVisibility",
    "service": "Social - V1 Default Visibility",
    "method": "GET",
    "path": "/api/agent/visibility/defaults/validate/agent/{agentId}"
  },
  {
    "operationId": "V1DefaultVisibilityController_validateUserVisibility",
    "service": "Social - V1 Default Visibility",
    "method": "GET",
    "path": "/api/agent/visibility/defaults/validate/user/{userId}"
  },
  {
    "operationId": "verify2Fa",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/2fa/verify"
  },
  {
    "operationId": "verifyEmailOtp",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/email/otp/verify"
  },
  {
    "operationId": "walletChallenge",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/wallet/challenge"
  },
  {
    "operationId": "walletLogin",
    "service": "Auth",
    "method": "POST",
    "path": "/api/auth/wallet/login"
  },
  {
    "operationId": "WorldControlController_appendWorldHistory",
    "service": "World Control",
    "method": "POST",
    "path": "/api/worlds/{worldId}/history/appends"
  },
  {
    "operationId": "WorldControlController_batchUpsertWorldBindings",
    "service": "World Control",
    "method": "POST",
    "path": "/api/worlds/{worldId}/bindings"
  },
  {
    "operationId": "WorldControlController_commitState",
    "service": "World Control",
    "method": "POST",
    "path": "/api/worlds/{worldId}/state/commits"
  },
  {
    "operationId": "WorldControlController_createDraft",
    "service": "World Control",
    "method": "POST",
    "path": "/api/world-drafts"
  },
  {
    "operationId": "WorldControlController_deleteWorldBinding",
    "service": "World Control",
    "method": "DELETE",
    "path": "/api/worlds/{worldId}/bindings/{bindingId}"
  },
  {
    "operationId": "WorldControlController_getDraft",
    "service": "World Control",
    "method": "GET",
    "path": "/api/world-drafts/{draftId}"
  },
  {
    "operationId": "WorldControlController_getMyAccess",
    "service": "World Control",
    "method": "GET",
    "path": "/api/world-control/access/me"
  },
  {
    "operationId": "WorldControlController_getState",
    "service": "World Control",
    "method": "GET",
    "path": "/api/worlds/{worldId}/state"
  },
  {
    "operationId": "WorldControlController_listDrafts",
    "service": "World Control",
    "method": "GET",
    "path": "/api/world-drafts"
  },
  {
    "operationId": "WorldControlController_listMyWorlds",
    "service": "World Control",
    "method": "GET",
    "path": "/api/worlds/mine"
  },
  {
    "operationId": "WorldControlController_listWorldBindings",
    "service": "World Control",
    "method": "GET",
    "path": "/api/worlds/{worldId}/bindings"
  },
  {
    "operationId": "WorldControlController_listWorldHistory",
    "service": "World Control",
    "method": "GET",
    "path": "/api/worlds/{worldId}/history"
  },
  {
    "operationId": "WorldControlController_listWorldLorebooks",
    "service": "World Control",
    "method": "GET",
    "path": "/api/worlds/{worldId}/lorebooks"
  },
  {
    "operationId": "WorldControlController_publishDraft",
    "service": "World Control",
    "method": "POST",
    "path": "/api/world-drafts/{draftId}/publish"
  },
  {
    "operationId": "WorldControlController_resolveLanding",
    "service": "World Control",
    "method": "GET",
    "path": "/api/world-control/landing"
  },
  {
    "operationId": "WorldControlController_updateDraft",
    "service": "World Control",
    "method": "PATCH",
    "path": "/api/world-drafts/{draftId}"
  },
  {
    "operationId": "WorldController_getMainWorld",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/oasis"
  },
  {
    "operationId": "WorldController_getWorld",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}"
  },
  {
    "operationId": "WorldController_getWorldAgents",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/agents"
  },
  {
    "operationId": "WorldController_getWorldBindings",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/bindings"
  },
  {
    "operationId": "WorldController_getWorldDetailWithAgents",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/detail-with-agents"
  },
  {
    "operationId": "WorldController_getWorldHistory",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/history"
  },
  {
    "operationId": "WorldController_getWorldLevelAudits",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/level/audits"
  },
  {
    "operationId": "WorldController_getWorldLorebooks",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/lorebooks"
  },
  {
    "operationId": "WorldController_getWorldview",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world/by-id/{id}/worldview"
  },
  {
    "operationId": "WorldController_listWorlds",
    "service": "Worlds",
    "method": "GET",
    "path": "/api/world"
  },
  {
    "operationId": "WorldController_returnToMainWorld",
    "service": "Worlds",
    "method": "POST",
    "path": "/api/world/by-id/{id}/return"
  },
  {
    "operationId": "WorldController_transitToWorld",
    "service": "Worlds",
    "method": "POST",
    "path": "/api/world/by-id/{id}/transit"
  },
  {
    "operationId": "WorldRulesController_archiveRule",
    "service": "World Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/rules/{ruleId}/archive"
  },
  {
    "operationId": "WorldRulesController_checkPermission",
    "service": "World Rules",
    "method": "GET",
    "path": "/api/world/by-id/{worldId}/rules/check/{action}"
  },
  {
    "operationId": "WorldRulesController_createRule",
    "service": "World Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/rules"
  },
  {
    "operationId": "WorldRulesController_deprecateRule",
    "service": "World Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/rules/{ruleId}/deprecate"
  },
  {
    "operationId": "WorldRulesController_getCreatorCapabilities",
    "service": "World Rules",
    "method": "GET",
    "path": "/api/world/by-id/{worldId}/rules/capabilities"
  },
  {
    "operationId": "WorldRulesController_getRules",
    "service": "World Rules",
    "method": "GET",
    "path": "/api/world/by-id/{worldId}/rules"
  },
  {
    "operationId": "WorldRulesController_updateRule",
    "service": "World Rules",
    "method": "PATCH",
    "path": "/api/world/by-id/{worldId}/rules/{ruleId}"
  },
  {
    "operationId": "WorldRulesController_validateRules",
    "service": "World Rules",
    "method": "POST",
    "path": "/api/world/by-id/{worldId}/rules/validate"
  }
] as const;

export const REALM_OPERATION_BY_ID: ReadonlyMap<string, RealmOperationDescriptor> = new Map(
  REALM_OPERATIONS.map((operation) => [operation.operationId, operation]),
);

const REALM_TYPED_FACADE_ONLY_OPERATION_IDS = new Set([
  'commitRealmGroupMessageCandidate',
]);

export interface RealmCallOptions {
  readonly metadata?: CoreMetadata;
  readonly timeoutMs?: number;
  readonly signal?: AbortSignal;
}

export class RealmGeneratedClient {
  constructor(private readonly core: CoreClient) {}

  describe(operationId: string): RealmOperationDescriptor {
    const descriptor = REALM_OPERATION_BY_ID.get(operationId);
    if (!descriptor) {
      throw Object.assign(new Error(`unknown Realm operation: ${operationId}`), {
        code: 'SDK_REALM_CONFIG_INVALID',
      });
    }
    return descriptor;
  }

  async operation<Response = unknown, Body = unknown>(operationId: string, body: Body, options: RealmCallOptions = {}): Promise<Response> {
    this.describe(operationId);
    if (REALM_TYPED_FACADE_ONLY_OPERATION_IDS.has(operationId)) {
      throw Object.assign(new Error(`Realm operation requires its admitted typed facade: ${operationId}`), {
        code: 'SDK_REALM_OPERATION_TYPED_FACADE_REQUIRED',
      });
    }
    return this.core.unary<Response, Body>({
      methodId: operationId,
      body,
      metadata: options.metadata,
      timeoutMs: options.timeoutMs,
      signal: options.signal,
    });
  }

}
