// Code generated by scripts/generate-runtime-realm-broker-policy.mjs; DO NOT EDIT.

package account

import runtimev1 "github.com/nimiplatform/nimi/runtime/gen/runtime/v1"

var realmBrokerOperations = map[string]realmUnaryOperation{
	"WorldCoreController_createSourceMaterializationPacket": {
		method: "POST",
		path:   "/api/realm/core/source-materialization-packets",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{},
		requiredPathParameters: map[string]struct{}{},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     true,
		requestBodyRequired:    true,
		responseMaxBytes:       524288,
	},
	"WorldCoreController_getRealmPersona": {
		method: "GET",
		path:   "/api/realm/core/personas/{personaId}",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{"personaId": {}},
		requiredPathParameters: map[string]struct{}{"personaId": {}},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldCoreController_getWorldCharacter": {
		method: "GET",
		path:   "/api/realm/core/world-characters/{characterId}",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{"characterId": {}},
		requiredPathParameters: map[string]struct{}{"characterId": {}},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldCoreController_getWorldEntity": {
		method: "GET",
		path:   "/api/realm/core/world-entities/{entityId}",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{"entityId": {}},
		requiredPathParameters: map[string]struct{}{"entityId": {}},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldCoreController_listRealmPersonas": {
		method: "GET",
		path:   "/api/realm/core/personas",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{},
		requiredPathParameters: map[string]struct{}{},
		allowedQueryParameters: map[string]struct{}{"take": {}, "visibility": {}},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldCoreController_listWorldRelationships": {
		method: "GET",
		path:   "/api/realm/core/worlds/{worldId}/relationships",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{"worldId": {}},
		requiredPathParameters: map[string]struct{}{"worldId": {}},
		allowedQueryParameters: map[string]struct{}{"take": {}, "afterId": {}, "type": {}, "targetEntityId": {}, "sourceEntityId": {}, "entityId": {}},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldPublicController_getWorld": {
		method: "GET",
		path:   "/api/world/by-id/{worldId}",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{"worldId": {}},
		requiredPathParameters: map[string]struct{}{"worldId": {}},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldPublicController_getWorldDetailWithCharacters": {
		method: "GET",
		path:   "/api/world/by-id/{worldId}/detail-with-characters",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{"worldId": {}},
		requiredPathParameters: map[string]struct{}{"worldId": {}},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
	"WorldPublicController_listWorlds": {
		method: "GET",
		path:   "/api/world",
		allowedCallerModes: map[runtimev1.AccountCallerMode]struct{}{
			runtimev1.AccountCallerMode_ACCOUNT_CALLER_MODE_DESKTOP_SHELL: {},
		},
		authorizationProfile:   "protected_desktop_source_readiness",
		allowedPathParameters:  map[string]struct{}{},
		requiredPathParameters: map[string]struct{}{},
		allowedQueryParameters: map[string]struct{}{},
		requestBodyAllowed:     false,
		requestBodyRequired:    false,
		responseMaxBytes:       1048576,
	},
}
