// Code generated by scripts/generate-runtime-realm-broker-policy.mjs; DO NOT EDIT.

export const NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_IDS = [
  "WorldPublicController_getCharacterSource",
  "WorldCoreController_getPersonaCharacter",
  "WorldCoreController_getWorldCharacter",
  "WorldCoreController_getWorldEntity",
  "WorldCoreController_listPersonaCharacters",
  "WorldCoreController_discoverPersonaCharacters",
  "WorldCoreController_listWorldRelationships",
  "WorldPublicController_getWorld",
  "WorldPublicController_getWorldDetailWithCharacters",
  "WorldPublicController_listWorlds",
] as const;

export type NimiDesktopSourceReadinessRealmOperationID =
  typeof NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_IDS[number];

const NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_ID_SET: ReadonlySet<string> =
  new Set(NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_IDS);

export function isNimiDesktopSourceReadinessRealmOperationID(
  value: string,
): value is NimiDesktopSourceReadinessRealmOperationID {
  return NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_ID_SET.has(value.trim());
}

export const NIMI_DESKTOP_PRODUCT_REALM_OPERATION_IDS = [
  "WorldPublicController_getCharacterSource",
  "WorldCoreController_getPersonaCharacter",
  "WorldCoreController_getWorldCharacter",
  "WorldCoreController_getWorldEntity",
  "WorldCoreController_listPersonaCharacters",
  "WorldCoreController_discoverPersonaCharacters",
  "WorldCoreController_listWorldRelationships",
  "WorldPublicController_getWorld",
  "WorldPublicController_getWorldDetailWithCharacters",
  "WorldPublicController_listWorlds",
  "WorldPublicController_listWorldCharacters",
  "getMe",
  "updateMe",
  "listMyFriendsWithDetails",
  "getMyPendingFriendRequests",
  "getMyBlockedUsers",
  "getUser",
  "addFriend",
  "removeFriend",
  "blockUser",
  "unblockUser",
  "getHomeFeed",
  "getExploreFeed",
  "listLikedPosts",
  "getPost",
  "createPost",
  "deletePost",
  "updatePost",
  "likePost",
  "unlikePost",
  "ReportController_createReport",
  "getChatById",
  "listChats",
  "listMessages",
  "markChatRead",
  "sendMessage",
  "startChat",
  "syncChatEvents",
  "getUnreadCount",
  "listNotifications",
  "markNotificationRead",
  "markNotificationsRead",
  "getMyCreatorEligibility",
  "getMyNotificationSettings",
  "getMySettings",
  "updateMyNotificationSettings",
  "updateMySettings",
  "updatePassword",
  "prepare2Fa",
  "enable2Fa",
  "disable2Fa",
  "EconomyController_canWithdraw",
  "EconomyController_createSparkCheckout",
  "EconomyController_createWithdrawal",
  "EconomyController_getBalances",
  "EconomyController_getGemHistory",
  "EconomyController_getSparkHistory",
  "EconomyController_getSparkPackages",
  "EconomyController_getSubscription",
  "EconomyController_getWithdrawalHistory",
] as const;

export type NimiDesktopProductRealmOperationID =
  typeof NIMI_DESKTOP_PRODUCT_REALM_OPERATION_IDS[number];

const NIMI_DESKTOP_PRODUCT_REALM_OPERATION_ID_SET: ReadonlySet<string> =
  new Set(NIMI_DESKTOP_PRODUCT_REALM_OPERATION_IDS);

export function isNimiDesktopProductRealmOperationID(
  value: string,
): value is NimiDesktopProductRealmOperationID {
  return NIMI_DESKTOP_PRODUCT_REALM_OPERATION_ID_SET.has(value.trim());
}

export const NIMI_BUNDLED_AVATAR_REALM_OPERATION_ID = "WorldCoreController_listPersonaCharacters" as const;
