// Code generated by scripts/generate-runtime-realm-broker-policy.mjs; DO NOT EDIT.

export const NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_IDS = [
  "WorldCoreController_getPersonaCharacter",
  "WorldCoreController_getWorldCharacter",
  "WorldCoreController_getWorldEntity",
  "WorldCoreController_listPersonaCharacters",
  "WorldCoreController_discoverPersonaCharacters",
  "WorldCoreController_listWorldRelationships",
  "WorldPublicController_getWorld",
  "WorldPublicController_getWorldDetailWithCharacters",
  "WorldPublicController_listWorlds",
] as const;

export type NimiDesktopSourceReadinessRealmOperationID =
  typeof NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_IDS[number];

const NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_ID_SET: ReadonlySet<string> =
  new Set(NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_IDS);

export function isNimiDesktopSourceReadinessRealmOperationID(
  value: string,
): value is NimiDesktopSourceReadinessRealmOperationID {
  return NIMI_DESKTOP_SOURCE_READINESS_REALM_OPERATION_ID_SET.has(value.trim());
}

export const NIMI_BUNDLED_AVATAR_REALM_OPERATION_ID = "WorldCoreController_listPersonaCharacters" as const;
