export const E2E_IDS = {
  appLoadingScreen: 'app-loading-screen',
  appBootstrapErrorScreen: 'app-bootstrap-error-screen',
  loginScreen: 'login-screen',
  loginLogoTrigger: 'login-logo-trigger',
  loginEmailInput: 'login-email-input',
  loginAlternativeToggle: 'login-alternative-toggle',
  loginAlternativePanel: 'login-alternative-panel',
  loginPasswordInput: 'login-password-input',
  loginEmailSubmitArrow: 'login-email-submit-arrow',
  loginOtpButton: 'login-otp-button',
  mainShell: 'main-shell',
  shellSidebarRail: 'shell-sidebar-rail',
  desktopReleaseStrip: 'desktop-release-strip',
  desktopReleaseOpenUpdates: 'desktop-release-open-updates',
  offlineStrip: 'offline-strip',
  panel: (name: string) => `panel:${name}`,
  navTab: (tabId: string) => `nav-tab:${tabId}`,
  runtimeSidebarPage: (pageId: string) => `runtime-sidebar:${pageId}`,
  runtimePageRoot: (pageId: string) => `runtime-page:${pageId}`,
  chatList: 'chat-list',
  chatRow: (chatId: string) => `chat-row:${chatId}`,
  chatHeaderProfileToggle: 'chat-header-profile-toggle',
  chatOpenUserProfile: 'chat-open-user-profile',
  messageTimeline: 'message-timeline',
  feedPostAuthor: (postId: string) => `feed-post-author:${postId}`,
  contactDetailProfileModal: 'contact-detail-profile-modal',
  contactDetailProfileModalClose: 'contact-detail-profile-modal-close',
  profileDetailSurface: 'profile-detail-surface',
  exploreQuickAddFriendDialog: 'explore-quick-add-friend-dialog',
  contactsBlockConfirmDialog: 'contacts-block-confirm-dialog',
  contactsUnblockConfirmDialog: 'contacts-unblock-confirm-dialog',
  notificationRejectGiftDialog: 'notification-reject-gift-dialog',
  sendGiftDialog: 'send-gift-dialog',
  createPostDialog: 'create-post-dialog',
  createPostEmojiPanel: 'create-post-emoji-panel',
  createPostLocationPanel: 'create-post-location-panel',
  createPostTagPanel: 'create-post-tag-panel',
  profileTopSupportersDialog: 'profile-top-supporters-dialog',
} as const;
