import {
  DISABLED_PERSONA_ID,
  OWNER_USER_ID,
  VALID_PERSONA_ID,
  VALID_SOURCE_REF,
} from './acceptance-constants.mjs';

export function createRealmFixtureManifest(origin) {
  const longChineseName = '青屿档案馆的长名伙伴-会整理星图、记忆线索与每日对话节奏的角色';
  const longChineseSummary = '这是一个用于真实 Desktop Explore 验收的长中文简介。她会在具体 persona 语境下成为伙伴，文本足够长以覆盖窄屏换行、按钮可用性和中文可读性，不允许把 Runtime LocalAgent 暴露成用户创建对象。';
  return {
    scenarioId: 'desktop.explore.persona-materialization.acceptance',
    realmFixture: {
      restOnline: true,
      currentUser: {
        id: OWNER_USER_ID,
        displayName: '验收用户',
        handle: '@acceptance-user',
        email: 'acceptance@nimi.local',
        avatarUrl: '',
      },
      chats: { items: [] },
      messagesByChatId: {},
      groupChats: { items: [] },
      economyBalances: { sparkBalance: 0, gemBalance: 0, currency: 'NIMI' },
      subscription: {
        id: 'subscription-acceptance-free',
        tier: 'FREE',
        status: 'ACTIVE',
        cancelAtPeriodEnd: false,
        currentPeriodStart: null,
        currentPeriodEnd: null,
        tierConfig: { tier: 'FREE', priceUsd: 0, features: [] },
      },
      notificationUnreadCount: { unreadCount: 0 },
      friends: { items: [] },
      pendingFriends: { received: [], sent: [] },
      blocked: { items: [] },
      creatorCharacters: [],
      worlds: [{
        id: VALID_SOURCE_REF.worldId,
        name: '青屿验收世界',
        summary: '用于 Desktop Explore persona materialization 真实链路验收。',
        description: '用于 Desktop Explore persona materialization 真实链路验收。',
        visibility: 'system',
        tags: ['验收', '伙伴', 'Persona'],
        media: { iconUrl: null, bannerUrl: null, heroUrl: null, highlightUrls: [] },
        stats: {
          characterCount: 0,
          personaCount: 2,
          sceneCount: 1,
          systemCount: 1,
          timelineEventCount: 1,
        },
        rules: ['Materialization must be Runtime-mediated.'],
        systems: ['Partner relationship acceptance system'],
        scenes: ['Explore persona acceptance'],
        timeline: ['Persona admitted'],
        type: 'OASIS',
        status: 'DISCOVERABLE',
        createdAt: '2026-03-15T00:00:00.000Z',
        updatedAt: '2026-03-15T00:00:00.000Z',
        computed: {
          time: {
            currentWorldTime: '2026-03-15T00:00:00.000Z',
            currentLabel: '验收时刻',
            eraLabel: '青屿纪元',
            flowRatio: 1,
            isPaused: false,
          },
          score: { scoreEwma: 91 },
          featuredCharacterCount: 0,
        },
        characters: [],
        personas: [{
          id: VALID_PERSONA_ID,
          worldId: VALID_SOURCE_REF.worldId,
          sourceRef: VALID_SOURCE_REF,
          contentHash: VALID_SOURCE_REF.sourceContentHash,
          displayName: longChineseName,
          handle: '~qingyu-acceptance-partner',
          summary: longChineseSummary,
          role: '档案伙伴',
          archetype: '记忆整理者',
          pacing: 'calm',
          origin: { kind: 'manual', sourceId: VALID_PERSONA_ID, sourceContentHash: VALID_SOURCE_REF.sourceContentHash },
          tags: ['中文长文', '关系建立', '伙伴'],
          media: { avatarUrl: null, profileCoverUrl: null },
          relation: { state: 'connectable', connectionId: null },
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        }, {
          id: DISABLED_PERSONA_ID,
          worldId: VALID_SOURCE_REF.worldId,
          omitContentHash: true,
          materializationUnavailable: true,
          displayName: '缺失来源哈希的伙伴候选',
          handle: '~missing-hash-persona',
          summary: '这个 persona 故意缺失 contentHash，用于验证 CTA fail-closed disabled 状态和中文可读失败态。',
          role: '不可 materialize 的候选',
          archetype: 'missing-source-hash',
          pacing: 'calm',
          origin: { kind: 'manual', sourceId: DISABLED_PERSONA_ID, sourceContentHash: '' },
          tags: ['失败态', '禁用态'],
          createdAt: '2026-03-15T00:00:00.000Z',
          updatedAt: '2026-03-15T00:00:00.000Z',
        }],
        events: [],
        levelAudits: [],
        worldview: {},
        worldviewEvents: [],
        worldviewSnapshots: [],
      }],
      searchUsers: { items: [] },
      exploreFeed: { items: [] },
      postFeed: { items: [] },
    },
    tauriFixture: {
      runtimeDefaults: {
        realm: {
          realmBaseUrl: origin,
          realtimeUrl: origin,
          accessToken: 'desktop-acceptance-access-token',
          jwksUrl: `${origin}/api/auth/jwks`,
          revocationUrl: `${origin}/api/auth/sessions/introspect`,
          jwtIssuer: origin,
          jwtAudience: 'nimi-runtime',
        },
      },
    },
  };
}
