// Code generated by scripts/generate-runtime-connector-auth-profiles.mjs. DO NOT EDIT.

package connector

type ProviderAuthProfileSpec struct {
	ID string
	AuthKind string
	AllowedProviders []string
	HeaderBehavior string
}

var GeneratedProviderAuthProfiles = map[string]ProviderAuthProfileSpec{
	"anthropic": {
		ID: "anthropic",
		AuthKind: "oauth_managed",
		AllowedProviders: []string{
			"anthropic",
		},
		HeaderBehavior: "anthropic",
	},
	"openai_codex": {
		ID: "openai_codex",
		AuthKind: "oauth_managed",
		AllowedProviders: []string{
			"openai_codex",
		},
		HeaderBehavior: "codex_oauth",
	},
	"qwen_oauth": {
		ID: "qwen_oauth",
		AuthKind: "oauth_managed",
		AllowedProviders: []string{
			"openai_compatible",
		},
		HeaderBehavior: "none",
	},
}
