package main

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"os/signal"
	"path/filepath"
	"sort"
	"strings"
	"syscall"
	"time"
)

func runRuntimeModCreate(args []string) error {
	fs := flag.NewFlagSet("nimi mod create", flag.ContinueOnError)
	fs.SetOutput(os.Stdout)
	dirRaw := fs.String("dir", ".", "target directory")
	name := fs.String("name", "My Mod", "display name")
	modID := fs.String("mod-id", "", "mod id, e.g. world.nimi.my-mod")
	jsonOutput := fs.Bool("json", false, "output json")
	if err := fs.Parse(args); err != nil {
		return err
	}

	dir, err := filepath.Abs(strings.TrimSpace(*dirRaw))
	if err != nil {
		return err
	}
	if err := ensureDirEmptyOrMissing(dir); err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Join(dir, "src"), 0o755); err != nil {
		return fmt.Errorf("create src dir: %w", err)
	}

	normalizedName := strings.TrimSpace(*name)
	if normalizedName == "" {
		normalizedName = "My Mod"
	}
	normalizedID := strings.TrimSpace(*modID)
	if normalizedID == "" {
		normalizedID = "world.nimi." + slugify(normalizedName)
	}
	manifest := normalizeManifest(modManifest{
		ID:           normalizedID,
		Name:         normalizedName,
		Version:      "0.1.0",
		Description:  "Generated by nimi mod create",
		License:      "MIT",
		Capabilities: []string{"runtime.ai.text.generate"},
	}, dir)

	if err := writeManifestYAML(filepath.Join(dir, "mod.manifest.yaml"), manifest); err != nil {
		return fmt.Errorf("write manifest: %w", err)
	}

	packageJSON := map[string]any{
		"name":    slugify(manifest.Name),
		"private": true,
		"type":    "module",
		"version": manifest.Version,
		"scripts": map[string]any{
			"build": "nimi mod build --dir .",
			"dev":   "nimi mod dev --dir . --watch",
		},
	}
	if err := writeJSONFile(filepath.Join(dir, "package.json"), packageJSON); err != nil {
		return fmt.Errorf("write package.json: %w", err)
	}

	tsconfig := map[string]any{
		"compilerOptions": map[string]any{
			"target":           "ES2022",
			"module":           "ESNext",
			"moduleResolution": "Bundler",
			"strict":           true,
			"noEmit":           false,
			"outDir":           "dist",
		},
		"include": []string{"src/**/*.ts"},
	}
	if err := writeJSONFile(filepath.Join(dir, "tsconfig.json"), tsconfig); err != nil {
		return fmt.Errorf("write tsconfig.json: %w", err)
	}

	source := fmt.Sprintf("export const modId = '%s';\n\nexport function setup() {\n  return { ok: true, modId };\n}\n", manifest.ID)
	if err := os.WriteFile(filepath.Join(dir, "src", "index.ts"), []byte(source), 0o644); err != nil {
		return fmt.Errorf("write src/index.ts: %w", err)
	}

	if *jsonOutput {
		return writeJSON(map[string]any{
			"ok":       true,
			"mod_id":   manifest.ID,
			"name":     manifest.Name,
			"dir":      dir,
			"manifest": filepath.Join(dir, "mod.manifest.yaml"),
		})
	}

	fmt.Printf("created mod scaffold at %s (mod_id=%s)\n", dir, manifest.ID)
	return nil
}

func runRuntimeModDev(args []string) error {
	fs := flag.NewFlagSet("nimi mod dev", flag.ContinueOnError)
	fs.SetOutput(os.Stdout)
	dirRaw := fs.String("dir", ".", "mod project directory")
	watch := fs.Bool("watch", false, "watch source and rebuild on change")
	intervalRaw := fs.String("interval", "1500ms", "watch polling interval")
	jsonOutput := fs.Bool("json", false, "output json")
	if err := fs.Parse(args); err != nil {
		return err
	}

	dir, err := filepath.Abs(strings.TrimSpace(*dirRaw))
	if err != nil {
		return err
	}

	bundlePath, hash, _, err := buildModBundle(dir)
	if err != nil {
		return err
	}

	if !*watch {
		if *jsonOutput {
			return writeJSON(map[string]any{
				"ok":          true,
				"mode":        "oneshot",
				"dir":         dir,
				"bundle_path": bundlePath,
				"bundle_hash": "sha256:" + hash,
			})
		}
		fmt.Printf("dev build complete: %s (sha256:%s)\n", bundlePath, hash)
		return nil
	}

	interval, err := time.ParseDuration(*intervalRaw)
	if err != nil {
		return fmt.Errorf("parse interval: %w", err)
	}
	if interval < 200*time.Millisecond {
		interval = 200 * time.Millisecond
	}

	sourcePath, err := resolvePrimarySourceFile(dir)
	if err != nil {
		return err
	}
	currentSourceHash, err := readSHA256Hex(sourcePath)
	if err != nil {
		return err
	}

	if *jsonOutput {
		_ = writeJSON(map[string]any{
			"ok":          true,
			"mode":        "watch",
			"dir":         dir,
			"bundle_path": bundlePath,
			"bundle_hash": "sha256:" + hash,
			"source":      sourcePath,
			"interval":    interval.String(),
		})
	} else {
		fmt.Printf("watching %s every %s\n", sourcePath, interval)
	}

	ticker := time.NewTicker(interval)
	defer ticker.Stop()
	sigCh := make(chan os.Signal, 1)
	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
	defer signal.Stop(sigCh)

	for {
		select {
		case <-sigCh:
			return nil
		case <-ticker.C:
			nextHash, hashErr := readSHA256Hex(sourcePath)
			if hashErr != nil {
				continue
			}
			if nextHash == currentSourceHash {
				continue
			}
			currentSourceHash = nextHash
			bundlePath, hash, _, err = buildModBundle(dir)
			if err != nil {
				fmt.Fprintf(os.Stderr, "rebuild failed: %v\n", err)
				continue
			}
			if *jsonOutput {
				_ = writeJSON(map[string]any{
					"ok":          true,
					"event":       "rebuilt",
					"bundle_path": bundlePath,
					"bundle_hash": "sha256:" + hash,
				})
			} else {
				fmt.Printf("rebuilt: %s (sha256:%s)\n", bundlePath, hash)
			}
		}
	}
}

func runRuntimeModBuild(args []string) error {
	fs := flag.NewFlagSet("nimi mod build", flag.ContinueOnError)
	fs.SetOutput(os.Stdout)
	dirRaw := fs.String("dir", ".", "mod project directory")
	jsonOutput := fs.Bool("json", false, "output json")
	if err := fs.Parse(args); err != nil {
		return err
	}

	dir, err := filepath.Abs(strings.TrimSpace(*dirRaw))
	if err != nil {
		return err
	}

	bundlePath, hash, bytesWritten, err := buildModBundle(dir)
	if err != nil {
		return err
	}

	if *jsonOutput {
		return writeJSON(map[string]any{
			"ok":            true,
			"dir":           dir,
			"bundle_path":   bundlePath,
			"bundle_hash":   "sha256:" + hash,
			"bytes_written": bytesWritten,
		})
	}

	fmt.Printf("built mod bundle: %s (sha256:%s)\n", bundlePath, hash)
	return nil
}

func runRuntimeModPublish(args []string) error {
	fs := flag.NewFlagSet("nimi mod publish", flag.ContinueOnError)
	fs.SetOutput(os.Stdout)
	dirRaw := fs.String("dir", ".", "mod project directory")
	sourceRepoRaw := fs.String("source-repo", "", "source mod repo owner/name")
	author := fs.String("author", strings.TrimSpace(os.Getenv("GITHUB_ACTOR")), "mod author")
	modCircleRepoRaw := fs.String("mod-circle-repo", defaultModCircleRepo, "mod circle repo owner/name")
	base := fs.String("base", "main", "base branch")
	branchPrefix := fs.String("branch-prefix", "nimi-mod", "publish branch prefix")
	title := fs.String("title", "", "pull request title")
	body := fs.String("body", "", "pull request body")
	apiBase := fs.String("api-base", resolveGitHubAPIBase(), "GitHub API base URL")
	tokenRaw := fs.String("token", "", "GitHub token (default: $GITHUB_TOKEN)")
	jsonOutput := fs.Bool("json", false, "output json")
	if err := fs.Parse(args); err != nil {
		return err
	}

	dir, err := filepath.Abs(strings.TrimSpace(*dirRaw))
	if err != nil {
		return err
	}
	sourceRepo := strings.TrimSpace(*sourceRepoRaw)
	if sourceRepo == "" {
		return fmt.Errorf("MOD_PUBLISH_SOURCE_REPO_REQUIRED: actionHint=pass_--source-repo_owner_repo")
	}
	if _, _, _, err := parseGitHubRepoReference(sourceRepo); err != nil {
		return fmt.Errorf("invalid source-repo: %w", err)
	}

	token := strings.TrimSpace(*tokenRaw)
	if token == "" {
		token = strings.TrimSpace(os.Getenv("GITHUB_TOKEN"))
	}
	if token == "" {
		return fmt.Errorf("MOD_PUBLISH_GITHUB_TOKEN_MISSING: actionHint=export_GITHUB_TOKEN_then_retry")
	}

	manifest, err := loadManifest(dir)
	if err != nil {
		return fmt.Errorf("load manifest: %w", err)
	}
	manifest = normalizeManifest(manifest, dir)

	_, bundleHash, _, err := buildModBundle(dir)
	if err != nil {
		return err
	}

	entry := map[string]any{
		"id":                manifest.ID,
		"name":              manifest.Name,
		"description":       manifest.Description,
		"author":            defaultString(strings.TrimSpace(*author), "unknown"),
		"repo":              "github:" + normalizeGitHubRepoToken(sourceRepo),
		"minDesktopVersion": "0.1.0",
		"capabilities":      manifest.Capabilities,
		"tags":              []string{},
		"license":           manifest.License,
		"verified":          false,
		"addedAt":           time.Now().UTC().Format("2006-01-02"),
	}
	entryRaw, err := json.MarshalIndent(entry, "", "  ")
	if err != nil {
		return err
	}

	owner, repo, _, err := parseGitHubRepoReference(*modCircleRepoRaw)
	if err != nil {
		return fmt.Errorf("invalid mod-circle-repo: %w", err)
	}

	prefix := strings.Trim(strings.TrimSpace(*branchPrefix), "/")
	if prefix == "" {
		prefix = "nimi-mod"
	}
	branch := fmt.Sprintf("%s/%s-%d", prefix, slugify(manifest.ID), time.Now().UTC().Unix())
	indexPath := fmt.Sprintf("mods/%s.json", manifest.ID)

	client := newGitHubRESTClient(strings.TrimSpace(*apiBase), token)
	ctx, cancel := context.WithTimeout(context.Background(), 30*time.Second)
	defer cancel()

	baseSHA, err := client.getBranchSHA(ctx, owner, repo, strings.TrimSpace(*base))
	if err != nil {
		return err
	}
	if err := client.createBranch(ctx, owner, repo, branch, baseSHA); err != nil {
		return err
	}
	if err := client.putFile(ctx, owner, repo, indexPath, branch, "mod: add "+manifest.ID, entryRaw); err != nil {
		return err
	}

	prTitle := strings.TrimSpace(*title)
	if prTitle == "" {
		prTitle = fmt.Sprintf("mod: add %s", manifest.ID)
	}
	prBody := strings.TrimSpace(*body)
	if prBody == "" {
		prBody = fmt.Sprintf("source repo: github:%s\nmanifest: %s\nbundle hash: sha256:%s", normalizeGitHubRepoToken(sourceRepo), manifest.ID, bundleHash)
	}

	pr, err := client.createPullRequest(ctx, owner, repo, prTitle, branch, strings.TrimSpace(*base), prBody)
	if err != nil {
		return err
	}

	result := modPublishResult{
		Repo:       owner + "/" + repo,
		Branch:     branch,
		PRNumber:   pr.Number,
		PRURL:      pr.HTMLURL,
		IndexPath:  indexPath,
		BundleHash: "sha256:" + bundleHash,
	}

	if *jsonOutput {
		return writeJSON(result)
	}
	fmt.Printf("created mod circle PR: #%d %s\n", result.PRNumber, result.PRURL)
	return nil
}

func resolveModsDir(raw string) (string, error) {
	if value := strings.TrimSpace(raw); value != "" {
		return filepath.Clean(value), nil
	}
	if value := strings.TrimSpace(os.Getenv("NIMI_RUNTIME_MODS_DIR")); value != "" {
		return filepath.Clean(value), nil
	}
	return "", fmt.Errorf("MODS_DIR_REQUIRED: actionHint=set_--mods-dir_or_NIMI_RUNTIME_MODS_DIR")
}

func resolveGitHubAPIBase() string {
	if value := strings.TrimSpace(os.Getenv("GITHUB_API_URL")); value != "" {
		return value
	}
	return defaultGitHubAPIBase
}

func listInstalledMods(modsDir string) ([]modListItem, error) {
	entries, err := os.ReadDir(modsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return []modListItem{}, nil
		}
		return nil, fmt.Errorf("read mods dir: %w", err)
	}

	items := make([]modListItem, 0, len(entries))
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		modPath := filepath.Join(modsDir, entry.Name())
		manifest, err := loadManifest(modPath)
		if err != nil {
			manifest = normalizeManifest(modManifest{Name: titleFromSlug(entry.Name())}, modPath)
		}
		metadata := readInstallMetadata(modPath)
		items = append(items, modListItem{
			ModID:        manifest.ID,
			Name:         manifest.Name,
			Version:      manifest.Version,
			Path:         modPath,
			Source:       metadata.Source,
			InstalledAt:  metadata.InstalledAt,
			Verified:     metadata.Verified,
			Capabilities: append([]string(nil), manifest.Capabilities...),
		})
	}

	sort.Slice(items, func(i, j int) bool {
		return items[i].ModID < items[j].ModID
	})
	return items, nil
}

func readInstallMetadata(modPath string) modInstallMetadata {
	path := filepath.Join(modPath, ".nimi-install.json")
	raw, err := os.ReadFile(path)
	if err != nil {
		return modInstallMetadata{}
	}
	var metadata modInstallMetadata
	if err := json.Unmarshal(raw, &metadata); err != nil {
		return modInstallMetadata{}
	}
	return metadata
}

func ensureDirEmptyOrMissing(dir string) error {
	entries, err := os.ReadDir(dir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil
		}
		return err
	}
	if len(entries) > 0 {
		return fmt.Errorf("directory is not empty: %s", dir)
	}
	return nil
}
