package main

import (
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"strings"
	"time"
)

func buildModBundle(modDir string) (string, string, int, error) {
	if _, err := os.Stat(modDir); err != nil {
		return "", "", 0, fmt.Errorf("mod dir not found: %w", err)
	}
	manifest, err := loadManifest(modDir)
	if err != nil {
		return "", "", 0, fmt.Errorf("manifest required: %w", err)
	}
	manifest = normalizeManifest(manifest, modDir)

	sourcePath, err := resolvePrimarySourceFile(modDir)
	if err != nil {
		return "", "", 0, err
	}
	sourceRaw, err := os.ReadFile(sourcePath)
	if err != nil {
		return "", "", 0, fmt.Errorf("read source file: %w", err)
	}

	distDir := filepath.Join(modDir, "dist")
	if err := os.MkdirAll(distDir, 0o755); err != nil {
		return "", "", 0, fmt.Errorf("create dist dir: %w", err)
	}
	bundlePath := filepath.Join(distDir, "index.js")
	bundleRaw := []byte("// generated by nimi mod build\n" + string(sourceRaw))
	if err := os.WriteFile(bundlePath, bundleRaw, 0o644); err != nil {
		return "", "", 0, fmt.Errorf("write bundle: %w", err)
	}

	sum := sha256.Sum256(bundleRaw)
	hash := fmt.Sprintf("%x", sum[:])
	if err := updateManifestHash(modDir, hash); err != nil {
		return "", "", 0, fmt.Errorf("update manifest hash: %w", err)
	}

	buildMeta := map[string]any{
		"mod_id":      manifest.ID,
		"built_at":    time.Now().UTC().Format(time.RFC3339Nano),
		"bundle_path": bundlePath,
		"bundle_hash": "sha256:" + hash,
	}
	if err := writeJSONFile(filepath.Join(modDir, ".nimi-build.json"), buildMeta); err != nil {
		return "", "", 0, fmt.Errorf("write build metadata: %w", err)
	}

	return bundlePath, hash, len(bundleRaw), nil
}

func resolvePrimarySourceFile(modDir string) (string, error) {
	candidates := []string{
		filepath.Join(modDir, "src", "index.ts"),
		filepath.Join(modDir, "src", "main.ts"),
		filepath.Join(modDir, "index.ts"),
	}
	for _, candidate := range candidates {
		if info, err := os.Stat(candidate); err == nil && !info.IsDir() {
			return candidate, nil
		}
	}
	return "", fmt.Errorf("mod source file not found (expected src/index.ts)")
}

func loadManifest(modDir string) (modManifest, error) {
	jsonPath := filepath.Join(modDir, "mod.manifest.json")
	if raw, err := os.ReadFile(jsonPath); err == nil {
		manifest, parseErr := parseManifestJSON(raw)
		if parseErr != nil {
			return modManifest{}, parseErr
		}
		return normalizeManifest(manifest, modDir), nil
	}

	yamlCandidates := []string{
		filepath.Join(modDir, "mod.manifest.yaml"),
		filepath.Join(modDir, "mod.manifest.yml"),
	}
	for _, candidate := range yamlCandidates {
		if raw, err := os.ReadFile(candidate); err == nil {
			manifest := parseManifestYAML(raw)
			return normalizeManifest(manifest, modDir), nil
		}
	}
	return modManifest{}, fmt.Errorf("manifest not found in %s", modDir)
}

func parseManifestJSON(raw []byte) (modManifest, error) {
	var payload map[string]any
	if err := json.Unmarshal(raw, &payload); err != nil {
		return modManifest{}, fmt.Errorf("parse mod.manifest.json: %w", err)
	}
	manifest := modManifest{
		ID:          asManifestString(payload["id"]),
		Name:        asManifestString(payload["name"]),
		Version:     asManifestString(payload["version"]),
		Description: asManifestString(payload["description"]),
		License:     asManifestString(payload["license"]),
	}
	manifest.Capabilities = asManifestStringSlice(payload["capabilities"])
	return manifest, nil
}

func parseManifestYAML(raw []byte) modManifest {
	lines := strings.Split(string(raw), "\n")
	manifest := modManifest{}
	capabilities := make([]string, 0)
	inCapabilities := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}

		if strings.HasPrefix(trimmed, "capabilities:") {
			inCapabilities = true
			continue
		}
		if inCapabilities {
			if strings.HasPrefix(trimmed, "-") {
				item := strings.TrimSpace(strings.TrimPrefix(trimmed, "-"))
				item = trimQuotes(item)
				if item != "" {
					capabilities = append(capabilities, item)
				}
				continue
			}
			if !strings.HasPrefix(line, " ") && !strings.HasPrefix(line, "\t") {
				inCapabilities = false
			}
		}

		key, value, ok := strings.Cut(trimmed, ":")
		if !ok {
			continue
		}
		key = strings.TrimSpace(key)
		value = trimQuotes(strings.TrimSpace(value))
		switch key {
		case "id":
			manifest.ID = value
		case "name":
			manifest.Name = value
		case "version":
			manifest.Version = value
		case "description":
			manifest.Description = value
		case "license":
			manifest.License = value
		}
	}

	manifest.Capabilities = capabilities
	return manifest
}

func normalizeManifest(manifest modManifest, modDir string) modManifest {
	fallbackName := titleFromSlug(filepath.Base(modDir))
	if strings.TrimSpace(manifest.Name) == "" {
		manifest.Name = fallbackName
	}
	if strings.TrimSpace(manifest.ID) == "" {
		manifest.ID = "world.nimi." + slugify(manifest.Name)
	}
	if strings.TrimSpace(manifest.Version) == "" {
		manifest.Version = "0.1.0"
	}
	if strings.TrimSpace(manifest.Description) == "" {
		manifest.Description = "Nimi mod"
	}
	if strings.TrimSpace(manifest.License) == "" {
		manifest.License = "MIT"
	}
	if manifest.Capabilities == nil {
		manifest.Capabilities = []string{}
	}
	return manifest
}

func writeManifestYAML(path string, manifest modManifest) error {
	manifest = normalizeManifest(manifest, filepath.Dir(path))
	lines := []string{
		"id: " + manifest.ID,
		"name: " + manifest.Name,
		"version: " + manifest.Version,
		"description: " + manifest.Description,
		"entry: ./dist/index.js",
		"license: " + manifest.License,
	}
	if len(manifest.Capabilities) > 0 {
		lines = append(lines, "capabilities:")
		for _, capability := range manifest.Capabilities {
			trimmed := strings.TrimSpace(capability)
			if trimmed == "" {
				continue
			}
			lines = append(lines, "  - "+trimmed)
		}
	}
	content := strings.Join(lines, "\n") + "\n"
	return os.WriteFile(path, []byte(content), 0o644)
}

func updateManifestHash(modDir string, hash string) error {
	jsonPath := filepath.Join(modDir, "mod.manifest.json")
	if raw, err := os.ReadFile(jsonPath); err == nil {
		var payload map[string]any
		if err := json.Unmarshal(raw, &payload); err != nil {
			return err
		}
		payload["hash"] = "sha256:" + hash
		return writeJSONFile(jsonPath, payload)
	}

	yamlCandidates := []string{
		filepath.Join(modDir, "mod.manifest.yaml"),
		filepath.Join(modDir, "mod.manifest.yml"),
	}
	for _, candidate := range yamlCandidates {
		raw, err := os.ReadFile(candidate)
		if err != nil {
			continue
		}
		lines := strings.Split(string(raw), "\n")
		replaced := false
		for idx, line := range lines {
			trimmed := strings.TrimSpace(line)
			if strings.HasPrefix(trimmed, "hash:") {
				lines[idx] = "hash: sha256:" + hash
				replaced = true
				break
			}
		}
		if !replaced {
			if len(lines) > 0 && strings.TrimSpace(lines[len(lines)-1]) == "" {
				lines = lines[:len(lines)-1]
			}
			lines = append(lines, "hash: sha256:"+hash)
		}
		updated := strings.Join(lines, "\n")
		if !strings.HasSuffix(updated, "\n") {
			updated += "\n"
		}
		return os.WriteFile(candidate, []byte(updated), 0o644)
	}
	return fmt.Errorf("manifest file not found for hash update")
}

func resolveExistingDir(value string) (string, bool) {
	trimmed := strings.TrimSpace(value)
	if trimmed == "" {
		return "", false
	}
	if strings.HasPrefix(trimmed, "github:") || strings.HasPrefix(trimmed, "https://github.com/") {
		return "", false
	}
	if strings.Contains(trimmed, "/") || strings.Contains(trimmed, "\\") {
		if info, err := os.Stat(trimmed); err == nil && info.IsDir() {
			abs, _ := filepath.Abs(trimmed)
			if abs != "" {
				return abs, true
			}
			return trimmed, true
		}
	}
	if info, err := os.Stat(trimmed); err == nil && info.IsDir() {
		abs, _ := filepath.Abs(trimmed)
		if abs != "" {
			return abs, true
		}
		return trimmed, true
	}
	return "", false
}

func copyDirectory(source string, destination string) error {
	return filepath.WalkDir(source, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(source, path)
		if err != nil {
			return err
		}
		targetPath := filepath.Join(destination, rel)
		if d.IsDir() {
			return os.MkdirAll(targetPath, 0o755)
		}
		if d.Type()&os.ModeSymlink != 0 {
			return nil
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(targetPath), 0o755); err != nil {
			return err
		}
		return os.WriteFile(targetPath, data, 0o644)
	})
}

func deriveInstallTargetName(source string) string {
	if localDir, ok := resolveExistingDir(source); ok {
		return slugify(filepath.Base(localDir))
	}
	if modCircleSelector, ok := parseModCircleInstallSelector(source); ok {
		return slugify(modCircleSelector)
	}
	owner, repo, subpath, err := parseGitHubRepoReference(source)
	if err != nil {
		return ""
	}
	if subpath != "" {
		parts := strings.Split(subpath, "/")
		last := strings.TrimSpace(parts[len(parts)-1])
		if last != "" {
			return slugify(last)
		}
	}
	if repo != "" {
		return slugify(repo)
	}
	return slugify(owner)
}

func parseGitHubRepoReference(raw string) (string, string, string, error) {
	normalized := normalizeGitHubRepoToken(raw)
	parts := strings.Split(normalized, "/")
	clean := make([]string, 0, len(parts))
	for _, part := range parts {
		trimmed := strings.TrimSpace(part)
		if trimmed == "" {
			continue
		}
		clean = append(clean, trimmed)
	}
	if len(clean) < 2 {
		return "", "", "", fmt.Errorf("invalid GitHub repo reference %q (expected owner/repo)", raw)
	}
	owner := clean[0]
	repo := strings.TrimSuffix(clean[1], ".git")
	subpath := ""
	if len(clean) > 2 {
		subpath = strings.Join(clean[2:], "/")
	}
	if owner == "" || repo == "" {
		return "", "", "", fmt.Errorf("invalid GitHub repo reference %q", raw)
	}
	return owner, repo, subpath, nil
}

func normalizeGitHubRepoToken(raw string) string {
	normalized := strings.TrimSpace(raw)
	normalized = strings.TrimPrefix(normalized, "github:")
	normalized = strings.TrimPrefix(normalized, "https://github.com/")
	normalized = strings.TrimPrefix(normalized, "http://github.com/")
	normalized = strings.TrimSuffix(normalized, ".git")
	normalized = strings.Trim(normalized, "/")
	return normalized
}

func writeJSON(value any) error {
	raw, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	fmt.Println(string(raw))
	return nil
}

func writeJSONFile(path string, value any) error {
	raw, err := json.MarshalIndent(value, "", "  ")
	if err != nil {
		return err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, raw, 0o644)
}

func readSHA256Hex(path string) (string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return "", err
	}
	sum := sha256.Sum256(raw)
	return fmt.Sprintf("%x", sum[:]), nil
}

func asManifestString(value any) string {
	switch v := value.(type) {
	case string:
		return strings.TrimSpace(v)
	default:
		return ""
	}
}

func asManifestStringSlice(value any) []string {
	items, ok := value.([]any)
	if !ok {
		if casted, ok := value.([]string); ok {
			out := make([]string, 0, len(casted))
			for _, item := range casted {
				trimmed := strings.TrimSpace(item)
				if trimmed == "" {
					continue
				}
				out = append(out, trimmed)
			}
			return out
		}
		return []string{}
	}
	out := make([]string, 0, len(items))
	for _, item := range items {
		trimmed := asManifestString(item)
		if trimmed == "" {
			continue
		}
		out = append(out, trimmed)
	}
	return out
}

func slugify(input string) string {
	trimmed := strings.ToLower(strings.TrimSpace(input))
	if trimmed == "" {
		return "mod"
	}
	replacer := strings.NewReplacer(
		" ", "-",
		"_", "-",
		"/", "-",
		"\\", "-",
		".", "-",
		":", "-",
	)
	trimmed = replacer.Replace(trimmed)
	builder := strings.Builder{}
	lastDash := false
	for _, char := range trimmed {
		if (char >= 'a' && char <= 'z') || (char >= '0' && char <= '9') {
			builder.WriteRune(char)
			lastDash = false
			continue
		}
		if !lastDash {
			builder.WriteRune('-')
			lastDash = true
		}
	}
	result := strings.Trim(builder.String(), "-")
	if result == "" {
		return "mod"
	}
	return result
}

func titleFromSlug(input string) string {
	parts := strings.Split(slugify(input), "-")
	words := make([]string, 0, len(parts))
	for _, part := range parts {
		if part == "" {
			continue
		}
		words = append(words, strings.ToUpper(part[:1])+part[1:])
	}
	if len(words) == 0 {
		return "My Mod"
	}
	return strings.Join(words, " ")
}

func trimQuotes(input string) string {
	trimmed := strings.TrimSpace(input)
	trimmed = strings.TrimPrefix(trimmed, `"`)
	trimmed = strings.TrimSuffix(trimmed, `"`)
	trimmed = strings.TrimPrefix(trimmed, "'")
	trimmed = strings.TrimSuffix(trimmed, "'")
	return strings.TrimSpace(trimmed)
}

func defaultString(input string, fallback string) string {
	if strings.TrimSpace(input) == "" {
		return fallback
	}
	return input
}
