// @generated by protobuf-ts 2.11.1 with parameter long_type_string,ts_nocheck,client_none
// @generated from protobuf file "runtime/v1/agent_work.proto" (package "nimi.runtime.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ReasonCode } from "./common";
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkReference
 */
export interface LocalAppAgentWorkReference {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string display_name = 2
     */
    displayName: string;
    /**
     * @generated from protobuf field: optional string avatar_url = 3
     */
    avatarUrl?: string;
    /**
     * @generated from protobuf field: string agent_binding = 4
     */
    agentBinding: string;
    /**
     * Non-authorizing Activity grouping reference, never an Agent selector.
     *
     * @generated from protobuf field: string activity_agent_ref = 5
     */
    activityAgentRef: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.ListLocalAppAgentWorkReferencesRequest
 */
export interface ListLocalAppAgentWorkReferencesRequest {
}
/**
 * @generated from protobuf message nimi.runtime.v1.ListLocalAppAgentWorkReferencesResponse
 */
export interface ListLocalAppAgentWorkReferencesResponse {
    /**
     * @generated from protobuf field: repeated nimi.runtime.v1.LocalAppAgentWorkReference references = 1
     */
    references: LocalAppAgentWorkReference[];
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkSource
 */
export interface LocalAppAgentWorkSource {
    /**
     * @generated from protobuf field: string source_id = 1
     */
    sourceId: string;
    /**
     * @generated from protobuf field: string title = 2
     */
    title: string;
    /**
     * @generated from protobuf field: string content = 3
     */
    content: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkTool
 */
export interface LocalAppAgentWorkTool {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string description = 2
     */
    description: string;
    /**
     * @generated from protobuf field: string input_schema_json = 3
     */
    inputSchemaJson: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkInput
 */
export interface LocalAppAgentWorkInput {
    /**
     * @generated from protobuf field: string work_id = 1
     */
    workId: string;
    /**
     * @generated from protobuf field: string instructions = 2
     */
    instructions: string;
    /**
     * @generated from protobuf field: repeated nimi.runtime.v1.LocalAppAgentWorkSource sources = 3
     */
    sources: LocalAppAgentWorkSource[];
    /**
     * @generated from protobuf field: repeated nimi.runtime.v1.LocalAppAgentWorkTool tools = 4
     */
    tools: LocalAppAgentWorkTool[];
    /**
     * @generated from protobuf field: optional string routine_name = 5
     */
    routineName?: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.StartLocalAppAgentWorkRequest
 */
export interface StartLocalAppAgentWorkRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string request_id = 2
     */
    requestId: string;
    /**
     * @generated from protobuf field: string prompt = 3
     */
    prompt: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppAgentWorkInput work = 4
     */
    work?: LocalAppAgentWorkInput;
}
/**
 * @generated from protobuf message nimi.runtime.v1.StartLocalAppAgentWorkResponse
 */
export interface StartLocalAppAgentWorkResponse {
    /**
     * @generated from protobuf field: string execution_id = 1
     */
    executionId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkExecution
 */
export interface LocalAppAgentWorkExecution {
    /**
     * @generated from protobuf field: string execution_id = 1
     */
    executionId: string;
    /**
     * @generated from protobuf field: string work_id = 2
     */
    workId: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppAgentWorkState state = 3
     */
    state: LocalAppAgentWorkState;
    /**
     * Present only after successful complete validated model output.
     *
     * @generated from protobuf field: string output_text = 4
     */
    outputText: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 5
     */
    reasonCode: ReasonCode;
    /**
     * @generated from protobuf field: string message = 6
     */
    message: string;
    /**
     * @generated from protobuf field: uint64 sequence = 7
     */
    sequence: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetLocalAppAgentWorkRequest
 */
export interface GetLocalAppAgentWorkRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string execution_id = 2
     */
    executionId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetLocalAppAgentWorkResponse
 */
export interface GetLocalAppAgentWorkResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppAgentWorkExecution execution = 1
     */
    execution?: LocalAppAgentWorkExecution;
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetLocalAppAgentWorkStatusRequest
 */
export interface GetLocalAppAgentWorkStatusRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetLocalAppAgentWorkStatusResponse
 */
export interface GetLocalAppAgentWorkStatusResponse {
    /**
     * @generated from protobuf field: bool busy = 1
     */
    busy: boolean;
    /**
     * Omitted for another App's execution or canonical chat.
     *
     * @generated from protobuf field: optional string own_execution_id = 2
     */
    ownExecutionId?: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkToolCall
 */
export interface LocalAppAgentWorkToolCall {
    /**
     * @generated from protobuf field: string call_id = 1
     */
    callId: string;
    /**
     * @generated from protobuf field: string execution_id = 2
     */
    executionId: string;
    /**
     * @generated from protobuf field: string name = 3
     */
    name: string;
    /**
     * @generated from protobuf field: string arguments_json = 4
     */
    argumentsJson: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.ListLocalAppAgentWorkToolCallsRequest
 */
export interface ListLocalAppAgentWorkToolCallsRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string execution_id = 2
     */
    executionId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.ListLocalAppAgentWorkToolCallsResponse
 */
export interface ListLocalAppAgentWorkToolCallsResponse {
    /**
     * @generated from protobuf field: repeated nimi.runtime.v1.LocalAppAgentWorkToolCall calls = 1
     */
    calls: LocalAppAgentWorkToolCall[];
}
/**
 * @generated from protobuf message nimi.runtime.v1.SubmitLocalAppAgentWorkToolResultRequest
 */
export interface SubmitLocalAppAgentWorkToolResultRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string execution_id = 2
     */
    executionId: string;
    /**
     * @generated from protobuf field: string call_id = 3
     */
    callId: string;
    /**
     * @generated from protobuf field: string result_json = 4
     */
    resultJson: string;
    /**
     * @generated from protobuf field: bool is_error = 5
     */
    isError: boolean;
}
/**
 * @generated from protobuf message nimi.runtime.v1.SubmitLocalAppAgentWorkToolResultResponse
 */
export interface SubmitLocalAppAgentWorkToolResultResponse {
    /**
     * @generated from protobuf field: string call_id = 1
     */
    callId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.CancelLocalAppAgentWorkRequest
 */
export interface CancelLocalAppAgentWorkRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string execution_id = 2
     */
    executionId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.CancelLocalAppAgentWorkResponse
 */
export interface CancelLocalAppAgentWorkResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppAgentWorkExecution execution = 1
     */
    execution?: LocalAppAgentWorkExecution;
}
/**
 * @generated from protobuf message nimi.runtime.v1.SubscribeLocalAppAgentWorkEventsRequest
 */
export interface SubscribeLocalAppAgentWorkEventsRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string execution_id = 2
     */
    executionId: string;
    /**
     * @generated from protobuf field: uint64 after_sequence = 3
     */
    afterSequence: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppAgentWorkEvent
 */
export interface LocalAppAgentWorkEvent {
    /**
     * @generated from protobuf field: string execution_id = 1
     */
    executionId: string;
    /**
     * @generated from protobuf field: uint64 sequence = 2
     */
    sequence: string;
    /**
     * @generated from protobuf oneof: event
     */
    event: {
        oneofKind: "snapshot";
        /**
         * @generated from protobuf field: nimi.runtime.v1.LocalAppAgentWorkExecution snapshot = 3
         */
        snapshot: LocalAppAgentWorkExecution;
    } | {
        oneofKind: "textDelta";
        /**
         * @generated from protobuf field: string text_delta = 4
         */
        textDelta: string;
    } | {
        oneofKind: "toolCall";
        /**
         * @generated from protobuf field: nimi.runtime.v1.LocalAppAgentWorkToolCall tool_call = 5
         */
        toolCall: LocalAppAgentWorkToolCall;
    } | {
        oneofKind: undefined;
    };
}
/**
 * A bounded model execution owned by the initiating protected App scope.
 * No message in this surface is a canonical Conversation message.
 *
 * @generated from protobuf enum nimi.runtime.v1.LocalAppAgentWorkState
 */
export enum LocalAppAgentWorkState {
    /**
     * @generated from protobuf enum value: LOCAL_APP_AGENT_WORK_STATE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LOCAL_APP_AGENT_WORK_STATE_RUNNING = 1;
     */
    RUNNING = 1,
    /**
     * @generated from protobuf enum value: LOCAL_APP_AGENT_WORK_STATE_WAITING_TOOL = 2;
     */
    WAITING_TOOL = 2,
    /**
     * @generated from protobuf enum value: LOCAL_APP_AGENT_WORK_STATE_SUCCEEDED = 3;
     */
    SUCCEEDED = 3,
    /**
     * @generated from protobuf enum value: LOCAL_APP_AGENT_WORK_STATE_FAILED = 4;
     */
    FAILED = 4,
    /**
     * @generated from protobuf enum value: LOCAL_APP_AGENT_WORK_STATE_CANCELLED = 5;
     */
    CANCELLED = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkReference$Type extends MessageType<LocalAppAgentWorkReference> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkReference", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "avatar_url", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "agent_binding", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "activity_agent_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkReference>): LocalAppAgentWorkReference {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.displayName = "";
        message.agentBinding = "";
        message.activityAgentRef = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkReference>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkReference): LocalAppAgentWorkReference {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string display_name */ 2:
                    message.displayName = reader.string();
                    break;
                case /* optional string avatar_url */ 3:
                    message.avatarUrl = reader.string();
                    break;
                case /* string agent_binding */ 4:
                    message.agentBinding = reader.string();
                    break;
                case /* string activity_agent_ref */ 5:
                    message.activityAgentRef = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkReference, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string display_name = 2; */
        if (message.displayName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.displayName);
        /* optional string avatar_url = 3; */
        if (message.avatarUrl !== undefined)
            writer.tag(3, WireType.LengthDelimited).string(message.avatarUrl);
        /* string agent_binding = 4; */
        if (message.agentBinding !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.agentBinding);
        /* string activity_agent_ref = 5; */
        if (message.activityAgentRef !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.activityAgentRef);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkReference
 */
export const LocalAppAgentWorkReference = new LocalAppAgentWorkReference$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLocalAppAgentWorkReferencesRequest$Type extends MessageType<ListLocalAppAgentWorkReferencesRequest> {
    constructor() {
        super("nimi.runtime.v1.ListLocalAppAgentWorkReferencesRequest", []);
    }
    create(value?: PartialMessage<ListLocalAppAgentWorkReferencesRequest>): ListLocalAppAgentWorkReferencesRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListLocalAppAgentWorkReferencesRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLocalAppAgentWorkReferencesRequest): ListLocalAppAgentWorkReferencesRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLocalAppAgentWorkReferencesRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.ListLocalAppAgentWorkReferencesRequest
 */
export const ListLocalAppAgentWorkReferencesRequest = new ListLocalAppAgentWorkReferencesRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLocalAppAgentWorkReferencesResponse$Type extends MessageType<ListLocalAppAgentWorkReferencesResponse> {
    constructor() {
        super("nimi.runtime.v1.ListLocalAppAgentWorkReferencesResponse", [
            { no: 1, name: "references", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LocalAppAgentWorkReference }
        ]);
    }
    create(value?: PartialMessage<ListLocalAppAgentWorkReferencesResponse>): ListLocalAppAgentWorkReferencesResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.references = [];
        if (value !== undefined)
            reflectionMergePartial<ListLocalAppAgentWorkReferencesResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLocalAppAgentWorkReferencesResponse): ListLocalAppAgentWorkReferencesResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated nimi.runtime.v1.LocalAppAgentWorkReference references */ 1:
                    message.references.push(LocalAppAgentWorkReference.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLocalAppAgentWorkReferencesResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated nimi.runtime.v1.LocalAppAgentWorkReference references = 1; */
        for (let i = 0; i < message.references.length; i++)
            LocalAppAgentWorkReference.internalBinaryWrite(message.references[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.ListLocalAppAgentWorkReferencesResponse
 */
export const ListLocalAppAgentWorkReferencesResponse = new ListLocalAppAgentWorkReferencesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkSource$Type extends MessageType<LocalAppAgentWorkSource> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkSource", [
            { no: 1, name: "source_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "title", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "content", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkSource>): LocalAppAgentWorkSource {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sourceId = "";
        message.title = "";
        message.content = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkSource>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkSource): LocalAppAgentWorkSource {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string source_id */ 1:
                    message.sourceId = reader.string();
                    break;
                case /* string title */ 2:
                    message.title = reader.string();
                    break;
                case /* string content */ 3:
                    message.content = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkSource, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string source_id = 1; */
        if (message.sourceId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.sourceId);
        /* string title = 2; */
        if (message.title !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.title);
        /* string content = 3; */
        if (message.content !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.content);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkSource
 */
export const LocalAppAgentWorkSource = new LocalAppAgentWorkSource$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkTool$Type extends MessageType<LocalAppAgentWorkTool> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkTool", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "description", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "input_schema_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkTool>): LocalAppAgentWorkTool {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.description = "";
        message.inputSchemaJson = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkTool>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkTool): LocalAppAgentWorkTool {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string description */ 2:
                    message.description = reader.string();
                    break;
                case /* string input_schema_json */ 3:
                    message.inputSchemaJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkTool, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string description = 2; */
        if (message.description !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.description);
        /* string input_schema_json = 3; */
        if (message.inputSchemaJson !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.inputSchemaJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkTool
 */
export const LocalAppAgentWorkTool = new LocalAppAgentWorkTool$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkInput$Type extends MessageType<LocalAppAgentWorkInput> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkInput", [
            { no: 1, name: "work_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "instructions", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "sources", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LocalAppAgentWorkSource },
            { no: 4, name: "tools", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LocalAppAgentWorkTool },
            { no: 5, name: "routine_name", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkInput>): LocalAppAgentWorkInput {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.workId = "";
        message.instructions = "";
        message.sources = [];
        message.tools = [];
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkInput>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkInput): LocalAppAgentWorkInput {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string work_id */ 1:
                    message.workId = reader.string();
                    break;
                case /* string instructions */ 2:
                    message.instructions = reader.string();
                    break;
                case /* repeated nimi.runtime.v1.LocalAppAgentWorkSource sources */ 3:
                    message.sources.push(LocalAppAgentWorkSource.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* repeated nimi.runtime.v1.LocalAppAgentWorkTool tools */ 4:
                    message.tools.push(LocalAppAgentWorkTool.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* optional string routine_name */ 5:
                    message.routineName = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkInput, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string work_id = 1; */
        if (message.workId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.workId);
        /* string instructions = 2; */
        if (message.instructions !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.instructions);
        /* repeated nimi.runtime.v1.LocalAppAgentWorkSource sources = 3; */
        for (let i = 0; i < message.sources.length; i++)
            LocalAppAgentWorkSource.internalBinaryWrite(message.sources[i], writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* repeated nimi.runtime.v1.LocalAppAgentWorkTool tools = 4; */
        for (let i = 0; i < message.tools.length; i++)
            LocalAppAgentWorkTool.internalBinaryWrite(message.tools[i], writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* optional string routine_name = 5; */
        if (message.routineName !== undefined)
            writer.tag(5, WireType.LengthDelimited).string(message.routineName);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkInput
 */
export const LocalAppAgentWorkInput = new LocalAppAgentWorkInput$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartLocalAppAgentWorkRequest$Type extends MessageType<StartLocalAppAgentWorkRequest> {
    constructor() {
        super("nimi.runtime.v1.StartLocalAppAgentWorkRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "request_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "prompt", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "work", kind: "message", T: () => LocalAppAgentWorkInput }
        ]);
    }
    create(value?: PartialMessage<StartLocalAppAgentWorkRequest>): StartLocalAppAgentWorkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.requestId = "";
        message.prompt = "";
        if (value !== undefined)
            reflectionMergePartial<StartLocalAppAgentWorkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StartLocalAppAgentWorkRequest): StartLocalAppAgentWorkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string request_id */ 2:
                    message.requestId = reader.string();
                    break;
                case /* string prompt */ 3:
                    message.prompt = reader.string();
                    break;
                case /* nimi.runtime.v1.LocalAppAgentWorkInput work */ 4:
                    message.work = LocalAppAgentWorkInput.internalBinaryRead(reader, reader.uint32(), options, message.work);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StartLocalAppAgentWorkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string request_id = 2; */
        if (message.requestId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.requestId);
        /* string prompt = 3; */
        if (message.prompt !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.prompt);
        /* nimi.runtime.v1.LocalAppAgentWorkInput work = 4; */
        if (message.work)
            LocalAppAgentWorkInput.internalBinaryWrite(message.work, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.StartLocalAppAgentWorkRequest
 */
export const StartLocalAppAgentWorkRequest = new StartLocalAppAgentWorkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StartLocalAppAgentWorkResponse$Type extends MessageType<StartLocalAppAgentWorkResponse> {
    constructor() {
        super("nimi.runtime.v1.StartLocalAppAgentWorkResponse", [
            { no: 1, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StartLocalAppAgentWorkResponse>): StartLocalAppAgentWorkResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.executionId = "";
        if (value !== undefined)
            reflectionMergePartial<StartLocalAppAgentWorkResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StartLocalAppAgentWorkResponse): StartLocalAppAgentWorkResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string execution_id */ 1:
                    message.executionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StartLocalAppAgentWorkResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string execution_id = 1; */
        if (message.executionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.executionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.StartLocalAppAgentWorkResponse
 */
export const StartLocalAppAgentWorkResponse = new StartLocalAppAgentWorkResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkExecution$Type extends MessageType<LocalAppAgentWorkExecution> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkExecution", [
            { no: 1, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "work_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "state", kind: "enum", T: () => ["nimi.runtime.v1.LocalAppAgentWorkState", LocalAppAgentWorkState, "LOCAL_APP_AGENT_WORK_STATE_"] },
            { no: 4, name: "output_text", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] },
            { no: 6, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkExecution>): LocalAppAgentWorkExecution {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.executionId = "";
        message.workId = "";
        message.state = 0;
        message.outputText = "";
        message.reasonCode = 0;
        message.message = "";
        message.sequence = "0";
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkExecution>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkExecution): LocalAppAgentWorkExecution {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string execution_id */ 1:
                    message.executionId = reader.string();
                    break;
                case /* string work_id */ 2:
                    message.workId = reader.string();
                    break;
                case /* nimi.runtime.v1.LocalAppAgentWorkState state */ 3:
                    message.state = reader.int32();
                    break;
                case /* string output_text */ 4:
                    message.outputText = reader.string();
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 5:
                    message.reasonCode = reader.int32();
                    break;
                case /* string message */ 6:
                    message.message = reader.string();
                    break;
                case /* uint64 sequence */ 7:
                    message.sequence = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkExecution, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string execution_id = 1; */
        if (message.executionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.executionId);
        /* string work_id = 2; */
        if (message.workId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.workId);
        /* nimi.runtime.v1.LocalAppAgentWorkState state = 3; */
        if (message.state !== 0)
            writer.tag(3, WireType.Varint).int32(message.state);
        /* string output_text = 4; */
        if (message.outputText !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.outputText);
        /* nimi.runtime.v1.ReasonCode reason_code = 5; */
        if (message.reasonCode !== 0)
            writer.tag(5, WireType.Varint).int32(message.reasonCode);
        /* string message = 6; */
        if (message.message !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.message);
        /* uint64 sequence = 7; */
        if (message.sequence !== "0")
            writer.tag(7, WireType.Varint).uint64(message.sequence);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkExecution
 */
export const LocalAppAgentWorkExecution = new LocalAppAgentWorkExecution$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLocalAppAgentWorkRequest$Type extends MessageType<GetLocalAppAgentWorkRequest> {
    constructor() {
        super("nimi.runtime.v1.GetLocalAppAgentWorkRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetLocalAppAgentWorkRequest>): GetLocalAppAgentWorkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.executionId = "";
        if (value !== undefined)
            reflectionMergePartial<GetLocalAppAgentWorkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLocalAppAgentWorkRequest): GetLocalAppAgentWorkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string execution_id */ 2:
                    message.executionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLocalAppAgentWorkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string execution_id = 2; */
        if (message.executionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.executionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetLocalAppAgentWorkRequest
 */
export const GetLocalAppAgentWorkRequest = new GetLocalAppAgentWorkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLocalAppAgentWorkResponse$Type extends MessageType<GetLocalAppAgentWorkResponse> {
    constructor() {
        super("nimi.runtime.v1.GetLocalAppAgentWorkResponse", [
            { no: 1, name: "execution", kind: "message", T: () => LocalAppAgentWorkExecution }
        ]);
    }
    create(value?: PartialMessage<GetLocalAppAgentWorkResponse>): GetLocalAppAgentWorkResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetLocalAppAgentWorkResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLocalAppAgentWorkResponse): GetLocalAppAgentWorkResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.LocalAppAgentWorkExecution execution */ 1:
                    message.execution = LocalAppAgentWorkExecution.internalBinaryRead(reader, reader.uint32(), options, message.execution);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLocalAppAgentWorkResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.LocalAppAgentWorkExecution execution = 1; */
        if (message.execution)
            LocalAppAgentWorkExecution.internalBinaryWrite(message.execution, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetLocalAppAgentWorkResponse
 */
export const GetLocalAppAgentWorkResponse = new GetLocalAppAgentWorkResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLocalAppAgentWorkStatusRequest$Type extends MessageType<GetLocalAppAgentWorkStatusRequest> {
    constructor() {
        super("nimi.runtime.v1.GetLocalAppAgentWorkStatusRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetLocalAppAgentWorkStatusRequest>): GetLocalAppAgentWorkStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        if (value !== undefined)
            reflectionMergePartial<GetLocalAppAgentWorkStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLocalAppAgentWorkStatusRequest): GetLocalAppAgentWorkStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLocalAppAgentWorkStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetLocalAppAgentWorkStatusRequest
 */
export const GetLocalAppAgentWorkStatusRequest = new GetLocalAppAgentWorkStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLocalAppAgentWorkStatusResponse$Type extends MessageType<GetLocalAppAgentWorkStatusResponse> {
    constructor() {
        super("nimi.runtime.v1.GetLocalAppAgentWorkStatusResponse", [
            { no: 1, name: "busy", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "own_execution_id", kind: "scalar", opt: true, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetLocalAppAgentWorkStatusResponse>): GetLocalAppAgentWorkStatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.busy = false;
        if (value !== undefined)
            reflectionMergePartial<GetLocalAppAgentWorkStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLocalAppAgentWorkStatusResponse): GetLocalAppAgentWorkStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool busy */ 1:
                    message.busy = reader.bool();
                    break;
                case /* optional string own_execution_id */ 2:
                    message.ownExecutionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLocalAppAgentWorkStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool busy = 1; */
        if (message.busy !== false)
            writer.tag(1, WireType.Varint).bool(message.busy);
        /* optional string own_execution_id = 2; */
        if (message.ownExecutionId !== undefined)
            writer.tag(2, WireType.LengthDelimited).string(message.ownExecutionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetLocalAppAgentWorkStatusResponse
 */
export const GetLocalAppAgentWorkStatusResponse = new GetLocalAppAgentWorkStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkToolCall$Type extends MessageType<LocalAppAgentWorkToolCall> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkToolCall", [
            { no: 1, name: "call_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "arguments_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkToolCall>): LocalAppAgentWorkToolCall {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.callId = "";
        message.executionId = "";
        message.name = "";
        message.argumentsJson = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkToolCall>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkToolCall): LocalAppAgentWorkToolCall {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string call_id */ 1:
                    message.callId = reader.string();
                    break;
                case /* string execution_id */ 2:
                    message.executionId = reader.string();
                    break;
                case /* string name */ 3:
                    message.name = reader.string();
                    break;
                case /* string arguments_json */ 4:
                    message.argumentsJson = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkToolCall, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string call_id = 1; */
        if (message.callId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.callId);
        /* string execution_id = 2; */
        if (message.executionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.executionId);
        /* string name = 3; */
        if (message.name !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.name);
        /* string arguments_json = 4; */
        if (message.argumentsJson !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.argumentsJson);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkToolCall
 */
export const LocalAppAgentWorkToolCall = new LocalAppAgentWorkToolCall$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLocalAppAgentWorkToolCallsRequest$Type extends MessageType<ListLocalAppAgentWorkToolCallsRequest> {
    constructor() {
        super("nimi.runtime.v1.ListLocalAppAgentWorkToolCallsRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ListLocalAppAgentWorkToolCallsRequest>): ListLocalAppAgentWorkToolCallsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.executionId = "";
        if (value !== undefined)
            reflectionMergePartial<ListLocalAppAgentWorkToolCallsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLocalAppAgentWorkToolCallsRequest): ListLocalAppAgentWorkToolCallsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string execution_id */ 2:
                    message.executionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLocalAppAgentWorkToolCallsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string execution_id = 2; */
        if (message.executionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.executionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.ListLocalAppAgentWorkToolCallsRequest
 */
export const ListLocalAppAgentWorkToolCallsRequest = new ListLocalAppAgentWorkToolCallsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLocalAppAgentWorkToolCallsResponse$Type extends MessageType<ListLocalAppAgentWorkToolCallsResponse> {
    constructor() {
        super("nimi.runtime.v1.ListLocalAppAgentWorkToolCallsResponse", [
            { no: 1, name: "calls", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LocalAppAgentWorkToolCall }
        ]);
    }
    create(value?: PartialMessage<ListLocalAppAgentWorkToolCallsResponse>): ListLocalAppAgentWorkToolCallsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.calls = [];
        if (value !== undefined)
            reflectionMergePartial<ListLocalAppAgentWorkToolCallsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLocalAppAgentWorkToolCallsResponse): ListLocalAppAgentWorkToolCallsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated nimi.runtime.v1.LocalAppAgentWorkToolCall calls */ 1:
                    message.calls.push(LocalAppAgentWorkToolCall.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLocalAppAgentWorkToolCallsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated nimi.runtime.v1.LocalAppAgentWorkToolCall calls = 1; */
        for (let i = 0; i < message.calls.length; i++)
            LocalAppAgentWorkToolCall.internalBinaryWrite(message.calls[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.ListLocalAppAgentWorkToolCallsResponse
 */
export const ListLocalAppAgentWorkToolCallsResponse = new ListLocalAppAgentWorkToolCallsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubmitLocalAppAgentWorkToolResultRequest$Type extends MessageType<SubmitLocalAppAgentWorkToolResultRequest> {
    constructor() {
        super("nimi.runtime.v1.SubmitLocalAppAgentWorkToolResultRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "call_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "result_json", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "is_error", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SubmitLocalAppAgentWorkToolResultRequest>): SubmitLocalAppAgentWorkToolResultRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.executionId = "";
        message.callId = "";
        message.resultJson = "";
        message.isError = false;
        if (value !== undefined)
            reflectionMergePartial<SubmitLocalAppAgentWorkToolResultRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubmitLocalAppAgentWorkToolResultRequest): SubmitLocalAppAgentWorkToolResultRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string execution_id */ 2:
                    message.executionId = reader.string();
                    break;
                case /* string call_id */ 3:
                    message.callId = reader.string();
                    break;
                case /* string result_json */ 4:
                    message.resultJson = reader.string();
                    break;
                case /* bool is_error */ 5:
                    message.isError = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubmitLocalAppAgentWorkToolResultRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string execution_id = 2; */
        if (message.executionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.executionId);
        /* string call_id = 3; */
        if (message.callId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.callId);
        /* string result_json = 4; */
        if (message.resultJson !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.resultJson);
        /* bool is_error = 5; */
        if (message.isError !== false)
            writer.tag(5, WireType.Varint).bool(message.isError);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.SubmitLocalAppAgentWorkToolResultRequest
 */
export const SubmitLocalAppAgentWorkToolResultRequest = new SubmitLocalAppAgentWorkToolResultRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubmitLocalAppAgentWorkToolResultResponse$Type extends MessageType<SubmitLocalAppAgentWorkToolResultResponse> {
    constructor() {
        super("nimi.runtime.v1.SubmitLocalAppAgentWorkToolResultResponse", [
            { no: 1, name: "call_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SubmitLocalAppAgentWorkToolResultResponse>): SubmitLocalAppAgentWorkToolResultResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.callId = "";
        if (value !== undefined)
            reflectionMergePartial<SubmitLocalAppAgentWorkToolResultResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubmitLocalAppAgentWorkToolResultResponse): SubmitLocalAppAgentWorkToolResultResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string call_id */ 1:
                    message.callId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubmitLocalAppAgentWorkToolResultResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string call_id = 1; */
        if (message.callId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.callId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.SubmitLocalAppAgentWorkToolResultResponse
 */
export const SubmitLocalAppAgentWorkToolResultResponse = new SubmitLocalAppAgentWorkToolResultResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelLocalAppAgentWorkRequest$Type extends MessageType<CancelLocalAppAgentWorkRequest> {
    constructor() {
        super("nimi.runtime.v1.CancelLocalAppAgentWorkRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<CancelLocalAppAgentWorkRequest>): CancelLocalAppAgentWorkRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.executionId = "";
        if (value !== undefined)
            reflectionMergePartial<CancelLocalAppAgentWorkRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelLocalAppAgentWorkRequest): CancelLocalAppAgentWorkRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string execution_id */ 2:
                    message.executionId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelLocalAppAgentWorkRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string execution_id = 2; */
        if (message.executionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.executionId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.CancelLocalAppAgentWorkRequest
 */
export const CancelLocalAppAgentWorkRequest = new CancelLocalAppAgentWorkRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class CancelLocalAppAgentWorkResponse$Type extends MessageType<CancelLocalAppAgentWorkResponse> {
    constructor() {
        super("nimi.runtime.v1.CancelLocalAppAgentWorkResponse", [
            { no: 1, name: "execution", kind: "message", T: () => LocalAppAgentWorkExecution }
        ]);
    }
    create(value?: PartialMessage<CancelLocalAppAgentWorkResponse>): CancelLocalAppAgentWorkResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<CancelLocalAppAgentWorkResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: CancelLocalAppAgentWorkResponse): CancelLocalAppAgentWorkResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.LocalAppAgentWorkExecution execution */ 1:
                    message.execution = LocalAppAgentWorkExecution.internalBinaryRead(reader, reader.uint32(), options, message.execution);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: CancelLocalAppAgentWorkResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.LocalAppAgentWorkExecution execution = 1; */
        if (message.execution)
            LocalAppAgentWorkExecution.internalBinaryWrite(message.execution, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.CancelLocalAppAgentWorkResponse
 */
export const CancelLocalAppAgentWorkResponse = new CancelLocalAppAgentWorkResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscribeLocalAppAgentWorkEventsRequest$Type extends MessageType<SubscribeLocalAppAgentWorkEventsRequest> {
    constructor() {
        super("nimi.runtime.v1.SubscribeLocalAppAgentWorkEventsRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "after_sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<SubscribeLocalAppAgentWorkEventsRequest>): SubscribeLocalAppAgentWorkEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.executionId = "";
        message.afterSequence = "0";
        if (value !== undefined)
            reflectionMergePartial<SubscribeLocalAppAgentWorkEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscribeLocalAppAgentWorkEventsRequest): SubscribeLocalAppAgentWorkEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string execution_id */ 2:
                    message.executionId = reader.string();
                    break;
                case /* uint64 after_sequence */ 3:
                    message.afterSequence = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscribeLocalAppAgentWorkEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string execution_id = 2; */
        if (message.executionId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.executionId);
        /* uint64 after_sequence = 3; */
        if (message.afterSequence !== "0")
            writer.tag(3, WireType.Varint).uint64(message.afterSequence);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.SubscribeLocalAppAgentWorkEventsRequest
 */
export const SubscribeLocalAppAgentWorkEventsRequest = new SubscribeLocalAppAgentWorkEventsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppAgentWorkEvent$Type extends MessageType<LocalAppAgentWorkEvent> {
    constructor() {
        super("nimi.runtime.v1.LocalAppAgentWorkEvent", [
            { no: 1, name: "execution_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 3, name: "snapshot", kind: "message", oneof: "event", T: () => LocalAppAgentWorkExecution },
            { no: 4, name: "text_delta", kind: "scalar", oneof: "event", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "tool_call", kind: "message", oneof: "event", T: () => LocalAppAgentWorkToolCall }
        ]);
    }
    create(value?: PartialMessage<LocalAppAgentWorkEvent>): LocalAppAgentWorkEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.executionId = "";
        message.sequence = "0";
        message.event = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<LocalAppAgentWorkEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppAgentWorkEvent): LocalAppAgentWorkEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string execution_id */ 1:
                    message.executionId = reader.string();
                    break;
                case /* uint64 sequence */ 2:
                    message.sequence = reader.uint64().toString();
                    break;
                case /* nimi.runtime.v1.LocalAppAgentWorkExecution snapshot */ 3:
                    message.event = {
                        oneofKind: "snapshot",
                        snapshot: LocalAppAgentWorkExecution.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).snapshot)
                    };
                    break;
                case /* string text_delta */ 4:
                    message.event = {
                        oneofKind: "textDelta",
                        textDelta: reader.string()
                    };
                    break;
                case /* nimi.runtime.v1.LocalAppAgentWorkToolCall tool_call */ 5:
                    message.event = {
                        oneofKind: "toolCall",
                        toolCall: LocalAppAgentWorkToolCall.internalBinaryRead(reader, reader.uint32(), options, (message.event as any).toolCall)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppAgentWorkEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string execution_id = 1; */
        if (message.executionId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.executionId);
        /* uint64 sequence = 2; */
        if (message.sequence !== "0")
            writer.tag(2, WireType.Varint).uint64(message.sequence);
        /* nimi.runtime.v1.LocalAppAgentWorkExecution snapshot = 3; */
        if (message.event.oneofKind === "snapshot")
            LocalAppAgentWorkExecution.internalBinaryWrite(message.event.snapshot, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* string text_delta = 4; */
        if (message.event.oneofKind === "textDelta")
            writer.tag(4, WireType.LengthDelimited).string(message.event.textDelta);
        /* nimi.runtime.v1.LocalAppAgentWorkToolCall tool_call = 5; */
        if (message.event.oneofKind === "toolCall")
            LocalAppAgentWorkToolCall.internalBinaryWrite(message.event.toolCall, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppAgentWorkEvent
 */
export const LocalAppAgentWorkEvent = new LocalAppAgentWorkEvent$Type();
