// @generated by protobuf-ts 2.11.1 with parameter long_type_string,ts_nocheck,client_none
// @generated from protobuf file "runtime/v1/agent_embodiment.proto" (package "nimi.runtime.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppEmbodimentActivity
 */
export interface LocalAppEmbodimentActivity {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string category = 2
     */
    category: string;
    /**
     * @generated from protobuf field: string intensity = 3
     */
    intensity: string;
    /**
     * @generated from protobuf field: string source = 4
     */
    source: string;
    /**
     * @generated from protobuf field: string turn_ref = 5
     */
    turnRef: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppEmbodimentEmotion
 */
export interface LocalAppEmbodimentEmotion {
    /**
     * @generated from protobuf field: string name = 1
     */
    name: string;
    /**
     * @generated from protobuf field: string source = 2
     */
    source: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppEmbodimentPosture
 */
export interface LocalAppEmbodimentPosture {
    /**
     * @generated from protobuf field: string action_family = 1
     */
    actionFamily: string;
    /**
     * @generated from protobuf field: string interrupt_mode = 2
     */
    interruptMode: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppEmbodimentVoiceTiming
 */
export interface LocalAppEmbodimentVoiceTiming {
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentVoicePhase phase = 1
     */
    phase: LocalAppEmbodimentVoicePhase;
    /**
     * @generated from protobuf field: int64 duration_ms = 2
     */
    durationMs: string;
    /**
     * @generated from protobuf field: int64 deadline_offset_ms = 3
     */
    deadlineOffsetMs: string;
    /**
     * @generated from protobuf field: string turn_ref = 4
     */
    turnRef: string;
    /**
     * @generated from protobuf field: string correlation_ref = 5
     */
    correlationRef: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppEmbodimentSnapshot
 */
export interface LocalAppEmbodimentSnapshot {
    /**
     * @generated from protobuf field: uint64 sequence = 1
     */
    sequence: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp observed_at = 2
     */
    observedAt?: Timestamp;
    /**
     * @generated from protobuf field: string provenance = 3
     */
    provenance: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentActivity activity = 4
     */
    activity?: LocalAppEmbodimentActivity;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentEmotion emotion = 5
     */
    emotion?: LocalAppEmbodimentEmotion;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentPosture posture = 6
     */
    posture?: LocalAppEmbodimentPosture;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentVoiceTiming voice_timing = 7
     */
    voiceTiming?: LocalAppEmbodimentVoiceTiming;
}
/**
 * @generated from protobuf message nimi.runtime.v1.LocalAppEmbodimentEvent
 */
export interface LocalAppEmbodimentEvent {
    /**
     * @generated from protobuf field: uint64 sequence = 1
     */
    sequence: string;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp observed_at = 2
     */
    observedAt?: Timestamp;
    /**
     * @generated from protobuf field: string provenance = 3
     */
    provenance: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentEventKind kind = 4
     */
    kind: LocalAppEmbodimentEventKind;
    /**
     * @generated from protobuf oneof: payload
     */
    payload: {
        oneofKind: "activity";
        /**
         * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentActivity activity = 10
         */
        activity: LocalAppEmbodimentActivity;
    } | {
        oneofKind: "emotion";
        /**
         * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentEmotion emotion = 11
         */
        emotion: LocalAppEmbodimentEmotion;
    } | {
        oneofKind: "posture";
        /**
         * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentPosture posture = 12
         */
        posture: LocalAppEmbodimentPosture;
    } | {
        oneofKind: "voiceTiming";
        /**
         * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentVoiceTiming voice_timing = 13
         */
        voiceTiming: LocalAppEmbodimentVoiceTiming;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetLocalAppEmbodimentSnapshotRequest
 */
export interface GetLocalAppEmbodimentSnapshotRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string conversation_anchor_id = 2
     */
    conversationAnchorId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetLocalAppEmbodimentSnapshotResponse
 */
export interface GetLocalAppEmbodimentSnapshotResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalAppEmbodimentSnapshot snapshot = 1
     */
    snapshot?: LocalAppEmbodimentSnapshot;
}
/**
 * @generated from protobuf message nimi.runtime.v1.SubscribeLocalAppEmbodimentEventsRequest
 */
export interface SubscribeLocalAppEmbodimentEventsRequest {
    /**
     * @generated from protobuf field: string agent_handle = 1
     */
    agentHandle: string;
    /**
     * @generated from protobuf field: string conversation_anchor_id = 2
     */
    conversationAnchorId: string;
    /**
     * @generated from protobuf field: uint64 after_sequence = 3
     */
    afterSequence: string;
}
/**
 * @generated from protobuf enum nimi.runtime.v1.LocalAppEmbodimentEventKind
 */
export enum LocalAppEmbodimentEventKind {
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_EVENT_KIND_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_EVENT_KIND_ACTIVITY = 1;
     */
    ACTIVITY = 1,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_EVENT_KIND_EMOTION = 2;
     */
    EMOTION = 2,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_EVENT_KIND_POSTURE = 3;
     */
    POSTURE = 3,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_EVENT_KIND_VOICE_TIMING = 4;
     */
    VOICE_TIMING = 4
}
/**
 * @generated from protobuf enum nimi.runtime.v1.LocalAppEmbodimentVoicePhase
 */
export enum LocalAppEmbodimentVoicePhase {
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_VOICE_PHASE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_VOICE_PHASE_ACTIVE = 1;
     */
    ACTIVE = 1,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_VOICE_PHASE_COMPLETED = 2;
     */
    COMPLETED = 2,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_VOICE_PHASE_FAILED = 3;
     */
    FAILED = 3,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_VOICE_PHASE_INTERRUPTED = 4;
     */
    INTERRUPTED = 4,
    /**
     * @generated from protobuf enum value: LOCAL_APP_EMBODIMENT_VOICE_PHASE_CANCELED = 5;
     */
    CANCELED = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppEmbodimentActivity$Type extends MessageType<LocalAppEmbodimentActivity> {
    constructor() {
        super("nimi.runtime.v1.LocalAppEmbodimentActivity", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "category", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "intensity", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "turn_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppEmbodimentActivity>): LocalAppEmbodimentActivity {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.category = "";
        message.intensity = "";
        message.source = "";
        message.turnRef = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppEmbodimentActivity>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppEmbodimentActivity): LocalAppEmbodimentActivity {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string category */ 2:
                    message.category = reader.string();
                    break;
                case /* string intensity */ 3:
                    message.intensity = reader.string();
                    break;
                case /* string source */ 4:
                    message.source = reader.string();
                    break;
                case /* string turn_ref */ 5:
                    message.turnRef = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppEmbodimentActivity, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string category = 2; */
        if (message.category !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.category);
        /* string intensity = 3; */
        if (message.intensity !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.intensity);
        /* string source = 4; */
        if (message.source !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.source);
        /* string turn_ref = 5; */
        if (message.turnRef !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.turnRef);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppEmbodimentActivity
 */
export const LocalAppEmbodimentActivity = new LocalAppEmbodimentActivity$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppEmbodimentEmotion$Type extends MessageType<LocalAppEmbodimentEmotion> {
    constructor() {
        super("nimi.runtime.v1.LocalAppEmbodimentEmotion", [
            { no: 1, name: "name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "source", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppEmbodimentEmotion>): LocalAppEmbodimentEmotion {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.name = "";
        message.source = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppEmbodimentEmotion>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppEmbodimentEmotion): LocalAppEmbodimentEmotion {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string name */ 1:
                    message.name = reader.string();
                    break;
                case /* string source */ 2:
                    message.source = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppEmbodimentEmotion, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string name = 1; */
        if (message.name !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.name);
        /* string source = 2; */
        if (message.source !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.source);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppEmbodimentEmotion
 */
export const LocalAppEmbodimentEmotion = new LocalAppEmbodimentEmotion$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppEmbodimentPosture$Type extends MessageType<LocalAppEmbodimentPosture> {
    constructor() {
        super("nimi.runtime.v1.LocalAppEmbodimentPosture", [
            { no: 1, name: "action_family", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "interrupt_mode", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppEmbodimentPosture>): LocalAppEmbodimentPosture {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.actionFamily = "";
        message.interruptMode = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppEmbodimentPosture>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppEmbodimentPosture): LocalAppEmbodimentPosture {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string action_family */ 1:
                    message.actionFamily = reader.string();
                    break;
                case /* string interrupt_mode */ 2:
                    message.interruptMode = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppEmbodimentPosture, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string action_family = 1; */
        if (message.actionFamily !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.actionFamily);
        /* string interrupt_mode = 2; */
        if (message.interruptMode !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.interruptMode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppEmbodimentPosture
 */
export const LocalAppEmbodimentPosture = new LocalAppEmbodimentPosture$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppEmbodimentVoiceTiming$Type extends MessageType<LocalAppEmbodimentVoiceTiming> {
    constructor() {
        super("nimi.runtime.v1.LocalAppEmbodimentVoiceTiming", [
            { no: 1, name: "phase", kind: "enum", T: () => ["nimi.runtime.v1.LocalAppEmbodimentVoicePhase", LocalAppEmbodimentVoicePhase, "LOCAL_APP_EMBODIMENT_VOICE_PHASE_"] },
            { no: 2, name: "duration_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 3, name: "deadline_offset_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/ },
            { no: 4, name: "turn_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "correlation_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<LocalAppEmbodimentVoiceTiming>): LocalAppEmbodimentVoiceTiming {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.phase = 0;
        message.durationMs = "0";
        message.deadlineOffsetMs = "0";
        message.turnRef = "";
        message.correlationRef = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppEmbodimentVoiceTiming>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppEmbodimentVoiceTiming): LocalAppEmbodimentVoiceTiming {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.LocalAppEmbodimentVoicePhase phase */ 1:
                    message.phase = reader.int32();
                    break;
                case /* int64 duration_ms */ 2:
                    message.durationMs = reader.int64().toString();
                    break;
                case /* int64 deadline_offset_ms */ 3:
                    message.deadlineOffsetMs = reader.int64().toString();
                    break;
                case /* string turn_ref */ 4:
                    message.turnRef = reader.string();
                    break;
                case /* string correlation_ref */ 5:
                    message.correlationRef = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppEmbodimentVoiceTiming, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.LocalAppEmbodimentVoicePhase phase = 1; */
        if (message.phase !== 0)
            writer.tag(1, WireType.Varint).int32(message.phase);
        /* int64 duration_ms = 2; */
        if (message.durationMs !== "0")
            writer.tag(2, WireType.Varint).int64(message.durationMs);
        /* int64 deadline_offset_ms = 3; */
        if (message.deadlineOffsetMs !== "0")
            writer.tag(3, WireType.Varint).int64(message.deadlineOffsetMs);
        /* string turn_ref = 4; */
        if (message.turnRef !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.turnRef);
        /* string correlation_ref = 5; */
        if (message.correlationRef !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.correlationRef);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppEmbodimentVoiceTiming
 */
export const LocalAppEmbodimentVoiceTiming = new LocalAppEmbodimentVoiceTiming$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppEmbodimentSnapshot$Type extends MessageType<LocalAppEmbodimentSnapshot> {
    constructor() {
        super("nimi.runtime.v1.LocalAppEmbodimentSnapshot", [
            { no: 1, name: "sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "observed_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "provenance", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "activity", kind: "message", T: () => LocalAppEmbodimentActivity },
            { no: 5, name: "emotion", kind: "message", T: () => LocalAppEmbodimentEmotion },
            { no: 6, name: "posture", kind: "message", T: () => LocalAppEmbodimentPosture },
            { no: 7, name: "voice_timing", kind: "message", T: () => LocalAppEmbodimentVoiceTiming }
        ]);
    }
    create(value?: PartialMessage<LocalAppEmbodimentSnapshot>): LocalAppEmbodimentSnapshot {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sequence = "0";
        message.provenance = "";
        if (value !== undefined)
            reflectionMergePartial<LocalAppEmbodimentSnapshot>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppEmbodimentSnapshot): LocalAppEmbodimentSnapshot {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 sequence */ 1:
                    message.sequence = reader.uint64().toString();
                    break;
                case /* google.protobuf.Timestamp observed_at */ 2:
                    message.observedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.observedAt);
                    break;
                case /* string provenance */ 3:
                    message.provenance = reader.string();
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentActivity activity */ 4:
                    message.activity = LocalAppEmbodimentActivity.internalBinaryRead(reader, reader.uint32(), options, message.activity);
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentEmotion emotion */ 5:
                    message.emotion = LocalAppEmbodimentEmotion.internalBinaryRead(reader, reader.uint32(), options, message.emotion);
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentPosture posture */ 6:
                    message.posture = LocalAppEmbodimentPosture.internalBinaryRead(reader, reader.uint32(), options, message.posture);
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentVoiceTiming voice_timing */ 7:
                    message.voiceTiming = LocalAppEmbodimentVoiceTiming.internalBinaryRead(reader, reader.uint32(), options, message.voiceTiming);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppEmbodimentSnapshot, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 sequence = 1; */
        if (message.sequence !== "0")
            writer.tag(1, WireType.Varint).uint64(message.sequence);
        /* google.protobuf.Timestamp observed_at = 2; */
        if (message.observedAt)
            Timestamp.internalBinaryWrite(message.observedAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string provenance = 3; */
        if (message.provenance !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.provenance);
        /* nimi.runtime.v1.LocalAppEmbodimentActivity activity = 4; */
        if (message.activity)
            LocalAppEmbodimentActivity.internalBinaryWrite(message.activity, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.LocalAppEmbodimentEmotion emotion = 5; */
        if (message.emotion)
            LocalAppEmbodimentEmotion.internalBinaryWrite(message.emotion, writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.LocalAppEmbodimentPosture posture = 6; */
        if (message.posture)
            LocalAppEmbodimentPosture.internalBinaryWrite(message.posture, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.LocalAppEmbodimentVoiceTiming voice_timing = 7; */
        if (message.voiceTiming)
            LocalAppEmbodimentVoiceTiming.internalBinaryWrite(message.voiceTiming, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppEmbodimentSnapshot
 */
export const LocalAppEmbodimentSnapshot = new LocalAppEmbodimentSnapshot$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalAppEmbodimentEvent$Type extends MessageType<LocalAppEmbodimentEvent> {
    constructor() {
        super("nimi.runtime.v1.LocalAppEmbodimentEvent", [
            { no: 1, name: "sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 2, name: "observed_at", kind: "message", T: () => Timestamp },
            { no: 3, name: "provenance", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "kind", kind: "enum", T: () => ["nimi.runtime.v1.LocalAppEmbodimentEventKind", LocalAppEmbodimentEventKind, "LOCAL_APP_EMBODIMENT_EVENT_KIND_"] },
            { no: 10, name: "activity", kind: "message", oneof: "payload", T: () => LocalAppEmbodimentActivity },
            { no: 11, name: "emotion", kind: "message", oneof: "payload", T: () => LocalAppEmbodimentEmotion },
            { no: 12, name: "posture", kind: "message", oneof: "payload", T: () => LocalAppEmbodimentPosture },
            { no: 13, name: "voice_timing", kind: "message", oneof: "payload", T: () => LocalAppEmbodimentVoiceTiming }
        ]);
    }
    create(value?: PartialMessage<LocalAppEmbodimentEvent>): LocalAppEmbodimentEvent {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.sequence = "0";
        message.provenance = "";
        message.kind = 0;
        message.payload = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<LocalAppEmbodimentEvent>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalAppEmbodimentEvent): LocalAppEmbodimentEvent {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 sequence */ 1:
                    message.sequence = reader.uint64().toString();
                    break;
                case /* google.protobuf.Timestamp observed_at */ 2:
                    message.observedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.observedAt);
                    break;
                case /* string provenance */ 3:
                    message.provenance = reader.string();
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentEventKind kind */ 4:
                    message.kind = reader.int32();
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentActivity activity */ 10:
                    message.payload = {
                        oneofKind: "activity",
                        activity: LocalAppEmbodimentActivity.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).activity)
                    };
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentEmotion emotion */ 11:
                    message.payload = {
                        oneofKind: "emotion",
                        emotion: LocalAppEmbodimentEmotion.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).emotion)
                    };
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentPosture posture */ 12:
                    message.payload = {
                        oneofKind: "posture",
                        posture: LocalAppEmbodimentPosture.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).posture)
                    };
                    break;
                case /* nimi.runtime.v1.LocalAppEmbodimentVoiceTiming voice_timing */ 13:
                    message.payload = {
                        oneofKind: "voiceTiming",
                        voiceTiming: LocalAppEmbodimentVoiceTiming.internalBinaryRead(reader, reader.uint32(), options, (message.payload as any).voiceTiming)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalAppEmbodimentEvent, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 sequence = 1; */
        if (message.sequence !== "0")
            writer.tag(1, WireType.Varint).uint64(message.sequence);
        /* google.protobuf.Timestamp observed_at = 2; */
        if (message.observedAt)
            Timestamp.internalBinaryWrite(message.observedAt, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string provenance = 3; */
        if (message.provenance !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.provenance);
        /* nimi.runtime.v1.LocalAppEmbodimentEventKind kind = 4; */
        if (message.kind !== 0)
            writer.tag(4, WireType.Varint).int32(message.kind);
        /* nimi.runtime.v1.LocalAppEmbodimentActivity activity = 10; */
        if (message.payload.oneofKind === "activity")
            LocalAppEmbodimentActivity.internalBinaryWrite(message.payload.activity, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.LocalAppEmbodimentEmotion emotion = 11; */
        if (message.payload.oneofKind === "emotion")
            LocalAppEmbodimentEmotion.internalBinaryWrite(message.payload.emotion, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.LocalAppEmbodimentPosture posture = 12; */
        if (message.payload.oneofKind === "posture")
            LocalAppEmbodimentPosture.internalBinaryWrite(message.payload.posture, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.LocalAppEmbodimentVoiceTiming voice_timing = 13; */
        if (message.payload.oneofKind === "voiceTiming")
            LocalAppEmbodimentVoiceTiming.internalBinaryWrite(message.payload.voiceTiming, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalAppEmbodimentEvent
 */
export const LocalAppEmbodimentEvent = new LocalAppEmbodimentEvent$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLocalAppEmbodimentSnapshotRequest$Type extends MessageType<GetLocalAppEmbodimentSnapshotRequest> {
    constructor() {
        super("nimi.runtime.v1.GetLocalAppEmbodimentSnapshotRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "conversation_anchor_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetLocalAppEmbodimentSnapshotRequest>): GetLocalAppEmbodimentSnapshotRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.conversationAnchorId = "";
        if (value !== undefined)
            reflectionMergePartial<GetLocalAppEmbodimentSnapshotRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLocalAppEmbodimentSnapshotRequest): GetLocalAppEmbodimentSnapshotRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string conversation_anchor_id */ 2:
                    message.conversationAnchorId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLocalAppEmbodimentSnapshotRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string conversation_anchor_id = 2; */
        if (message.conversationAnchorId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.conversationAnchorId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetLocalAppEmbodimentSnapshotRequest
 */
export const GetLocalAppEmbodimentSnapshotRequest = new GetLocalAppEmbodimentSnapshotRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetLocalAppEmbodimentSnapshotResponse$Type extends MessageType<GetLocalAppEmbodimentSnapshotResponse> {
    constructor() {
        super("nimi.runtime.v1.GetLocalAppEmbodimentSnapshotResponse", [
            { no: 1, name: "snapshot", kind: "message", T: () => LocalAppEmbodimentSnapshot }
        ]);
    }
    create(value?: PartialMessage<GetLocalAppEmbodimentSnapshotResponse>): GetLocalAppEmbodimentSnapshotResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetLocalAppEmbodimentSnapshotResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetLocalAppEmbodimentSnapshotResponse): GetLocalAppEmbodimentSnapshotResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.LocalAppEmbodimentSnapshot snapshot */ 1:
                    message.snapshot = LocalAppEmbodimentSnapshot.internalBinaryRead(reader, reader.uint32(), options, message.snapshot);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetLocalAppEmbodimentSnapshotResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.LocalAppEmbodimentSnapshot snapshot = 1; */
        if (message.snapshot)
            LocalAppEmbodimentSnapshot.internalBinaryWrite(message.snapshot, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetLocalAppEmbodimentSnapshotResponse
 */
export const GetLocalAppEmbodimentSnapshotResponse = new GetLocalAppEmbodimentSnapshotResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SubscribeLocalAppEmbodimentEventsRequest$Type extends MessageType<SubscribeLocalAppEmbodimentEventsRequest> {
    constructor() {
        super("nimi.runtime.v1.SubscribeLocalAppEmbodimentEventsRequest", [
            { no: 1, name: "agent_handle", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "conversation_anchor_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "after_sequence", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<SubscribeLocalAppEmbodimentEventsRequest>): SubscribeLocalAppEmbodimentEventsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.agentHandle = "";
        message.conversationAnchorId = "";
        message.afterSequence = "0";
        if (value !== undefined)
            reflectionMergePartial<SubscribeLocalAppEmbodimentEventsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SubscribeLocalAppEmbodimentEventsRequest): SubscribeLocalAppEmbodimentEventsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string agent_handle */ 1:
                    message.agentHandle = reader.string();
                    break;
                case /* string conversation_anchor_id */ 2:
                    message.conversationAnchorId = reader.string();
                    break;
                case /* uint64 after_sequence */ 3:
                    message.afterSequence = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SubscribeLocalAppEmbodimentEventsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string agent_handle = 1; */
        if (message.agentHandle !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.agentHandle);
        /* string conversation_anchor_id = 2; */
        if (message.conversationAnchorId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.conversationAnchorId);
        /* uint64 after_sequence = 3; */
        if (message.afterSequence !== "0")
            writer.tag(3, WireType.Varint).uint64(message.afterSequence);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.SubscribeLocalAppEmbodimentEventsRequest
 */
export const SubscribeLocalAppEmbodimentEventsRequest = new SubscribeLocalAppEmbodimentEventsRequest$Type();
