// @generated by protobuf-ts 2.11.1 with parameter long_type_string,ts_nocheck,client_none
// @generated from protobuf file "runtime/v1/development.proto" (package "nimi.runtime.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
import { ReasonCode } from "./common";
/**
 * @generated from protobuf message nimi.runtime.v1.GetDeveloperModeStatusRequest
 */
export interface GetDeveloperModeStatusRequest {
}
/**
 * @generated from protobuf message nimi.runtime.v1.GetDeveloperModeStatusResponse
 */
export interface GetDeveloperModeStatusResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.DeveloperModeState state = 1
     */
    state: DeveloperModeState;
    /**
     * @generated from protobuf field: uint64 revision = 2
     */
    revision: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 4
     */
    reasonCode: ReasonCode;
}
/**
 * @generated from protobuf message nimi.runtime.v1.SetDeveloperModeRequest
 */
export interface SetDeveloperModeRequest {
    /**
     * @generated from protobuf field: bool enabled = 1
     */
    enabled: boolean;
}
/**
 * @generated from protobuf message nimi.runtime.v1.SetDeveloperModeResponse
 */
export interface SetDeveloperModeResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.DeveloperModeState state = 1
     */
    state: DeveloperModeState;
    /**
     * @generated from protobuf field: uint64 revision = 2
     */
    revision: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 4
     */
    reasonCode: ReasonCode;
}
/**
 * Desktop-evaluated development source and declaration input. app_access keeps
 * the raw declaration for transparency; Runtime activates only supported
 * domains when it commits the current declaration generation.
 *
 * @generated from protobuf message nimi.runtime.v1.LocalDevelopmentProjectProjection
 */
export interface LocalDevelopmentProjectProjection {
    /**
     * @generated from protobuf field: string app_id = 1
     */
    appId: string;
    /**
     * @generated from protobuf field: string display_name = 2
     */
    displayName: string;
    /**
     * @generated from protobuf field: string canonical_project_root = 3
     */
    canonicalProjectRoot: string;
    /**
     * @generated from protobuf field: string canonical_manifest_path = 4
     */
    canonicalManifestPath: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalDevelopmentShellKind shell_kind = 5
     */
    shellKind: LocalDevelopmentShellKind;
    /**
     * @generated from protobuf field: repeated string app_access = 7
     */
    appAccess: string[];
    /**
     * @generated from protobuf field: string trust_class = 9
     */
    trustClass: string;
    /**
     * @generated from protobuf field: uint64 source_generation = 10
     */
    sourceGeneration: string;
    /**
     * @generated from protobuf field: uint64 declaration_generation = 11
     */
    declarationGeneration: string;
}
/**
 * registration_handle is a non-secret management selector. It is not the
 * Registered App Subject and grants no launch, session, or operation access.
 *
 * @generated from protobuf message nimi.runtime.v1.LocalDevelopmentRegistrationProjection
 */
export interface LocalDevelopmentRegistrationProjection {
    /**
     * @generated from protobuf field: bytes registration_handle = 1
     */
    registrationHandle: Uint8Array;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalDevelopmentProjectProjection project = 2
     */
    project?: LocalDevelopmentProjectProjection;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp registered_at = 3
     */
    registeredAt?: Timestamp;
    /**
     * @generated from protobuf field: google.protobuf.Timestamp updated_at = 4
     */
    updatedAt?: Timestamp;
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 5
     */
    reasonCode: ReasonCode;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RegisterLocalDevelopmentProjectRequest
 */
export interface RegisterLocalDevelopmentProjectRequest {
    /**
     * @generated from protobuf field: string expected_app_id = 1
     */
    expectedAppId: string;
    /**
     * @generated from protobuf field: string project_root = 2
     */
    projectRoot: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalDevelopmentShellKind shell_kind = 3
     */
    shellKind: LocalDevelopmentShellKind;
    /**
     * Desktop-owned run correlation only; never registration or access truth.
     *
     * @generated from protobuf field: bytes supervisor_run_id = 4
     */
    supervisorRunId: Uint8Array;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RegisterLocalDevelopmentProjectResponse
 */
export interface RegisterLocalDevelopmentProjectResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.LocalDevelopmentRegistrationProjection registration = 1
     */
    registration?: LocalDevelopmentRegistrationProjection;
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 2
     */
    reasonCode: ReasonCode;
}
/**
 * @generated from protobuf message nimi.runtime.v1.ListLocalDevelopmentRegistrationsRequest
 */
export interface ListLocalDevelopmentRegistrationsRequest {
}
/**
 * @generated from protobuf message nimi.runtime.v1.ListLocalDevelopmentRegistrationsResponse
 */
export interface ListLocalDevelopmentRegistrationsResponse {
    /**
     * @generated from protobuf field: repeated nimi.runtime.v1.LocalDevelopmentRegistrationProjection registrations = 1
     */
    registrations: LocalDevelopmentRegistrationProjection[];
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 2
     */
    reasonCode: ReasonCode;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RemoveLocalDevelopmentRegistrationRequest
 */
export interface RemoveLocalDevelopmentRegistrationRequest {
    /**
     * @generated from protobuf field: bytes registration_handle = 1
     */
    registrationHandle: Uint8Array;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RemoveLocalDevelopmentRegistrationResponse
 */
export interface RemoveLocalDevelopmentRegistrationResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 1
     */
    reasonCode: ReasonCode;
}
/**
 * @generated from protobuf message nimi.runtime.v1.EndLocalDevelopmentRunRequest
 */
export interface EndLocalDevelopmentRunRequest {
    /**
     * @generated from protobuf field: bytes registration_handle = 1
     */
    registrationHandle: Uint8Array;
    /**
     * @generated from protobuf field: bytes supervisor_run_id = 2
     */
    supervisorRunId: Uint8Array;
}
/**
 * @generated from protobuf message nimi.runtime.v1.EndLocalDevelopmentRunResponse
 */
export interface EndLocalDevelopmentRunResponse {
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 1
     */
    reasonCode: ReasonCode;
}
/**
 * @generated from protobuf enum nimi.runtime.v1.LocalDevelopmentShellKind
 */
export enum LocalDevelopmentShellKind {
    /**
     * @generated from protobuf enum value: LOCAL_DEVELOPMENT_SHELL_KIND_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: LOCAL_DEVELOPMENT_SHELL_KIND_ELECTRON = 1;
     */
    ELECTRON = 1,
    /**
     * @generated from protobuf enum value: LOCAL_DEVELOPMENT_SHELL_KIND_TAURI = 2;
     */
    TAURI = 2
}
/**
 * @generated from protobuf enum nimi.runtime.v1.DeveloperModeState
 */
export enum DeveloperModeState {
    /**
     * @generated from protobuf enum value: DEVELOPER_MODE_STATE_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: DEVELOPER_MODE_STATE_DISABLED = 1;
     */
    DISABLED = 1,
    /**
     * @generated from protobuf enum value: DEVELOPER_MODE_STATE_ENABLED = 2;
     */
    ENABLED = 2,
    /**
     * @generated from protobuf enum value: DEVELOPER_MODE_STATE_UNAVAILABLE = 3;
     */
    UNAVAILABLE = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class GetDeveloperModeStatusRequest$Type extends MessageType<GetDeveloperModeStatusRequest> {
    constructor() {
        super("nimi.runtime.v1.GetDeveloperModeStatusRequest", []);
    }
    create(value?: PartialMessage<GetDeveloperModeStatusRequest>): GetDeveloperModeStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetDeveloperModeStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeveloperModeStatusRequest): GetDeveloperModeStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeveloperModeStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetDeveloperModeStatusRequest
 */
export const GetDeveloperModeStatusRequest = new GetDeveloperModeStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetDeveloperModeStatusResponse$Type extends MessageType<GetDeveloperModeStatusResponse> {
    constructor() {
        super("nimi.runtime.v1.GetDeveloperModeStatusResponse", [
            { no: 1, name: "state", kind: "enum", T: () => ["nimi.runtime.v1.DeveloperModeState", DeveloperModeState, "DEVELOPER_MODE_STATE_"] },
            { no: 2, name: "revision", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 4, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<GetDeveloperModeStatusResponse>): GetDeveloperModeStatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.state = 0;
        message.revision = "0";
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<GetDeveloperModeStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetDeveloperModeStatusResponse): GetDeveloperModeStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.DeveloperModeState state */ 1:
                    message.state = reader.int32();
                    break;
                case /* uint64 revision */ 2:
                    message.revision = reader.uint64().toString();
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 4:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetDeveloperModeStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.DeveloperModeState state = 1; */
        if (message.state !== 0)
            writer.tag(1, WireType.Varint).int32(message.state);
        /* uint64 revision = 2; */
        if (message.revision !== "0")
            writer.tag(2, WireType.Varint).uint64(message.revision);
        /* nimi.runtime.v1.ReasonCode reason_code = 4; */
        if (message.reasonCode !== 0)
            writer.tag(4, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.GetDeveloperModeStatusResponse
 */
export const GetDeveloperModeStatusResponse = new GetDeveloperModeStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetDeveloperModeRequest$Type extends MessageType<SetDeveloperModeRequest> {
    constructor() {
        super("nimi.runtime.v1.SetDeveloperModeRequest", [
            { no: 1, name: "enabled", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<SetDeveloperModeRequest>): SetDeveloperModeRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.enabled = false;
        if (value !== undefined)
            reflectionMergePartial<SetDeveloperModeRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetDeveloperModeRequest): SetDeveloperModeRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool enabled */ 1:
                    message.enabled = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetDeveloperModeRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool enabled = 1; */
        if (message.enabled !== false)
            writer.tag(1, WireType.Varint).bool(message.enabled);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.SetDeveloperModeRequest
 */
export const SetDeveloperModeRequest = new SetDeveloperModeRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetDeveloperModeResponse$Type extends MessageType<SetDeveloperModeResponse> {
    constructor() {
        super("nimi.runtime.v1.SetDeveloperModeResponse", [
            { no: 1, name: "state", kind: "enum", T: () => ["nimi.runtime.v1.DeveloperModeState", DeveloperModeState, "DEVELOPER_MODE_STATE_"] },
            { no: 2, name: "revision", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 4, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<SetDeveloperModeResponse>): SetDeveloperModeResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.state = 0;
        message.revision = "0";
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<SetDeveloperModeResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetDeveloperModeResponse): SetDeveloperModeResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.DeveloperModeState state */ 1:
                    message.state = reader.int32();
                    break;
                case /* uint64 revision */ 2:
                    message.revision = reader.uint64().toString();
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 4:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetDeveloperModeResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.DeveloperModeState state = 1; */
        if (message.state !== 0)
            writer.tag(1, WireType.Varint).int32(message.state);
        /* uint64 revision = 2; */
        if (message.revision !== "0")
            writer.tag(2, WireType.Varint).uint64(message.revision);
        /* nimi.runtime.v1.ReasonCode reason_code = 4; */
        if (message.reasonCode !== 0)
            writer.tag(4, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.SetDeveloperModeResponse
 */
export const SetDeveloperModeResponse = new SetDeveloperModeResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalDevelopmentProjectProjection$Type extends MessageType<LocalDevelopmentProjectProjection> {
    constructor() {
        super("nimi.runtime.v1.LocalDevelopmentProjectProjection", [
            { no: 1, name: "app_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "display_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "canonical_project_root", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "canonical_manifest_path", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "shell_kind", kind: "enum", T: () => ["nimi.runtime.v1.LocalDevelopmentShellKind", LocalDevelopmentShellKind, "LOCAL_DEVELOPMENT_SHELL_KIND_"] },
            { no: 7, name: "app_access", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ },
            { no: 9, name: "trust_class", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "source_generation", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 11, name: "declaration_generation", kind: "scalar", T: 4 /*ScalarType.UINT64*/ }
        ]);
    }
    create(value?: PartialMessage<LocalDevelopmentProjectProjection>): LocalDevelopmentProjectProjection {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.appId = "";
        message.displayName = "";
        message.canonicalProjectRoot = "";
        message.canonicalManifestPath = "";
        message.shellKind = 0;
        message.appAccess = [];
        message.trustClass = "";
        message.sourceGeneration = "0";
        message.declarationGeneration = "0";
        if (value !== undefined)
            reflectionMergePartial<LocalDevelopmentProjectProjection>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalDevelopmentProjectProjection): LocalDevelopmentProjectProjection {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string app_id */ 1:
                    message.appId = reader.string();
                    break;
                case /* string display_name */ 2:
                    message.displayName = reader.string();
                    break;
                case /* string canonical_project_root */ 3:
                    message.canonicalProjectRoot = reader.string();
                    break;
                case /* string canonical_manifest_path */ 4:
                    message.canonicalManifestPath = reader.string();
                    break;
                case /* nimi.runtime.v1.LocalDevelopmentShellKind shell_kind */ 5:
                    message.shellKind = reader.int32();
                    break;
                case /* repeated string app_access */ 7:
                    message.appAccess.push(reader.string());
                    break;
                case /* string trust_class */ 9:
                    message.trustClass = reader.string();
                    break;
                case /* uint64 source_generation */ 10:
                    message.sourceGeneration = reader.uint64().toString();
                    break;
                case /* uint64 declaration_generation */ 11:
                    message.declarationGeneration = reader.uint64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalDevelopmentProjectProjection, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string app_id = 1; */
        if (message.appId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.appId);
        /* string display_name = 2; */
        if (message.displayName !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.displayName);
        /* string canonical_project_root = 3; */
        if (message.canonicalProjectRoot !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.canonicalProjectRoot);
        /* string canonical_manifest_path = 4; */
        if (message.canonicalManifestPath !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.canonicalManifestPath);
        /* nimi.runtime.v1.LocalDevelopmentShellKind shell_kind = 5; */
        if (message.shellKind !== 0)
            writer.tag(5, WireType.Varint).int32(message.shellKind);
        /* repeated string app_access = 7; */
        for (let i = 0; i < message.appAccess.length; i++)
            writer.tag(7, WireType.LengthDelimited).string(message.appAccess[i]);
        /* string trust_class = 9; */
        if (message.trustClass !== "")
            writer.tag(9, WireType.LengthDelimited).string(message.trustClass);
        /* uint64 source_generation = 10; */
        if (message.sourceGeneration !== "0")
            writer.tag(10, WireType.Varint).uint64(message.sourceGeneration);
        /* uint64 declaration_generation = 11; */
        if (message.declarationGeneration !== "0")
            writer.tag(11, WireType.Varint).uint64(message.declarationGeneration);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalDevelopmentProjectProjection
 */
export const LocalDevelopmentProjectProjection = new LocalDevelopmentProjectProjection$Type();
// @generated message type with reflection information, may provide speed optimized methods
class LocalDevelopmentRegistrationProjection$Type extends MessageType<LocalDevelopmentRegistrationProjection> {
    constructor() {
        super("nimi.runtime.v1.LocalDevelopmentRegistrationProjection", [
            { no: 1, name: "registration_handle", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "project", kind: "message", T: () => LocalDevelopmentProjectProjection },
            { no: 3, name: "registered_at", kind: "message", T: () => Timestamp },
            { no: 4, name: "updated_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<LocalDevelopmentRegistrationProjection>): LocalDevelopmentRegistrationProjection {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.registrationHandle = new Uint8Array(0);
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<LocalDevelopmentRegistrationProjection>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: LocalDevelopmentRegistrationProjection): LocalDevelopmentRegistrationProjection {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes registration_handle */ 1:
                    message.registrationHandle = reader.bytes();
                    break;
                case /* nimi.runtime.v1.LocalDevelopmentProjectProjection project */ 2:
                    message.project = LocalDevelopmentProjectProjection.internalBinaryRead(reader, reader.uint32(), options, message.project);
                    break;
                case /* google.protobuf.Timestamp registered_at */ 3:
                    message.registeredAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.registeredAt);
                    break;
                case /* google.protobuf.Timestamp updated_at */ 4:
                    message.updatedAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.updatedAt);
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 5:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: LocalDevelopmentRegistrationProjection, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes registration_handle = 1; */
        if (message.registrationHandle.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.registrationHandle);
        /* nimi.runtime.v1.LocalDevelopmentProjectProjection project = 2; */
        if (message.project)
            LocalDevelopmentProjectProjection.internalBinaryWrite(message.project, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp registered_at = 3; */
        if (message.registeredAt)
            Timestamp.internalBinaryWrite(message.registeredAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Timestamp updated_at = 4; */
        if (message.updatedAt)
            Timestamp.internalBinaryWrite(message.updatedAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.ReasonCode reason_code = 5; */
        if (message.reasonCode !== 0)
            writer.tag(5, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.LocalDevelopmentRegistrationProjection
 */
export const LocalDevelopmentRegistrationProjection = new LocalDevelopmentRegistrationProjection$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterLocalDevelopmentProjectRequest$Type extends MessageType<RegisterLocalDevelopmentProjectRequest> {
    constructor() {
        super("nimi.runtime.v1.RegisterLocalDevelopmentProjectRequest", [
            { no: 1, name: "expected_app_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "project_root", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "shell_kind", kind: "enum", T: () => ["nimi.runtime.v1.LocalDevelopmentShellKind", LocalDevelopmentShellKind, "LOCAL_DEVELOPMENT_SHELL_KIND_"] },
            { no: 4, name: "supervisor_run_id", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<RegisterLocalDevelopmentProjectRequest>): RegisterLocalDevelopmentProjectRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.expectedAppId = "";
        message.projectRoot = "";
        message.shellKind = 0;
        message.supervisorRunId = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<RegisterLocalDevelopmentProjectRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterLocalDevelopmentProjectRequest): RegisterLocalDevelopmentProjectRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string expected_app_id */ 1:
                    message.expectedAppId = reader.string();
                    break;
                case /* string project_root */ 2:
                    message.projectRoot = reader.string();
                    break;
                case /* nimi.runtime.v1.LocalDevelopmentShellKind shell_kind */ 3:
                    message.shellKind = reader.int32();
                    break;
                case /* bytes supervisor_run_id */ 4:
                    message.supervisorRunId = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterLocalDevelopmentProjectRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string expected_app_id = 1; */
        if (message.expectedAppId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.expectedAppId);
        /* string project_root = 2; */
        if (message.projectRoot !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.projectRoot);
        /* nimi.runtime.v1.LocalDevelopmentShellKind shell_kind = 3; */
        if (message.shellKind !== 0)
            writer.tag(3, WireType.Varint).int32(message.shellKind);
        /* bytes supervisor_run_id = 4; */
        if (message.supervisorRunId.length)
            writer.tag(4, WireType.LengthDelimited).bytes(message.supervisorRunId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RegisterLocalDevelopmentProjectRequest
 */
export const RegisterLocalDevelopmentProjectRequest = new RegisterLocalDevelopmentProjectRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RegisterLocalDevelopmentProjectResponse$Type extends MessageType<RegisterLocalDevelopmentProjectResponse> {
    constructor() {
        super("nimi.runtime.v1.RegisterLocalDevelopmentProjectResponse", [
            { no: 1, name: "registration", kind: "message", T: () => LocalDevelopmentRegistrationProjection },
            { no: 2, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<RegisterLocalDevelopmentProjectResponse>): RegisterLocalDevelopmentProjectResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<RegisterLocalDevelopmentProjectResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RegisterLocalDevelopmentProjectResponse): RegisterLocalDevelopmentProjectResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.LocalDevelopmentRegistrationProjection registration */ 1:
                    message.registration = LocalDevelopmentRegistrationProjection.internalBinaryRead(reader, reader.uint32(), options, message.registration);
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 2:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RegisterLocalDevelopmentProjectResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.LocalDevelopmentRegistrationProjection registration = 1; */
        if (message.registration)
            LocalDevelopmentRegistrationProjection.internalBinaryWrite(message.registration, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.ReasonCode reason_code = 2; */
        if (message.reasonCode !== 0)
            writer.tag(2, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RegisterLocalDevelopmentProjectResponse
 */
export const RegisterLocalDevelopmentProjectResponse = new RegisterLocalDevelopmentProjectResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLocalDevelopmentRegistrationsRequest$Type extends MessageType<ListLocalDevelopmentRegistrationsRequest> {
    constructor() {
        super("nimi.runtime.v1.ListLocalDevelopmentRegistrationsRequest", []);
    }
    create(value?: PartialMessage<ListLocalDevelopmentRegistrationsRequest>): ListLocalDevelopmentRegistrationsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<ListLocalDevelopmentRegistrationsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLocalDevelopmentRegistrationsRequest): ListLocalDevelopmentRegistrationsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLocalDevelopmentRegistrationsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.ListLocalDevelopmentRegistrationsRequest
 */
export const ListLocalDevelopmentRegistrationsRequest = new ListLocalDevelopmentRegistrationsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ListLocalDevelopmentRegistrationsResponse$Type extends MessageType<ListLocalDevelopmentRegistrationsResponse> {
    constructor() {
        super("nimi.runtime.v1.ListLocalDevelopmentRegistrationsResponse", [
            { no: 1, name: "registrations", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => LocalDevelopmentRegistrationProjection },
            { no: 2, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<ListLocalDevelopmentRegistrationsResponse>): ListLocalDevelopmentRegistrationsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.registrations = [];
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<ListLocalDevelopmentRegistrationsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ListLocalDevelopmentRegistrationsResponse): ListLocalDevelopmentRegistrationsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated nimi.runtime.v1.LocalDevelopmentRegistrationProjection registrations */ 1:
                    message.registrations.push(LocalDevelopmentRegistrationProjection.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 2:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ListLocalDevelopmentRegistrationsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated nimi.runtime.v1.LocalDevelopmentRegistrationProjection registrations = 1; */
        for (let i = 0; i < message.registrations.length; i++)
            LocalDevelopmentRegistrationProjection.internalBinaryWrite(message.registrations[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.ReasonCode reason_code = 2; */
        if (message.reasonCode !== 0)
            writer.tag(2, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.ListLocalDevelopmentRegistrationsResponse
 */
export const ListLocalDevelopmentRegistrationsResponse = new ListLocalDevelopmentRegistrationsResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveLocalDevelopmentRegistrationRequest$Type extends MessageType<RemoveLocalDevelopmentRegistrationRequest> {
    constructor() {
        super("nimi.runtime.v1.RemoveLocalDevelopmentRegistrationRequest", [
            { no: 1, name: "registration_handle", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<RemoveLocalDevelopmentRegistrationRequest>): RemoveLocalDevelopmentRegistrationRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.registrationHandle = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<RemoveLocalDevelopmentRegistrationRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveLocalDevelopmentRegistrationRequest): RemoveLocalDevelopmentRegistrationRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes registration_handle */ 1:
                    message.registrationHandle = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveLocalDevelopmentRegistrationRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes registration_handle = 1; */
        if (message.registrationHandle.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.registrationHandle);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RemoveLocalDevelopmentRegistrationRequest
 */
export const RemoveLocalDevelopmentRegistrationRequest = new RemoveLocalDevelopmentRegistrationRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RemoveLocalDevelopmentRegistrationResponse$Type extends MessageType<RemoveLocalDevelopmentRegistrationResponse> {
    constructor() {
        super("nimi.runtime.v1.RemoveLocalDevelopmentRegistrationResponse", [
            { no: 1, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<RemoveLocalDevelopmentRegistrationResponse>): RemoveLocalDevelopmentRegistrationResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<RemoveLocalDevelopmentRegistrationResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RemoveLocalDevelopmentRegistrationResponse): RemoveLocalDevelopmentRegistrationResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.ReasonCode reason_code */ 1:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RemoveLocalDevelopmentRegistrationResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.ReasonCode reason_code = 1; */
        if (message.reasonCode !== 0)
            writer.tag(1, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RemoveLocalDevelopmentRegistrationResponse
 */
export const RemoveLocalDevelopmentRegistrationResponse = new RemoveLocalDevelopmentRegistrationResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EndLocalDevelopmentRunRequest$Type extends MessageType<EndLocalDevelopmentRunRequest> {
    constructor() {
        super("nimi.runtime.v1.EndLocalDevelopmentRunRequest", [
            { no: 1, name: "registration_handle", kind: "scalar", T: 12 /*ScalarType.BYTES*/ },
            { no: 2, name: "supervisor_run_id", kind: "scalar", T: 12 /*ScalarType.BYTES*/ }
        ]);
    }
    create(value?: PartialMessage<EndLocalDevelopmentRunRequest>): EndLocalDevelopmentRunRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.registrationHandle = new Uint8Array(0);
        message.supervisorRunId = new Uint8Array(0);
        if (value !== undefined)
            reflectionMergePartial<EndLocalDevelopmentRunRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EndLocalDevelopmentRunRequest): EndLocalDevelopmentRunRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bytes registration_handle */ 1:
                    message.registrationHandle = reader.bytes();
                    break;
                case /* bytes supervisor_run_id */ 2:
                    message.supervisorRunId = reader.bytes();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EndLocalDevelopmentRunRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bytes registration_handle = 1; */
        if (message.registrationHandle.length)
            writer.tag(1, WireType.LengthDelimited).bytes(message.registrationHandle);
        /* bytes supervisor_run_id = 2; */
        if (message.supervisorRunId.length)
            writer.tag(2, WireType.LengthDelimited).bytes(message.supervisorRunId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.EndLocalDevelopmentRunRequest
 */
export const EndLocalDevelopmentRunRequest = new EndLocalDevelopmentRunRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EndLocalDevelopmentRunResponse$Type extends MessageType<EndLocalDevelopmentRunResponse> {
    constructor() {
        super("nimi.runtime.v1.EndLocalDevelopmentRunResponse", [
            { no: 1, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<EndLocalDevelopmentRunResponse>): EndLocalDevelopmentRunResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<EndLocalDevelopmentRunResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: EndLocalDevelopmentRunResponse): EndLocalDevelopmentRunResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.ReasonCode reason_code */ 1:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: EndLocalDevelopmentRunResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.ReasonCode reason_code = 1; */
        if (message.reasonCode !== 0)
            writer.tag(1, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.EndLocalDevelopmentRunResponse
 */
export const EndLocalDevelopmentRunResponse = new EndLocalDevelopmentRunResponse$Type();
