// @generated by protobuf-ts 2.11.1 with parameter long_type_string,ts_nocheck,client_none
// @generated from protobuf file "runtime/v1/runtime_target_identity.proto" (package "nimi.runtime.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message nimi.runtime.v1.RuntimeDurableLocalTargetRef
 */
export interface RuntimeDurableLocalTargetRef {
    /**
     * @generated from protobuf field: string version = 1
     */
    version: string;
    /**
     * @generated from protobuf oneof: ref
     */
    ref: {
        oneofKind: "profileBindingId";
        /**
         * @generated from protobuf field: string profile_binding_id = 2
         */
        profileBindingId: string;
    } | {
        oneofKind: "readinessRef";
        /**
         * @generated from protobuf field: string readiness_ref = 3
         */
        readinessRef: string;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message nimi.runtime.v1.RuntimeDurableCloudTargetRef
 */
export interface RuntimeDurableCloudTargetRef {
    /**
     * @generated from protobuf field: string version = 1
     */
    version: string;
    /**
     * @generated from protobuf field: string connector_id = 2
     */
    connectorId: string;
    /**
     * @generated from protobuf field: string remote_model_catalog_id = 3
     */
    remoteModelCatalogId: string;
    /**
     * @generated from protobuf field: string provider_model_id = 4
     */
    providerModelId: string;
    /**
     * @generated from protobuf field: string provider = 5
     */
    provider: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RuntimeDurableTargetRef
 */
export interface RuntimeDurableTargetRef {
    /**
     * @generated from protobuf oneof: target
     */
    target: {
        oneofKind: "localRuntime";
        /**
         * @generated from protobuf field: nimi.runtime.v1.RuntimeDurableLocalTargetRef local_runtime = 1
         */
        localRuntime: RuntimeDurableLocalTargetRef;
    } | {
        oneofKind: "cloud";
        /**
         * @generated from protobuf field: nimi.runtime.v1.RuntimeDurableCloudTargetRef cloud = 2
         */
        cloud: RuntimeDurableCloudTargetRef;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message nimi.runtime.v1.RuntimeResolvedLocalExecutionBinding
 */
export interface RuntimeResolvedLocalExecutionBinding {
    /**
     * @generated from protobuf field: string profile_binding_id = 1
     */
    profileBindingId: string;
    /**
     * @generated from protobuf field: string readiness_ref = 2
     */
    readinessRef: string;
    /**
     * @generated from protobuf field: string local_asset_id = 3
     */
    localAssetId: string;
    /**
     * @generated from protobuf field: string execution_profile_id = 4
     */
    executionProfileId: string;
    /**
     * @generated from protobuf field: string resolved_model_id = 5
     */
    resolvedModelId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RuntimeResolvedCloudExecutionBinding
 */
export interface RuntimeResolvedCloudExecutionBinding {
    /**
     * @generated from protobuf field: string connector_id = 1
     */
    connectorId: string;
    /**
     * @generated from protobuf field: string remote_model_catalog_id = 2
     */
    remoteModelCatalogId: string;
    /**
     * @generated from protobuf field: string provider_model_id = 3
     */
    providerModelId: string;
    /**
     * @generated from protobuf field: string provider = 4
     */
    provider: string;
    /**
     * @generated from protobuf field: string endpoint_profile_id = 5
     */
    endpointProfileId: string;
    /**
     * @generated from protobuf field: string connector_snapshot_id = 6
     */
    connectorSnapshotId: string;
}
/**
 * @generated from protobuf message nimi.runtime.v1.RuntimeResolvedExecutionBinding
 */
export interface RuntimeResolvedExecutionBinding {
    /**
     * @generated from protobuf field: string binding_version = 1
     */
    bindingVersion: string;
    /**
     * @generated from protobuf field: string capability = 2
     */
    capability: string;
    /**
     * @generated from protobuf field: string resolved_binding_ref = 3
     */
    resolvedBindingRef: string;
    /**
     * @generated from protobuf field: nimi.runtime.v1.RuntimeDurableTargetRef source_target_ref = 4
     */
    sourceTargetRef?: RuntimeDurableTargetRef;
    /**
     * @generated from protobuf field: string route_metadata_ref = 5
     */
    routeMetadataRef: string;
    /**
     * @generated from protobuf oneof: binding
     */
    binding: {
        oneofKind: "localRuntime";
        /**
         * @generated from protobuf field: nimi.runtime.v1.RuntimeResolvedLocalExecutionBinding local_runtime = 10
         */
        localRuntime: RuntimeResolvedLocalExecutionBinding;
    } | {
        oneofKind: "cloud";
        /**
         * @generated from protobuf field: nimi.runtime.v1.RuntimeResolvedCloudExecutionBinding cloud = 11
         */
        cloud: RuntimeResolvedCloudExecutionBinding;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class RuntimeDurableLocalTargetRef$Type extends MessageType<RuntimeDurableLocalTargetRef> {
    constructor() {
        super("nimi.runtime.v1.RuntimeDurableLocalTargetRef", [
            { no: 1, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "profile_binding_id", kind: "scalar", oneof: "ref", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "readiness_ref", kind: "scalar", oneof: "ref", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RuntimeDurableLocalTargetRef>): RuntimeDurableLocalTargetRef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.version = "";
        message.ref = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<RuntimeDurableLocalTargetRef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuntimeDurableLocalTargetRef): RuntimeDurableLocalTargetRef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string version */ 1:
                    message.version = reader.string();
                    break;
                case /* string profile_binding_id */ 2:
                    message.ref = {
                        oneofKind: "profileBindingId",
                        profileBindingId: reader.string()
                    };
                    break;
                case /* string readiness_ref */ 3:
                    message.ref = {
                        oneofKind: "readinessRef",
                        readinessRef: reader.string()
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuntimeDurableLocalTargetRef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string version = 1; */
        if (message.version !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.version);
        /* string profile_binding_id = 2; */
        if (message.ref.oneofKind === "profileBindingId")
            writer.tag(2, WireType.LengthDelimited).string(message.ref.profileBindingId);
        /* string readiness_ref = 3; */
        if (message.ref.oneofKind === "readinessRef")
            writer.tag(3, WireType.LengthDelimited).string(message.ref.readinessRef);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RuntimeDurableLocalTargetRef
 */
export const RuntimeDurableLocalTargetRef = new RuntimeDurableLocalTargetRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuntimeDurableCloudTargetRef$Type extends MessageType<RuntimeDurableCloudTargetRef> {
    constructor() {
        super("nimi.runtime.v1.RuntimeDurableCloudTargetRef", [
            { no: 1, name: "version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "connector_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "remote_model_catalog_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "provider_model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RuntimeDurableCloudTargetRef>): RuntimeDurableCloudTargetRef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.version = "";
        message.connectorId = "";
        message.remoteModelCatalogId = "";
        message.providerModelId = "";
        message.provider = "";
        if (value !== undefined)
            reflectionMergePartial<RuntimeDurableCloudTargetRef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuntimeDurableCloudTargetRef): RuntimeDurableCloudTargetRef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string version */ 1:
                    message.version = reader.string();
                    break;
                case /* string connector_id */ 2:
                    message.connectorId = reader.string();
                    break;
                case /* string remote_model_catalog_id */ 3:
                    message.remoteModelCatalogId = reader.string();
                    break;
                case /* string provider_model_id */ 4:
                    message.providerModelId = reader.string();
                    break;
                case /* string provider */ 5:
                    message.provider = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuntimeDurableCloudTargetRef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string version = 1; */
        if (message.version !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.version);
        /* string connector_id = 2; */
        if (message.connectorId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.connectorId);
        /* string remote_model_catalog_id = 3; */
        if (message.remoteModelCatalogId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.remoteModelCatalogId);
        /* string provider_model_id = 4; */
        if (message.providerModelId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.providerModelId);
        /* string provider = 5; */
        if (message.provider !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.provider);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RuntimeDurableCloudTargetRef
 */
export const RuntimeDurableCloudTargetRef = new RuntimeDurableCloudTargetRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuntimeDurableTargetRef$Type extends MessageType<RuntimeDurableTargetRef> {
    constructor() {
        super("nimi.runtime.v1.RuntimeDurableTargetRef", [
            { no: 1, name: "local_runtime", kind: "message", oneof: "target", T: () => RuntimeDurableLocalTargetRef },
            { no: 2, name: "cloud", kind: "message", oneof: "target", T: () => RuntimeDurableCloudTargetRef }
        ]);
    }
    create(value?: PartialMessage<RuntimeDurableTargetRef>): RuntimeDurableTargetRef {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.target = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<RuntimeDurableTargetRef>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuntimeDurableTargetRef): RuntimeDurableTargetRef {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* nimi.runtime.v1.RuntimeDurableLocalTargetRef local_runtime */ 1:
                    message.target = {
                        oneofKind: "localRuntime",
                        localRuntime: RuntimeDurableLocalTargetRef.internalBinaryRead(reader, reader.uint32(), options, (message.target as any).localRuntime)
                    };
                    break;
                case /* nimi.runtime.v1.RuntimeDurableCloudTargetRef cloud */ 2:
                    message.target = {
                        oneofKind: "cloud",
                        cloud: RuntimeDurableCloudTargetRef.internalBinaryRead(reader, reader.uint32(), options, (message.target as any).cloud)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuntimeDurableTargetRef, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* nimi.runtime.v1.RuntimeDurableLocalTargetRef local_runtime = 1; */
        if (message.target.oneofKind === "localRuntime")
            RuntimeDurableLocalTargetRef.internalBinaryWrite(message.target.localRuntime, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.RuntimeDurableCloudTargetRef cloud = 2; */
        if (message.target.oneofKind === "cloud")
            RuntimeDurableCloudTargetRef.internalBinaryWrite(message.target.cloud, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RuntimeDurableTargetRef
 */
export const RuntimeDurableTargetRef = new RuntimeDurableTargetRef$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuntimeResolvedLocalExecutionBinding$Type extends MessageType<RuntimeResolvedLocalExecutionBinding> {
    constructor() {
        super("nimi.runtime.v1.RuntimeResolvedLocalExecutionBinding", [
            { no: 1, name: "profile_binding_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "readiness_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "local_asset_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "execution_profile_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "resolved_model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RuntimeResolvedLocalExecutionBinding>): RuntimeResolvedLocalExecutionBinding {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.profileBindingId = "";
        message.readinessRef = "";
        message.localAssetId = "";
        message.executionProfileId = "";
        message.resolvedModelId = "";
        if (value !== undefined)
            reflectionMergePartial<RuntimeResolvedLocalExecutionBinding>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuntimeResolvedLocalExecutionBinding): RuntimeResolvedLocalExecutionBinding {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string profile_binding_id */ 1:
                    message.profileBindingId = reader.string();
                    break;
                case /* string readiness_ref */ 2:
                    message.readinessRef = reader.string();
                    break;
                case /* string local_asset_id */ 3:
                    message.localAssetId = reader.string();
                    break;
                case /* string execution_profile_id */ 4:
                    message.executionProfileId = reader.string();
                    break;
                case /* string resolved_model_id */ 5:
                    message.resolvedModelId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuntimeResolvedLocalExecutionBinding, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string profile_binding_id = 1; */
        if (message.profileBindingId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.profileBindingId);
        /* string readiness_ref = 2; */
        if (message.readinessRef !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.readinessRef);
        /* string local_asset_id = 3; */
        if (message.localAssetId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.localAssetId);
        /* string execution_profile_id = 4; */
        if (message.executionProfileId !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.executionProfileId);
        /* string resolved_model_id = 5; */
        if (message.resolvedModelId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.resolvedModelId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RuntimeResolvedLocalExecutionBinding
 */
export const RuntimeResolvedLocalExecutionBinding = new RuntimeResolvedLocalExecutionBinding$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuntimeResolvedCloudExecutionBinding$Type extends MessageType<RuntimeResolvedCloudExecutionBinding> {
    constructor() {
        super("nimi.runtime.v1.RuntimeResolvedCloudExecutionBinding", [
            { no: 1, name: "connector_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "remote_model_catalog_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "provider_model_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "provider", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "endpoint_profile_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 6, name: "connector_snapshot_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<RuntimeResolvedCloudExecutionBinding>): RuntimeResolvedCloudExecutionBinding {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.connectorId = "";
        message.remoteModelCatalogId = "";
        message.providerModelId = "";
        message.provider = "";
        message.endpointProfileId = "";
        message.connectorSnapshotId = "";
        if (value !== undefined)
            reflectionMergePartial<RuntimeResolvedCloudExecutionBinding>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuntimeResolvedCloudExecutionBinding): RuntimeResolvedCloudExecutionBinding {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string connector_id */ 1:
                    message.connectorId = reader.string();
                    break;
                case /* string remote_model_catalog_id */ 2:
                    message.remoteModelCatalogId = reader.string();
                    break;
                case /* string provider_model_id */ 3:
                    message.providerModelId = reader.string();
                    break;
                case /* string provider */ 4:
                    message.provider = reader.string();
                    break;
                case /* string endpoint_profile_id */ 5:
                    message.endpointProfileId = reader.string();
                    break;
                case /* string connector_snapshot_id */ 6:
                    message.connectorSnapshotId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuntimeResolvedCloudExecutionBinding, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string connector_id = 1; */
        if (message.connectorId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.connectorId);
        /* string remote_model_catalog_id = 2; */
        if (message.remoteModelCatalogId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.remoteModelCatalogId);
        /* string provider_model_id = 3; */
        if (message.providerModelId !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.providerModelId);
        /* string provider = 4; */
        if (message.provider !== "")
            writer.tag(4, WireType.LengthDelimited).string(message.provider);
        /* string endpoint_profile_id = 5; */
        if (message.endpointProfileId !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.endpointProfileId);
        /* string connector_snapshot_id = 6; */
        if (message.connectorSnapshotId !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.connectorSnapshotId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RuntimeResolvedCloudExecutionBinding
 */
export const RuntimeResolvedCloudExecutionBinding = new RuntimeResolvedCloudExecutionBinding$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RuntimeResolvedExecutionBinding$Type extends MessageType<RuntimeResolvedExecutionBinding> {
    constructor() {
        super("nimi.runtime.v1.RuntimeResolvedExecutionBinding", [
            { no: 1, name: "binding_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "capability", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "resolved_binding_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "source_target_ref", kind: "message", T: () => RuntimeDurableTargetRef },
            { no: 5, name: "route_metadata_ref", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 10, name: "local_runtime", kind: "message", oneof: "binding", T: () => RuntimeResolvedLocalExecutionBinding },
            { no: 11, name: "cloud", kind: "message", oneof: "binding", T: () => RuntimeResolvedCloudExecutionBinding }
        ]);
    }
    create(value?: PartialMessage<RuntimeResolvedExecutionBinding>): RuntimeResolvedExecutionBinding {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.bindingVersion = "";
        message.capability = "";
        message.resolvedBindingRef = "";
        message.routeMetadataRef = "";
        message.binding = { oneofKind: undefined };
        if (value !== undefined)
            reflectionMergePartial<RuntimeResolvedExecutionBinding>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RuntimeResolvedExecutionBinding): RuntimeResolvedExecutionBinding {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string binding_version */ 1:
                    message.bindingVersion = reader.string();
                    break;
                case /* string capability */ 2:
                    message.capability = reader.string();
                    break;
                case /* string resolved_binding_ref */ 3:
                    message.resolvedBindingRef = reader.string();
                    break;
                case /* nimi.runtime.v1.RuntimeDurableTargetRef source_target_ref */ 4:
                    message.sourceTargetRef = RuntimeDurableTargetRef.internalBinaryRead(reader, reader.uint32(), options, message.sourceTargetRef);
                    break;
                case /* string route_metadata_ref */ 5:
                    message.routeMetadataRef = reader.string();
                    break;
                case /* nimi.runtime.v1.RuntimeResolvedLocalExecutionBinding local_runtime */ 10:
                    message.binding = {
                        oneofKind: "localRuntime",
                        localRuntime: RuntimeResolvedLocalExecutionBinding.internalBinaryRead(reader, reader.uint32(), options, (message.binding as any).localRuntime)
                    };
                    break;
                case /* nimi.runtime.v1.RuntimeResolvedCloudExecutionBinding cloud */ 11:
                    message.binding = {
                        oneofKind: "cloud",
                        cloud: RuntimeResolvedCloudExecutionBinding.internalBinaryRead(reader, reader.uint32(), options, (message.binding as any).cloud)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RuntimeResolvedExecutionBinding, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string binding_version = 1; */
        if (message.bindingVersion !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.bindingVersion);
        /* string capability = 2; */
        if (message.capability !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.capability);
        /* string resolved_binding_ref = 3; */
        if (message.resolvedBindingRef !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.resolvedBindingRef);
        /* nimi.runtime.v1.RuntimeDurableTargetRef source_target_ref = 4; */
        if (message.sourceTargetRef)
            RuntimeDurableTargetRef.internalBinaryWrite(message.sourceTargetRef, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string route_metadata_ref = 5; */
        if (message.routeMetadataRef !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.routeMetadataRef);
        /* nimi.runtime.v1.RuntimeResolvedLocalExecutionBinding local_runtime = 10; */
        if (message.binding.oneofKind === "localRuntime")
            RuntimeResolvedLocalExecutionBinding.internalBinaryWrite(message.binding.localRuntime, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* nimi.runtime.v1.RuntimeResolvedCloudExecutionBinding cloud = 11; */
        if (message.binding.oneofKind === "cloud")
            RuntimeResolvedCloudExecutionBinding.internalBinaryWrite(message.binding.cloud, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RuntimeResolvedExecutionBinding
 */
export const RuntimeResolvedExecutionBinding = new RuntimeResolvedExecutionBinding$Type();
