// @generated by protobuf-ts 2.11.1 with parameter long_type_string,ts_nocheck,client_none
// @generated from protobuf file "runtime/v1/runtime_service_control.proto" (package "nimi.runtime.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { ReasonCode } from "./common";
/**
 * RequestRuntimeRestartRequest is intentionally empty. The mutually verified
 * desktop_control connection and its live boot-scoped Desktop session are the
 * complete authority input; service name, path, endpoint, timeout, recovery
 * policy, and portable credentials are forbidden request data.
 *
 * @generated from protobuf message nimi.runtime.v1.RequestRuntimeRestartRequest
 */
export interface RequestRuntimeRestartRequest {
}
/**
 * @generated from protobuf message nimi.runtime.v1.RequestRuntimeRestartResponse
 */
export interface RequestRuntimeRestartResponse {
    /**
     * @generated from protobuf field: bool accepted = 1
     */
    accepted: boolean;
    /**
     * @generated from protobuf field: nimi.runtime.v1.ReasonCode reason_code = 2
     */
    reasonCode: ReasonCode;
}
// @generated message type with reflection information, may provide speed optimized methods
class RequestRuntimeRestartRequest$Type extends MessageType<RequestRuntimeRestartRequest> {
    constructor() {
        super("nimi.runtime.v1.RequestRuntimeRestartRequest", []);
    }
    create(value?: PartialMessage<RequestRuntimeRestartRequest>): RequestRuntimeRestartRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<RequestRuntimeRestartRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestRuntimeRestartRequest): RequestRuntimeRestartRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequestRuntimeRestartRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RequestRuntimeRestartRequest
 */
export const RequestRuntimeRestartRequest = new RequestRuntimeRestartRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class RequestRuntimeRestartResponse$Type extends MessageType<RequestRuntimeRestartResponse> {
    constructor() {
        super("nimi.runtime.v1.RequestRuntimeRestartResponse", [
            { no: 1, name: "accepted", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 2, name: "reason_code", kind: "enum", T: () => ["nimi.runtime.v1.ReasonCode", ReasonCode] }
        ]);
    }
    create(value?: PartialMessage<RequestRuntimeRestartResponse>): RequestRuntimeRestartResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.accepted = false;
        message.reasonCode = 0;
        if (value !== undefined)
            reflectionMergePartial<RequestRuntimeRestartResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: RequestRuntimeRestartResponse): RequestRuntimeRestartResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* bool accepted */ 1:
                    message.accepted = reader.bool();
                    break;
                case /* nimi.runtime.v1.ReasonCode reason_code */ 2:
                    message.reasonCode = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: RequestRuntimeRestartResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* bool accepted = 1; */
        if (message.accepted !== false)
            writer.tag(1, WireType.Varint).bool(message.accepted);
        /* nimi.runtime.v1.ReasonCode reason_code = 2; */
        if (message.reasonCode !== 0)
            writer.tag(2, WireType.Varint).int32(message.reasonCode);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message nimi.runtime.v1.RequestRuntimeRestartResponse
 */
export const RequestRuntimeRestartResponse = new RequestRuntimeRestartResponse$Type();
