import type { LandingContent } from './landing-content.js';

const EN_SPEC_NOTE = `Authority: .nimi/spec/**
Docs: /docs/reference/spec-map
Boundary: public projection, not independent truth`;

export const landingContentEn: LandingContent = {
  skipToContent: 'Skip to main content',
  nav: {
    enterNimi: 'Enter Nimi',
    install: 'Start',
    sdk: 'SDK',
    catalog: 'Runtime',
    architecture: 'Platform',
    desktop: 'Desktop',
    security: 'Governance',
    mods: 'Mods',
    openSource: 'Source',
    faq: 'FAQ',
  },
  hero: {
    eyebrow: 'Open-source AI runtime',
    title: 'Build agents that live in worlds,',
    titleAccent: 'not chats.',
    subtitle: 'Open-source runtime, typed SDK, embodied agents — built on contracts you can read.',
    helperPrefix: 'Or',
    helperDocsCta: 'Read Docs',
    helperGithubCta: 'View Source',
    copyTooltipLabel: 'Copy link',
    copiedCommandLabel: 'Copied',
    previewAlt: 'Nimi runtime quickstart preview',
    getStartedTitle: 'Quickstart',
    getStartedSubtitle: 'Pick your integration entry',
    tabs: [
      { id: 'platform', label: 'Platform', command: '/docs/platform/', ctaText: 'Read Platform Docs' },
      { id: 'runtime', label: 'Runtime', command: '/docs/runtime/', ctaText: 'Read Runtime Docs' },
      { id: 'sdk', label: 'SDK', command: '/docs/sdk/', ctaText: 'Read SDK Docs' },
    ],
  },
  architecture: {
    title: 'One platform, many worlds.',
    subtitle: 'Architecture',
    description: 'Nimi gives you a typed SDK to build AI experiences that span persistent worlds, autonomous agents, shared memory, identity, social, and economy — bridged by a runtime you can run locally or in the cloud.',
    devTitle: 'For builders',
    devText: 'Integrate through the typed SDK. Compose agents, models, workflows, and memory the same way whether they run on a laptop or in cloud infrastructure you control.',
    userTitle: 'For product readers',
    userText: 'Nimi is an AI open world platform — agents that persist across sessions, share state across worlds, and act through admitted runtime capabilities. Not a chat wrapper, not a single-purpose app.',
    conclusion: 'Concept-led, contracts-first, runtime-anywhere.',
    slogan: 'Your code, your contracts, your worlds.',
    diagram: {
      appLabel: 'YOUR AI APP / MOD',
      realm: 'REALM',
      runtime: 'RUNTIME',
      cloudContextPlane: 'Cloud Context Plane',
      localExecutionPlane: 'Local Execution Plane',
      cloudContext: 'Cloud Context',
      localCompute: 'Local Compute',
      realmDomains: [
        { id: 'worlds', label: 'Worlds', icon: '\u{1F310}' },
        { id: 'agents', label: 'Agents', icon: '\u{1F916}' },
        { id: 'social', label: 'Social', icon: '\u{1F465}' },
        { id: 'economy', label: 'Economy', icon: '\u{1F4B0}' },
        { id: 'memory', label: 'Memory', icon: '\u{1F9E0}' },
        { id: 'identity', label: 'Identity', icon: '\u{1F464}' },
      ],
      runtimeCapabilities: [
        { id: 'ai-models', label: 'AI Models', icon: '\u{1F9E0}' },
        { id: 'workflows', label: 'Workflows', icon: '\u{26A1}' },
        { id: 'knowledge', label: 'Knowledge', icon: '\u{1F4DA}' },
      ],
      crossCutting: [
        { id: 'unified-account', label: 'Unified Account', icon: '\u{1F464}' },
        { id: 'shared-data', label: 'Shared Data', icon: '\u{1F4BE}' },
        { id: 'shared-auth', label: 'Shared Authorization', icon: '\u{1F512}' },
        { id: 'persistent-presence', label: 'Persistent Cross-World Presence', icon: '\u{1F310}' },
        { id: 'multi-world-exploration', label: 'Multi-World Exploration', icon: '\u{1F9ED}' },
        { id: 'seamless-ai', label: 'Seamless AI Experience', icon: '\u{2728}' },
      ],
      transportLabels: { rest: 'REST + WebSocket', grpc: 'gRPC' },
      mobileFallback: {
        sdkLabel: '@nimi/sdk',
        sdkDescription: 'Single surface connecting to local and cloud intelligence.',
      },
    },
  },
  modelCatalog: {
    kicker: 'Runtime governance',
    title: 'Provider and model claims are evidence-gated',
    subtitle: 'The landing page now describes the contract boundary instead of publishing an unadmitted model catalog.',
    overview: {
      searchPlaceholder: 'catalog details require admitted runtime evidence',
      cloudProvidersLabel: 'Cloud surfaces',
      localModelsLabel: 'Local surfaces',
      modalitiesLabel: 'Capabilities',
      modalitiesValue: 'GATED',
      modalitiesDescription: 'Contract-level only until catalog evidence is admitted',
      industryLeadersLabel: 'Evidence gate',
      shortcutLabel: 'Spec',
      clearSearchLabel: 'Clear',
      matchingProvidersLabel: 'matching entries',
      liveCatalogLabel: 'Evidence-gated',
    },
    liveBadge: 'Contract-level',
    featuredProvidersLabel: 'Provider details',
    featuredProviders: ['Admitted catalog evidence required'],
    stats: { providers: 'provider surfaces', models: 'model entries', cloudProviders: 'cloud routes', localModels: 'local routes' },
    localTitle: 'Local execution',
    localHeadline: 'Local capability claims require owner evidence.',
    localDescription: 'Runtime owns local execution contracts, device profiles, scheduling, and capability routing. Landing copy does not turn those contracts into availability promises.',
    capabilitiesTitle: 'Capability governance',
    capabilitiesHeadline: 'Capabilities stay contract-routed until evidence is admitted.',
    capabilitiesDescription: 'Text, embeddings, image, video, TTS, and STT are runtime capability categories. Detailed public availability belongs to admitted runtime catalog evidence.',
    capabilityLabels: {
      'text.generate': 'Text generation',
      'text.embed': 'Embeddings',
      'image.generate': 'Image generation',
      'video.generate': 'Video generation',
      'audio.synthesize': 'Speech synthesis',
      'audio.transcribe': 'Speech transcription',
      'music.generate': 'Music generation',
      'music.generate.iteration': 'Music iteration',
      'text.generate.vision': 'Vision-language generation',
      'voice_workflow.voice_clone': 'Voice cloning',
      'voice_workflow.voice_design': 'Voice design',
      'world.generate': 'World generation',
    },
    capabilityCountLabel: 'contract categories',
    cloudBadge: 'contract',
    matrixTitle: 'Catalog gate',
    matrixHeadline: 'No detailed provider listing without admitted evidence.',
    matrixDescription: 'Provider/model details are removed from landing until the runtime catalog evidence is admitted for publication.',
    providerDetailSuffix: 'entries require catalog evidence',
    searchResultsTitle: 'Evidence gate',
    searchResultsDescription: 'Search results are disabled until provider/model catalog evidence is admitted.',
    noResultsTitle: 'Provider/model details are gated.',
    noResultsDescription: 'Read runtime contracts and the spec map for current authority.',
    sourceNote: 'Source anchors: docs/runtime/index.md, docs/runtime/providers-and-models.md, .nimi/spec/runtime/kernel/model-catalog-contract.md, .nimi/spec/runtime/kernel/provider-health-contract.md.',
  },
  sdk: {
    title: 'SDK is the official app-facing boundary',
    subtitle: 'Apps integrate through admitted SDK surfaces instead of bypassing runtime or realm owner boundaries.',
    tabs: [
      { label: 'Authority', snippet: EN_SPEC_NOTE, caption: 'Public claims resolve to docs and .nimi/spec/**.' },
      { label: 'Runtime', snippet: 'docs/runtime/index.md -> .nimi/spec/runtime/kernel/index.md', caption: 'Runtime owns execution substrate contracts.' },
      { label: 'SDK', snippet: 'docs/sdk/index.md -> .nimi/spec/sdk/kernel/boundary-contract.md', caption: 'SDK owns the app-facing access boundary.' },
      { label: 'Realm', snippet: 'docs/realm/index.md -> .nimi/spec/realm/README.md', caption: 'Realm owns semantic truth and world state.' },
    ],
    previewLabel: 'SDK boundary',
    previewAlt: 'Nimi SDK boundary',
    previewCaption: 'SDK is the public integration route; private runtime and realm owner surfaces remain protected.',
    multimodalLabel: 'Runtime capability routing',
    multimodalAlt: 'Runtime capability routing',
    multimodalCaption: 'Capability categories are described at contract level until publication evidence is admitted.',
    callout: 'Integrate through authority, not shortcuts.',
  },
  desktop: {
    title: 'Desktop and Web have different authority',
    subtitle: 'Desktop is the native shell. Web is a constrained projection with explicit disabled native/local capabilities.',
    screenshotAlt: 'Nimi desktop and web boundary',
    features: [
      { icon: 'dashboard', title: 'Native shell', description: 'Desktop owns native shell surfaces through desktop kernel contracts.' },
      { icon: 'chat', title: 'Runtime route', description: 'AI execution remains routed through runtime contracts.' },
      { icon: 'mods', title: 'Governed mods', description: 'Mods are governed extension surfaces, not unrestricted plugin claims.' },
      { icon: 'models', title: 'Web boundary', description: 'Web mode does not imply desktop-native capability support.' },
    ],
    downloadCta: 'Read Desktop Boundary',
    availability: { eyebrow: 'Boundary', items: ['Desktop source: .nimi/spec/desktop/kernel/index.md', 'Web source: .nimi/spec/desktop/web-adapter.md', 'Release/distribution claims require admitted evidence'] },
  },
  faq: {
    eyebrow: 'FAQ',
    title: 'What the landing page can claim now',
    description: 'This surface is intentionally bounded to approved docs/spec truth.',
    communityCta: 'Join Discord',
    items: [
      { question: 'Is Nimi just a runtime?', answer: 'No. Runtime is the adoption path. Nimi is a platform model with Realm, SDK, Desktop/Web, Avatar, Cognition, and Nimi Coding surfaces.' },
      { question: 'Where do claims come from?', answer: 'Public claims come from docs pages that map back to .nimi/spec/** anchors.' },
      { question: 'Why are provider/model details gated?', answer: 'Detailed catalog claims require admitted runtime catalog evidence before publication.' },
      { question: 'Is Web the same as Desktop?', answer: 'No. Web is a constrained projection and must not imply desktop-native capabilities.' },
    ],
  },
  security: {
    title: 'Governance before claims',
    subtitle: 'Authority boundaries are part of the product surface.',
    intro: 'Nimi public surfaces are constrained by source ownership, admission gates, and explicit closeout evidence.',
    pillars: [
      { label: 'Authority', title: 'Spec-first truth', points: ['.nimi/spec/** owns public product and behavior authority.', 'Docs and landing are projections of that source.'] },
      { label: 'Boundary', title: 'Owner cuts stay visible', points: ['Runtime, SDK, Desktop, Realm, Avatar, Cognition, and Nimi Coding keep distinct ownership.', 'Private realm and mods truth stay in their owner surfaces.'] },
      { label: 'Evidence', title: 'Claims are gated', points: ['Provider/model and release claims require admitted evidence.', 'Future backlog is not current product truth.'] },
    ],
  },
  mods: {
    title: 'Mods are governed extension surfaces',
    subtitle: 'Landing copy describes the governance boundary, not an unadmitted marketplace.',
    items: [
      { icon: 'docs', name: 'Capability contracts', description: 'Mods route through admitted hook and capability contracts.' },
      { icon: 'sim', name: 'Owner boundaries', description: 'Mods must not bypass runtime, SDK, or desktop owner cuts.' },
      { icon: 'story', name: 'Future catalog', description: 'Public mod catalog claims require separate evidence admission.' },
    ],
    buildModCta: 'Read Desktop Mods Boundary',
  },
  openSource: {
    title: 'Open source with explicit authority',
    subtitle: 'The repository is readable, but not every file is source truth.',
    description: 'Use the spec map to distinguish public authority, implementation evidence, generated projections, private owner surfaces, and topic-local lifecycle records.',
    githubCta: 'View GitHub',
    docsCta: 'Read Spec Map',
  },
  finalCta: {
    title: 'Read Nimi from the source map',
    description: 'Start with platform docs, then resolve claims to .nimi/spec/** before treating them as product truth.',
    primaryCta: 'Read Docs',
    githubCta: 'View Source',
  },
  footer: { line1: 'Open-source AI runtime for apps. One CLI, one SDK, local and cloud AI.', line2: 'Read the docs to see what ships today and what is on the roadmap.', termsLabel: 'Terms', privacyLabel: 'Privacy' },
  localeToggleLabel: 'Language',
  localeOptions: {
    en: 'English',
    zh: '中文',
    switchToEn: 'Switch language to English',
    switchToZh: 'Switch language to Chinese',
  },
};
