import type { HeroDemoShijingPreview } from './landing-content.js';
import { shijingMingjingPreviewContent } from './landing-content.shijing-mingjing.js';

/**
 * ShiJing (时镜) preview content. The app is zh-CN-first and its product
 * copy lives in nimiapp-shijing `src/product/i18n/zh/*`; the labels here
 * mirror those tables (tab names, 今日总览 meter copy, 30日行动指南 panel, 问镜
 * composer) while the readings themselves are mock data for one demo user.
 */
export const shijingPreviewContent: HeroDemoShijingPreview = {
  appName: '时镜 ShiJing',
  brandName: '时镜',
  brandTagline: 'SHIJING · OS',
  accountName: '演示用户',
  accountMenuLabel: '账户菜单',
  navAriaLabel: '时镜六镜',
  // METHOD_LABELS (nimiapp-shijing product/reading/reading-format.ts) in the app's admitted order.
  methodProfiles: [
    { id: 'bazi_ziping_v1', label: '八字子平法' },
    { id: 'ziwei_sanhe_v1', label: '紫微斗数(三合派)' },
    { id: 'qizheng_siyu_guolao_v1', label: '七政四余/果老星宗' },
  ],
  tabs: [
    { id: 'rijing', label: '日镜' },
    { id: 'yuejing', label: '月镜' },
    { id: 'nianjing', label: '年镜' },
    { id: 'mingjing', label: '命镜' },
    { id: 'hejing', label: '合镜' },
    { id: 'shijing', label: '问镜' },
  ],
  rijing: {
    title: '日镜',
    refreshLabel: '刷新今日',
    refreshingLabel: '生成中…',
    refreshedHint: '今日日镜已按当前关注重新生成。',
    importLabel: '带入问镜',
    hero: {
      eyebrow: '今日总览',
      headline: '顺势承担',
      subtitle: '今天的能量偏向外放，适合把已经酝酿好的事情推出去；但在承诺之前，先确认对方是否真的准备好了。',
      leanings: [
        { label: '助力', tone: 'supportive' },
        { label: '观察', tone: 'watch' },
      ],
      meter: { percent: 68, band: '偏旺', stage: '进时', guidance: '宜进取，顺势主动' },
      meterAxisStart: '收敛蓄力',
      meterAxisEnd: '向外扩张',
      meterStrengthLabel: '旺衰',
      meterStageConnector: '· 处于',
      meterStageSuffix: '阶段，',
      confidencePrefix: '可信度',
      confidenceLabel: '较高',
      confidenceNote: '推演基于完整资料，结论可作为节奏参考。',
      eventTitle: '今日事件解析',
      eventBody: '你记下了「下午要谈一个重要合作」。今日日柱与月令相生，谈判本身有推进的势头；变数在于对方的决策节奏比你慢半拍。',
      eventGuidance: '把提案分成"今天能定"和"可以晚点定"两部分，先把前者敲实。对方犹豫时不要急着补条件，留一天让他消化，往往比当场让步更有利。',
      eventAction: '可以先落到一个小动作：会前把最想达成的一条写在纸上，只争取这一条。',
      closingLabel: '寄语',
      closingWish: '命由天定，运由己造；愿你在今天的节奏里，稳稳拿回自己的选择权。',
      flipToRite: '看今日黄历',
      flipToOverview: '返回日镜',
      rite: {
        eyebrow: '通用黄历',
        lunarTitle: '八月初九',
        ganzhiLine: '丙午年 · 丁酉月 · 甲子日',
        suitableTitle: '宜',
        suitable: ['开市', '签约', '出行', '会友', '纳财'],
        unsuitableTitle: '忌',
        unsuitable: ['动土', '安葬', '词讼'],
        cells: [
          { label: '喜神', value: '东北' },
          { label: '财神', value: '东南' },
          { label: '福神', value: '东南' },
          { label: '冲煞', value: '冲马 · 煞南' },
          { label: '值神', value: '青龙（黄道日）' },
          { label: '五行', value: '海中金' },
        ],
        hoursTitle: '时辰吉凶',
        hours: [
          { branch: '子', luck: '吉' }, { branch: '丑', luck: '凶' }, { branch: '寅', luck: '吉' }, { branch: '卯', luck: '平' },
          { branch: '辰', luck: '吉' }, { branch: '巳', luck: '凶' }, { branch: '午', luck: '吉' }, { branch: '未', luck: '平' },
          { branch: '申', luck: '吉' }, { branch: '酉', luck: '凶' }, { branch: '戌', luck: '平' }, { branch: '亥', luck: '吉' },
        ],
      },
    },
    projections: {
      title: '今日关注分镜',
      allLabel: '全部',
      manageLabel: '编辑关注',
      rows: [
        { id: 'career', name: '事业', tone: 'supportive', tendencyLabel: '助力', takeaway: '推进合作正当时，先把最关键的一条谈定，其余留给下周。', detail: '日主偏旺而月令相生，行动力和说服力都在线。对方处于观望，你的优势在于节奏而不是让步：先把"今天必须定"的一条讲清楚，其余条款主动提议改天再谈，反而显得从容。' },
        { id: 'relationship', name: '关系', tone: 'watch', tendencyLabel: '观察', takeaway: '容易把工作里的急躁带回家，晚上多留十分钟听对方说完。', detail: '今日火气偏盛，沟通里容易抢话。关系本身没有明显冲克，但对方对你语气的敏感度会高于平常。回家后先不谈安排，听完再说，是今天最省力的相处方式。' },
        { id: 'health', name: '身心', tone: 'steady', tendencyLabel: '平稳', takeaway: '精力充足，但下午三点后容易透支，安排一段十五分钟的放空。', detail: '整体能量偏旺，短时间高强度输出没有问题，问题在于恢复。午后安排一段不看屏幕的时间，晚上不要用工作填满，今天的"旺"才能延续到明天。' },
      ],
    },
    eventInput: {
      title: '今日参照',
      intro: '补充一件今天正在发生的事，系统会结合这件事与当前关注视角整理今日判断。',
      placeholder: '例如：下午要谈一个重要合作，心里有点不确定……',
      submit: '加入今日参照',
      successHint: '已加入今日参照，今日判断会优先结合这件事来看。',
      refsBadge: '已结合今日判断',
      references: ['下午要谈一个重要合作，心里有点不确定。'],
    },
    actions: {
      title: '今日行动',
      groups: [
        { id: 'career', name: '事业', recommendations: ['会前只写下最想达成的一条', '对方犹豫时留一天再回复', '把次要条款主动挪到下周'] },
        { id: 'relationship', name: '关系', recommendations: ['回家先听十分钟再说安排', '今天不在饭桌上谈工作'] },
        { id: 'health', name: '身心', recommendations: ['午后十五分钟不看屏幕', '晚上十点前结束工作'] },
      ],
    },
    evidence: {
      title: '推演依据与数据说明',
      chips: [
        { label: '旺衰', value: '偏旺' },
        { label: '用神 · 喜用', value: '水 · 金' },
        { label: '四柱 · 已知', value: '四柱齐备' },
        { label: '阶段驱动', value: '进时' },
        { label: '数据完整度', value: '已知 4/4' },
      ],
    },
  },
  yuejing: {
    title: '月镜',
    generatedAgo: '上次生成 2 小时前',
    importLabel: '导入到问镜',
    generateLabel: '已完成',
    startDate: '2026-09-20',
    weekdayHeaders: ['一', '二', '三', '四', '五', '六', '日'],
    weekdayShort: ['周一', '周二', '周三', '周四', '周五', '周六', '周日'],
    tendencyLabels: { supportive: '助力', steady: '平稳', watch: '观察', turning: '转折', blocked: '阻滞' },
    todayBodyByTone: {
      supportive: '整体助力,今天适合主动推进。',
      steady: '节奏平稳,适合按部就班的推进。',
      watch: '需要观察,留意细节与节奏。',
      blocked: '运势阻滞,宜守不宜攻。',
      turning: '局面转折,留意拐点信号。',
    },
    hero: {
      ariaLabel: '今日总览',
      eyebrow: '今日 · 总览',
      rowsAriaLabel: '今日各关注倾向',
      pending: '待生成',
      detailButton: '查看行动指南',
    },
    concernLimit: 5,
    concerns: [
      {
        id: 'career',
        name: '事业',
        subtitle: '工作 · 项目 · 产出',
        tones: [
          'supportive', 'supportive', 'supportive', 'steady', 'supportive', 'supportive', 'supportive', 'watch', 'steady', 'watch',
          'watch', 'blocked', 'steady', 'supportive', 'supportive', 'turning', 'turning', 'supportive', 'supportive', 'supportive',
          'steady', 'supportive', 'steady', 'turning', 'turning', 'steady', 'supportive', 'steady', 'steady', 'watch',
        ],
        details: {
          '2026-09-20': '推进合作正当时，先把最关键的一条谈定，其余留给下周。',
          '2026-09-30': '对方在观望，今天只收信息，不补条件。',
          '2026-10-09': '方案终稿提交日，把能确认的都确认掉。',
        },
      },
      {
        id: 'relationship',
        name: '关系',
        subtitle: '伴侣 · 家人 · 朋友',
        tones: [
          'watch', 'steady', 'supportive', 'steady', 'steady', 'supportive', 'steady', 'steady', 'steady', 'watch',
          'steady', 'watch', 'steady', 'steady', 'supportive', 'steady', 'watch', 'steady', 'supportive', 'steady',
          'steady', 'supportive', 'watch', 'steady', 'watch', 'turning', 'steady', 'steady', 'steady', 'steady',
        ],
        details: {
          '2026-09-20': '容易把工作里的急躁带回家，晚上多留十分钟听对方说完。',
        },
      },
      {
        id: 'health',
        name: '身心',
        subtitle: '状态 · 节律 · 休整',
        tones: [
          'steady', 'supportive', 'steady', 'steady', 'steady', 'supportive', 'supportive', 'steady', 'steady', 'steady',
          'watch', 'steady', 'steady', 'supportive', 'steady', 'steady', 'steady', 'supportive', 'steady', 'supportive',
          'steady', 'supportive', 'watch', 'steady', 'steady', 'steady', 'supportive', 'steady', 'blocked', 'steady',
        ],
        details: {
          '2026-09-20': '精力充足，但下午三点后容易透支，安排一段十五分钟的放空。',
          '2026-10-18': '本期唯一的阻滞日，不排会、不熬夜。',
        },
      },
    ],
    concernPresets: [
      { name: '财运', subtitle: '收入 · 支出 · 投资' },
      { name: '学业', subtitle: '学习 · 考试 · 进修' },
      { name: '家人', subtitle: '父母 · 子女 · 家庭' },
    ],
    filter: {
      toolbarAriaLabel: '按关注筛选 / 倾向图例',
      concernAriaLabel: '关注',
      concernLabel: '关注',
      all: '全部',
      manage: '✎ 编辑关注',
      legendAriaLabel: '倾向图例',
    },
    concernEditor: {
      ariaLabel: '管理关注',
      title: '管理关注',
      subtitle: '激活的关注会按日纳入 30 日推算，并独立着色每天的倾向。',
      activeHeading: '已激活',
      addableHeading: '可添加',
      remove: '移除',
      add: '添加',
      customPlaceholder: '自定义关注,如「学业」「创业」',
    },
    calendar: {
      ariaLabel: '30 日日历',
      gridAriaLabel: '30 日日历网格',
      todayBadge: '今日',
      hasRecordAriaLabel: '已有记录',
      lunarDays: [
        '初十', '十一', '十二', '十三', '十四', '十五', '十六', '十七', '十八', '十九',
        '二十', '廿一', '廿二', '廿三', '廿四', '廿五', '廿六', '廿七', '廿八', '廿九',
        '九月', '初二', '初三', '初四', '初五', '初六', '初七', '初八', '初九', '初十',
      ],
      markers: {
        '2026-09-23': { kind: 'solar_term', label: '秋分' },
        '2026-09-25': { kind: 'festival', label: '中秋节' },
        '2026-09-26': { kind: 'festival', label: '中秋节' },
        '2026-09-27': { kind: 'festival', label: '中秋节' },
        '2026-10-01': { kind: 'festival', label: '国庆节' },
        '2026-10-02': { kind: 'festival', label: '国庆节' },
        '2026-10-03': { kind: 'festival', label: '国庆节' },
        '2026-10-04': { kind: 'festival', label: '国庆节' },
        '2026-10-05': { kind: 'festival', label: '国庆节' },
        '2026-10-06': { kind: 'festival', label: '国庆节' },
        '2026-10-07': { kind: 'festival', label: '国庆节' },
        '2026-10-08': { kind: 'solar_term', label: '寒露' },
        '2026-10-10': { kind: 'lunar_month', label: '九月' },
        '2026-10-18': { kind: 'festival', label: '重阳节' },
      },
    },
    details: {
      summary: '30日行动指南摘要与生成依据',
      body: '接下来 30 天助力日偏多，主线是稳步推进已经确认的事情；9月29日–10月2日放缓判断，只收信息不定案；10月13日起留意转向信号，适合复盘与调整方向。',
      evidenceTitle: '生成依据',
      evidence: [
        '八字子平法 · 以日主旺衰与月令流转推算 30 日倾向',
        '关注镜片：事业、关系、身心，各自独立着色',
        '已结合 1 条今日参照与 1 条计划项',
        '生成于 2026年9月20日 · 30/30 日',
      ],
    },
    dayPanel: {
      close: '关闭',
      kindLabels: { past: '已过', today: '今日', future: '未来' },
      calendarTitle: '通用历法',
      lunarLabel: '农历',
      ganzhiLabel: '干支',
      solarTermLabel: '节气',
      festivalsLabel: '节日',
      lunar: [
        '农历八月初十', '农历八月十一', '农历八月十二', '农历八月十三', '农历八月十四', '农历八月十五', '农历八月十六', '农历八月十七', '农历八月十八', '农历八月十九',
        '农历八月二十', '农历八月廿一', '农历八月廿二', '农历八月廿三', '农历八月廿四', '农历八月廿五', '农历八月廿六', '农历八月廿七', '农历八月廿八', '农历八月廿九',
        '农历九月初一', '农历九月初二', '农历九月初三', '农历九月初四', '农历九月初五', '农历九月初六', '农历九月初七', '农历九月初八', '农历九月初九', '农历九月初十',
      ],
      ganzhi: [
        '丙午年 丁酉月 丁酉日', '丙午年 丁酉月 戊戌日', '丙午年 丁酉月 己亥日', '丙午年 丁酉月 庚子日', '丙午年 丁酉月 辛丑日',
        '丙午年 丁酉月 壬寅日', '丙午年 丁酉月 癸卯日', '丙午年 丁酉月 甲辰日', '丙午年 丁酉月 乙巳日', '丙午年 丁酉月 丙午日',
        '丙午年 丁酉月 丁未日', '丙午年 丁酉月 戊申日', '丙午年 丁酉月 己酉日', '丙午年 丁酉月 庚戌日', '丙午年 丁酉月 辛亥日',
        '丙午年 丁酉月 壬子日', '丙午年 丁酉月 癸丑日', '丙午年 丁酉月 甲寅日', '丙午年 戊戌月 乙卯日', '丙午年 戊戌月 丙辰日',
        '丙午年 戊戌月 丁巳日', '丙午年 戊戌月 戊午日', '丙午年 戊戌月 己未日', '丙午年 戊戌月 庚申日', '丙午年 戊戌月 辛酉日',
        '丙午年 戊戌月 壬戌日', '丙午年 戊戌月 癸亥日', '丙午年 戊戌月 甲子日', '丙午年 戊戌月 乙丑日', '丙午年 戊戌月 丙寅日',
      ],
      currentTendency: '当日倾向',
      entryHeadings: { past: '记一笔事件', today: '记一笔今日观察', future: '记一笔计划项' },
      placeholders: { memory: '这一天发生了什么…', plan: '这一天计划…' },
      saveLabels: { memory: '保存事件', plan: '保存计划' },
      recordKinds: { memory: '事件', plan: '计划' },
      recordsTitle: '已记录',
      recordsEmpty: '这一天还没有记录。',
      askThisRecord: '去问镜问这条',
      edit: '编辑',
      delete: '删除',
      cancel: '取消',
      save: '保存',
      editRecordContent: '编辑记录内容',
      seededRecords: [
        { id: 'seed-today', date: '2026-09-20', body: '下午要谈一个重要合作，心里有点不确定。' },
        { id: 'seed-plan', date: '2026-10-09', body: '提交合作方案终稿，只争取关键条款。' },
      ],
    },
    monthPanel: {
      title: '30日行动指南',
      close: '关闭',
      rangeLabel: '9月20日 – 10月19日',
      startLabel: '9月20日',
      endLabel: '10月19日',
      generatedPrefix: '已生成 ',
      generatedSuffix: '/30 日',
      concernsSuffix: '个关注',
      empty: '当前 30 日窗口还没有可用的月镜数据。生成后这里会给出本期结论、关键窗口和关注行动。',
      actionNotice: '行动导向的解读，聚焦你接下来该做什么。',
      conclusionTitle: '本期结论',
      bestForLabel: '最适合做',
      avoidLabel: '尽量避免',
      tendencyLanguage: {
        supportive: {
          body: '接下来30天适合稳步推进已确认的事情，不要急着换方向。',
          bestFor: ['推进', '整理', '复盘', '建立节奏'],
          avoid: ['冲动决策', '临时转向', '同时开太多新坑'],
        },
        steady: {
          body: '本期整体节奏平稳，适合有节奏地推进，小步积累看得见的结果。',
          bestFor: ['维持节奏', '例行推进', '整理细节', '轻量复盘'],
          avoid: ['突然加码', '短期冲刺', '节奏未稳就定案'],
        },
        watch: {
          body: '本期更适合校准节奏，先看清反馈与细节，再决定是否加速。',
          bestFor: ['观察反馈', '检查风险', '补齐信息', '放慢判断'],
          avoid: ['急下结论', '催促结果', '单点放大'],
        },
        turning: {
          body: '本期有转向信号，旧节奏可能需要重新评估，调整时记得预留空间。',
          bestFor: ['复盘方向', '调整策略', '记录变化', '重排节奏'],
          avoid: ['沿用旧办法', '仓促承诺', '忽略变化信号'],
        },
        blocked: {
          body: '本期阻力偏重，优先把重心放在止损、复核和保留余地上。',
          bestFor: ['止损', '复核', '降负荷', '保留余地'],
          avoid: ['硬碰硬', '冲动承诺', '高消耗投入'],
        },
      },
      distributionTitle: '本期分布',
      dayUnit: '日',
      windowsTitle: '三个关键窗口',
      windows: [
        {
          title: '主动推进窗口',
          tone: 'supportive',
          ranges: [
            { label: '9月22日–9月26日', from: '2026-09-22', to: '2026-09-26' },
            { label: '10月8日–10月11日', from: '2026-10-08', to: '2026-10-11' },
          ],
          brief: '适合沟通、提交、落实已确认事项。',
        },
        {
          title: '放缓判断窗口',
          tone: 'watch',
          ranges: [{ label: '9月29日–10月2日', from: '2026-09-29', to: '2026-10-02' }],
          brief: '不急着下结论，先观察反馈。',
        },
        {
          title: '转向信号窗口',
          tone: 'turning',
          ranges: [{ label: '10月13日–10月15日', from: '2026-10-13', to: '2026-10-15' }],
          brief: '适合复盘与调整策略。',
        },
      ],
      concernActionsTitle: '我的关注行动',
      primaryAxisPrefix: '主轴：',
      checklistTitle: '行动清单',
      remindersSuffix: '行动提醒',
      notGenerated: '尚未生成',
      pendingConcernBody: '这个关注还没有进入当前 30 日窗口的生成结果。重新生成后再纳入行动指南。',
      concernActions: [
        {
          concernId: 'career',
          summary: '助力日集中在两段推进窗口，适合把谈到一半的合作推到签字前一步；观察日与阻滞日只收信息，不追加承诺。',
          checklist: [
            { window: '9月22日–9月26日', label: '把合作提案压成一页，约对方当面确认关键条款', from: '2026-09-22', to: '2026-09-26' },
            { window: '9月29日–10月2日', label: '只收集反馈，不定价、不签字', from: '2026-09-29', to: '2026-10-02' },
            { window: '10月8日–10月11日', label: '提交终稿、发布或宣布已确认的安排', from: '2026-10-08', to: '2026-10-11' },
          ],
          reminders: ['先确认再扩张', '关键动作不挤在同一天', '观察日只收信息'],
        },
        {
          concernId: 'relationship',
          summary: '关系线本期以平稳为主，观察日多落在工作压力最大的几天，注意别把急躁带回家。',
          checklist: [
            { window: '9月20日–9月21日', label: '回家先听十分钟再说安排', from: '2026-09-20', to: '2026-09-21' },
            { window: '9月29日–10月2日', label: '想谈的安排先写下来，晚两天再说', from: '2026-09-29', to: '2026-10-02' },
            { window: '10月13日–10月15日', label: '复盘一次最近的争执，分清是节奏还是立场', from: '2026-10-13', to: '2026-10-15' },
          ],
          reminders: ['先听再说', '不在饭桌上谈工作', '拐点时先记录'],
        },
        {
          concernId: 'health',
          summary: '精力整体充足，10月18日是本期唯一的阻滞日，提前把高消耗的安排挪开。',
          checklist: [
            { window: '9月23日–9月26日', label: '午后留十五分钟不看屏幕', from: '2026-09-23', to: '2026-09-26' },
            { window: '10月1日–10月7日', label: '假期把睡眠补回来，不安排连续外出', from: '2026-10-01', to: '2026-10-07' },
            { window: '10月17日–10月18日', label: '降负荷：不排会、不熬夜、保留余地', from: '2026-10-17', to: '2026-10-18' },
          ],
          reminders: ['十点前收工', '午后放空十五分钟', '阻滞日降负荷'],
        },
      ],
      supplementaryAriaLabel: '30日详细节奏与生成依据',
      rhythmTitle: '30日详细节奏',
      themeLabel: '主题',
      suitableLabel: '适合',
      unsuitableLabel: '不适合',
      phases: [
        { title: '第一阶段', name: '记录变化', from: '2026-09-20', to: '2026-09-27', theme: '观察与记录，摸清节奏与变化', suitable: '记录变化、收集信息、整理思路', unsuitable: '急于下结论、推动关键决策' },
        { title: '第二阶段', name: '表达确认', from: '2026-09-28', to: '2026-10-04', theme: '表达与澄清，确认共识与方向', suitable: '沟通确认、反馈调整、推进协作', unsuitable: '冲动表态、强行推进、忽略反馈' },
        { title: '第三阶段', name: '稳定执行', from: '2026-10-05', to: '2026-10-12', theme: '落实执行，维持节奏与协同', suitable: '执行推进、分工协作、稳步落地', unsuitable: '频繁变动、临时改方向' },
        { title: '第四阶段', name: '收束复盘', from: '2026-10-13', to: '2026-10-19', theme: '收尾与复盘，总结成果与调整', suitable: '复盘总结、优化流程、收尾收束', unsuitable: '新开大项目、重大变动' },
      ],
      dailyDistributionTitle: '每日分布',
      rhythmAriaLabel: '每日节奏',
      pending: '待生成',
      evidenceTitle: '生成依据',
      evidence: [
        '八字子平法 · 以日主旺衰与月令流转推算 30 日倾向',
        '关注镜片：事业、关系、身心，各自独立着色',
        '已结合 1 条今日参照与 1 条计划项',
        '生成于 2026年9月20日 · 30/30 日',
      ],
      countsAriaLabel: '月内倾向分布',
      countUnit: '条',
    },
  },
  nianjing: {
    title: '年镜',
    subtitle: '先看十年节奏，再选年份看详情',
    years: [
      { year: 2026, tone: 'supportive', label: '助力' },
      { year: 2027, tone: 'supportive', label: '助力' },
      { year: 2028, tone: 'steady', label: '平稳' },
      { year: 2029, tone: 'turning', label: '转折' },
      { year: 2030, tone: 'watch', label: '观察' },
      { year: 2031, tone: 'steady', label: '平稳' },
      { year: 2032, tone: 'supportive', label: '助力' },
      { year: 2033, tone: 'blocked', label: '阻滞' },
      { year: 2034, tone: 'turning', label: '转折' },
      { year: 2035, tone: 'supportive', label: '助力' },
    ],
    selectedYearEyebrow: '选中年份 · 关键判断',
    summaryTitle: '2026 年',
    summaryTone: 'supportive',
    summaryLabel: '助力',
    summaryBody: '长期支撑逐渐打开：资源在向你聚拢，适合做需要耐心的布局，而不是短线冲刺。',
    yearLeadLabel: '年度主导',
    concerns: [
      { name: '事业', tone: 'supportive', label: '助力', body: '上半年适合确认方向，下半年资源到位后再扩张团队。' },
      { name: '关系', tone: 'steady', label: '平稳', body: '没有明显波动，重点是把日常节奏建立起来。' },
      { name: '身心', tone: 'watch', label: '观察', body: '春末与秋初两段需要主动减负，避免把旺盛用成透支。' },
    ],
    detailAction: '查看年度详情',
  },
  // Method-routed 命镜: engine-generated chart data for all three method profiles.
  mingjing: shijingMingjingPreviewContent,
  // 合镜 first-run: the app's immersive intake hero (product/i18n/zh/hejing.ts emptyHero).
  hejing: {
    title: '合镜',
    ariaLabel: '合镜起始页',
    eyebrow: 'TWO CHARTS · ONE MIRROR',
    titleLead: '看见你与 TA',
    titleEmphasis: '之间的相处之道',
    body: '合镜，从你和 TA 的出生资料出发，看见关系状态、相处重点与值得留意的时间窗口。在彼此的目光里，找到属于你们的方向。',
    primaryAction: '创建第一面合镜',
    stepsHint: '选择关系类型 → 填写出生信息 → 生成合镜解读',
    footer: '每一次相遇，都是通往更好自己的起点。',
    heroImage: '/demo/shijing/hejing-intake-hero.jpg',
  },
  ask: {
    // Labels mirror nimiapp-shijing product/i18n/zh/shijing.ts.
    title: '问镜',
    subtitle: '向时间提问，在变化中看见自己。',
    railAria: '提问记录',
    newQuestion: '新提问',
    newQuestionAria: '开始新的问镜提问',
    searchPlaceholder: '搜索提问',
    filterButton: '筛选关注',
    filterButtonActive: '筛选关注，已选 {{count}} 项',
    filterMenuAria: '按关注筛选提问记录',
    filterAll: '全部提问',
    railEmptyTitle: '还没有提问记录',
    railEmptyBody: '提问后会在这里形成你的时间脉络。',
    emptySearch: '没有匹配的提问',
    groups: { today: '今天', week: '本周', earlier: '更早' },
    justNow: '刚刚',
    composerAria: '提问',
    composerTitle: '你现在最想问什么？',
    questionAria: '你的问题',
    placeholderLines: [
      '接下来一个月，我该不该换工作?',
      '这段关系现在最需要注意什么?',
      '最近反复焦虑，是阶段变化还是方向不清?',
    ],
    contextTitle: '上下文焦点',
    contextDescription: '当前激活的关注会自动影响本次问镜解读。',
    contextEmpty: '未设置关注',
    contextManage: '编辑关注',
    concerns: ['事业', '关系', '身心'],
    generate: '✦ 生成解读',
    generateTitle: '生成解读',
    generating: '生成中…',
    send: '发送',
    sendTitle: '发送追问',
    sending: '发送中…',
    recallAria: '相关提问归档',
    recallTitle: '已有相关提问',
    resultAria: '解读结果',
    thinking: '正在思考…',
    roleUser: '我',
    roleAi: '时镜',
    citedFormat: '引用解读 {{count}} 份',
    fields: { riskLevel: '风险等级', why: '为什么需要注意', suggestion: '建议做什么', avoid: '避免做什么' },
    history: [
      { id: 'q-1', question: '这个月适合把合作谈定吗？', group: 'today', date: '10:24', concerns: ['事业'] },
      { id: 'q-2', question: '最近和伴侣容易起争执，是阶段问题吗？', group: 'week', date: '9月16日', concerns: ['关系'] },
      { id: 'q-3', question: '明年换城市工作会不会太急？', group: 'earlier', date: '8月30日', concerns: ['事业', '身心'] },
    ],
    followUpAnswer: [
      '如果只能改一件事：把会谈定在 22 日之后，其余照你原本的节奏走。',
      '追问里提到的“对方拖延”不用太在意。本月你的助力来自方向一致，而不是来自对方的速度；把自己的底线写下来，比催对方更有用。',
    ],
    answer: {
      title: '可以谈，但把"定"放在 22 日之后',
      conclusion: '本月整体是助力期，合作本身有推进的势头。风险不在对方，而在你的节奏：月初的三天你容易急着收口。',
      cards: [
        { title: '时间', risk: '低', why: '9 月 22 日到 26 日是本期第一个主动推进窗口，日镜与月镜方向一致。', suggestion: '把正式会谈约在这几天。', avoid: '不要在 29 日到 10 月 2 日之间签字。' },
        { title: '方式', risk: '中', why: '日主偏旺，说服力强，但容易在对方犹豫时主动让步。', suggestion: '会前只写下最想争取的一条。', avoid: '不要当场补条件。' },
      ],
      summary: '一句话：势头在你这边，慢半拍反而更稳。',
      cited: 3,
    },
  },
};
