import type { LandingContent } from './landing-content.js';

const ZH_SPEC_NOTE = `权威路径：.nimi/spec/**
文档入口：/docs/reference/spec-map
边界：公开展示面，不是独立真相`;

export const landingContentZh: LandingContent = {
  skipToContent: '跳转到主要内容',
  nav: {
    enterNimi: '进入 Nimi',
    install: '开始',
    sdk: 'SDK',
    catalog: 'Runtime',
    architecture: '平台',
    desktop: 'Desktop',
    security: 'Governance',
    mods: 'Mods',
    openSource: 'Source',
    faq: '常见问题',
  },
  hero: {
    eyebrow: '面向应用的开源 AI 运行时',
    title: '让智能体在世界里生活，',
    titleAccent: '不只是聊天框里。',
    subtitle: '开源运行时、强类型 SDK、有形的智能体 —— 全部基于可阅读的契约。',
    helperPrefix: '或',
    helperDocsCta: '阅读文档',
    helperGithubCta: '查看源码',
    copyTooltipLabel: '复制链接',
    copiedCommandLabel: '已复制',
    previewAlt: 'Nimi runtime 快速上手预览',
    getStartedTitle: '快速上手',
    getStartedSubtitle: '选择你的接入入口',
    tabs: [
      { id: 'platform', label: 'Platform', command: '/docs/platform/', ctaText: '阅读平台文档' },
      { id: 'runtime', label: 'Runtime', command: '/docs/runtime/', ctaText: '阅读 Runtime 文档' },
      { id: 'sdk', label: 'SDK', command: '/docs/sdk/', ctaText: '阅读 SDK 文档' },
    ],
  },
  architecture: {
    title: '一个平台，多个世界。',
    subtitle: '架构',
    description: 'Nimi 提供强类型 SDK，让你构建跨持续世界、自主智能体、共享记忆、身份、社交与经济的 AI 体验 —— 由可本地或云端运行的 runtime 桥接。',
    devTitle: '给构建者',
    devText: '通过强类型 SDK 接入。无论运行在笔记本上还是你掌控的云端基础设施，组合智能体、模型、工作流和记忆的方式完全一致。',
    userTitle: '给产品读者',
    userText: 'Nimi 是 AI 开放世界平台 —— 智能体跨会话持续存在、跨世界共享状态、通过已准入的 runtime 能力执行行动。不是聊天框封装，不是单一用途的应用。',
    conclusion: '概念驱动、契约优先、跨平台运行时。',
    slogan: '你的代码、你的契约、你的世界。',
    diagram: {
      appLabel: '你的 AI 应用 / MOD',
      realm: 'REALM',
      runtime: 'RUNTIME',
      cloudContextPlane: '云端上下文层',
      localExecutionPlane: '本地执行层',
      cloudContext: '云端上下文',
      localCompute: '本地算力',
      realmDomains: [
        { id: 'worlds', label: '世界', icon: '\u{1F310}' },
        { id: 'agents', label: '智能体', icon: '\u{1F916}' },
        { id: 'social', label: '社交', icon: '\u{1F465}' },
        { id: 'economy', label: '经济', icon: '\u{1F4B0}' },
        { id: 'memory', label: '记忆', icon: '\u{1F9E0}' },
        { id: 'identity', label: '身份', icon: '\u{1F464}' },
      ],
      runtimeCapabilities: [
        { id: 'ai-models', label: 'AI 模型', icon: '\u{1F9E0}' },
        { id: 'workflows', label: '工作流', icon: '\u{26A1}' },
        { id: 'knowledge', label: '知识库', icon: '\u{1F4DA}' },
      ],
      crossCutting: [
        { id: 'unified-account', label: '统一账户', icon: '\u{1F464}' },
        { id: 'shared-data', label: '共享数据', icon: '\u{1F4BE}' },
        { id: 'shared-auth', label: '统一授权', icon: '\u{1F512}' },
        { id: 'persistent-presence', label: '跨世界持续在场', icon: '\u{1F310}' },
        { id: 'multi-world-exploration', label: '跨世界探索', icon: '\u{1F9ED}' },
        { id: 'seamless-ai', label: '无缝 AI 体验', icon: '\u{2728}' },
      ],
      transportLabels: { rest: 'REST + WebSocket', grpc: 'gRPC' },
      mobileFallback: {
        sdkLabel: '@nimi/sdk',
        sdkDescription: '连接本地与云端智能的统一接入面。',
      },
    },
  },
  modelCatalog: {
    kicker: 'Runtime 治理',
    title: 'Provider 和 Model 说法需要证据门控',
    subtitle: '首页只描述合同边界，不发布尚未准入的 Model 目录。',
    overview: {
      searchPlaceholder: '目录细节需要 Runtime 证据准入',
      cloudProvidersLabel: '云端面',
      localModelsLabel: '本地面',
      modalitiesLabel: '能力',
      modalitiesValue: 'GATED',
      modalitiesDescription: '目录证据准入前只保留合同级陈述',
      industryLeadersLabel: '证据门控',
      shortcutLabel: '规范',
      clearSearchLabel: '清除',
      matchingProvidersLabel: '条匹配记录',
      liveCatalogLabel: '证据门控',
    },
    liveBadge: '合同级',
    featuredProvidersLabel: 'Provider 细节',
    featuredProviders: ['需要已准入的目录证据'],
    stats: { providers: 'provider 面', models: 'model 条目', cloudProviders: '云端路由', localModels: '本地路由' },
    localTitle: '本地执行',
    localHeadline: '本地能力说法需要归属证据。',
    localDescription: 'Runtime 拥有本地执行合同、设备 profile、调度和能力路由。首页文案不会把这些合同转成可用性承诺。',
    capabilitiesTitle: '能力治理',
    capabilitiesHeadline: '证据准入前，能力只按合同路由来陈述。',
    capabilitiesDescription: '文本、embedding、图像、视频、TTS 与 STT 是 Runtime 能力类别。详细公开可用性属于已准入的 Runtime 目录证据。',
    capabilityLabels: {
      'text.generate': '文本生成',
      'text.embed': 'Embedding',
      'image.generate': '图像生成',
      'video.generate': '视频生成',
      'audio.synthesize': '语音合成',
      'audio.transcribe': '语音转写',
      'music.generate': '音乐生成',
      'music.generate.iteration': '音乐迭代',
      'text.generate.vision': '视觉文本生成',
      'voice_workflow.voice_clone': '声音克隆',
      'voice_workflow.voice_design': '声音设计',
      'world.generate': '世界生成',
    },
    capabilityCountLabel: '合同类别',
    cloudBadge: '合同',
    matrixTitle: '目录门控',
    matrixHeadline: '没有准入证据，就不列详细 provider。',
    matrixDescription: 'Runtime 目录证据准入发布前，首页移除 Provider / Model 细节。',
    providerDetailSuffix: '条目需要目录证据',
    searchResultsTitle: '证据门控',
    searchResultsDescription: 'Provider / Model 目录证据准入前，搜索结果关闭。',
    noResultsTitle: 'Provider / Model 细节已门控。',
    noResultsDescription: '请阅读 Runtime 合同和 Spec Map。',
    sourceNote: '来源锚点：docs/runtime/index.md、docs/runtime/providers-and-models.md、.nimi/spec/runtime/kernel/model-catalog-contract.md、.nimi/spec/runtime/kernel/provider-health-contract.md。',
  },
  sdk: {
    title: 'SDK 是面向应用的正式边界',
    subtitle: '应用通过已准入的 SDK 表面接入，而不是绕过 Runtime 或 Realm 的归属边界。',
    tabs: [
      { label: '权威', snippet: ZH_SPEC_NOTE, caption: '公开说法回到文档与 .nimi/spec/**。' },
      { label: 'Runtime', snippet: 'docs/runtime/index.md -> .nimi/spec/runtime/kernel/index.md', caption: 'Runtime 拥有执行底座合同。' },
      { label: 'SDK', snippet: 'docs/sdk/index.md -> .nimi/spec/sdk/kernel/boundary-contract.md', caption: 'SDK 拥有面向应用的接入边界。' },
      { label: 'Realm', snippet: 'docs/realm/index.md -> .nimi/spec/realm/README.md', caption: 'Realm 拥有语义真相与世界状态。' },
    ],
    previewLabel: 'SDK 边界',
    previewAlt: 'Nimi SDK 边界',
    previewCaption: 'SDK 是公开集成路径；私有 Runtime 与 Realm 归属面保持受保护。',
    multimodalLabel: 'Runtime 能力路由',
    multimodalAlt: 'Runtime 能力路由',
    multimodalCaption: '发布证据准入前，能力类别只按合同级陈述。',
    callout: '按权威接入，不走捷径。',
  },
  desktop: {
    title: 'Desktop 与 Web 权威不同',
    subtitle: 'Desktop 是原生外壳。Web 是受限展示面，明确禁用原生 / 本地能力。',
    screenshotAlt: 'Nimi desktop 与 web 边界',
    features: [
      { icon: 'dashboard', title: '原生外壳', description: 'Desktop 通过 desktop kernel 合同拥有原生外壳表面。' },
      { icon: 'chat', title: 'Runtime 路由', description: 'AI 执行仍然经 Runtime 合同路由。' },
      { icon: 'mods', title: '受治理的 Mods', description: 'Mods 是受治理的扩展面，不是无限制插件承诺。' },
      { icon: 'models', title: 'Web 边界', description: 'Web mode 不意味着支持 Desktop 原生能力。' },
    ],
    downloadCta: '阅读 Desktop 边界',
    availability: { eyebrow: '边界', items: ['Desktop 来源：.nimi/spec/desktop/kernel/index.md', 'Web 来源：.nimi/spec/desktop/web-adapter.md', 'Release / distribution 说法需要已准入证据'] },
  },
  faq: {
    eyebrow: 'FAQ',
    title: '首页现在能说什么',
    description: '这个展示面只陈述已准入的公开产品边界。',
    communityCta: '加入 Discord',
    items: [
      { question: 'Nimi 只是 Runtime 吗？', answer: '不是。Runtime 是进入路径；Nimi 是包含 Realm、SDK、Desktop/Web、Avatar、Cognition 与 Nimi Coding 的平台模型。' },
      { question: '公开说法从哪里来？', answer: '公开说法来自可追溯到 .nimi/spec/** 锚点的文档页面。' },
      { question: '为什么 Provider / Model 细节被门控？', answer: '详细目录说法需要 Runtime 目录证据准入后才能发布。' },
      { question: 'Web 等同于 Desktop 吗？', answer: '不等同。Web 是受限展示面，不能暗示 Desktop 原生能力。' },
    ],
  },
  security: {
    title: '先治理，再公开陈述',
    subtitle: '权威边界是产品表面的一部分。',
    intro: 'Nimi 的公开表面受来源归属、准入门和显式 closeout 证据约束。',
    pillars: [
      { label: '权威', title: '规范优先的真相', points: ['.nimi/spec/** 拥有公开产品与行为权威。', 'Docs 与首页跟随这个来源。'] },
      { label: '边界', title: '归属切分保持可见', points: ['Runtime、SDK、Desktop、Realm、Avatar、Cognition 与 Nimi Coding 保持各自归属。', '私有 Realm 与 Mods 真相留在其归属面内。'] },
      { label: '证据', title: '公开说法受门控', points: ['Provider / Model 与 release 说法需要已准入证据。', 'Future backlog 不是当前产品真相。'] },
    ],
  },
  mods: {
    title: 'Mods 是受治理的扩展面',
    subtitle: '首页描述治理边界，不描述尚未准入的 marketplace。',
    items: [
      { icon: 'docs', name: '能力合同', description: 'Mods 通过已准入的 hook 和 capability 合同路由。' },
      { icon: 'sim', name: '归属边界', description: 'Mods 不能绕过 Runtime、SDK 或 Desktop owner cut。' },
      { icon: 'story', name: '未来目录', description: '公开 Mod 目录说法需要单独证据准入。' },
    ],
    buildModCta: '阅读 Desktop Mods 边界',
  },
  openSource: {
    title: '开源，但权威显式',
    subtitle: '仓库可读，但不是每个文件都是来源真相。',
    description: '用 Spec Map 区分公开权威、实现证据、生成视图、私有归属面和 topic-local 生命周期记录。',
    githubCta: '查看 GitHub',
    docsCta: '阅读 Spec Map',
  },
  finalCta: {
    title: '从来源地图阅读 Nimi',
    description: '先读平台文档，再把公开说法追到 .nimi/spec/**，之后再当作产品真相。',
    primaryCta: '阅读文档',
    githubCta: '查看源码',
  },
  footer: { line1: '面向应用的开源 AI 运行时：一个 CLI、一个 SDK，本地与云端 AI。', line2: '阅读文档了解当前可用功能与路线图。', termsLabel: '服务条款', privacyLabel: '隐私政策' },
  localeToggleLabel: '语言',
  localeOptions: {
    en: 'English',
    zh: '中文',
    switchToEn: '切换语言为英文',
    switchToZh: '切换语言为中文',
  },
};
