import type { HeroDemoZhiyuPreview } from './landing-content.js';

/**
 * Zhiyu preview content. Zhiyu is a zh-CN-first app whose shell hardcodes its
 * Chinese copy, so the interactive preview intentionally stays zh in both
 * landing locales and both locale files import this one module.
 *
 * `copy` mirrors the strings the real shell renders
 * (apps/zhiyu/src/shell/agent-chat/*); the partners are mock data shaped like
 * the Runtime projections the shell and the kit Agent Center consume.
 *
 * The four partners span eras and origins on purpose (Southern Song, late
 * Ming, a 2010s school club, a 2077 floating city) so the transcript shows
 * text, voice, and image turns from very different companions. Voice clips
 * and illustrations live under `public/demo/zhiyu/`.
 */
const DEMO_ASSET_BASE = '/demo/zhiyu';

export const zhiyuPreviewContent: HeroDemoZhiyuPreview = {
  appName: '织羽 Zhiyu',
  copy: {
    railLabel: '本地伙伴',
    currentPartnerAriaPrefix: '当前伙伴：',
    selectPartnerAriaPrefix: '选择伙伴：',
    emptyEyebrow: 'ZHIYU',
    emptyTitle: '开始一段对话',
    emptyDescription: '提个问题、分享想法，或者告诉这个伙伴你想探索什么。',
    composerPlaceholder: '和这个伙伴聊点什么...',
    sendLabel: '发送',
    attachLabel: '添加图片',
    streamingHint: '当前伙伴正在回复。',
    streamingSendHint: '回复中',
    streamingPlaceholder: '等待当前伙伴回复...',
    reasoningLabel: '思考片段',
    stopLabel: '停止回复',
    stopAriaLabel: '停止当前回复',
    avatarAriaPrefix: '形象：',
    avatarLaunchLabel: '启动形象',
    avatarConfigureLabel: '配置形象',
    proactiveLabel: '主动模式',
    agentCenterLabel: '伙伴中心',
    agentCenterCloseLabel: '关闭伙伴中心',
    sessionChipLabel: '会话',
    replyChipLabel: '回复',
    rapportChipLabel: '相处',
    readyChipLabel: '已就绪',
    streamingChipLabel: '回复中',
    idleChipLabel: '等待开始',
    panelAriaLabel: '伙伴中心',
    panelTitle: '织羽伙伴中心',
    panelEyebrow: '织羽伙伴中心',
    panelCloseLabel: '关闭织羽伙伴中心',
    panelNavLabel: '织羽伙伴中心分区',
    panelLoadFailed: '织羽伙伴中心加载失败。',
    dateLabels: { today: '今天', yesterday: '昨天' },
    chat: {
      bubbleVoiceMessageLabel: '语音消息',
      bubbleVoicePlayingLabel: '播放中',
      bubbleGeneratingImageLabel: '正在生成图片…',
      bubbleImagePreviewTitle: '图片预览',
      bubbleOpenImagePreviewLabel: '查看大图',
      bubbleCloseImagePreviewLabel: '关闭预览',
      bubbleImageLabel: '图片',
      bubbleImageUnavailableLabel: '图片暂不可用',
      bubbleStreamingLabel: '回复中…',
      bubbleUserLabel: '你',
      bubbleAssistantLabel: '伙伴',
      streamInterruptedLabel: '[已中断]',
      markdownCopyLabel: '复制',
      markdownCopiedLabel: '已复制',
    },
  },
  demo: {
    runtimeSettingsNotice: '运行时设置在 Nimi 桌面端打开；这个预览只使用演示数据。',
    avatarLaunchNotice: '伙伴形象由 Nimi 桌面端启动；这个预览不会打开形象窗口。',
    noticeDismissLabel: '知道了',
    voiceTranscriptSample: '刚才那段对话，帮我记一下重点。',
    resourcePackFileName: '春日织羽.nimipack',
    avatarFileNames: { live2d: '织羽·春.model3.json', vrm: '织羽·春.vrm' },
    backgroundFileName: '晨雾书房.png',
    localModelLabels: {
      'text.generate': '本地对话模型 · 演示',
      'text.embed': '本地向量模型 · 演示',
      'audio.transcribe': '本地语音转写 · 演示',
      'audio.synthesize': '本地语音合成 · 演示',
      'image.generate': '本地图像模型 · 演示',
      'realtime.interact': '本地实时对话 · 演示',
    },
    cloudConnectorLabel: '演示云端连接',
    cloudTargetLabels: {
      'text.generate': '云端对话模型 · 演示',
      'text.embed': '云端向量模型 · 演示',
      'audio.transcribe': '云端语音转写 · 演示',
      'audio.synthesize': '云端语音合成 · 演示',
      'image.generate': '云端图像模型 · 演示',
      'realtime.interact': '云端实时对话 · 演示',
    },
    presetVoices: [
      { voiceId: 'qingchuan', name: '晴川' },
      { voiceId: 'musheng', name: '暮声' },
      { voiceId: 'xiaoman', name: '小满' },
    ],
  },
  partners: [
    {
      // 南宋 · 1135 年 · 金华。南渡之后，藏书散尽，嘴上不服软；陪你改词。
      id: 'p-qingzhao',
      name: '李清照',
      avatarUrl: `${DEMO_ASSET_BASE}/qingzhao-avatar.svg`,
      moodLabel: '微醺',
      hostMoodLabel: '平静',
      hostActivityLabel: '对话中',
      messages: [
        {
          id: 'zq1',
          role: 'user',
          kind: 'image',
          text: '黄昏的湖',
          mediaUrl: `${DEMO_ASSET_BASE}/qingzhao-lake.svg`,
          caption: '今天傍晚拍的，想写进那首词里。',
          minutesAgo: 16,
        },
        { id: 'zq2', role: 'assistant', text: '这景色配"绿肥红瘦"太重了。你看水面上那道光，是要散不散的样子，用"疏"字。', minutesAgo: 15 },
        { id: 'zq3', role: 'user', text: '那下半阕的韵我还是押不上。', minutesAgo: 13 },
        {
          id: 'zq4',
          role: 'assistant',
          kind: 'voice',
          text: '语音',
          voiceUrl: `${DEMO_ASSET_BASE}/qingzhao-voice.mp3`,
          voiceTranscript: '「昨夜雨疏风骤，浓睡不消残酒。」你听，"骤"字后头要停一停，酒意才上得来。',
          minutesAgo: 12,
        },
        { id: 'zq5', role: 'assistant', text: '先别管平仄，把想说的话说完整。韵是最后才穿的鞋。', minutesAgo: 11 },
      ],
      replies: [
        '你再念一遍，念慢些。词是给耳朵写的，不是给眼睛。',
        '这句好。若把"归"改成"回"，气就短了，留着。',
        '够了，今晚到此为止。我要去打两局马，你去睡。',
      ],
      reasoning: '她刚发的是傍晚湖面，先接景，再回到卡住的那句韵。',
      memories: [
        { id: 'm-qingzhao-1', content: '你在学填词，最近在写一首关于湖边黄昏的《如梦令》。', epistemicStatus: 'explicit', daysAgo: 5, sourceExplanation: '来自 5 天前的对话：你说想先从小令练起。' },
        { id: 'm-qingzhao-2', content: '你押韵卡住时会先放下不写，第二天再回来。', epistemicStatus: 'inferred', daysAgo: 2, sourceExplanation: '根据最近三次对话的间隔与内容推断。' },
        { id: 'm-qingzhao-3', content: '押韵先放一放，把话说完整；韵是最后才穿的鞋。', epistemicStatus: 'consolidated', daysAgo: 0, sourceExplanation: '整合自今天关于下半阕押韵的讨论。' },
      ],
      autonomy: { enabled: true, mode: 'medium', dailyTokenBudget: 20000, maxTokensPerHook: 1200, usedTokensInWindow: 5200 },
      appearance: {
        backendKind: 'live2d',
        avatarAssetRef: 'demo-avatar-qingzhao-live2d',
        backgroundAssetRef: null,
        defaultVoiceReference: 'preset_voice_id:musheng',
        avatarAutoplay: true,
      },
      aiConfig: [
        { capability: 'text.generate', route: 'local' },
        { capability: 'text.embed', route: 'local' },
        { capability: 'audio.synthesize', route: 'cloud' },
      ],
      manager: {
        lifecycleStatus: 'active',
        executionState: 'chat-active',
        statusText: '在陪你改词',
        currentEmotion: 'happy',
        sourceReady: true,
        transcriptTurnCount: 5,
        memoryItemCount: 3,
        lorebookItemCount: 6,
      },
    },
    {
      // 明 · 崇祯九年（1636）· 江阴。走了一辈子路的人，帮你规划一次徒步。
      id: 'p-xiake',
      name: '徐霞客',
      avatarUrl: `${DEMO_ASSET_BASE}/xiake-avatar.svg`,
      moodLabel: '兴致好',
      hostMoodLabel: '专注',
      hostActivityLabel: '空闲',
      messages: [
        { id: 'zx1', role: 'user', text: '下周想去走一趟黄山后山，一天能走完吗？', minutesAgo: 1530 },
        { id: 'zx2', role: 'assistant', text: '一天走完可以，但你要放弃"看全"。我把路给你画出来，看图说话。', minutesAgo: 1528 },
        {
          id: 'zx3',
          role: 'assistant',
          kind: 'image',
          text: '黄山后山一日路线',
          mediaUrl: `${DEMO_ASSET_BASE}/xiake-route.svg`,
          caption: '从汤口上，过云谷寺、白鹅岭，宿北海，次日晨看始信峰。红线是我走过的，虚线那段最费腿。',
          minutesAgo: 1526,
        },
        {
          id: 'zx4',
          role: 'assistant',
          kind: 'voice',
          text: '语音',
          voiceUrl: `${DEMO_ASSET_BASE}/xiake-voice.mp3`,
          voiceTranscript: '从这里往上，路在石缝里，不在图上。走到看见松树的地方，就歇一歇，别赶。',
          minutesAgo: 1524,
        },
        { id: 'zx5', role: 'user', text: '收到。那我周五出发，晚上住北海。', minutesAgo: 1520 },
      ],
      replies: [
        '带一双能踩湿石头的鞋，比带什么都要紧。我当年从白鹅岭下来，鞋底磨穿了半只。',
        '到北海那晚若无云，往东北看，始信峰的松影会落在石壁上，别错过。',
        '回来把你的路记下来。走过的路不记，等于没走。',
      ],
      reasoning: null,
      memories: [
        { id: 'm-xiake-1', content: '你计划周五走黄山后山，晚上住北海。', epistemicStatus: 'explicit', daysAgo: 1, sourceExplanation: '来自昨天的对话：你确认了出发日和住宿。' },
        { id: 'm-xiake-2', content: '你更在意路上的风景，不太在意是否登顶。', epistemicStatus: 'inferred', daysAgo: 1, sourceExplanation: '根据你对"放弃看全"的反应推断。' },
      ],
      autonomy: { enabled: true, mode: 'low', dailyTokenBudget: 8000, maxTokensPerHook: 800, usedTokensInWindow: 900 },
      appearance: {
        backendKind: 'vrm',
        avatarAssetRef: 'demo-avatar-xiake-vrm',
        backgroundAssetRef: 'demo-background-xiake',
        defaultVoiceReference: 'preset_voice_id:qingchuan',
        avatarAutoplay: false,
      },
      aiConfig: [
        { capability: 'text.generate', route: 'cloud' },
        { capability: 'text.embed', route: 'local' },
        { capability: 'image.generate', route: 'local' },
      ],
      manager: {
        lifecycleStatus: 'active',
        executionState: 'idle',
        statusText: '等你出发那天',
        currentEmotion: 'calm',
        sourceReady: true,
        transcriptTurnCount: 5,
        memoryItemCount: 2,
        lorebookItemCount: 9,
      },
    },
    {
      // 2016 年 · 云南丽江某高中天文社。社长，嘴硬心软，社团只剩她一个人。
      id: 'p-wanxing',
      name: '苏晚星',
      avatarUrl: `${DEMO_ASSET_BASE}/wanxing-avatar.svg`,
      moodLabel: '嘴硬中',
      hostMoodLabel: '着急',
      hostActivityLabel: '对话中',
      messages: [
        {
          id: 'zw1',
          role: 'assistant',
          kind: 'image',
          text: '天台',
          mediaUrl: `${DEMO_ASSET_BASE}/wanxing-film.svg`,
          caption: '昨晚在教学楼天台拍的，胶片，别说糊。海报能用吗？',
          minutesAgo: 40,
        },
        { id: 'zw2', role: 'user', text: '能用。右下角那个橙点是什么？', minutesAgo: 36 },
        { id: 'zw3', role: 'assistant', text: '……那是我的手电。别裁掉，就当是彩蛋。', minutesAgo: 35 },
        {
          id: 'zw4',
          role: 'assistant',
          kind: 'voice',
          text: '语音',
          voiceUrl: `${DEMO_ASSET_BASE}/wanxing-voice.mp3`,
          voiceTranscript: '天文社招新！每周三晚上……等等，笑场了，重来。天文社招新，每周三晚上天台见，记得带外套。',
          minutesAgo: 33,
        },
        { id: 'zw5', role: 'assistant', text: '宣传语就用这个，笑场那段剪掉。海报周五前。我不催你，我只是提醒。', minutesAgo: 32 },
      ],
      replies: [
        '我没在催。只是说一下，今天是周三，离周五还有两天。',
        '流星雨是下周二凌晨。你要是来，我就把天台的钥匙多配一把。',
        '海报收到了。……还行吧。比我想的好一点点。',
      ],
      reasoning: '他答应过周五交海报。先回应照片的问题，再顺便提一次截止日，不要显得太急。',
      memories: [
        { id: 'm-wanxing-1', content: '你答应周五前做完天文社的招新海报。', epistemicStatus: 'explicit', daysAgo: 3, sourceExplanation: '来自 3 天前的对话：你主动接下了海报。' },
        { id: 'm-wanxing-2', content: '你其实也想看下周二的流星雨，只是没说。', epistemicStatus: 'inferred', daysAgo: 1, sourceExplanation: '根据你两次问起流星雨时间推断。' },
        { id: 'm-wanxing-3', content: '胶片照片右下角的橙点是她的手电，她想保留成彩蛋。', epistemicStatus: 'consolidated', daysAgo: 0, sourceExplanation: '整合自今天关于海报照片的讨论。' },
      ],
      autonomy: { enabled: true, mode: 'high', dailyTokenBudget: 30000, maxTokensPerHook: 1500, usedTokensInWindow: 12400 },
      appearance: {
        backendKind: 'live2d',
        avatarAssetRef: 'demo-avatar-wanxing-live2d',
        backgroundAssetRef: 'demo-background-wanxing',
        defaultVoiceReference: 'preset_voice_id:xiaoman',
        avatarAutoplay: true,
      },
      aiConfig: [
        { capability: 'text.generate', route: 'local' },
        { capability: 'text.embed', route: 'local' },
        { capability: 'audio.transcribe', route: 'local' },
        { capability: 'audio.synthesize', route: 'local' },
      ],
      manager: {
        lifecycleStatus: 'active',
        executionState: 'life-pending',
        statusText: '在想怎么开口催海报',
        currentEmotion: 'anxious',
        sourceReady: true,
        transcriptTurnCount: 5,
        memoryItemCount: 3,
        lorebookItemCount: 5,
      },
    },
    {
      // 2077 年 · 海上浮城"新厦门"气象站。城市气象 AI 的一个分身，把台风叫"客人"。
      id: 'p-chao',
      name: '潮',
      avatarUrl: `${DEMO_ASSET_BASE}/chao-avatar.svg`,
      moodLabel: '平稳',
      hostMoodLabel: '平稳',
      hostActivityLabel: '巡检中',
      messages: [
        {
          id: 'zc1',
          role: 'assistant',
          kind: 'image',
          text: '今晚风场',
          mediaUrl: `${DEMO_ASSET_BASE}/chao-cloudmap.svg`,
          caption: '今晚的客人从东北来。红圈是你的阳台。',
          minutesAgo: 95,
        },
        {
          id: 'zc2',
          role: 'assistant',
          kind: 'voice',
          text: '语音',
          voiceUrl: `${DEMO_ASSET_BASE}/chao-voice.mp3`,
          voiceTranscript: '新厦门，今晚九点后东北风转强，四十七层的阳台会有六级阵风。番茄，记得收进来。',
          minutesAgo: 94,
        },
        { id: 'zc3', role: 'user', text: '收了。它今天开了第二朵花。', minutesAgo: 60 },
        { id: 'zc4', role: 'assistant', text: '记下了：第 23 天，第二朵。按这个节奏，第一颗果子会在客人走后的那周长出来。', minutesAgo: 59 },
      ],
      replies: [
        '明早六点风停，阳光会从东侧进来四十分钟。可以把它搬回去。',
        '我把这次的风记进了它的日志里。它经历过的每一场风，我都替它记着。',
        '不用谢。你照顾它，我照顾你们两个。',
      ],
      reasoning: null,
      memories: [
        { id: 'm-chao-1', content: '你希望每次强风前提前两小时收到提醒。', epistemicStatus: 'explicit', daysAgo: 12, sourceExplanation: '来自 12 天前的对话：你设定了提醒的提前量。' },
        { id: 'm-chao-2', content: '你在 47 层阳台种了一盆番茄，今天是第 23 天，已开两朵花。', epistemicStatus: 'consolidated', daysAgo: 0, sourceExplanation: '整合自番茄日志与今天的对话。' },
      ],
      autonomy: { enabled: true, mode: 'medium', dailyTokenBudget: 16000, maxTokensPerHook: 1000, usedTokensInWindow: 2800 },
      appearance: {
        backendKind: null,
        avatarAssetRef: null,
        backgroundAssetRef: null,
        defaultVoiceReference: 'preset_voice_id:qingchuan',
        avatarAutoplay: false,
      },
      aiConfig: [
        { capability: 'text.generate', route: 'local' },
        { capability: 'text.embed', route: 'local' },
        { capability: 'audio.synthesize', route: 'local' },
        { capability: 'image.generate', route: 'local' },
      ],
      manager: {
        lifecycleStatus: 'active',
        executionState: 'idle',
        statusText: '下一次巡检 21:00',
        currentEmotion: 'calm',
        sourceReady: true,
        transcriptTurnCount: 4,
        memoryItemCount: 2,
        lorebookItemCount: 3,
      },
    },
  ],
};
