import type { HeroDemoParentosPreview } from './landing-content.js';

/**
 * ParentOS (成长底稿) preview content. The app renders zh-first copy from
 * its own locale catalog (nimiapp-parentos `locales/zh.json`); the strings
 * here mirror those keys so the preview reads like the app. Records are
 * mock data for one demo child and never leave the browser.
 */
export const parentosPreviewContent: HeroDemoParentosPreview = {
  appName: 'ParentOS',
  logoAlt: 'ParentOS',
  nav: { timeline: '首页', profile: '档案', journal: '成长随记', advisor: '顾问', reports: '报告', settings: '设置' },
  childMenuLabel: '孩子与应用菜单',
  childSwitcherLabel: '切换孩子',
  addFamilyMember: '添加家庭成员',
  child: {
    name: '小满',
    ageLabel: '4岁3个月',
    genderLabel: '女孩',
    nurtureMode: '平衡模式',
    avatarSrc: '/demo/parentos-avatar.png',
    siblings: [{ name: '阿澈', ageLabel: '1岁2个月' }],
  },
  home: {
    viewFullProfile: '查看完整档案',
    stageFocusTitle: '当前发展阶段',
    viewAllReminders: '查看全部提醒',
    healthGroup: '健康窗口',
    devGroup: '发展关注',
    overflowFormat: '还有 {{count}} 项 →',
    health: [
      { id: 'vision', title: '4 岁视力筛查', description: '4-5 岁是弱视干预的关键窗口，建议每年做一次视力与屈光筛查，记录裸眼视力和是否有眯眼、歪头看物的表现。' },
      { id: 'dental', title: '乳牙涂氟随访', description: '每 3-6 个月复查一次乳牙，检查有无新龋，涂氟后两小时内避免进食。' },
    ],
    development: [
      { id: 'social', title: '同伴交往敏感期', description: '4 岁左右孩子开始在意"朋友"，会经历合作、争执与和好。观察她加入游戏的方式，比纠正冲突更有价值。' },
      { id: 'language', title: '叙事表达在快速发展', description: '她开始能讲有开头和结尾的小故事，睡前让她复述今天发生的事，是最自然的语言练习。' },
    ],
    healthOverflow: 2,
    quickLinksTitle: '常用入口',
    quickLinks: [
      { id: 'growth', label: '生长曲线' },
      { id: 'vaccines', label: '疫苗' },
      { id: 'sleep', label: '睡眠' },
      { id: 'journal', label: '成长随记' },
      { id: 'vision', label: '视力' },
      { id: 'dental', label: '口腔' },
    ],
    growthSnapshotTitle: '成长快照',
    viewCurves: '查看曲线',
    latestMeasurement: '最近一次成长测量',
    updatedLabel: '3 天前更新',
    trends: [
      { id: 'height', label: '身高', unit: 'cm', latestValue: '104.6', delta: '+1.2', deltaPercent: '+1.2%', points: [98.4, 99.6, 100.9, 102.1, 103.4, 104.6] },
      { id: 'weight', label: '体重', unit: 'kg', latestValue: '16.8', delta: '+0.4', deltaPercent: '+2.4%', points: [15.1, 15.4, 15.8, 16.1, 16.4, 16.8] },
    ],
    sleepTitle: '睡眠趋势',
    viewDetails: '查看详情',
    sleep: {
      average: '10h20m',
      averageLabel: '近 10 天平均时长',
      bedtimeLabel: '最近入睡',
      bedtime: '20:45',
      wakeLabel: '最近起床',
      wake: '07:05',
      points: [
        { date: '09-11', minutes: 610 }, { date: '09-12', minutes: 640 }, { date: '09-13', minutes: 600 },
        { date: '09-14', minutes: 655 }, { date: '09-15', minutes: 625 }, { date: '09-16', minutes: 590 },
        { date: '09-17', minutes: 635 }, { date: '09-18', minutes: 645 }, { date: '09-19', minutes: 615 },
        { date: '09-20', minutes: 620 },
      ],
    },
    visionTitle: '视力',
    vision: { leftLabel: '左眼', left: '5.0', rightLabel: '右眼', right: '4.9', measured: '8 月 26 日测量' },
    outdoorTitle: '每周户外目标',
    outdoor: { minutes: 540, goal: 840, unit: '分钟', primary: '本周已户外 9 小时，离目标还差 5 小时。', secondary: '周末各安排一次公园活动就能完成。' },
    sensitiveBadge: '敏感期',
    periods: [
      { title: '社交敏感期', sign: '开始主动找固定的玩伴，会为"谁先玩"讨价还价。' },
      { title: '秩序敏感期（尾声）', sign: '仍会坚持某些顺序，但已经能接受偶尔的变化。' },
    ],
    recordAction: '去记录',
    milestoneTitle: '里程碑',
    viewAll: '查看全部',
    recentlyAchieved: '最近达成',
    upcoming: '即将到来',
    milestones: {
      achieved: [
        { title: '能单脚跳三下以上', meta: '大运动 · 5 天前' },
        { title: '会讲有开头和结尾的小故事', meta: '语言 · 2 周前' },
      ],
      upcoming: [
        { title: '能自己系扣子', meta: '自理 · 通常在 4-5 岁' },
        { title: '能画出有头身四肢的人', meta: '精细动作 · 通常在 4-5 岁' },
      ],
    },
    recentLinesTitle: '最近线索',
    viewAllRecords: '查看全部记录',
    lines: [
      { badge: '珍藏', keepsake: true, when: '昨天', title: '第一次自己讲完整个《三只小猪》，还给狼配了音。', detail: '语言 · 妈妈记录', tag: '珍藏时刻 · 第一次' },
      { badge: '观察', keepsake: false, when: '3 天前', title: '在游乐场主动邀请陌生小朋友一起玩滑梯，被拒绝后也没有难过。', detail: '社交 · 爸爸记录', tag: null },
      { badge: '语音', keepsake: false, when: '5 天前', title: '睡前语音：今天在幼儿园学会了折纸飞机，说明天要教弟弟。', detail: '语音观察 · 已转写', tag: null },
      { badge: '观察', keepsake: false, when: '1 周前', title: '搭积木时反复尝试把塔搭得更高，倒了五次都没放弃。', detail: '专注 · 妈妈记录', tag: null },
    ],
    observationTitle: '观察分布',
    viewRecords: '查看记录',
    last30: '最近 30 天共 {{count}} 条记录',
    observations: [
      { name: '社交互动', count: 6, ratio: 0.32 },
      { name: '语言表达', count: 5, ratio: 0.26 },
      { name: '专注投入', count: 4, ratio: 0.21 },
      { name: '情绪节奏', count: 4, ratio: 0.21 },
    ],
    monthlyReportTitle: '本月成长信',
    viewFullReport: '查看完整报告',
    teaser: '这个月小满最明显的变化在语言和社交：她开始用完整的故事表达自己，也第一次主动处理了和同伴的分歧。',
    todoTitle: '本月可以做的一件事',
    actionText: '每周留一次 20 分钟的"她当老师"时间，让她教你一件事。',
  },
  panel: {
    title: '待办事项',
    todayTab: '今天',
    upcomingTab: '近期 7 天',
    overdueSummary: '逾期汇总',
    reminders: [
      { id: 'r-vision', title: '4 岁视力筛查', status: '今天到期', primary: '记录数据', kind: 'task' },
      { id: 'r-social', title: '观察她怎么加入同伴的游戏', status: '本周', primary: '打开笔记', kind: 'practice' },
      { id: 'r-story', title: '睡前请她复述今天的一件事', status: '本周', primary: '查看指南', kind: 'guide' },
      { id: 'r-sleep', title: '记录昨晚睡眠', status: '今天到期', primary: '记录数据', kind: 'task' },
    ],
    upcoming: [
      { id: 'u-dental', title: '乳牙涂氟随访', status: '3 天后开始', primary: '查看详情', kind: 'task' },
      { id: 'u-growth', title: '记录一下身高体重', status: '5 天后开始', primary: '记录数据', kind: 'task' },
      { id: 'u-consult', title: '和 AI 顾问聊聊入园分离焦虑', status: '本周', primary: '问问 AI 顾问', kind: 'consult' },
    ],
    overdue: [
      { id: 'o-vaccine', title: '流感疫苗（秋季）', status: '逾期 6 天', primary: '记录疫苗' },
    ],
    schedule: '安排时间',
    markComplete: '标记完成',
    customTodoPlaceholder: '添加日常待办...',
    customTodoTitlePlaceholder: '比如：提醒我每晚读 10 分钟绘本',
    add: '添加',
    todos: [
      { id: 't-book', title: '每晚读 10 分钟绘本', due: '今天' },
      { id: 't-park', title: '周六去公园两小时', due: '2天后' },
    ],
    observationNudges: '观察建议',
    nudges: [
      { text: '孩子最近沉浸在什么事情里？', question: '有没有发现孩子特别投入的瞬间？' },
      { text: '孩子面对选择时是果断还是犹豫？', question: '今天让孩子自己做个小决定试试' },
    ],
    observe: '去观察',
  },
  advisor: {
    newConversation: '新对话',
    conversations: [
      {
        id: 'c-1',
        title: '入园后早上分离焦虑怎么办',
        when: '今天',
        messages: [
          { role: 'user', content: '小满开学两周了，每天早上送到幼儿园门口还是会哭，要抱很久才肯进去。我该坚持还是再等等？' },
          { role: 'assistant', content: '4 岁孩子入园两周仍有分离哭闹是很常见的，**不代表适应失败**。从你记录的随记看，她在园内的社交和语言表现很活跃，说明分离时刻的情绪是"告别的仪式"，而不是全天的状态。\n\n可以试试：\n- 固定一个很短的告别仪式（拥抱、击掌、一句固定的话），每天一样\n- 告别后不回头，交给老师即可；拉长告别反而延长焦虑\n- 回家后不追问"今天哭了吗"，改问"今天和谁玩了"\n\n如果三周后仍无缓解，或她在园内也持续退缩，再考虑和老师一起观察具体触发点。' },
        ],
      },
      { id: 'c-2', title: '4 岁视力筛查要看什么', when: '3 天前', messages: [
        { role: 'user', content: '这周要带小满去做视力筛查，家长应该重点问哪些？' },
        { role: 'assistant', content: '4 岁筛查重点是**裸眼视力、屈光度和双眼是否有明显差异**。可以主动请医生记录：\n- 双眼裸眼视力（记到档案里，方便和明年对比）\n- 是否有散光或远视储备偏低\n- 是否需要散瞳复查\n\n回来后把数值录进档案，ParentOS 会在下一年提醒复查。' },
      ] },
      { id: 'c-3', title: '弟弟出生后姐姐的情绪变化', when: '2 周前', messages: [
        { role: 'user', content: '弟弟出生后小满最近特别黏人，还会故意惹弟弟哭。' },
        { role: 'assistant', content: '这是典型的**手足竞争期**表现。她在确认自己仍然被爱。每天给她 10-15 分钟完全属于她的"专属时间"，比反复讲道理更有效。' },
      ] },
    ],
    user: '你',
    assistant: '成长顾问',
    thinking: 'AI 正在思考...',
    stop: '停止',
    placeholder: '输入问题...',
    send: '发送',
    recordData: '去记录数据',
    suggestions: ['她这个阶段最该关注什么？', '怎么陪她练习讲故事？', '户外时间不够会影响视力吗？'],
    emptyEyebrow: 'AI 顾问',
    emptyTitle: '选择或创建一个对话',
    emptyDescription: 'AI 顾问基于 小满 的档案和本地记录工作',
    replies: [
      '结合小满 4 岁 3 个月的阶段和最近的记录来看，这件事**不需要着急**。她的语言和社交都在正常范围内，可以先把观察记录下来，一到两周后我们再一起看有没有变化。\n\n建议这周：\n- 每天留一段不被打断的自由玩耍时间\n- 记录她主动发起互动的次数\n- 有让你意外的瞬间就写进成长随记',
      '可以这样理解：4-5 岁是**叙事能力**快速发展的窗口。你不需要专门"教"，只要在她讲的时候多问一句"然后呢"，故事就会越来越完整。\n\n如果想更系统一点，可以把她讲的故事录成语音随记，一个月后回听会很有意思。',
    ],
  },
  journal: {
    heroLead: '成长',
    heroTail: '随记',
    subtitleLead: '写下今天的一个瞬间。',
    subtitleTail: '不需要完整，她的成长会自己串起来。',
    stats: { thisMonth: '本月', total: '累计', keepsake: '珍藏' },
    counts: { thisMonth: 12, total: 148, keepsake: 9 },
    captureText: '文字',
    captureVoice: '语音',
    placeholder: '今天小满做了什么让你印象深刻的事？',
    save: '保存记录',
    keepsakeToggle: '标记为珍藏',
    filterAll: '全部',
    filterKeepsake: '珍藏',
    keepsakeBadge: '珍藏',
    entries: [
      { id: 'j-1', dateLabel: '今天', time: '08:40', text: '早上送园时只哭了一小会儿，老师一牵手就自己走进去了，回头还挥了挥手。', dimension: '情绪节奏', keepsake: false, recorder: '妈妈' },
      { id: 'j-2', dateLabel: '昨天', time: '20:15', text: '第一次自己讲完整个《三只小猪》，还给狼配了音，讲到最后自己笑得停不下来。', dimension: '语言表达', keepsake: true, recorder: '妈妈' },
      { id: 'j-3', dateLabel: '9月17日', time: '17:30', text: '在游乐场主动邀请陌生小朋友一起玩滑梯，被拒绝后也没有难过，自己又去找了别人。', dimension: '社交互动', keepsake: false, recorder: '爸爸' },
      { id: 'j-4', dateLabel: '9月15日', time: '21:05', text: '睡前语音：今天在幼儿园学会了折纸飞机，说明天要教弟弟。', dimension: null, keepsake: false, recorder: '妈妈' },
    ],
  },
  profile: {
    title: '健康档案',
    recordSummary: '已记录 86 条成长数据 · 最近一次记录是 3 天前',
    completenessLabel: '档案完整度',
    completeness: 86,
    addData: '添加健康数据',
    editChild: '编辑资料',
    archiveTitle: '成长故事，分门别类',
    groups: [
      { id: 'growth', name: '生长', summary: '身高 104.6 cm · 体重 16.8 kg', metrics: [{ label: '身高', value: '104.6 cm' }, { label: '体重', value: '16.8 kg' }, { label: '头围', value: '50.2 cm' }] },
      { id: 'vision', name: '视力', summary: '左 5.0 · 右 4.9', metrics: [{ label: '左眼', value: '5.0' }, { label: '右眼', value: '4.9' }, { label: '屈光', value: '远视储备正常' }] },
      { id: 'dental', name: '口腔', summary: '20 颗乳牙 · 无龋', metrics: [{ label: '乳牙', value: '20 颗' }, { label: '涂氟', value: '6 月 12 日' }, { label: '龋齿', value: '无' }] },
      { id: 'vaccines', name: '疫苗', summary: '已完成 18 针 · 待补 1 针', metrics: [{ label: '已完成', value: '18 针' }, { label: '待补', value: '流感（秋季）' }] },
      { id: 'sleep', name: '睡眠', summary: '平均 10h20m', metrics: [{ label: '平均时长', value: '10h20m' }, { label: '入睡', value: '20:45' }] },
      { id: 'milestones', name: '里程碑', summary: '已达成 31 项', metrics: [{ label: '大运动', value: '8 项' }, { label: '语言', value: '7 项' }, { label: '社交情绪', value: '6 项' }] },
    ],
  },
  reports: {
    title: '成长报告',
    subtitle: '每月自动整理一封成长信，也可以按时间段生成。',
    generate: '生成报告',
    presets: ['本月', '上月', '本季度', '上季度', '自定义'],
    letter: {
      badge: '月度成长信',
      period: '2026 年 8 月 20 日 – 9 月 19 日',
      greeting: '亲爱的小满爸爸妈妈：',
      paragraphs: [
        '这个月小满最明显的变化在语言和社交。她开始用完整的故事表达自己，讲《三只小猪》时会给每个角色配上不同的声音；在游乐场，她第一次在被拒绝后没有退缩，转身又去找了新的玩伴。',
        '身高这个月长了 1.2 厘米，体重增加 0.4 公斤，都在她自己的曲线通道内。睡眠稳定在 10 小时左右，入睡时间比上个月提前了 15 分钟。',
        '视力筛查已经到期，建议本周完成；秋季流感疫苗仍然待补。',
      ],
      actionsTitle: '下个月可以做的三件事',
      actions: ['每周留一次 20 分钟的"她当老师"时间', '完成 4 岁视力筛查并录入数值', '周末各安排一次两小时的户外活动'],
    },
  },
  settings: {
    title: '设置',
    general: '通用',
    other: '其他',
    account: { name: 'Halliday', note: '登录和账户切换由 Nimi Desktop 统一管理。' },
    languageTitle: '界面语言',
    languageDesc: '切换 ParentOS 的全局界面文案。',
    sections: [
      { id: 'children', label: '孩子与家庭成员', desc: '管理孩子档案、记录人与头像。' },
      { id: 'nurture', label: '养育模式', desc: '轻松 · 平衡 · 进阶，决定提醒的密度与语气。' },
      { id: 'reminders', label: '提醒偏好', desc: '按领域调整提醒频率，或暂时关闭。' },
      { id: 'ai', label: 'AI 与本地模型', desc: '成长顾问与语音转写使用的本地模型。' },
    ],
    info: [
      { label: '隐私与本地数据', desc: '所有记录只保存在这台设备上。' },
      { label: '关于 ParentOS', desc: '版本 0.1.6 · 演示数据' },
    ],
  },
  notices: {
    hostOnly: '这个预览只使用演示数据；文件、相机与本地模型在 Nimi 桌面端中可用。',
    dismiss: '知道了',
  },
};
