export type ModelCatalogProvider = {
  provider: string;
  runtimePlane: 'local' | 'cloud';
  capabilities: string[];
  models: string[];
};

// Snapshot derived from runtime/catalog/providers/*.yaml on 2026-03-10.
export const MODEL_CATALOG_PROVIDERS: ModelCatalogProvider[] = [
  {
    provider: 'anthropic',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: ['claude-opus-4-6', 'claude-sonnet-4-6', 'claude-haiku-4-5'],
  },
  {
    provider: 'aws_polly',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize'],
    models: ['polly-neural-tts'],
  },
  {
    provider: 'azure',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'text.embed', 'text.generate'],
    models: ['gpt-5.2', 'text-embedding-3-large', 'gpt-image-1.5'],
  },
  {
    provider: 'azure_speech',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize'],
    models: ['azure-neural-tts'],
  },
  {
    provider: 'bedrock',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: [
      'anthropic.claude-sonnet-4-6-v1:0',
      'claude-sonnet-4-6',
      'anthropic.claude-haiku-4-5-v1:0',
      'claude-haiku-4-5',
      'amazon.nova-pro-v1:0',
      'nova-pro',
    ],
  },
  {
    provider: 'cohere',
    runtimePlane: 'cloud',
    capabilities: ['text.embed', 'text.generate'],
    models: ['command-r-plus', 'command-r', 'embed-v4.0'],
  },
  {
    provider: 'dashscope',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize', 'audio.transcribe', 'image.generate', 'text.embed', 'text.generate'],
    models: [
      'qwen-tts',
      'qwen-tts-2025-04-10',
      'qwen-tts-2025-05-22',
      'qwen-tts-latest',
      'qwen3-tts-instruct-flash',
      'qwen3-tts-instruct-flash-2026-01-26',
      'qwen3-tts-flash',
      'qwen3-tts-flash-2025-09-18',
      'qwen3-tts-flash-2025-11-27',
      'qwen3-tts-vc',
      'qwen3-tts-vc-2026-01-22',
      'qwen3-tts-vd',
      'qwen3-tts-vd-2026-01-26',
      'qwen3-max',
      'qwen3.5-plus',
      'qwen3.5-flash',
      'qwen-plus-latest',
      'qwen-plus-2025-12-01',
      'qwen-vl-max-latest',
      'deepseek-v3.2',
      'deepseek-v3.2-exp',
      'deepseek-v3.1',
      'deepseek-r1',
      'deepseek-r1-0528',
      'deepseek-v3',
      'siliconflow/deepseek-v3.2',
      'siliconflow/deepseek-v3.1-terminus',
      'siliconflow/deepseek-r1-0528',
      'siliconflow/deepseek-v3-0324',
      'kimi/kimi-k2.5',
      'kimi-k2.5',
      'kimi-k2-thinking',
      'Moonshot-Kimi-K2-Instruct',
      'glm-5',
      'glm-4.7',
      'glm-4.6',
      'glm-4.5',
      'glm-4.5-air',
      'MiniMax/MiniMax-M2.5',
      'MiniMax-M2.5',
      'MiniMax/MiniMax-M2.1',
      'MiniMax-M2.1',
      'text-embedding-v4',
      'qwen3-asr-flash',
      'qwen3-asr-flash-2025-09-08',
      'qwen3-asr-flash-2026-02-10',
      'qwen-image-2.0-pro',
      'qwen-image-2.0-pro-2026-03-03',
      'qwen-image-2.0',
      'qwen-image-2.0-2026-03-03',
      'z-image-turbo',
      'wan2.6-t2i',
      'wan2.5-t2i-preview',
      'flux-schnell',
      'flux-dev',
      'flux-merged',
    ],
  },
  {
    provider: 'deepseek',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: ['deepseek-chat', 'deepseek-coder', 'deepseek-reasoner'],
  },
  {
    provider: 'elevenlabs',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize'],
    models: ['eleven_v3', 'eleven_multilingual_v2', 'eleven_flash_v2_5', 'eleven_turbo_v2_5'],
  },
  {
    provider: 'fireworks',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: [
      'accounts/fireworks/models/llama4-maverick-instruct-basic',
      'llama-4-maverick',
      'accounts/fireworks/models/llama4-scout-instruct-basic',
      'llama-4-scout',
      'accounts/fireworks/models/deepseek-r1',
      'deepseek-r1',
      'accounts/fireworks/models/qwen3-235b-a22b',
      'qwen3-235b',
    ],
  },
  {
    provider: 'fish_audio',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize'],
    models: ['fish-speech-1.5', 'fish-speech', 'fish-agent-v1'],
  },
  {
    provider: 'flux',
    runtimePlane: 'cloud',
    capabilities: ['image.generate'],
    models: ['flux-pro-1.1-ultra', 'flux-pro-ultra', 'flux-pro-1.1', 'flux-pro', 'flux-dev'],
  },
  {
    provider: 'gemini',
    runtimePlane: 'cloud',
    capabilities: ['audio.transcribe', 'image.generate', 'text.embed', 'text.generate'],
    models: [
      'gemini-2.5-pro',
      'gemini-2.5-flash',
      'gemini-embedding-001',
      'gemini-2.5-flash-image',
      'gemini-3.1-pro-preview',
      'gemini-3-flash-preview',
      'gemini-3.1-flash-lite-preview',
      'gemini-3.1-flash-image-preview',
    ],
  },
  {
    provider: 'glm',
    runtimePlane: 'cloud',
    capabilities: ['audio.transcribe', 'image.generate', 'text.embed', 'text.generate'],
    models: ['glm-4.7', 'embedding-3', 'glm-asr-2512', 'glm-image'],
  },
  {
    provider: 'google_cloud_tts',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize'],
    models: ['chirp-3-hd'],
  },
  {
    provider: 'google_veo',
    runtimePlane: 'cloud',
    capabilities: ['video.generate'],
    models: ['veo-3', 'veo-3-fast'],
  },
  {
    provider: 'groq',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: [
      'meta-llama/llama-4-scout-17b-16e-instruct',
      'llama-4-scout',
      'meta-llama/llama-4-maverick-17b-128e-instruct',
      'llama-4-maverick',
      'deepseek-r1-distill-llama-70b',
      'llama-3.3-70b-versatile',
    ],
  },
  {
    provider: 'hunyuan',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'text.embed', 'text.generate'],
    models: ['hunyuan-turbo', 'hunyuan-embedding', 'hunyuan-dit'],
  },
  {
    provider: 'ideogram',
    runtimePlane: 'cloud',
    capabilities: ['image.generate'],
    models: ['ideogram-v3', 'V_3', 'ideogram-v2-turbo', 'V_2_TURBO'],
  },
  {
    provider: 'kimi',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'text.generate'],
    models: ['kimi-k2.5', 'kimi-k2-0905-preview', 'moonshot-v1-vision', 'moonshot-v1-vision-preview'],
  },
  {
    provider: 'kling',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'video.generate'],
    models: ['kling-v2', 'kling-v1.6', 'kling-image'],
  },
  {
    provider: 'local',
    runtimePlane: 'local',
    capabilities: ['audio.synthesize'],
    models: [
      'qwen3-tts-local',
      'qwen3-tts',
      'Qwen/Qwen3-TTS-8B',
      'cosyvoice2-local',
      'gpt-sovits-local',
      'f5-tts-local',
      'piper-local',
      'kokoro-local',
    ],
  },
  {
    provider: 'luma',
    runtimePlane: 'cloud',
    capabilities: ['video.generate'],
    models: ['ray-3', 'ray-2', 'ray-flash-2'],
  },
  {
    provider: 'minimax',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'text.generate', 'video.generate'],
    models: ['MiniMax-M2.5', 'MiniMax-M2.5-highspeed', 'video-01', 'video-01-live', 'image-01'],
  },
  {
    provider: 'mistral',
    runtimePlane: 'cloud',
    capabilities: ['text.embed', 'text.generate'],
    models: ['mistral-large-latest', 'mistral-medium-latest', 'mistral-small-latest', 'codestral-latest', 'mistral-embed'],
  },
  {
    provider: 'openai',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize', 'audio.transcribe', 'image.generate', 'text.embed', 'text.generate', 'video.generate'],
    models: [
      'gpt-audio',
      'gpt-audio-mini',
      'tts-1',
      'gpt-4o-transcribe',
      'gpt-4o-mini-transcribe',
      'whisper-1',
      'gpt-5.2',
      'gpt-5.2-2025-12-11',
      'gpt-5.2-pro',
      'text-embedding-3-large',
      'gpt-image-1.5',
      'gpt-image-1.5-2025-04-14',
      'o3',
      'o3-mini',
      'gpt-5.3-codex',
      'sora-2',
      'sora-2-2025-12-08',
    ],
  },
  {
    provider: 'openrouter',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: ['openrouter/auto'],
  },
  {
    provider: 'perplexity',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: ['sonar-pro', 'sonar', 'sonar-reasoning-pro', 'sonar-reasoning'],
  },
  {
    provider: 'pika',
    runtimePlane: 'cloud',
    capabilities: ['video.generate'],
    models: ['pika-2.2', 'pika-2.2-fast'],
  },
  {
    provider: 'playht',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize'],
    models: ['playht-tts-2.0'],
  },
  {
    provider: 'qianfan',
    runtimePlane: 'cloud',
    capabilities: ['text.embed', 'text.generate'],
    models: ['ernie-5.0', 'ernie-4.5-turbo-128k', 'embedding-v1'],
  },
  {
    provider: 'runway',
    runtimePlane: 'cloud',
    capabilities: ['video.generate'],
    models: ['gen4.5', 'gen4_turbo', 'gen3a_turbo'],
  },
  {
    provider: 'siliconflow',
    runtimePlane: 'cloud',
    capabilities: ['text.embed', 'text.generate'],
    models: [
      'deepseek-ai/DeepSeek-V3',
      'deepseek-v3',
      'deepseek-ai/DeepSeek-R1',
      'deepseek-r1',
      'Qwen/Qwen3-235B-A22B',
      'qwen3-235b',
      'THUDM/GLM-4-32B',
      'glm-4-32b',
      'BAAI/bge-m3',
      'bge-m3',
    ],
  },
  {
    provider: 'spark',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: ['spark-x1', 'spark-lite-max', 'lite'],
  },
  {
    provider: 'stability',
    runtimePlane: 'cloud',
    capabilities: ['image.generate'],
    models: ['stable-diffusion-3.5-large', 'sd3.5-large', 'stable-diffusion-3.5-medium', 'sd3.5-medium'],
  },
  {
    provider: 'stepfun',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize', 'image.generate', 'text.generate'],
    models: [
      'step-3.5-flash',
      'step-3',
      'step-r1-v-mini',
      'step-2-mini',
      'step-2-16k',
      'step-1o-turbo-vision',
      'step-1o-vision-32k',
      'step-1v-8k',
      'step-1v-32k',
      'step-1-8k',
      'step-1-32k',
      'step-1-256k',
      'step-tts-2',
      'step-tts-mini',
      'step-tts-vivid',
      'step-1x-medium',
      'step-1x-edit',
      'step-2x-large',
    ],
  },
  {
    provider: 'together',
    runtimePlane: 'cloud',
    capabilities: ['text.generate'],
    models: [
      'meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8',
      'llama-4-maverick',
      'meta-llama/Llama-4-Scout-17B-16E-Instruct',
      'llama-4-scout',
      'deepseek-ai/DeepSeek-R1',
      'deepseek-r1',
      'Qwen/Qwen3-235B-A22B-fp8',
      'qwen3-235b',
    ],
  },
  {
    provider: 'volcengine',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'text.embed', 'text.generate', 'video.generate'],
    models: [
      'seedance-1-5-pro',
      'seedance-1.5-pro',
      'seedance_v1_5_pro',
      'doubao-seedance-2-0-260128',
      'seedance-2.0',
      'doubao-seed-2-0-pro-260215',
      'doubao-seed-2.0-pro',
      'doubao-seed-2-0-lite-260215',
      'doubao-seed-2.0-lite',
      'doubao-seed-2-0-mini-260215',
      'doubao-seed-2.0-mini',
      'doubao-seed-2-0-code-preview-260215',
      'doubao-seed-2.0-code',
      'doubao-1.5-pro-256k',
      'doubao-1.5-pro',
      'doubao-embedding',
      'doubao-embedding-250615',
      'doubao-seedream-5-0-260128',
      'seedream-5.0',
      'doubao-seedream-4-5-251128',
    ],
  },
  {
    provider: 'volcengine_openspeech',
    runtimePlane: 'cloud',
    capabilities: ['audio.synthesize', 'audio.transcribe'],
    models: ['volc.service_type.10029', 'doubao-tts', 'volc.bigasr.auc_turbo', 'doubao-asr-flash'],
  },
  {
    provider: 'xai',
    runtimePlane: 'cloud',
    capabilities: ['image.generate', 'text.generate'],
    models: ['grok-4', 'grok-3', 'grok-3-mini', 'grok-2-vision-1212', 'grok-2-image-1212'],
  },
];
